


CREATE FUNCTION [dbo].[SONDA_FUNC_GET_MANIFEST_DETAIL]
(	
	@pMANIFEST_ID int
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		A.MANIFEST_ID,
		B.ROUTE_ID,
		B.DELIVERY_CLIENT_NAME,
		A.ERP_DOC,
		A.DOC_BOXES,
		A.DOC_PRIZES,
		A.DOC_BULTOS
	FROM 
		dbo.SONDA_LOADING_MANIFEST_DETAIL A,
		dbo.SONDA_DOCS B
	WHERE 
		A.MANIFEST_ID = @pMANIFEST_ID AND
		B.ERP_DOC = A.ERP_DOC
)