CREATE TABLE [dbo].[LOG_CHANGE_MATERIAL] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [LOGIN_ID]     VARCHAR (50)  NOT NULL,
    [OLD_VALUES]   VARCHAR (MAX) NOT NULL,
    [NEW_VALUES]   VARCHAR (MAX) NOT NULL,
    [DATE_UPDATED] DATETIME      NOT NULL,
    CONSTRAINT [PK_LogChangeMaterial_Id] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

