CREATE TABLE [dbo].[LOG_PROJECT] (
    [ID]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [PROJECT_ID]       UNIQUEIDENTIFIER NOT NULL,
    [OPPORTUNITY_NAME] VARCHAR (150)    NULL,
    [CUSTOMER_CODE]    VARCHAR (20)     NULL,
    [STATUS]           VARCHAR (20)     NULL,
    [TYPE_LOG]         VARCHAR (20)     NOT NULL,
    [CREATED_BY]       VARCHAR (64)     NULL,
    [CREATED_DATE]     DATETIME         NULL,
    [CUSTOMER_NAME]    VARCHAR (300)    NULL,
    [CUSTOMER_OWNER]   VARCHAR (30)     NULL,
    CONSTRAINT [PK_LogProject_Id] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

