CREATE TABLE [dbo].[OP_WMS_INV_HISTORY] (
    [CODE_TRANS]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [CLIENT_NAME]      VARCHAR (MAX)  NOT NULL,
    [NUMERO_ORDEN]     VARCHAR (MAX)  NOT NULL,
    [LICENSE_ID]       NUMERIC (18)   NOT NULL,
    [BARCODE_ID]       NVARCHAR (50)  NOT NULL,
    [MATERIAL_NAME]    NVARCHAR (MAX) NOT NULL,
    [QTY]              NUMERIC (18)   NOT NULL,
    [CURRENT_LOCATION] NVARCHAR (50)  NOT NULL,
    [BODEGA]           NVARCHAR (50)  NOT NULL,
    [VALOR_UNITARIO]   DECIMAL (18)   NOT NULL,
    [TOTAL_VALOR]      DECIMAL (18)   NOT NULL,
    [VOLUMEN]          DECIMAL (18)   NOT NULL,
    [TOTAL_VOLUMEN]    DECIMAL (18)   NOT NULL,
    [TERMS_OF_TRADE]   NVARCHAR (50)  NOT NULL,
    [DATE]             DATE           CONSTRAINT [DF_OP_WMS_INV_HISTORY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_OP_WMS_INV_HISTORY] PRIMARY KEY CLUSTERED ([CODE_TRANS] ASC) WITH (FILLFACTOR = 80)
);

