CREATE TABLE [dbo].[SONDA_LOADING_MANIFEST_DETAIL] (
    [MANIFEST_ID] INT          NOT NULL,
    [ERP_DOC]     VARCHAR (25) NOT NULL,
    [DOC_BOXES]   INT          NULL,
    [DOC_PRIZES]  INT          NULL,
    [DOC_BULTOS]  INT          NULL,
    CONSTRAINT [PK_SONDA_LOADING_MANIFEST_DETAIL] PRIMARY KEY CLUSTERED ([MANIFEST_ID] ASC, [ERP_DOC] ASC) WITH (FILLFACTOR = 80)
);

