CREATE TABLE [dbo].[SONDA_DOCS] (
    [DOC_ID]                   NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [ROUTE_ID]                 VARCHAR (50)    NULL,
    [CREATED]                  DATETIME        NULL,
    [CREATED_BY]               VARCHAR (25)    NULL,
    [STATUS]                   VARCHAR (50)    NULL,
    [LAST_UPDATE]              DATETIME        NULL,
    [LAST_UPDATE_BY]           VARCHAR (25)    NULL,
    [COUNTED_ASSIGNED_TO]      VARCHAR (25)    NULL,
    [COUNTED_STARTED_DATE]     DATETIME        NULL,
    [COUNTED_FINISHED_DATE]    DATETIME        NULL,
    [LOADING_GATE]             NUMERIC (18)    NULL,
    [DELIVERY_GPS_URL]         VARCHAR (250)   NULL,
    [DELIVERY_IMAGE]           IMAGE           NULL,
    [DELIVERY_ASSIGNED_TO]     VARCHAR (50)    NULL,
    [DELIVERY_DRIVER_NAME]     VARCHAR (150)   NULL,
    [DELIVERY_VEHICULE_PLATES] VARCHAR (50)    NULL,
    [DELIVERY_VEHICULE_TYPE]   VARCHAR (50)    NULL,
    [DELIVERY_DATE]            DATETIME        NULL,
    [NO_DELIVERY_REASON]       VARCHAR (250)   NULL,
    [MPC_1]                    VARCHAR (50)    NULL,
    [MPC_2]                    VARCHAR (50)    NULL,
    [MPC_3]                    NUMERIC (18, 2) NULL,
    [MPC_4]                    DATETIME        NULL,
    [IS_ADDENDUM]              NUMERIC (18)    CONSTRAINT [DF_SONDA_DOCS_IS_ADDENDUM] DEFAULT ((0)) NULL,
    [ERP_DOC]                  VARCHAR (50)    NULL,
    [TOTAL_PACKAGES]           NUMERIC (18)    NULL,
    [DOC_OWNER]                NUMERIC (18)    NULL,
    [DELIVERY_CLIENT_NAME]     VARCHAR (200)   NULL,
    [DELIVERY_CLIENT_PHONE]    VARCHAR (50)    NULL,
    [DELIVERY_CLIENT_ADDRESS]  VARCHAR (300)   NULL,
    [INTERMEDIATE_PARENT]      VARCHAR (50)    NULL,
    [DOC_PARENT]               NUMERIC (18)    NULL,
    [DELIVERY_COMPANY_ID]      NUMERIC (18)    NULL,
    [DELIVERY_COMPANY_NAME]    VARCHAR (250)   NULL,
    [DELIVERY_CLIENT_CODE]     VARCHAR (50)    NULL,
    [SEQUENCE_SUGGESTED]       NUMERIC (18)    NULL,
    [SEQUENCE_DELIVERED]       NUMERIC (18)    NULL,
    [SIGNAL_LEVEL]             VARCHAR (50)    NULL,
    [BATTERY_LEVEL]            VARCHAR (50)    NULL,
    [PROCESSED_IN_SAP]         DATETIME        NULL,
    [CAMPAING_ID]              VARCHAR (15)    NULL,
    [PRIZES]                   NUMERIC (18)    NULL,
    CONSTRAINT [PK_SONDA_DOCS] PRIMARY KEY CLUSTERED ([DOC_ID] ASC) WITH (FILLFACTOR = 80)
);

