
CREATE PROCEDURE [dbo].[SWIFT_SP_UPDATEUSERHEADER]
@CODE_ENTERPRISE VARCHAR(50),
@NAME_ENTERPRISE VARCHAR(50),
@NUMBER_OF_USER INT,
@CONEXION_STRING VARCHAR(150),
@CORRELATIVE INT,
@USER VARCHAR(50),
@PASS VARCHAR(50),
@IMAGE VARCHAR(MAX)
AS
UPDATE dbo.SWIFT_EXTERNAL_USER SET 
	--CODE_ENTERPRISE=@CODE_ENTERPRISE,
	NAME_ENTERPRISE=@NAME_ENTERPRISE,
	NUMBER_OF_USERS=@NUMBER_OF_USER,
	[IMAGE] =  @IMAGE
	--CONNECTION_STRING=@CONEXION_STRING,
	--[USER]=@USER,
	--PASS=@PASS
WHERE CORRELATIVE=@CORRELATIVE
