CREATE PROCEDURE [dbo].[SWIFT_SP_UPDATE_ENTERPRISE]
@ENTERPRISE INT,
@NAME_ENTERPRISE VARCHAR(50),
@PHONE_ENTERPRISE VARCHAR(50),
@NAME_CONTACT VARCHAR(50),
@PHONE_CONTACT VARCHAR(50)
AS
UPDATE dbo.SWIFT_ENTERPRISE
SET 
	NAME_ENTERPRISE= @NAME_ENTERPRISE,
	PHONE_ENTERPRISE = @PHONE_ENTERPRISE,
	CONTACT_NAME = @NAME_CONTACT,
	PHONE_CONTACT = @PHONE_CONTACT
WHERE
	ENTERPRISE = @ENTERPRISE
