CREATE PROCEDURE [dbo].[SWIFT_SP_INSERT_ENTERPRISE]
@CODE_ENTERPRISE VARCHAR(50),
@NAME_ENTERPRISE VARCHAR(50),
@PHONE_ENTERPRISE VARCHAR(50),
@NAME_CONTACT VARCHAR(50),
@PHONE_CONTACT VARCHAR(50)
AS
INSERT INTO dbo.SWIFT_ENTERPRISE(
	CODE_ENTERPRISE,
	NAME_ENTERPRISE,
	PHONE_ENTERPRISE,
	CONTACT_NAME,
	PHONE_CONTACT)
VALUES(
	@CODE_ENTERPRISE,
	@NAME_ENTERPRISE,
	@PHONE_ENTERPRISE,
	@NAME_CONTACT,
	@PHONE_CONTACT)
