

CREATE PROCEDURE [dbo].[SWIFT_SP_INSERTUSERHEADER]
@CODE_ENTERPRISE VARCHAR(50),
@NAME_ENTERPRISE VARCHAR(50),
@NUMBER_OF_USER INT,
@CONEXION_STRING VARCHAR(150),
@USER VARCHAR(150),
@PASS VARCHAR(50),
@IMAGE VARCHAR(MAX)
AS
INSERT INTO dbo.SWIFT_EXTERNAL_USER (
	CODE_ENTERPRISE,
	NAME_ENTERPRISE,
	NUMBER_OF_USERS,
	CONNECTION_STRING,
	LAST_UPDATE,
	LAST_UPDATE_BY,
	[USER],
	PASS,
	[IMAGE])
VALUES(
	@CODE_ENTERPRISE,
	@NAME_ENTERPRISE,
	@NUMBER_OF_USER,
	@CONEXION_STRING,
	GETDATE(),
	'USER_MOBILITY',
	@USER,
	@PASS,
	@IMAGE)
EXEC dbo.CREATE_USER @USER, @PASS
