
CREATE PROCEDURE [dbo].[SWIFT_DELETE_EXTERNAL_USER]
@CORRELATIVE INT
AS
DECLARE @USER VARCHAR(150)
SET @USER = (SELECT [USER] FROM dbo.SWIFT_EXTERNAL_USER WHERE CORRELATIVE=@CORRELATIVE)
EXEC DELETE_USER @USER 

DELETE FROM dbo.SWIFT_USER 
WHERE CODE_ENTERPRISE = (SELECT CODE_ENTERPRISE FROM dbo.SWIFT_EXTERNAL_USER WHERE CORRELATIVE=@CORRELATIVE)

DELETE  FROM dbo.SWIFT_EXTERNAL_USER WHERE CORRELATIVE=@CORRELATIVE
