
CREATE PROCEDURE [dbo].[SWIFT_SP_GETUSER_FOR_CORRELATIVE]
@CORRELATIVE INT
AS
SELECT 
	A.CORRELATIVE,
	A.[LOGIN],
	A.NAME_USER,
	A.TYPE_USER,
	A.[PASSWORD],
	A.CODE_ENTERPRISE,
	A.[IMAGE],
	A.RELATED_SELLER AS RS,
	C.NAME_ROUTE AS SELLER_ROUTE,
	B.SELLER_NAME AS RELATED_SELLER
FROM dbo.SWIFT_USER AS A
LEFT OUTER JOIN profinsa.SWIFT_VIEW_SAP_SELLERS AS B
	ON A.RELATED_SELLER = B.SELLER_CODE
LEFT OUTER JOIN profinsa.SWIFT_VIEW_ROUTES AS C
	ON A.SELLER_ROUTE = C.CODE_ROUTE
 WHERE A.CORRELATIVE = @CORRELATIVE

-- MERGE dbo.SWIFT_USER TRG
--	USING (SELECT ISNULL(RELATED_SELLER,-999) AS RELATED_SELLER FROM dbo.SWIFT_USER WHERE CORRELATIVE = @CORRELATIVE) AS SRC
--	ON TRG.RELATED_SELLER = SRC.RELATED_SELLER AND TRG.CORRELATIVE = @CORRELATIVE
--WHEN MATCHED THEN 
--	UPDATE SET TRG.RELATED_SELLER = '';
