CREATE PROCEDURE [dbo].[SWIFT_SP_UPDATEUSER]
@LOGIN VARCHAR(50),
@NAME_USER VARCHAR(50),
@TYPE_USER VARCHAR(50),
@PASSWORD VARCHAR(50),
@CODE_ENTERPRISE VARCHAR(50),
@CORRELATIVE INT,
@SELLER_ROUTE VARCHAR(50),
@RELATED_SELLER VARCHAR(50),
@IMAGE VARCHAR(MAX)
AS
UPDATE dbo.SWIFT_USER SET 
	NAME_USER=@NAME_USER,
	TYPE_USER=@TYPE_USER,
	[PASSWORD]=@PASSWORD,
	CODE_ENTERPRISE=@CODE_ENTERPRISE, 
	SELLER_ROUTE = @SELLER_ROUTE,
	RELATED_SELLER = @RELATED_SELLER,
	[IMAGE] = @IMAGE
WHERE 
	CORRELATIVE=@CORRELATIVE
