
CREATE VIEW [wms].[OP_WMS_VIEW_POLIZA_IMAGES]
AS
SELECT     A.CODIGO_POLIZA, A.IMAGEN, A.UPLOADED_BY, A.UPLOADED_DATE, B.NUMERO_ORDEN, B.FECHA_LLEGADA, B.ACUERDO_COMERCIAL, B.FECHA_DOCUMENTO, 
                      B.CLIENT_CODE, C.CLIENT_NAME
FROM         [wms].OP_WMS_IMAGENES_POLIZA AS A INNER JOIN
                      [wms].OP_WMS_POLIZA_HEADER AS B ON A.CODIGO_POLIZA = B.CODIGO_POLIZA INNER JOIN
                      [wms].OP_WMS_VIEW_CLIENTS AS C ON B.CLIENT_CODE = C.CLIENT_CODE COLLATE DATABASE_DEFAULT