CREATE VIEW [wms].OP_WMS3PL_VIEW_AUTORIZATIONS_PENDING_AUTO
AS
SELECT     tr.SERIAL_NUMBER, tr.TERMS_OF_TRADE, tr.TRANS_DATE, tr.LOGIN_ID, tr.LOGIN_NAME, tr.TRANS_TYPE, tr.TRANS_DESCRIPTION, tr.TRANS_EXTRA_COMMENTS, 
                      tr.MATERIAL_BARCODE, tr.MATERIAL_CODE, tr.MATERIAL_DESCRIPTION, tr.MATERIAL_TYPE, tr.MATERIAL_COST, tr.SOURCE_LICENSE, tr.TARGET_LICENSE, 
                      tr.SOURCE_LOCATION, tr.TARGET_LOCATION, tr.CLIENT_OWNER, tr.CLIENT_NAME, tr.QUANTITY_UNITS, tr.SOURCE_WAREHOUSE, tr.TARGET_WAREHOUSE, 
                      tr.TRANS_SUBTYPE, tr.CODIGO_POLIZA, tr.LICENSE_ID, tr.STATUS, tr.WAVE_PICKING_ID, ph.NUMERO_DUA, ph.NUMERO_ORDEN
FROM         [wms].OP_WMS_TRANS AS tr INNER JOIN
                      [wms].OP_WMS_POLIZA_HEADER AS ph ON tr.CODIGO_POLIZA = ph.CODIGO_POLIZA
WHERE     (tr.TRANS_TYPE IN ('INICIALIZACION_FISCAL', 'INGRESO_FISCAL')) AND ((ISNULL(CONVERT(VARCHAR, tr.SERIAL_NUMBER), 'NA') + ISNULL(tr.MATERIAL_CODE, 'NA') 
                      + ISNULL(tr.CODIGO_POLIZA, 'na')) NOT IN
                          (SELECT     ISNULL(CONVERT(VARCHAR, TRANS_ID), 'NA') + ISNULL(MATERIAL_CODE, 'NA') + ISNULL(CODIGO_POLIZA, 'na') AS Expr1
                            FROM          [wms].OP_WMS3PL_POLIZA_TRANS_MATCH))