

CREATE VIEW [wms].[OP_WMS3PL_VIEW_PENDING]
AS
--SELECT     ph.WAREHOUSE_REGIMEN, pd.DOC_ID, pd.LINE_NUMBER, pd.CODIGO_POLIZA_ORIGEN, ph.CODIGO_POLIZA, ph.CLIENT_CODE, pd.SKU_DESCRIPTION, 
--                      pd.ORIGIN_DOC_ID, pd.ORIGIN_LINE_NUMBER, ABS(pd.QTY) AS QTY, ABS(pd.BULTOS) AS BULTOS, ph.NUMERO_DUA, ph.NUMERO_ORDEN
--FROM         [wms].OP_WMS_POLIZA_DETAIL AS pd INNER JOIN
--                      [wms].OP_WMS_POLIZA_HEADER AS ph ON pd.DOC_ID = ph.DOC_ID
--WHERE     (ph.TIPO = 'EGRESO') AND (UPPER(ISNULL(pd.PICKING_STATUS, 'PENDING')) IN ('PENDING', 'ON_PROCESS'))

SELECT ph.WAREHOUSE_REGIMEN
	, pd.DOC_ID
	, pd.LINE_NUMBER
	, pd.CODIGO_POLIZA_ORIGEN
	, ph.CODIGO_POLIZA
	, ph.CLIENT_CODE
	, pd.SKU_DESCRIPTION
	, pd.ORIGIN_DOC_ID
	, pd.ORIGIN_LINE_NUMBER
	, ABS(pd.QTY) AS QTY
	, ABS(pd.BULTOS) AS BULTOS, ph.NUMERO_DUA, ph.NUMERO_ORDEN
	, PH.REGIMEN
	, ISNULL((SELECT [DOC_ID]
		FROM [wms].[OP_WMS_POLIZA_HEADER] PHG
		WHERE PHG.CODIGO_POLIZA = PH.CODIGO_POLIZA
		AND PHG.NUMERO_ORDEN = PH.NUMERO_ORDEN
		AND PHG.TIPO = 'INGRESO'
		AND PHG.WAREHOUSE_REGIMEN = 'GENERAL'), 0) AS DOC_TRASLADO 
	, ISNULL(ph.TRANSLATION, 'NO') AS TRANSLATION
FROM [wms].OP_WMS_POLIZA_DETAIL AS pd 
		INNER JOIN [wms].OP_WMS_POLIZA_HEADER AS ph ON pd.DOC_ID = ph.DOC_ID
WHERE (ph.TIPO = 'EGRESO') 
	AND (UPPER(ISNULL(pd.PICKING_STATUS, 'PENDING')) 
	IN ('PENDING', 'ON_PROCESS'))