CREATE VIEW [wms].OP_WMS_VIEW_PICKING_VS_AUDIT
AS
SELECT     ISNULL
                          ((SELECT     TOP (1) AUDIT_ID
                              FROM         [wms].OP_WMS_VIEW_AUDIT_DISPATCH AS AU
                              WHERE     (CODIGO_POLIZA = PI.CODIGO_POLIZA_TARGET) AND (STATUS = 'FINISHED') AND (MATERIAL_ID = PI.MATERIAL_ID)), 0) AS AUDIT_ID, 
                      CODIGO_POLIZA_TARGET, MATERIAL_ID, BARCODE_ID, MATERIAL_NAME, SUM(QUANTITY_ASSIGNED) AS PICKED, ISNULL
                          ((SELECT     SUM(QTY) AS Expr1
                              FROM         [wms].OP_WMS_VIEW_AUDIT_DISPATCH AS AU
                              WHERE     (CODIGO_POLIZA = PI.CODIGO_POLIZA_TARGET) AND (STATUS = 'FINISHED') AND (MATERIAL_ID = PI.MATERIAL_ID)), 0) AS AUDITED, 
                      SUM(QUANTITY_ASSIGNED) - ISNULL
                          ((SELECT     SUM(QTY) AS Expr1
                              FROM         [wms].OP_WMS_VIEW_AUDIT_DISPATCH AS AU
                              WHERE     (CODIGO_POLIZA = PI.CODIGO_POLIZA_TARGET) AND (STATUS = 'FINISHED') AND (MATERIAL_ID = PI.MATERIAL_ID)), 0) AS DIFFERENCE, 
                      COMPLETED_DATE
FROM         [wms].OP_WMS_TASK_LIST AS PI
WHERE     (IS_COMPLETED = 1) AND (TASK_SUBTYPE IN ('DESPACHO_FISCAL'))
GROUP BY CODIGO_POLIZA_TARGET, MATERIAL_ID, BARCODE_ID, MATERIAL_NAME, COMPLETED_DATE