-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	20-05-2018 @ Sprint Capibara???
-- Description:			Obtiene el encabezado de los pickings detallado

-- Autor:				rudi.garcia
-- Fecha de Creacion: 	02-Jan-2019 @ Sprint Perezoso
-- Description:			Se agrego la columna de quien creo la tarea.

/*
-- Ejemplo de Ejecucion:
			SELECT * FROM [wms].OP_WMS_VIEW_TASK_REALLOC_HEADER_DETAILED 
*/
-- =============================================
CREATE VIEW [wms].[OP_WMS_VIEW_TASK_REALLOC_HEADER_DETAILED]
AS
SELECT
  MAX([A].[SERIAL_NUMBER]) AS [SERIAL_NUMBER]
 ,[A].[WAVE_PICKING_ID] AS [WAVE_PICKING_ID]
 ,CASE
    WHEN MAX([PDH].[IS_CONSOLIDATED]) = 1 THEN 'CONSOLIDADO'
    WHEN MAX([PDH].[IS_CONSOLIDATED]) IS NULL THEN MAX([A].[CLIENT_NAME])
    ELSE MAX([PDH].[CLIENT_NAME])
  END [CLIENT_NAME]
 ,MAX([A].[TASK_TYPE]) AS [TASK_TYPE]
 ,MAX([A].[TASK_COMMENTS]) AS [TASK_COMMENTS]
 ,MAX([A].[REGIMEN]) AS [REGIMEN]
 ,MAX([A].[IS_PAUSED]) AS [IS_PAUSED]
 ,MAX([A].[ASSIGNED_DATE]) AS [ASSIGNED_DATE]
 ,MAX([A].[ACCEPTED_DATE]) AS [ACCEPTED_DATE]
 ,MAX([A].[COMPLETED_DATE]) AS [PICKING_FINISHED_DATE]
 ,MAX([A].[IS_CANCELED]) AS [IS_CANCELED]
 ,CAST(NULL AS VARCHAR) AS [NUMERO_ORDEN_SOURCE]
 ,CAST(NULL AS VARCHAR) AS [NUMERO_ORDEN_TARGET]
 ,NULL AS [CODIGO_POLIZA_SOURCE]
 ,MAX([A].[CODIGO_POLIZA_TARGET]) AS [CODIGO_POLIZA_TARGET]
 ,CASE MIN([A].[IS_COMPLETED])
    WHEN 0 THEN CASE MAX([A].[IS_ACCEPTED])
        WHEN 0 THEN 'INCOMPLETA'
        WHEN 1 THEN 'ACEPTADA'
      END
    ELSE 'COMPLETA'
  END AS [IS_COMPLETED]
 ,MAX([A].[IS_DISCRETIONARY]) AS [IS_DISCRETIONARY]
 ,CASE MAX([A].[IS_DISCRETIONARY])
    WHEN 1 THEN 'Discrecional'
    ELSE 'Dirigido'
  END AS [TYPE_PICKING]
 ,MAX([A].[IS_ACCEPTED]) AS [IS_ACCEPTED]
 ,CASE MAX([A].[IS_FROM_ERP])
    WHEN 1 THEN 'Si'
    WHEN 0 THEN 'No'
    ELSE 'No'
  END AS [IS_FROM_ERP]
 ,CASE MAX([A].[IS_FROM_SONDA])
    WHEN 1 THEN 'Si'
    WHEN 0 THEN 'No'
    ELSE 'No'
  END AS [IS_FROM_SONDA]
 ,CASE
    WHEN MAX([A].[LOCATION_SPOT_TARGET]) <> MIN([A].[TASK_ASSIGNEDTO]) THEN 'Multiple'
    WHEN MAX([A].[LOCATION_SPOT_TARGET]) = MIN([A].[LOCATION_SPOT_TARGET]) THEN MAX([A].[LOCATION_SPOT_TARGET])
  END AS [LOCATION_SPOT_TARGET]
 ,MAX([A].[WAREHOUSE_SOURCE]) AS [WAREHOUSE_SOURCE]
 ,MAX([A].[TASK_ASSIGNEDTO]) [TASK_ASSIGNEDTO]
 ,MAX([A].[PRIORITY]) AS [PRIORITY]
 ,[A].[MATERIAL_ID]
 ,SUM([A].[QUANTITY_ASSIGNED]) [QUANTITY_ASSIGNED]
 ,SUM([A].[QUANTITY_PENDING]) [QUANTITY_PENDING]
 ,MAX([A].[TASK_SUBTYPE]) + ISNULL(' - '
  + MAX([PDH].[TYPE_DEMAND_NAME]),
  '') [TASK_SUBTYPE]
 ,MAX([PDH].[DEMAND_TYPE]) AS [SOURCE_TYPE]
 ,MAX([A].[TASK_OWNER]) AS [CREATE_BY]
FROM [wms].[OP_WMS_TASK_LIST] [A]
LEFT JOIN [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH]
  ON [PDH].[WAVE_PICKING_ID] = [A].[WAVE_PICKING_ID]
WHERE [A].[TASK_TYPE] = 'TAREA_REUBICACION'
GROUP BY [A].[WAVE_PICKING_ID]
        ,[A].[MATERIAL_ID];