






/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [wms].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH]
*/
-- =============================================
CREATE VIEW [wms].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH]
AS
(SELECT 
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,SUM(CASE 
				WHEN [IL].[LOCKED_BY_INTERFACES] = 1 AND TL.TASK_TYPE = 'TAREA_RECEPCION' THEN [IL].[QTY]
				ELSE 0
				END) [INVENTORY_IN_RECEPTION]
		,sum(CASE
               WHEN ISNULL([IL].[LOCKED_BY_INTERFACES], 0) = 1 THEN
                   0
               ELSE
           ([il].[QTY] - ISNULL([CI].[COMMITED_QTY], 0))
           END ) as [AVAILABLE]
		--,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,ISNULL ([TW].RESERVADO, 0) AS [EN_TRANSITO]
		--,MAX([PWT].[RESERVADO]) [PICKED_PENDING_ERP_WT]
		,[W].[WAREHOUSE_ID] as [CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
	 FROM
		[wms].[OP_WMS_INV_X_LICENSE] [IL]
		INNER JOIN [wms].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
		INNER JOIN [wms].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
		INNER JOIN [wms].[OP_WMS_SHELF_SPOTS] [S] ON [S].[LOCATION_SPOT] = [L].[CURRENT_LOCATION]
		INNER JOIN [wms].[OP_WMS_WAREHOUSES] [W] ON [S].[WAREHOUSE_PARENT] = [W].[WAREHOUSE_ID]
		LEFT JOIN  [wms].[OP_WMS_VW_GET_TRANSIT_INVENTORY_WT] [TW] ON [TW].WAREHOUSE_TO = [W].WAREHOUSE_ID 
												AND [TW].MATERIAL_ID = [IL].MATERIAL_ID
		LEFT JOIN [wms].[OP_WMS_POLIZA_HEADER] [PH] ON ([PH].[CODIGO_POLIZA] = [L].[CODIGO_POLIZA])
		--LEFT JOIN [wms].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING] [P] ON [P].[MATERIAL_ID] = [IL].[MATERIAL_ID]
		--										AND [P].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		--LEFT JOIN [wms].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING_WT] [PWT] ON [PWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
		--										AND [PWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		-- Inventario sin confirmar
		LEFT JOIN [wms].[OP_WMS_TASK_LIST] [TL] ON (
														CAST(TL.DOC_ID_SOURCE AS VARCHAR) = L.CODIGO_POLIZA
														)
		-- Para que no tome encuenta el estado DISPATCH
		LEFT JOIN [wms].[OP_WMS_TASK_LIST] [#TL] ON ([L].[CODIGO_POLIZA] = [#TL].[CODIGO_POLIZA_TARGET] )
		LEFT JOIN [wms].[OP_WMS_PASS_DETAIL] [PD] ON ([#TL].[WAVE_PICKING_ID] = [PD].[WAVE_PICKING_ID])
		LEFT JOIN wms.[OP_WMS3PL_PASSES] PS ON (PD.PASS_HEADER_ID = PS.PASS_ID)

		-- Para que tome el inventario disponible
		LEFT JOIN [wms].[OP_WMS_FN_GET_COMMITED_INVENTORY_BY_LICENCE]() [CI]
				ON (
					   [IL].[MATERIAL_ID] = [CI].[MATERIAL_ID]
					   AND [L].[CLIENT_OWNER] = [CI].[CLIENT_OWNER]
					   AND [CI].[LICENCE_ID] = [IL].[LICENSE_ID]
				   )
	WHERE
		[IL].[QTY] > 0
		AND [IL].[STATUS] <> 'DISPATCH'
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [M].[NON_STORAGE] = 0
		--AND [W].[WAREHOUSE_ID] = 'BODEGA_SPS'
		AND [L].[WAVE_PICKING_ID] IS NULL
		--AND [M].[IS_MASTER_PACK] = 0
		AND PS.PASS_ID IS NULL
		--AND [TW].MATERIAL_ID IN ('ALZA/10100', 'ALZA/10101')
		
	GROUP BY
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[W].[WAREHOUSE_ID]
		,[W].[ERP_WAREHOUSE]
		,[TW].[RESERVADO]
	);
