-- =============================================
-- Autor:					rudi.garcia
-- Fecha de Creacion: 		14-Dec-16 @ A-Team Sprint 6
-- Description:			    Se agrego el convert a la condicion poliza asegurada con doc id
-- =============================================

/*
-- Ejemplo de Ejecucion:
				SELECT * FROM [wms].OP_WMS_VIEW_INSURANCE_DOC
*/
-- =============================================


CREATE VIEW [wms].OP_WMS_VIEW_INSURANCE_DOC
AS

SELECT
  ID.DOC_ID
 ,ID.POLIZA_INSURANCE
 ,IC.COMPANY_NAME
 ,ID.AMOUNT
 ,ID.VALIN_TO
 ,VC.CLIENT_NAME
 ,ID.COVERAGE
 ,ID.INSURANCE_OWHEN
 ,ISNULL(SUM(VV.TOTAL_VALOR), 0) AMOUNTINV
 ,ID.AMOUNT - ISNULL(SUM(VV.TOTAL_VALOR), 0) AMOUNTDIF
FROM [wms].OP_WMS_INSURANCE_DOCS ID
INNER JOIN [wms].OP_WMS_INSURANCE_COMPANIES IC ON (
  ID.COMPANY_ID = IC.COMPANY_ID
)
INNER JOIN [wms].OP_WMS_VIEW_CLIENTS VC ON (
  ID.CLIENT_CODE = VC.CLIENT_CODE COLLATE database_default
)
LEFT JOIN [wms].OP_WMS_POLIZA_HEADER PH ON (
  PH.POLIZA_ASEGURADA = CONVERT(VARCHAR, ID.DOC_ID)
)
LEFT JOIN [wms].OP_WMS_VIEW_VALORIZACION VV ON (
  VV.CODIGO_POLIZA = PH.CODIGO_POLIZA
)
GROUP BY  
  ID.DOC_ID
 ,ID.POLIZA_INSURANCE
 ,IC.COMPANY_NAME
 ,ID.AMOUNT
 ,ID.VALIN_TO
 ,VC.CLIENT_NAME
 ,ID.COVERAGE
 ,ID.INSURANCE_OWHEN

UNION
SELECT
  0 AS DOC_ID
 ,C.TEXT_VALUE AS POLIZA_INSURANCE
 ,C.SPARE1 AS COMPANY_NAME
 ,CONVERT(MONEY, C.MONEY_VALUE) AS AMOUNT
 ,CONVERT(DATE, C.RANGE_DATE_END) AS VALIN_TO
 ,C.PARAM_CAPTION AS CLIENT_NAME
 ,C.SPARE2 AS COVERAGE
 ,'PROPIA' AS INSURANCE_OWHEN
 ,ISNULL(SUM(VV.TOTAL_VALOR), 0) AS AMOUNTINV
 ,CONVERT(MONEY, C.MONEY_VALUE) - ISNULL(SUM(VV.TOTAL_VALOR), 0) AS AMOUNTDIF
FROM [wms].OP_WMS_CONFIGURATIONS C
LEFT JOIN [wms].OP_WMS_POLIZA_HEADER PH ON (
  PH.POLIZA_ASEGURADA = C.TEXT_VALUE
)
LEFT JOIN [wms].OP_WMS_VIEW_VALORIZACION VV ON (
  VV.CODIGO_POLIZA = PH.CODIGO_POLIZA
)
WHERE PARAM_TYPE = 'POLIZAS'
AND PARAM_GROUP = 'POLIZAS_SEGUROS'
GROUP BY
  C.TEXT_VALUE
  ,C.SPARE1
  ,C.MONEY_VALUE
  ,C.RANGE_DATE_END
  ,C.PARAM_CAPTION
  ,C.SPARE2



/*SELECT
  DOC_ID
 ,POLIZA_INSURANCE
 ,COMPANY_NAME
 ,AMOUNT
 ,VALIN_TO
 ,CLIENT_NAME
 ,COVERAGE
 ,INSURANCE_OWHEN
 ,(SELECT
      ISNULL(SUM(TOTAL_VALOR), 0)
    FROM [wms].OP_WMS_VIEW_VALORIZACION V
    JOIN [wms].OP_WMS_POLIZA_HEADER P
      ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
    WHERE POLIZA_ASEGURADA = convert(VARCHAR,isd.DOC_ID))
  AS AMOUNTINV
 ,AMOUNT - (SELECT
      ISNULL(SUM(TOTAL_VALOR), 0)
    FROM [wms].OP_WMS_VIEW_VALORIZACION V
    JOIN [wms].OP_WMS_POLIZA_HEADER P
      ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
    WHERE POLIZA_ASEGURADA = CONVERT(varchar,isd.DOC_ID))
  AS AMOUNTDIF
FROM [wms].OP_WMS_INSURANCE_DOCS isd
INNER JOIN [wms].OP_WMS_INSURANCE_COMPANIES isc
  ON isd.COMPANY_ID = isc.COMPANY_ID
INNER JOIN [wms].OP_WMS_VIEW_CLIENTS vc
  ON isd.CLIENT_CODE = vc.CLIENT_CODE COLLATE database_default
UNION
SELECT
  0 AS DOC_ID
 ,C.TEXT_VALUE AS POLIZA_INSURANCE
 ,SPARE1 AS COMPANY_NAME
 ,CONVERT(MONEY, MONEY_VALUE) AS AMOUNT
 ,CONVERT(DATE, RANGE_DATE_END) AS VALIN_TO
 ,C.PARAM_CAPTION AS CLIENT_NAME
 ,SPARE2 AS COVERAGE
 ,'PROPIA' AS INSURANCE_OWHEN
 ,(SELECT
      ISNULL(SUM(TOTAL_VALOR), 0)
    FROM [wms].OP_WMS_VIEW_VALORIZACION V
    JOIN [wms].OP_WMS_POLIZA_HEADER P
      ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
    WHERE POLIZA_ASEGURADA = C.TEXT_VALUE)
  AS AMOUNTINV
 ,CONVERT(MONEY, MONEY_VALUE) - (SELECT
      ISNULL(SUM(TOTAL_VALOR), 0)
    FROM [wms].OP_WMS_VIEW_VALORIZACION V
    JOIN [wms].OP_WMS_POLIZA_HEADER P
      ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
    WHERE POLIZA_ASEGURADA = C.TEXT_VALUE)
  AS AMOUNTDIF
FROM [wms].OP_WMS_CONFIGURATIONS C
WHERE PARAM_TYPE = 'POLIZAS'
AND PARAM_GROUP = 'POLIZAS_SEGUROS'*/