


CREATE VIEW [wms].[OP_WMS_VIEW_INVENTORY_TRANS_CURRENT_MONTH]
AS

SELECT 
	ISNULL((SELECT REGIMEN FROM [wms].OP_WMS_LICENSES WHERE LICENSE_ID = A.SOURCE_LICENSE),'N/A') AS REGIMEN,
	A.TRANS_DATE, 
	A.LOGIN_NAME, 
	A.TRANS_DESCRIPTION, 
	A.SOURCE_LICENSE,
	A.TARGET_LICENSE,
	A.MATERIAL_CODE, 
	A.MATERIAL_BARCODE, 
	A.MATERIAL_DESCRIPTION,
	A.QUANTITY_UNITS,
	A.CLIENT_OWNER,
	A.CLIENT_NAME,
	A.CODIGO_POLIZA,
	ISNULL((SELECT TOP 1 NUMERO_ORDEN FROM [wms].OP_WMS_POLIZA_HEADER WHERE CODIGO_POLIZA = A.CODIGO_POLIZA),'N/A') AS NUMERO_ORDEN,
	A.WAVE_PICKING_ID
FROM 
	[wms].OP_WMS_TRANS A
WHERE 
	A.TRANS_DATE >= DATEADD(MONTH, DATEDIFF(MONTH, 0, getDate())    , 0) AND 
	A.TRANS_DATE <  DATEADD(MONTH, DATEDIFF(MONTH, 0, getDate()) + 1, 0)