CREATE VIEW [wms].[OP_WMS_VIEW_COUNT_TRANSACTION_BY_USER]
AS
SELECT
	SUBSTRING([T].[LOGIN_ID], 0,
				IIF(CHARINDEX('@', [T].[LOGIN_ID]) = 0, LEN([T].[LOGIN_ID])
				+ 1, CHARINDEX('@', [T].[LOGIN_ID]))) [USUARIO]
	,[T].[TRANS_TYPE] [TIPO_TRANSACCION]
	,ISNULL((SELECT TOP 1
					[PARAM_CAPTION]
				FROM
					[wms].[OP_WMS_CONFIGURATIONS] [C]
				WHERE
					[PARAM_GROUP] = 'TRANS_TYPES'
					AND [PARAM_GROUP_CAPTION] = 'TIPOS DE TRANSACCIONES'
					AND [C].[PARAM_NAME] = [T].[TRANS_TYPE]),
			[T].[TRANS_TYPE]) [DESCRIPCION_TIPO_TRANSACCION]
	,CAST([T].[TRANS_DATE] AS DATE) [FECHA_TRANSACCION]
	,SUM([T].[QUANTITY_UNITS]) [UNIDADES]
FROM
	[wms].[OP_WMS_TRANS] [T]
WHERE
	[T].[STATUS] = 'PROCESSED'
GROUP BY
	SUBSTRING([T].[LOGIN_ID], 0,
				IIF(CHARINDEX('@', [T].[LOGIN_ID]) = 0, LEN([T].[LOGIN_ID])
				+ 1, CHARINDEX('@', [T].[LOGIN_ID])))
	,[T].[TRANS_TYPE]
	,CAST([T].[TRANS_DATE] AS DATE);