
CREATE VIEW [wms].[OP_WMS_VIEW_OCCUPANCY_LEVEL]
AS
SELECT     INPUT_DATE, LOCATION_SPOT, OCCUPANCY_LEVEL, SUBSTRING(LOCATION_SPOT, 1, 3) AS WAREHOUSE_OWNER, SUBSTRING(LOCATION_SPOT, 4, 3) AS TRAMO,
                          (SELECT     ISNULL(MAX_MT2_OCCUPANCY, 0) AS Expr1
                            FROM          [wms].OP_WMS_SHELF_SPOTS
                            WHERE      (LOCATION_SPOT = A.LOCATION_SPOT)) AS MAX_MT2_OCCUPANCY,
                          (SELECT     ISNULL(MAX_MT2_OCCUPANCY, 0) AS Expr1
                            FROM          [wms].OP_WMS_SHELF_SPOTS AS OP_WMS_SHELF_SPOTS_1
                            WHERE      (LOCATION_SPOT = A.LOCATION_SPOT)) * (OCCUPANCY_LEVEL / 100) AS OCCUPANCY_MT2, WAREHOUSE_PARENT, SPOT_TYPE, LAST_UPDATED, 
                      LAST_UPDATED_BY
FROM         [wms].OP_WMS_OCCUPANCY_LEVEL AS A