-- =============================================
-- Autor:					rudi.garcia
-- Fecha de Creacion: 		27-06-2016
-- Description:			    Obtiene el las transacciones

-- Modificacion 03-10-2016 @ A-TEAM Sprint 2
-- juancarlos.escalante
-- Se agregó la columna TASK_ID en el select

-- Modificacion 27-01-2017 @ Team ERGON - Sprint ERGON II
-- hecto.gonzalez
-- se modifico para que tome en cuenta las transacciones explode

/*
-- Ejemplo de Ejecucion:
		--
		SELECT * FROM [wms].OP_WMS_VIEW_TRANS_BASIC
		-- 
*/
-- =============================================

CREATE VIEW [wms].[OP_WMS_VIEW_TRANS_BASIC]
AS
SELECT
	[A].[SERIAL_NUMBER] AS [SERIAL]
	,MAX([A].[TRANS_WEIGTH]) AS [TRANS_WEIGTH]
	,MAX([A].[TERMS_OF_TRADE]) AS [TERMS_OF_TRADE]
	,MAX([A].[LOGIN_ID]) AS [LOGIN_ID]
	,MAX([A].[LOGIN_NAME]) AS [LOGIN_NAME]
	,MAX([A].[TRANS_TYPE]) AS [TRANS_TYPE]
	,MAX([A].[TRANS_DESCRIPTION]) AS [TRANS_DESCRIPTION]
	,[A].[MATERIAL_BARCODE]
	,MAX([A].[MATERIAL_CODE]) AS [MATERIAL_CODE]
	,MAX([A].[MATERIAL_DESCRIPTION]) AS [MATERIAL_DESCRIPTION]
	,MAX([A].[SOURCE_LICENSE]) AS [SOURCE_LICENSE]
	,[A].[TARGET_LICENSE]
	,MAX([A].[SOURCE_LOCATION]) AS [SOURCE_LOCATION]
	,MAX([A].[TARGET_LOCATION]) AS [TARGET_LOCATION]
	,MAX([A].[CLIENT_OWNER]) AS [CLIENT_OWNER]
	,MAX([A].[CLIENT_NAME]) AS [CLIENT_NAME]
	,SUM([A].[QUANTITY_UNITS]) AS [QUANTITY_UNITS]
	,MAX([A].[SOURCE_WAREHOUSE]) AS [SOURCE_WAREHOUSE]
	,MAX([A].[TARGET_WAREHOUSE]) AS [TARGET_WAREHOUSE]
 --,A.CODIGO_POLIZA
	,MAX(ISNULL([B].[NUMERO_ORDEN], [A].[CODIGO_POLIZA])) [CODIGO_POLIZA]
	,MAX([A].[LICENSE_ID]) AS [LICENSE_ID]
	,MAX([A].[STATUS]) AS [STATUS]
	,MAX([A].[WAVE_PICKING_ID]) AS [WAVE_PICKING_ID]
	,MAX([B].[NUMERO_ORDEN]) AS [NUMERO_ORDEN]
	,MAX([A].[TRANS_DATE]) AS [TRANS_DATE]
	,(CASE MAX([TRANS_TYPE])
		WHEN 'EXPLODE_IN' THEN 'EXPLOSION ENTRADA'
		WHEN 'EXPLODE_OUT' THEN 'EXPLOSION SALIDA'
		WHEN 'DESPACHO_FISCAL' THEN 'FISCAL'
		WHEN 'TRASLADO_GENERAL' THEN 'FISCAL'
		WHEN 'INGRESO_FISCAL' THEN 'FISCAL'
		WHEN 'DESPACHO_GENERAL' THEN 'GENERAL'
		WHEN 'INGRESO_GENERAL' THEN 'GENERAL'
		WHEN 'RECEP_GENERAL_X_TRASLADO' THEN 'GENERAL'
		WHEN 'INICIALIZACION_GENERAL' THEN 'GENERAL'
		WHEN 'INICIALIZACION_FISCAL' THEN 'FISCAL'
		WHEN 'REUBICACION_PARCIAL'
		THEN (SELECT
					[REGIMEN]
				FROM
					[wms].[OP_WMS_LICENSES]
				WHERE
					[LICENSE_ID] = MAX([A].[SOURCE_LICENSE]))
		END) AS [REGIMEN]
	,(CASE MAX([TRANS_TYPE])
		WHEN 'EXPLODE_IN' THEN '+'
		WHEN 'EXPLODE_OUT' THEN '-'
		WHEN 'DESPACHO_FISCAL' THEN '+'
		WHEN 'TRASLADO_GENERAL' THEN '-'
		WHEN 'INGRESO_FISCAL' THEN '+'
		WHEN 'DESPACHO_GENERAL' THEN '-'
		WHEN 'INGRESO_GENERAL' THEN '+'
		WHEN 'RECEP_GENERAL_X_TRASLADO' THEN '+'
		WHEN 'INICIALIZACION_GENERAL' THEN 'NA'
		WHEN 'INICIALIZACION_FISCAL' THEN 'NA'
		WHEN 'REUBICACION_PARCIAL' THEN 'NA'
		END) AS [ACTION]
	,[A].[POSTED_TO_ERP_STAMP]
	,[A].[VIN]
	,MAX([A].[TASK_ID]) AS [TASK_ID]
FROM
	[wms].[OP_WMS_TRANS] AS [A]
LEFT JOIN [wms].[OP_WMS_POLIZA_HEADER] AS [B] ON [A].[CODIGO_POLIZA] = [B].[CODIGO_POLIZA]
WHERE
	[A].[STATUS] = 'PROCESSED'
	AND [TRANS_TYPE] NOT IN ('REUBICACION_COMPLETA',
								'REUBICACION_PARCIAL')
GROUP BY
	[A].[SERIAL_NUMBER]
	,[A].[TARGET_LICENSE]
	,[A].[MATERIAL_BARCODE]
	,[A].[CODIGO_POLIZA]
	,[A].[POSTED_TO_ERP_STAMP]
	,[A].[VIN];