
CREATE VIEW [wms].[OP_WMS_VIEW_REPORTES_S1]
AS
SELECT     'FISCAL' AS REGIMEN, A.CLIENT_OWNER, A.CLIENT_NAME, A.BARCODE_ID, A.MATERIAL_NAME, A.BODEGA, SUM(A.QTY) AS QTY, SUM(A.TOTAL_VALOR) 
                      AS TOTAL_VALOR, SUM(A.TOTAL_VOLUMEN) AS TOTAL_VOLUMEN, A.MATERIAL_CLASS
FROM         [wms].OP_WMS_VIEW_REPORTES_FISCAL A
WHERE     A.CLIENT_OWNER NOT IN ('1', '0042', '0043', '0044', '0045', '0046', '0047', '0048', '0049', '0035', '0038', '2') AND A.QTY > 0
GROUP BY A.CLIENT_OWNER, A.CLIENT_NAME, A.bARCODE_ID, A.MATERIAL_NAME, A.BODEGA, A.MATERIAL_CLASS
UNION
SELECT     'GENERAL' AS REGIMEN, A.CLIENT_OWNER, A.CLIENT_NAME, A.BARCODE_ID, A.MATERIAL_NAME, A.BODEGA, SUM(A.QTY) AS QTY, SUM(A.TOTAL_VALOR) 
                      AS TOTAL_VALOR, SUM(A.TOTAL_VOLUMEN) AS TOTAL_VOLUMEN, A.MATERIAL_CLASS
FROM         [wms].OP_WMS_VIEW_REPORTES_ALMGEN A
WHERE     A.CLIENT_OWNER NOT IN ('1', '0042', '0043', '0044', '0045', '0046', '0047', '0048', '0049', '0035', '0038', '2') AND A.QTY > 0
GROUP BY A.CLIENT_OWNER, A.CLIENT_NAME, A.bARCODE_ID, A.MATERIAL_NAME, A.BODEGA, A.MATERIAL_CLASS