-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	20-05-2018 @ Sprint Capibara???
-- Description:			Obtiene el encabezado de los pickings detallado

-- Autor:				rudi.garcia
-- Fecha de Creacion: 	02-Jan-2019 @ Sprint Perezoso
-- Description:			Se agrego la columna de quien creo la tarea.

/*
	Ejemplo Ejecucion: 
    SELECT * FROM [wms].[OP_WMS_VIEW_TASK_PICKING_HEADER_DETAILED]
	where wave_picking_id = 598
 */
-- =============================================

CREATE VIEW [wms].[OP_WMS_VIEW_TASK_PICKING_HEADER_DETAILED]
AS
SELECT
  MAX([A].[SERIAL_NUMBER]) AS [SERIAL_NUMBER]
 ,[A].[WAVE_PICKING_ID] AS [WAVE_PICKING_ID]
 ,MAX([A].[TASK_TYPE]) AS [TASK_TYPE]
 ,MAX([A].[TASK_COMMENTS]) AS [TASK_COMMENTS]
 ,MAX([A].[REGIMEN]) AS [REGIMEN]
 ,MAX([A].[IS_PAUSED]) AS [IS_PAUSED]
 ,MAX([A].[ASSIGNED_DATE]) AS [ASSIGNED_DATE]
 ,MAX([A].[ACCEPTED_DATE]) AS [ACCEPTED_DATE]
 ,MAX([A].[COMPLETED_DATE]) AS [PICKING_FINISHED_DATE]
 ,MIN([A].[IS_CANCELED]) AS [IS_CANCELED]
 ,MAX([PHS].[NUMERO_ORDEN]) AS [NUMERO_ORDEN_SOURCE]
 ,MAX([PHT].[NUMERO_ORDEN]) AS [NUMERO_ORDEN_TARGET]
 ,NULL AS [CODIGO_POLIZA_SOURCE]
 ,MAX([A].[CODIGO_POLIZA_TARGET]) AS [CODIGO_POLIZA_TARGET]
 ,CASE MIN([A].[IS_COMPLETED])
    WHEN 0 THEN CASE MAX([A].[IS_ACCEPTED])
        WHEN 0 THEN 'INCOMPLETA'
        WHEN 1 THEN 'ACEPTADA'
        ELSE 'INCOMPLETA'
      END
    ELSE 'COMPLETA'
  END AS [IS_COMPLETED]
 ,MAX([A].[IS_DISCRETIONARY]) AS [IS_DISCRETIONARY]
 ,CASE MAX([A].[IS_DISCRETIONARY])
    WHEN 1 THEN 'Discrecional'
    ELSE 'Dirigido'
  END AS [TYPE_PICKING]
 ,MAX([A].[IS_ACCEPTED]) AS [IS_ACCEPTED]
 ,CASE MAX([A].[IS_FROM_ERP])
    WHEN 1 THEN 'Si'
    WHEN 0 THEN 'No'
    ELSE 'No'
  END AS [IS_FROM_ERP]
 ,CASE MAX([A].[IS_FROM_SONDA])
    WHEN 1 THEN 'Si'
    WHEN 0 THEN 'No'
    ELSE 'No'
  END AS [IS_FROM_SONDA]
 ,MAX([A].[LOCATION_SPOT_TARGET]) AS [LOCATION_SPOT_TARGET]
 ,MAX([A].[WAREHOUSE_SOURCE]) AS [WAREHOUSE_SOURCE]
 ,MAX([A].[TASK_ASSIGNEDTO]) [TASK_ASSIGNEDTO]
 ,MAX([A].[PRIORITY]) AS [PRIORITY]
 ,[A].[MATERIAL_ID]
 ,SUM([A].[QUANTITY_ASSIGNED]) [QUANTITY_ASSIGNED]
 ,SUM([A].[QUANTITY_PENDING]) [QUANTITY_PENDING]
 ,CASE
    WHEN MAX([A].[TASK_SUBTYPE]) = 'DESPACHO_GENERAL' AND
      MAX([PDH].[PICKING_DEMAND_HEADER_ID]) IS NOT NULL THEN 'DESPACHO_PEDIDO' + ISNULL(' - '
      + MAX([PDH].[TYPE_DEMAND_NAME]),
      '')
    ELSE MAX([A].[TASK_SUBTYPE]) + ISNULL(' - '
      + MAX([PDH].[TYPE_DEMAND_NAME]),
      '')
  END [TASK_SUBTYPE]
 ,MAX([PDH].[CODE_ROUTE]) [CODE_ROUTE]
 ,MAX([PDH].[DEMAND_TYPE]) [SOURCE_TYPE]
 ,CASE
    WHEN (
      MAX([W].[USE_PICKING_LINE]) = 1 AND
      (
      MAX([PDH].[IS_FROM_ERP]) = 1 OR
      MAX([PDH].[IS_FROM_SONDA]) = 1
      )
      ) THEN 1
    ELSE 0
  END AS [USE_PICKING_LINE]
 ,COALESCE(MAX([PDH].[IS_AUTHORIZED]),
  MAX([PD].[IS_AUTHORIZED]), 0) [IS_AUTHORIZED]
 ,ISNULL(MAX([PDH].[ERP_REFERENCE_DOC_NUM]),
  MAX([PD].[ERP_REFERENCE_DOC_NUM])) [ERP_REFERENCE]
 ,ISNULL(MAX([PDH].[POSTED_ERP]), MAX([PD].[POSTED_ERP])) [POSTED_ERP]
 ,ISNULL(MAX([PDH].[POSTED_RESPONSE]),
  MAX([PD].[POSTED_RESPONSE])) [POSTED_RESPONSE]
 ,CASE
    WHEN COALESCE(MAX([PDH].[IS_POSTED_ERP]),
      MAX([PD].[IS_POSTED_ERP]), 0) = -1 THEN 'Fallido'
    WHEN COALESCE(MAX([PDH].[IS_POSTED_ERP]),
      MAX([PD].[IS_POSTED_ERP]), 0) = 0 AND
      ISNULL(MAX([PDH].[IS_AUTHORIZED]), 0) = 1 THEN 'Autorizada'
    WHEN COALESCE(MAX([PDH].[IS_POSTED_ERP]),
      MAX([PD].[IS_POSTED_ERP]), 0) = 0 AND
      COALESCE(MAX([PDH].[IS_AUTHORIZED]),
      MAX([PD].[IS_AUTHORIZED]),
      0) = 0 THEN 'Pendiente de Autorización'
    WHEN COALESCE(MAX([PDH].[IS_POSTED_ERP]),
      MAX([PD].[IS_POSTED_ERP]), 0) = 1 THEN 'Enviado'
  END [STATUS_POSTED_ERP]
 ,COALESCE(MAX([PDH].[IS_POSTED_ERP]),
  MAX([PD].[IS_POSTED_ERP]), 0) [IS_POSTED_ERP]
 ,CASE
    WHEN MAX([PDH].[IS_CONSOLIDATED]) = 1 THEN 'CONSOLIDADO'
    WHEN MAX([PDH].[IS_CONSOLIDATED]) IS NULL AND
      MAX([PD].[PICKING_ERP_DOCUMENT_ID]) IS NULL THEN CAST([A].[WAVE_PICKING_ID] AS VARCHAR)
    WHEN MAX([PDH].[IS_CONSOLIDATED]) IS NULL THEN CAST(ISNULL(MAX([PD].[WAVE_PICKING_ID]), '') AS VARCHAR)
    ELSE CAST(MAX([PDH].[DOC_NUM]) AS VARCHAR)
  END [NO_DOC]
  --ISNULL(MAX([PDH].[DOC_NUM]), MAX([PD].[WAVE_PICKING_ID])) AS [NO_DOC]
 ,ISNULL(MAX([PDH].[PICKING_DEMAND_HEADER_ID]),
  MAX([PD].[PICKING_ERP_DOCUMENT_ID])) [WMS_DOCUMENT_HEADER_ID]
 ,COALESCE(MAX([PDH].[DOC_NUM]),
  MAX([PD].[WAVE_PICKING_ID]),
  [A].[WAVE_PICKING_ID]) [DOC_ID]
 ,ISNULL(MAX([PDH].[ATTEMPTED_WITH_ERROR]),
  MAX([PD].[ATTEMPTED_WITH_ERROR])) [ATTEMPTED_WITH_ERROR]
 ,CASE
    WHEN MAX([PDH].[IS_CONSOLIDATED]) = 1 THEN 'CONSOLIDADO'
    WHEN MAX([PDH].[IS_CONSOLIDATED]) IS NULL THEN MAX([A].[CLIENT_NAME])
    ELSE MAX([PDH].[CLIENT_NAME])
  END [CLIENT_NAME]
 ,MAX([A].[TASK_OWNER]) AS [CREATE_BY]
FROM [wms].[OP_WMS_TASK_LIST] [A]
INNER JOIN [wms].[OP_WMS_WAREHOUSES] [W]
  ON [A].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
LEFT OUTER JOIN [wms].[OP_WMS_POLIZA_HEADER] [PHS]
  ON [PHS].[DOC_ID] = [A].[DOC_ID_SOURCE]
  AND [PHS].[WAREHOUSE_REGIMEN] = [A].[REGIMEN]
LEFT OUTER JOIN [wms].[OP_WMS_POLIZA_HEADER] [PHT]
  ON [PHT].[DOC_ID] = [A].[DOC_ID_TARGET]
  AND [PHT].[WAREHOUSE_REGIMEN] = [A].[REGIMEN]
LEFT JOIN [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH]
  ON ([A].[WAVE_PICKING_ID] = [PDH].[WAVE_PICKING_ID])
LEFT JOIN [wms].[OP_WMS_PICKING_ERP_DOCUMENT] [PD]
  ON [PD].[WAVE_PICKING_ID] = [A].[WAVE_PICKING_ID]
WHERE [A].[TASK_TYPE] = 'TAREA_PICKING'
GROUP BY [A].[WAVE_PICKING_ID]
        ,[A].[MATERIAL_ID];
--,A.CODIGO_POLIZA_TARGET