
CREATE VIEW [wms].[OP_WMS_VIEW_AUDIT_RECEPTION]
AS
--SELECT     AUDIT_ID, ISNULL
--                          ((SELECT     CODIGO_POLIZA
--                              FROM         [wms].OP_WMS_AUDIT_RECEPTION_CONTROL AS B
--                              WHERE     (AUDIT_ID = A.AUDIT_ID)), 'N/A') AS CODIGO_POLIZA, ISNULL
--                          ((SELECT     CONTENEDOR
--                              FROM         [wms].OP_WMS_AUDIT_RECEPTION_CONTROL AS B
--                              WHERE     (AUDIT_ID = A.AUDIT_ID)), 'N/A') AS CONTENEDOR, MATERIAL_ID, BARCODE_ID, MATERIAL_NAME, 
--                      CASE A.SCANNED_COUNT WHEN 0 THEN A.INPUTED_COUNT ELSE A.SCANNED_COUNT END AS QTY
--FROM         [wms].OP_WMS_AUDIT_RECEPTION_SKUS AS A
SELECT A.AUDIT_ID
	, ISNULL ((SELECT CODIGO_POLIZA
				FROM [wms].OP_WMS_AUDIT_RECEPTION_CONTROL AS B
				WHERE (AUDIT_ID = A.AUDIT_ID)), 'N/A') AS CODIGO_POLIZA
	, ISNULL ((SELECT CONTENEDOR
				FROM [wms].OP_WMS_AUDIT_RECEPTION_CONTROL AS B
                WHERE (AUDIT_ID = A.AUDIT_ID)), 'N/A') AS CONTENEDOR
    , A.MATERIAL_ID
    , BARCODE_ID
    , MATERIAL_NAME
    , CASE A.SCANNED_COUNT WHEN 0 THEN A.INPUTED_COUNT ELSE A.SCANNED_COUNT END AS QTY    
    , S.SERIAL_NUMBER
    , (SELECT COUNTING_METHOD
		FROM [wms].OP_WMS_AUDIT_RECEPTION_CONTROL B
		WHERE A.AUDIT_ID = B.AUDIT_ID) AS COUNTING_METHOD
FROM [wms].OP_WMS_AUDIT_RECEPTION_SKUS AS A
	LEFT JOIN [wms].OP_WMS_AUDIT_RECEPTION_SERIES S ON A.MATERIAL_ID = S.MATERIAL_ID AND A.AUDIT_ID = S.AUDIT_ID