
CREATE VIEW [wms].[OP_WMS3PL_VIEW_POLIZA_MATERIAL_MATCH]
AS
SELECT     pm.CODIGO_POLIZA, pm.LINENO_POLIZA,
                          (SELECT     SUM(QTY) AS Expr1
                            FROM          [wms].OP_WMS_VIEW_INVENTORY_DETAIL_FISCAL AS Z
                            WHERE      (MATERIAL_ID = pm.MATERIAL_CODE) AND (CODIGO_POLIZA = pm.CODIGO_POLIZA)) AS QTY_TRANS, pm.DOC_ID, pm.MATERIAL_CODE, 
                      mt.BARCODE_ID, mt.ALTERNATE_BARCODE, mt.MATERIAL_NAME
		,(SELECT SUM(QTY) AS Expr1
					FROM [wms].OP_WMS_VIEW_INVENTORY_DETAIL_FISCAL AS Z
					WHERE (MATERIAL_ID = pm.MATERIAL_CODE) AND (CODIGO_POLIZA = pm.CODIGO_POLIZA)) - ISNULL(MAX(its.QTY), 0) AS AVAILABLE			
		, (SELECT     SUM(QTY) AS Expr1
                            FROM          [wms].OP_WMS_VIEW_INVENTORY_DETAIL_FISCAL AS Z
                            WHERE      (MATERIAL_ID = pm.MATERIAL_CODE) AND (CODIGO_POLIZA = pm.CODIGO_POLIZA)) AS QTY
					
FROM [wms].OP_WMS3PL_POLIZA_TRANS_MATCH AS pm INNER JOIN
		[wms].OP_WMS_MATERIALS AS mt ON mt.MATERIAL_ID = pm.MATERIAL_CODE
		
		LEFT OUTER JOIN
	(
		select Cantidades.MATERIAL_ID as MATERIAL_ID, SUM(Cantidades.QUANTITY_PENDING) AS QTY, Cantidades.CODIGO_POLIZA_SOURCE
		from (
				select wave_picking_id, QUANTITY_PENDING, MATERIAL_ID, CODIGO_POLIZA_SOURCE
				from [wms].OP_WMS_TASK_LIST
				WHERE (IS_COMPLETED <> 1) AND (IS_PAUSED <> 3) 
				AND (CANCELED_DATETIME IS NULL)
				AND REGIMEN = 'FISCAL'
				group by wave_picking_id, QUANTITY_PENDING, MATERIAL_ID, CODIGO_POLIZA_SOURCE
		) as Cantidades
		GROUP BY Cantidades.MATERIAL_ID, Cantidades.CODIGO_POLIZA_SOURCE
	) AS its ON (mt.MATERIAL_ID = its.MATERIAL_ID AND pm.CODIGO_POLIZA = its.CODIGO_POLIZA_SOURCE)
                      
GROUP BY pm.CODIGO_POLIZA, pm.LINENO_POLIZA, pm.DOC_ID, pm.MATERIAL_CODE, mt.BARCODE_ID, mt.ALTERNATE_BARCODE, mt.MATERIAL_NAME