
CREATE VIEW [wms].[OP_WMS_VIEW_MOVIMIENTO_X_SKU]
AS
SELECT     A.SERIAL_NUMBER, A.TRANS_DATE, A.TRANS_DESCRIPTION, A.CODIGO_POLIZA, C.NUMERO_ORDEN, A.CLIENT_NAME, C.REGIMEN, A.MATERIAL_BARCODE, 
                      A.MATERIAL_DESCRIPTION, A.QUANTITY_UNITS AS ENTRADA, '0 ' AS SALIDA, D .MATERIAL_ID, D .MATERIAL_NAME, A.QUANTITY_UNITS AS CANTIDAD
FROM         [wms].OP_WMS_TRANS A LEFT JOIN
                      [wms].OP_WMS_LICENSES B ON A.LICENSE_ID = B.LICENSE_ID LEFT JOIN
                      [wms].OP_WMS_POLIZA_HEADER C ON B.CODIGO_POLIZA = C.CODIGO_POLIZA AND B.REGIMEN = C.WAREHOUSE_REGIMEN LEFT JOIN
                      [wms].OP_WMS_MATERIALS D ON A.MATERIAL_BARCODE = D .ALTERNATE_BARCODE
WHERE     A.TRANS_DESCRIPTION LIKE 'IN%'
UNION
SELECT     A.SERIAL_NUMBER, A.TRANS_DATE, A.TRANS_DESCRIPTION, A.CODIGO_POLIZA, C.NUMERO_ORDEN, A.CLIENT_NAME, C.REGIMEN, A.MATERIAL_BARCODE, 
                      A.MATERIAL_DESCRIPTION, '0', A.QUANTITY_UNITS AS SALIDA, D .MATERIAL_ID, D .MATERIAL_NAME, A.QUANTITY_UNITS AS CANTIDAD
FROM         [wms].OP_WMS_TRANS A LEFT JOIN
                      [wms].OP_WMS_LICENSES B ON A.LICENSE_ID = B.LICENSE_ID LEFT JOIN
                      [wms].OP_WMS_POLIZA_HEADER C ON A.CODIGO_POLIZA = C.CODIGO_POLIZA AND B.REGIMEN = C.WAREHOUSE_REGIMEN LEFT JOIN
                      [wms].OP_WMS_MATERIALS D ON A.MATERIAL_BARCODE = D .ALTERNATE_BARCODE
WHERE     (A.TRANS_DESCRIPTION LIKE 'TRA%' OR
                      A.TRANS_DESCRIPTION LIKE 'DES%')