CREATE VIEW [wms].OP_WMS_VIEW_AUDIT_DISPATCH_CERTIFICATES
AS
SELECT
  A.AUDIT_ID
 ,A.CODIGO_POLIZA
 ,A.MATERIAL_ID
 ,C.BARCODE_ID
 ,A.MATERIAL_NAME
 ,ADC.STATUS
 ,ADC.NUMERO_ORDEN
 ,ADC.LAST_UPDATED
 ,CASE A.SCANNED_COUNT
    WHEN 0 THEN A.INPUTED_COUNT
    ELSE A.SCANNED_COUNT
  END AS QTY
 ,S.SERIAL_NUMBER
 ,[PH].[TIPO]
 ,ADC.COUNTING_METHOD
 ,'' AS PACKING
 ,[CDD].[CERTIFICATE_DEPOSIT_ID_HEADER]
 ,(SELECT TOP 1  [VUA].[VALOR_UNITARIO] from [wms].[OP_WMS_FUNC_GET_SKU_VALOR_UNITARIO_ALMGEN]([PH].[DOC_ID], '%' + [C].[BARCODE_ID] + '%') VUA) AS UNIT_VALUE
 ,(SELECT TOP 1  [VUA].[VALOR_UNITARIO] * ((CASE A.SCANNED_COUNT
    WHEN 0 THEN A.INPUTED_COUNT
    ELSE A.SCANNED_COUNT
  END) * -1) from [wms].[OP_WMS_FUNC_GET_SKU_VALOR_UNITARIO_ALMGEN]([PH].[DOC_ID], '%' + [C].[BARCODE_ID] + '%') VUA) AS TOTAL_LINE 
FROM [wms].OP_WMS_AUDIT_DISPATCH_SKUS AS A
INNER JOIN [wms].OP_WMS_AUDIT_DISPATCH_CONTROL AS ADC ON (
  A.AUDIT_ID = ADC.AUDIT_ID
)
INNER JOIN [wms].OP_WMS_MATERIALS AS C ON (
  A.MATERIAL_ID = C.MATERIAL_ID
)
LEFT JOIN [wms].OP_WMS_AUDIT_DISPATCH_SERIES AS S ON (
  A.MATERIAL_ID = S.MATERIAL_ID
  AND A.AUDIT_ID = S.AUDIT_ID
)
LEFT JOIN [wms].[OP_WMS_TASK_LIST] [TL] ON(
  [TL].[CODIGO_POLIZA_TARGET] = [ADC].[CODIGO_POLIZA]
)
LEFT JOIN [wms].[OP_WMS_POLIZA_HEADER] [PH] ON(
  [PH].[CODIGO_POLIZA] = [TL].[CODIGO_POLIZA_SOURCE]
  AND [PH].[TIPO] = 'INGRESO'
)
LEFT JOIN [wms].[OP_WMS_CERTIFICATE_DEPOSIT_DETAIL] [CDD] ON(
  [CDD].[DOC_ID] = [PH].[DOC_ID]
)