
CREATE VIEW [wms].[OP_WMS_VIEW_ACOUNTABLE_LOCATIONS]
AS
SELECT     (SELECT     CLIENT_CODE COLLATE DATABASE_DEFAULT
                       FROM          [wms].OP_WMS_VIEW_CLIENTS
                       WHERE      (CLIENT_CODE = B.CLIENT_OWNER COLLATE DATABASE_DEFAULT)) AS CLIENT_CODE, A.MATERIAL_ID, A.BARCODE_ID, A.MATERIAL_NAME, B.REGIMEN, B.CODIGO_POLIZA, 
                      B.CURRENT_LOCATION, B.CURRENT_WAREHOUSE AS WAREHOUSE_ID
FROM         [wms].OP_WMS_INV_X_LICENSE AS A INNER JOIN
                      [wms].OP_WMS_LICENSES AS B ON A.LICENSE_ID = B.LICENSE_ID INNER JOIN
                      [wms].OP_WMS_MATERIALS AS C ON A.MATERIAL_ID = C.MATERIAL_ID
WHERE     (B.CURRENT_LOCATION IS NOT NULL)
GROUP BY A.MATERIAL_ID, A.BARCODE_ID, A.MATERIAL_NAME, B.REGIMEN, B.CODIGO_POLIZA, B.CURRENT_LOCATION, B.CURRENT_WAREHOUSE, B.CLIENT_OWNER