
CREATE VIEW [wms].[OP_WMS_VIEW_AUDIT_DISPATCH]
AS
--SELECT     A.AUDIT_ID, A.CODIGO_POLIZA, A.MATERIAL_ID, C.BARCODE_ID, A.MATERIAL_NAME, B.STATUS, B.NUMERO_ORDEN, B.LAST_UPDATED, 
--                      CASE A.SCANNED_COUNT WHEN 0 THEN A.INPUTED_COUNT ELSE A.SCANNED_COUNT END AS QTY
--FROM         [wms].OP_WMS_AUDIT_DISPATCH_SKUS AS A INNER JOIN
--                      [wms].OP_WMS_AUDIT_DISPATCH_CONTROL AS B ON A.AUDIT_ID = B.AUDIT_ID INNER JOIN
--                      [wms].OP_WMS_MATERIALS AS C ON A.MATERIAL_ID = C.MATERIAL_ID
SELECT A.AUDIT_ID
		, A.CODIGO_POLIZA
		, A.MATERIAL_ID
		, C.BARCODE_ID
		, A.MATERIAL_NAME
		, B.STATUS
		, B.NUMERO_ORDEN
		, B.LAST_UPDATED
		, CASE A.SCANNED_COUNT WHEN 0 THEN A.INPUTED_COUNT ELSE A.SCANNED_COUNT END AS QTY
		, S.SERIAL_NUMBER
		, B.COUNTING_METHOD
FROM [wms].OP_WMS_AUDIT_DISPATCH_SKUS AS A 
	INNER JOIN [wms].OP_WMS_AUDIT_DISPATCH_CONTROL AS B ON A.AUDIT_ID = B.AUDIT_ID 
	INNER JOIN [wms].OP_WMS_MATERIALS AS C ON A.MATERIAL_ID = C.MATERIAL_ID
	LEFT JOIN [wms].OP_WMS_AUDIT_DISPATCH_SERIES AS S ON A.MATERIAL_ID = S.MATERIAL_ID AND A.AUDIT_ID = S.AUDIT_ID