CREATE VIEW [wms].OP_WMS_VIEW_SERVICES_X_CLIENT
AS
SELECT     CLIENT_CODE, CLIENT_NAME, CLIENT_ROUTE, CLIENT_ERP_CODE, ISNULL
                          ((SELECT     COUNT(1) AS Expr1
                              FROM         [wms].OP_WMS_SERVICES_TO_BILL AS Z
                              WHERE     (CLIENT_ERP_CODE = A.CLIENT_ERP_CODE)), 0) AS QTY_SERVICES_TO_BILL
FROM         [wms].OP_WMS_VIEW_CLIENTS AS A
WHERE     (CLIENT_ERP_CODE IS NOT NULL) AND (CLIENT_ERP_CODE <> '')