


/*SELECT     (SELECT     TOP (1) CLIENT_CODE
                       FROM          cealsa.OP_WMS_CLIENTS
                       WHERE      (CONVERT(INT, CLIENT_ERP_CODE) = a.codcliente)) AS CLIENT_CODE, codacuerdo AS ACUERDO_COMERCIAL, descrip AS DESCRIPCION
FROM         aritecdb.dbo.acuerdoscomerciales AS a
WHERE     (emp = 1)*/
CREATE VIEW [wms].[OP_WMS_VIEW_CUSTOMER_TERMS_OF_TRADE]
AS
--SELECT	(SELECT TOP (1)CLIENT_CODE
--         FROM [wms].OP_WMS_CLIENTS
--		WHERE (CONVERT(INT, CLIENT_ERP_CODE) = a.codcliente)) AS CLIENT_CODE, 
--		codacuerdo AS ACUERDO_COMERCIAL, 
--		descrip AS DESCRIPCION
--		FROM aritecdb.dbo.acuerdoscomerciales AS a
--		WHERE(emp = 1)

		SELECT	(SELECT TOP (1)CLIENT_CODE
		FROM [wms].OP_WMS_VIEW_CLIENTS
		WHERE (CLIENT_CODE = a.CLIENT_ID COLLATE DATABASE_DEFAULT)) AS CLIENT_CODE, 
			 t.ACUERDO_COMERCIAL_ID AS ACUERDO_COMERCIAL, 
			convert(varchar(10),t.ACUERDO_COMERCIAL_ID) +'-'+ t.ACUERDO_COMERCIAL_NOMBRE AS DESCRIPCION
		FROM [wms].OP_WMS_ACUERDOS_X_CLIENTE AS a
			INNER JOIN [wms].OP_WMS_TARIFICADOR_HEADER t ON a.ACUERDO_COMERCIAL = t.ACUERDO_COMERCIAL_ID 
		WHERE(t.[STATUS]= 'ACTIVE')