
-- =============================================
-- Autor:				ppablo.loukota
-- Fecha de Creacion: 	18-12-2015
-- Description:			Vista que obtiene detalles de SKU 

-- modificacion 26-01-2016
				-- alberto.ruiz
				-- Se corrigio la columna de CODE_PROVIDER

-- modificacion 23-05-2016
				-- alberto.ruiz
				-- Se agrego la columna de USE_LINE_PICKING

-- Modificacion 27-05-2016
					-- alberto.ruiz
					-- Se agrego que tomara los campos de volumen, peso y medidas

-- Modificacion 8/31/2017 @ Reborn-Team Sprint Collin
					-- diego.as
					-- Se agregan columnas 
/*
-- Ejemplo de Ejecucion:
				SELECT * FROM [SONDA].[ERP_VIEW_SKU]
*/
-- =============================================
CREATE VIEW [SONDA].[ERP_VIEW_SKU]
AS

	SELECT * 
	FROM OPENQUERY(ERP_SERVER, '
		SELECT
			- 1 AS SKU
			,CONVERT(VARCHAR(50),sku.[CVE_ART]) COLLATE DATABASE_DEFAULT AS CODE_SKU
			,CONVERT(VARCHAR(MAX),sku.[DESCR]) COLLATE DATABASE_DEFAULT AS DESCRIPTION_SKU
			,CONVERT(VARCHAR(50),sku.[CVE_ART]) COLLATE DATABASE_DEFAULT AS BARCODE_SKU
			,CAST(NULL AS VARCHAR) COLLATE DATABASE_DEFAULT AS NAME_PROVIDER
			,CONVERT(FLOAT, ISNULL(sku.[COSTO_PROM], 0)) AS ''COST''
			,CONVERT(NUMERIC(18, 2), ISNULL(sku.[COSTO_PROM], 0)) AS ''LIST_PRICE''
			,CONVERT(VARCHAR(50),'''') COLLATE DATABASE_DEFAULT AS MEASURE
			,CONVERT(VARCHAR(150),'''') COLLATE DATABASE_DEFAULT AS NAME_CLASSIFICATION
			,CONVERT(INT, ISNULL(0, 0)) AS ''UNIT_MEASURE_SKU''
			,CONVERT([numeric](18, 2), ISNULL(sku.[PESO], 0)) AS ''WEIGHT_SKU''
			,CONVERT([numeric](18, 2), ISNULL(sku.[VOLUMEN], 0)) AS ''VOLUME_SKU''		
			,CONVERT([numeric](18, 2), 0) AS ''LONG_SKU''
			,CONVERT([numeric](18, 2), 0) AS ''WIDTH_SKU''
			,CONVERT([numeric](18, 2), 0) AS ''HIGH_SKU''
			,''1'' COLLATE DATABASE_DEFAULT AS VALUE_TEXT_CLASSIFICATION
			,CONVERT(VARCHAR(2),CASE [CON_SERIE] WHEN ''S'' THEN 1 ELSE 0 END) COLLATE DATABASE_DEFAULT AS HANDLE_SERIAL_NUMBER
			,CASE [CON_SERIE] WHEN ''S'' THEN ''1'' ELSE ''0'' END COLLATE DATABASE_DEFAULT AS HANDLE_BATCH
			,CONVERT(VARCHAR(2),1) COLLATE DATABASE_DEFAULT AS FROM_ERP
			,[COSTO_PROM] AS PRICE
			,''1'' AS LIST_NUM
			,CAST(NULL AS VARCHAR) COLLATE DATABASE_DEFAULT AS CODE_PROVIDER
			,CAST(NULL AS DATETIME) LAST_UPDATE
			,CAST(NULL AS VARCHAR) COLLATE DATABASE_DEFAULT AS LAST_UPDATE_BY
			,CAST([LIN_PROD] as Varchar(50)) AS CODE_FAMILY_SKU
			,0 USE_LINE_PICKING
			,CONVERT(VARCHAR, '''') AS VOLUME_CODE_UNIT
			,CONVERT(VARCHAR, '''') AS VOLUME_NAME_UNIT
			,CAST(''SONDA'' AS VARCHAR) AS OWNER
			,CONVERT(VARCHAR(50),sku.[CVE_ART]) COLLATE DATABASE_DEFAULT AS OWNER_ID
			,CONVERT(VARCHAR(20),NULL) COLLATE DATABASE_DEFAULT AS ART_CODE
			,(CASE WHEN IMP.[IMPUESTO4] > 0 THEN ''ISV'' ELSE ''EXE'' END) COLLATE DATABASE_DEFAULT AS VAT_CODE
		FROM [SAE70EMPRESA01].[dbo].[INVE01] AS sku 
		LEFT JOIN [SAE70EMPRESA01].[dbo].[IMPU01] IMP ON sku.[CVE_ESQIMPU] = IMP.[CVE_ESQIMPU]
		WHERE sku.[TIPO_ELE] = ''P'' AND ISNULL(sku.[UNI_MED],'''')<>'''' AND sku.[STATUS] <> ''B''
	')




