CREATE TABLE [SONDA].[BULK_DATA_CONFIGURATION_LOG] (
    [CONFIGURATION_LOG] INT            IDENTITY (1, 1) NOT NULL,
    [SP]                VARCHAR (1000) NOT NULL,
    [START_RUN]         DATETIME       NULL,
    [END_RUN]           DATETIME       NULL,
    [MESSAGE]           VARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_BULK_DATA_CONFIGURATION_LOG] PRIMARY KEY CLUSTERED ([CONFIGURATION_LOG] ASC)
);

