CREATE TABLE [SONDA].[SWIFT_WAREHOUSES] (
    [WAREHOUSE]                   INT           IDENTITY (1, 1) NOT NULL,
    [CODE_WAREHOUSE]              VARCHAR (50)  NULL,
    [DESCRIPTION_WAREHOUSE]       VARCHAR (MAX) NULL,
    [WEATHER_WAREHOUSE]           VARCHAR (50)  NULL,
    [STATUS_WAREHOUSE]            VARCHAR (10)  NULL,
    [LAST_UPDATE]                 DATETIME      NULL,
    [LAST_UPDATE_BY]              VARCHAR (50)  NULL,
    [IS_EXTERNAL]                 INT           NULL,
    [BARCODE_WAREHOUSE]           VARCHAR (50)  NULL,
    [SHORT_DESCRIPTION_WAREHOUSE] VARCHAR (MAX) NULL,
    [TYPE_WAREHOUSE]              INT           NULL,
    [ERP_WAREHOUSE]               VARCHAR (MAX) NULL,
    [ADDRESS_WAREHOUSE]           VARCHAR (50)  NULL,
    CONSTRAINT [UQ__SWIFT_WA__D8193FC2656C112C] UNIQUE NONCLUSTERED ([CODE_WAREHOUSE] ASC)
);

