CREATE TABLE [SONDA].[SWIFT_ERP_SELLER] (
    [SELLER_CODE] VARCHAR (250) NOT NULL,
    [SELLER_NAME] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_SWIFT_ERP_SELLER] PRIMARY KEY CLUSTERED ([SELLER_CODE] ASC)
);

