CREATE TABLE [SONDA].[SWIFT_ERP_ORDER_HEADER] (
    [DocEntry]             INT             NOT NULL,
    [DocNum]               INT             NOT NULL,
    [DocType]              CHAR (1)        NULL,
    [CANCELED]             CHAR (1)        NULL,
    [Handwrtten]           CHAR (1)        NULL,
    [Printed]              CHAR (1)        NULL,
    [DocStatus]            CHAR (1)        NULL,
    [InvntSttus]           CHAR (1)        NULL,
    [Transfered]           CHAR (1)        NULL,
    [ObjType]              NVARCHAR (20)   NULL,
    [DocDate]              DATETIME        NULL,
    [DocDueDate]           DATETIME        NULL,
    [CardCode]             NVARCHAR (15)   NULL,
    [CardName]             NVARCHAR (100)  NULL,
    [Address]              NVARCHAR (254)  NULL,
    [NumAtCard]            NVARCHAR (100)  NULL,
    [VatPercent]           NUMERIC (19, 6) NULL,
    [VatSum]               NUMERIC (19, 6) NULL,
    [VatSumFC]             NUMERIC (19, 6) NULL,
    [DiscPrcnt]            NUMERIC (19, 6) NULL,
    [DiscSum]              NUMERIC (19, 6) NULL,
    [DiscSumFC]            NUMERIC (19, 6) NULL,
    [DocCur]               NVARCHAR (3)    NULL,
    [DocRate]              NUMERIC (19, 6) NULL,
    [DocTotal]             NUMERIC (19, 6) NULL,
    [DocTotalFC]           NUMERIC (19, 6) NULL,
    [PaidToDate]           NUMERIC (19, 6) NULL,
    [PaidFC]               NUMERIC (19, 6) NULL,
    [GrosProfit]           NUMERIC (19, 6) NULL,
    [GrosProfFC]           NUMERIC (19, 6) NULL,
    [Ref1]                 NVARCHAR (11)   NULL,
    [Ref2]                 NVARCHAR (11)   NULL,
    [Comments]             NVARCHAR (254)  NULL,
    [JrnlMemo]             NVARCHAR (50)   NULL,
    [TransId]              INT             NULL,
    [ReceiptNum]           INT             NULL,
    [GroupNum]             SMALLINT        NULL,
    [DocTime]              SMALLINT        NULL,
    [SlpCode]              SMALLINT        NULL,
    [TrnspCode]            SMALLINT        NULL,
    [PartSupply]           CHAR (1)        NULL,
    [Confirmed]            CHAR (1)        NULL,
    [GrossBase]            SMALLINT        NULL,
    [ImportEnt]            INT             NULL,
    [CreateTran]           CHAR (1)        NULL,
    [SummryType]           CHAR (1)        NULL,
    [UpdInvnt]             CHAR (1)        NULL,
    [UpdCardBal]           CHAR (1)        NULL,
    [Instance]             SMALLINT        NOT NULL,
    [Flags]                INT             NULL,
    [InvntDirec]           CHAR (1)        NULL,
    [CntctCode]            INT             NULL,
    [ShowSCN]              CHAR (1)        NULL,
    [FatherCard]           NVARCHAR (15)   NULL,
    [SysRate]              NUMERIC (19, 6) NULL,
    [CurSource]            CHAR (1)        NULL,
    [VatSumSy]             NUMERIC (19, 6) NULL,
    [DiscSumSy]            NUMERIC (19, 6) NULL,
    [DocTotalSy]           NUMERIC (19, 6) NULL,
    [PaidSys]              NUMERIC (19, 6) NULL,
    [FatherType]           CHAR (1)        NULL,
    [GrosProfSy]           NUMERIC (19, 6) NULL,
    [UpdateDate]           DATETIME        NULL,
    [IsICT]                CHAR (1)        NULL,
    [CreateDate]           DATETIME        NULL,
    [Volume]               NUMERIC (19, 6) NULL,
    [VolUnit]              SMALLINT        NULL,
    [Weight]               NUMERIC (19, 6) NULL,
    [WeightUnit]           SMALLINT        NULL,
    [Series]               SMALLINT        NULL,
    [TaxDate]              DATETIME        NULL,
    [Filler]               NVARCHAR (8)    NULL,
    [DataSource]           CHAR (1)        NULL,
    [StampNum]             NVARCHAR (16)   NULL,
    [isCrin]               CHAR (1)        NULL,
    [FinncPriod]           INT             NULL,
    [UserSign]             SMALLINT        NULL,
    [selfInv]              CHAR (1)        NULL,
    [VatPaid]              NUMERIC (19, 6) NULL,
    [VatPaidFC]            NUMERIC (19, 6) NULL,
    [VatPaidSys]           NUMERIC (19, 6) NULL,
    [UserSign2]            SMALLINT        NULL,
    [WddStatus]            CHAR (1)        NULL,
    [draftKey]             INT             NULL,
    [TotalExpns]           NUMERIC (19, 6) NULL,
    [TotalExpFC]           NUMERIC (19, 6) NULL,
    [TotalExpSC]           NUMERIC (19, 6) NULL,
    [DunnLevel]            INT             NULL,
    [Address2]             NVARCHAR (254)  NULL,
    [LogInstanc]           INT             NULL,
    [Exported]             CHAR (1)        NULL,
    [StationID]            INT             NULL,
    [Indicator]            NVARCHAR (2)    NULL,
    [NetProc]              CHAR (1)        NULL,
    [AqcsTax]              NUMERIC (19, 6) NULL,
    [AqcsTaxFC]            NUMERIC (19, 6) NULL,
    [AqcsTaxSC]            NUMERIC (19, 6) NULL,
    [CashDiscPr]           NUMERIC (19, 6) NULL,
    [CashDiscnt]           NUMERIC (19, 6) NULL,
    [CashDiscFC]           NUMERIC (19, 6) NULL,
    [CashDiscSC]           NUMERIC (19, 6) NULL,
    [ShipToCode]           NVARCHAR (50)   NULL,
    [LicTradNum]           NVARCHAR (32)   NULL,
    [PaymentRef]           NVARCHAR (27)   NULL,
    [WTSum]                NUMERIC (19, 6) NULL,
    [WTSumFC]              NUMERIC (19, 6) NULL,
    [WTSumSC]              NUMERIC (19, 6) NULL,
    [RoundDif]             NUMERIC (19, 6) NULL,
    [RoundDifFC]           NUMERIC (19, 6) NULL,
    [RoundDifSy]           NUMERIC (19, 6) NULL,
    [CheckDigit]           CHAR (1)        NULL,
    [Form1099]             INT             NULL,
    [Box1099]              NVARCHAR (20)   NULL,
    [submitted]            CHAR (1)        NULL,
    [PoPrss]               CHAR (1)        NULL,
    [Rounding]             CHAR (1)        NULL,
    [RevisionPo]           CHAR (1)        NULL,
    [Segment]              SMALLINT        NOT NULL,
    [ReqDate]              DATETIME        NULL,
    [CancelDate]           DATETIME        NULL,
    [PickStatus]           CHAR (1)        NULL,
    [Pick]                 CHAR (1)        NULL,
    [BlockDunn]            CHAR (1)        NULL,
    [PeyMethod]            NVARCHAR (15)   NULL,
    [PayBlock]             CHAR (1)        NULL,
    [PayBlckRef]           INT             NULL,
    [MaxDscn]              CHAR (1)        NULL,
    [Reserve]              CHAR (1)        NULL,
    [Max1099]              NUMERIC (19, 6) NULL,
    [CntrlBnk]             NVARCHAR (15)   NULL,
    [PickRmrk]             NVARCHAR (254)  NULL,
    [ISRCodLine]           NVARCHAR (53)   NULL,
    [ExpAppl]              NUMERIC (19, 6) NULL,
    [ExpApplFC]            NUMERIC (19, 6) NULL,
    [ExpApplSC]            NUMERIC (19, 6) NULL,
    [Project]              NVARCHAR (20)   NULL,
    [DeferrTax]            CHAR (1)        NULL,
    [LetterNum]            NVARCHAR (20)   NULL,
    [FromDate]             DATETIME        NULL,
    [ToDate]               DATETIME        NULL,
    [WTApplied]            NUMERIC (19, 6) NULL,
    [WTAppliedF]           NUMERIC (19, 6) NULL,
    [BoeReserev]           CHAR (1)        NULL,
    [AgentCode]            NVARCHAR (32)   NULL,
    [WTAppliedS]           NUMERIC (19, 6) NULL,
    [EquVatSum]            NUMERIC (19, 6) NULL,
    [EquVatSumF]           NUMERIC (19, 6) NULL,
    [EquVatSumS]           NUMERIC (19, 6) NULL,
    [Installmnt]           SMALLINT        NULL,
    [VATFirst]             CHAR (1)        NULL,
    [NnSbAmnt]             NUMERIC (19, 6) NULL,
    [NnSbAmntSC]           NUMERIC (19, 6) NULL,
    [NbSbAmntFC]           NUMERIC (19, 6) NULL,
    [ExepAmnt]             NUMERIC (19, 6) NULL,
    [ExepAmntSC]           NUMERIC (19, 6) NULL,
    [ExepAmntFC]           NUMERIC (19, 6) NULL,
    [VatDate]              DATETIME        NULL,
    [CorrExt]              NVARCHAR (25)   NULL,
    [CorrInv]              INT             NULL,
    [NCorrInv]             INT             NULL,
    [CEECFlag]             CHAR (1)        NULL,
    [BaseAmnt]             NUMERIC (19, 6) NULL,
    [BaseAmntSC]           NUMERIC (19, 6) NULL,
    [BaseAmntFC]           NUMERIC (19, 6) NULL,
    [CtlAccount]           NVARCHAR (15)   NULL,
    [BPLId]                INT             NULL,
    [BPLName]              NVARCHAR (100)  NULL,
    [VATRegNum]            NVARCHAR (32)   NULL,
    [TxInvRptNo]           NVARCHAR (10)   NULL,
    [TxInvRptDt]           DATETIME        NULL,
    [KVVATCode]            NTEXT           NULL,
    [WTDetails]            NVARCHAR (100)  NULL,
    [SumAbsId]             INT             NULL,
    [SumRptDate]           DATETIME        NULL,
    [PIndicator]           NVARCHAR (10)   NOT NULL,
    [ManualNum]            NVARCHAR (20)   NULL,
    [UseShpdGd]            CHAR (1)        NULL,
    [BaseVtAt]             NUMERIC (19, 6) NULL,
    [BaseVtAtSC]           NUMERIC (19, 6) NULL,
    [BaseVtAtFC]           NUMERIC (19, 6) NULL,
    [NnSbVAt]              NUMERIC (19, 6) NULL,
    [NnSbVAtSC]            NUMERIC (19, 6) NULL,
    [NbSbVAtFC]            NUMERIC (19, 6) NULL,
    [ExptVAt]              NUMERIC (19, 6) NULL,
    [ExptVAtSC]            NUMERIC (19, 6) NULL,
    [ExptVAtFC]            NUMERIC (19, 6) NULL,
    [LYPmtAt]              NUMERIC (19, 6) NULL,
    [LYPmtAtSC]            NUMERIC (19, 6) NULL,
    [LYPmtAtFC]            NUMERIC (19, 6) NULL,
    [ExpAnSum]             NUMERIC (19, 6) NULL,
    [ExpAnSys]             NUMERIC (19, 6) NULL,
    [ExpAnFrgn]            NUMERIC (19, 6) NULL,
    [DocSubType]           NVARCHAR (2)    NOT NULL,
    [DpmStatus]            CHAR (1)        NULL,
    [DpmAmnt]              NUMERIC (19, 6) NULL,
    [DpmAmntSC]            NUMERIC (19, 6) NULL,
    [DpmAmntFC]            NUMERIC (19, 6) NULL,
    [DpmDrawn]             CHAR (1)        NULL,
    [DpmPrcnt]             NUMERIC (19, 6) NULL,
    [PaidSum]              NUMERIC (19, 6) NULL,
    [PaidSumFc]            NUMERIC (19, 6) NULL,
    [PaidSumSc]            NUMERIC (19, 6) NULL,
    [FolioPref]            NVARCHAR (2)    NULL,
    [FolioNum]             INT             NULL,
    [DpmAppl]              NUMERIC (19, 6) NULL,
    [DpmApplFc]            NUMERIC (19, 6) NULL,
    [DpmApplSc]            NUMERIC (19, 6) NULL,
    [LPgFolioN]            INT             NULL,
    [Header]               NTEXT           NULL,
    [Footer]               NTEXT           NULL,
    [Posted]               CHAR (1)        NULL,
    [OwnerCode]            INT             NULL,
    [BPChCode]             NVARCHAR (15)   NULL,
    [BPChCntc]             INT             NULL,
    [PayToCode]            NVARCHAR (50)   NULL,
    [IsPaytoBnk]           CHAR (1)        NULL,
    [BnkCntry]             NVARCHAR (3)    NULL,
    [BankCode]             NVARCHAR (30)   NULL,
    [BnkAccount]           NVARCHAR (50)   NULL,
    [BnkBranch]            NVARCHAR (50)   NULL,
    [isIns]                CHAR (1)        NULL,
    [TrackNo]              NVARCHAR (30)   NULL,
    [VersionNum]           NVARCHAR (11)   NULL,
    [LangCode]             INT             NULL,
    [BPNameOW]             CHAR (1)        NULL,
    [BillToOW]             CHAR (1)        NULL,
    [ShipToOW]             CHAR (1)        NULL,
    [RetInvoice]           CHAR (1)        NULL,
    [ClsDate]              DATETIME        NULL,
    [MInvNum]              INT             NULL,
    [MInvDate]             DATETIME        NULL,
    [SeqCode]              SMALLINT        NULL,
    [Serial]               INT             NULL,
    [SeriesStr]            NVARCHAR (3)    NULL,
    [SubStr]               NVARCHAR (3)    NULL,
    [Model]                NVARCHAR (6)    NULL,
    [TaxOnExp]             NUMERIC (19, 6) NULL,
    [TaxOnExpFc]           NUMERIC (19, 6) NULL,
    [TaxOnExpSc]           NUMERIC (19, 6) NULL,
    [TaxOnExAp]            NUMERIC (19, 6) NULL,
    [TaxOnExApF]           NUMERIC (19, 6) NULL,
    [TaxOnExApS]           NUMERIC (19, 6) NULL,
    [LastPmnTyp]           CHAR (1)        NULL,
    [LndCstNum]            INT             NULL,
    [UseCorrVat]           CHAR (1)        NULL,
    [BlkCredMmo]           CHAR (1)        NULL,
    [OpenForLaC]           CHAR (1)        NULL,
    [Excised]              CHAR (1)        NULL,
    [ExcRefDate]           DATETIME        NULL,
    [ExcRmvTime]           NVARCHAR (8)    NULL,
    [SrvGpPrcnt]           NUMERIC (19, 6) NULL,
    [DepositNum]           INT             NULL,
    [CertNum]              NVARCHAR (31)   NULL,
    [DutyStatus]           CHAR (1)        NULL,
    [AutoCrtFlw]           CHAR (1)        NULL,
    [FlwRefDate]           DATETIME        NULL,
    [FlwRefNum]            NVARCHAR (100)  NULL,
    [VatJENum]             INT             NULL,
    [DpmVat]               NUMERIC (19, 6) NULL,
    [DpmVatFc]             NUMERIC (19, 6) NULL,
    [DpmVatSc]             NUMERIC (19, 6) NULL,
    [DpmAppVat]            NUMERIC (19, 6) NULL,
    [DpmAppVatF]           NUMERIC (19, 6) NULL,
    [DpmAppVatS]           NUMERIC (19, 6) NULL,
    [InsurOp347]           CHAR (1)        NULL,
    [IgnRelDoc]            CHAR (1)        NULL,
    [BuildDesc]            NVARCHAR (50)   NULL,
    [ResidenNum]           CHAR (1)        NULL,
    [Checker]              INT             NULL,
    [Payee]                INT             NULL,
    [CopyNumber]           INT             NULL,
    [SSIExmpt]             CHAR (1)        NULL,
    [PQTGrpSer]            SMALLINT        NULL,
    [PQTGrpNum]            INT             NULL,
    [PQTGrpHW]             CHAR (1)        NULL,
    [ReopOriDoc]           CHAR (1)        NULL,
    [ReopManCls]           CHAR (1)        NULL,
    [DocManClsd]           CHAR (1)        NULL,
    [ClosingOpt]           SMALLINT        NULL,
    [SpecDate]             DATETIME        NULL,
    [Ordered]              CHAR (1)        NULL,
    [NTSApprov]            CHAR (1)        NULL,
    [NTSWebSite]           SMALLINT        NULL,
    [NTSeTaxNo]            NVARCHAR (50)   NULL,
    [NTSApprNo]            NVARCHAR (50)   NULL,
    [PayDuMonth]           CHAR (1)        NULL,
    [ExtraMonth]           SMALLINT        NULL,
    [ExtraDays]            SMALLINT        NULL,
    [CdcOffset]            SMALLINT        NULL,
    [SignMsg]              NTEXT           NULL,
    [SignDigest]           NTEXT           NULL,
    [CertifNum]            NVARCHAR (50)   NULL,
    [KeyVersion]           INT             NULL,
    [EDocGenTyp]           CHAR (1)        NULL,
    [ESeries]              SMALLINT        NULL,
    [EDocNum]              NVARCHAR (50)   NULL,
    [EDocExpFrm]           INT             NULL,
    [OnlineQuo]            CHAR (1)        NULL,
    [POSEqNum]             NVARCHAR (20)   NULL,
    [POSManufSN]           NVARCHAR (20)   NULL,
    [POSCashN]             INT             NULL,
    [EDocStatus]           CHAR (1)        NULL,
    [EDocCntnt]            NTEXT           NULL,
    [EDocProces]           CHAR (1)        NULL,
    [EDocErrCod]           NVARCHAR (50)   NULL,
    [EDocErrMsg]           NTEXT           NULL,
    [EDocCancel]           CHAR (1)        NULL,
    [EDocTest]             CHAR (1)        NULL,
    [EDocPrefix]           NVARCHAR (10)   NULL,
    [CUP]                  INT             NULL,
    [CIG]                  INT             NULL,
    [DpmAsDscnt]           CHAR (1)        NULL,
    [Attachment]           NTEXT           NULL,
    [AtcEntry]             INT             NULL,
    [SupplCode]            NVARCHAR (254)  NULL,
    [GTSRlvnt]             CHAR (1)        NULL,
    [BaseDisc]             NUMERIC (19, 6) NULL,
    [BaseDiscSc]           NUMERIC (19, 6) NULL,
    [BaseDiscFc]           NUMERIC (19, 6) NULL,
    [BaseDiscPr]           NUMERIC (19, 6) NULL,
    [CreateTS]             INT             NULL,
    [UpdateTS]             INT             NULL,
    [SrvTaxRule]           CHAR (1)        NULL,
    [AnnInvDecR]           INT             NULL,
    [Supplier]             NVARCHAR (15)   NULL,
    [Releaser]             INT             NULL,
    [Receiver]             INT             NULL,
    [AgrNo]                INT             NULL,
    [IsAlt]                CHAR (1)        NULL,
    [AltBaseTyp]           INT             NULL,
    [AltBaseEnt]           INT             NULL,
    [PaidDpm]              NUMERIC (19, 6) NULL,
    [PaidDpmF]             NUMERIC (19, 6) NULL,
    [PaidDpmS]             NUMERIC (19, 6) NULL,
    [U_Guatex]             NVARCHAR (100)  NULL,
    [U_KM]                 NUMERIC (19, 6) NULL,
    [Ship_To_Address_Type] NVARCHAR (100)  NULL,
    [Ship_To_Street]       NVARCHAR (100)  NULL,
    [Ship_To_State]        NVARCHAR (3)    NULL,
    [Ship_To_Country]      NVARCHAR (3)    NULL
);

