
-- =============================================
-- Autor:				pablo.aguilar
-- Fecha de Creacion: 	18-08-2016
-- Description:			SP que importa las frecuencias a SWIFT_EXPRESS

/*
--DROP PROCEDURE [wms].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
-- Ejemplo de Ejecucion:
				-- 
				EXEC [wms].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
				SELECT * FROM SWIFT_EXPRESS.wms.SWIFT_FREQUENCY_X_CUSTOMER
				SELECT * FROM SWIFT_EXPRESS.wms.SWIFT_FREQUENCY
				SELECT * FROM SWIFT_EXPRESS.wms.SWIFT_TASKS
*/
-- =============================================
CREATE PROCEDURE [wms].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
AS
BEGIN
  SET NOCOUNT ON;
  --


  DELETE FC
    FROM SWIFT_EXPRESS.wms.SWIFT_FREQUENCY_X_CUSTOMER FC
    INNER JOIN SWIFT_EXPRESS.wms.SWIFT_FREQUENCY F
      ON F.ID_FREQUENCY = FC.ID_FREQUENCY
  WHERE F.REFERENCE_SOURCE = 'BULK_DATA'


  DELETE SWIFT_EXPRESS.wms.SWIFT_FREQUENCY
  WHERE REFERENCE_SOURCE = 'BULK_DATA'

  INSERT INTO SWIFT_EXPRESS.wms.SWIFT_FREQUENCY (CODE_FREQUENCY
  , CODE_ROUTE
  , FREQUENCY_WEEKS
  , MONDAY
  , TUESDAY
  , WEDNESDAY
  , THURSDAY
  , FRIDAY
  , SATURDAY
  , SUNDAY
  , LAST_UPDATED
  , LAST_UPDATED_BY
  , LAST_WEEK_VISITED
  , REFERENCE_SOURCE
  , TYPE_TASK)
    SELECT
      'PRESALE_' + SELLER_CODE + '_' + CONCAT(
      CASE DATEPART(DW, GETDATE())
        WHEN 2 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 3 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 4 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 5 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 6 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 7 THEN 1
        ELSE 0
      END
      , CASE DATEPART(DW, GETDATE())
        WHEN 1 THEN 1
        ELSE 0
      END
      ) CODE_FREQUENCY
     ,CODE_ROUTE
     ,1 FREQUENCY_WEEKS
     ,CASE DATEPART(DW, GETDATE())
        WHEN 2 THEN 1
        ELSE 0
      END MONDAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 3 THEN 1
        ELSE 0
      END TUESDAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 4 THEN 1
        ELSE 0
      END WEDNESDAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 5 THEN 1
        ELSE 0
      END THURSDAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 6 THEN 1
        ELSE 0
      END FRIDCAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 7 THEN 1
        ELSE 0
      END SATURDAY
     ,CASE DATEPART(DW, GETDATE())
        WHEN 1 THEN 1
        ELSE 0
      END SUNDAY
     ,GETDATE() LAST_UPDATED
     ,'BULK_DATA' LAST_UPDATED_BY
     ,CONVERT(DATE, DATEADD(DAY,
      -1 - (DATEPART(dw, GETDATE()) + @@DATEFIRST - 2) % 7,
      GETDATE()
      )) AS LAST_WEEK_VISITED
     ,'BULK_DATA' REFERENCE_SOURCE
     ,'PRESALE' TYPE_TASK
    FROM SWIFT_INTERFACES_ONLINE.wms.ERP_VIEW_SELLER

  INSERT INTO SWIFT_EXPRESS.wms.SWIFT_FREQUENCY_X_CUSTOMER ([ID_FREQUENCY]
  , [CODE_CUSTOMER]
  , [PRIORITY])
    SELECT
      [F].[ID_FREQUENCY]
     ,[C].[CODE_CUSTOMER]
     ,1 AS [PRIORITY]
    FROM [SWIFT_INTERFACES_ONLINE].[wms].[ERP_VIEW_COSTUMER] C
    INNER JOIN SWIFT_EXPRESS.wms.SWIFT_FREQUENCY F
      ON C.CODE_ROUTE = F.CODE_ROUTE
    WHERE F.REFERENCE_SOURCE = 'BULK_DATA'


  EXEC [SWIFT_EXPRESS].[wms].SONDA_SP_GENERATE_ROUTE_PLAN


END


