

--CREATE VIEW [wms].[ERP_PURCHASE_ORDER_COMP01]
--AS
--SELECT
--[COM01].[CVE_DOC],
--[MAT01].[MATERIAL_ID],
--[MAT01].[MATERIAL_NAME],
--[MAT01].[MATERIAL_CLASS],
--[COM01].[COST]
--FROM [SAE70EMPRESA01].[dbo].[PAR_COMPO01] COM01 INNER JOIN [OP_WMS_ALZA].[wms].[OP_WMS_MATERIALS] MAT01 ON COM01.CVE_ART COLLATE DATABASE_DEFAULT = MAT01.BARCODE_ID

