CREATE TABLE [dbo].[CARTAPORTE01] (
    [CLAVE_DOC]       VARCHAR (20) NOT NULL,
    [TIPO_DOC]        VARCHAR (1)  NOT NULL,
    [XML_COMPLEMENTO] TEXT         NULL,
    CONSTRAINT [PK_CARTAPORTE01] PRIMARY KEY CLUSTERED ([CLAVE_DOC] ASC, [TIPO_DOC] ASC)
);

