CREATE TABLE [dbo].[CFDI01] (
    [TIPO_DOC]        VARCHAR (1)  NOT NULL,
    [CVE_DOC]         VARCHAR (20) NOT NULL,
    [VERSION]         VARCHAR (5)  NULL,
    [UUID]            VARCHAR (36) NULL,
    [NO_SERIE]        VARCHAR (30) NULL,
    [FECHA_CERT]      VARCHAR (30) NULL,
    [FECHA_CANCELA]   VARCHAR (30) NULL,
    [XML_DOC]         TEXT         NULL,
    [XML_DOC_CANCELA] TEXT         NULL,
    [DESGLOCEIMP1]    VARCHAR (1)  NULL,
    [DESGLOCEIMP2]    VARCHAR (1)  NULL,
    [DESGLOCEIMP3]    VARCHAR (1)  NULL,
    [DESGLOCEIMP4]    VARCHAR (1)  NULL,
    [MSJ_CANC]        VARCHAR (80) NULL,
    [PENDIENTE]       VARCHAR (2)  NULL,
    [CVE_USUARIO]     INT          NULL,
    [MOTIVO_CANC]     VARCHAR (3)  NULL,
    [UUID_REL]        VARCHAR (36) NULL,
    CONSTRAINT [PK_CFDI01] PRIMARY KEY CLUSTERED ([TIPO_DOC] ASC, [CVE_DOC] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IDX_PENDIENTE01]
    ON [dbo].[CFDI01]([PENDIENTE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_VERSION_V01]
    ON [dbo].[CFDI01]([VERSION] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_USUARIO01]
    ON [dbo].[CFDI01]([CVE_USUARIO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_CFDI_CVE_DOC01]
    ON [dbo].[CFDI01]([CVE_DOC] ASC);


GO



GO



GO



GO



GO



GO



GO



GO



GO



GO



GO



GO



GO
CREATE NONCLUSTERED INDEX [IDX_CFDI_PAGOS01]
    ON [dbo].[CFDI01]([CVE_DOC] ASC, [TIPO_DOC] ASC, [UUID] ASC, [VERSION] ASC);

