CREATE TABLE [dbo].[CLIE_TIENDA01] (
    [CVE_COMP]   VARCHAR (40) NOT NULL,
    [CLAVE]      VARCHAR (10) NOT NULL,
    [CVE_TIENDA] VARCHAR (2)  NOT NULL,
    CONSTRAINT [PK_CLIE_TIENDA01] PRIMARY KEY CLUSTERED ([CVE_COMP] ASC, [CLAVE] ASC, [CVE_TIENDA] ASC)
);

