CREATE TABLE [dbo].[COMPO_CLIB01] (
    [CLAVE_DOC] VARCHAR (20) NOT NULL,
    [CAMPLIB1]  VARCHAR (50) NULL,
    [CAMPLIB2]  DATETIME     NULL,
    [CAMPLIB3]  VARCHAR (50) NULL,
    [CAMPLIB4]  VARCHAR (1)  NULL,
    [CAMPLIB5]  VARCHAR (1)  NULL,
    [CAMPLIB6]  VARCHAR (1)  NULL,
    [CAMPLIB7]  VARCHAR (1)  NULL,
    [CAMPLIB8]  FLOAT (53)   NULL,
    [CAMPLIB9]  FLOAT (53)   NULL,
    [CAMPLIB10] FLOAT (53)   NULL,
    [CAMPLIB11] VARCHAR (40) NULL,
    [CAMPLIB12] VARCHAR (50) NULL,
    [CAMPLIB13] DATETIME     NULL,
    [CAMPLIB14] VARCHAR (1)  NULL,
    [CAMPLIB15] VARCHAR (20) NULL,
    [CAMPLIB16] FLOAT (53)   NULL,
    [CAMPLIB17] FLOAT (53)   NULL,
    [CAMPLIB18] FLOAT (53)   NULL,
    [CAMPLIB19] FLOAT (53)   NULL,
    [CAMPLIB20] FLOAT (53)   NULL,
    CONSTRAINT [PK_COMPO_CLIB01] PRIMARY KEY CLUSTERED ([CLAVE_DOC] ASC)
);




GO


