CREATE TABLE [dbo].[CONFIG_ENVIOS01] (
    [CVE_ART] VARCHAR (30) NOT NULL,
    [NUM_ENV] INT          NOT NULL,
    [DESCR]   VARCHAR (80) NOT NULL,
    [COSTO]   FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_CONFIG_ENVIOS01] PRIMARY KEY CLUSTERED ([CVE_ART] ASC, [NUM_ENV] ASC)
);

