CREATE TABLE [dbo].[FACT_GLOBAL01] (
    [CLAVE_DOC]    VARCHAR (20) NOT NULL,
    [PERIODICIDAD] VARCHAR (3)  NULL,
    [MESES]        VARCHAR (3)  NULL,
    [ANIO]         INT          NULL,
    CONSTRAINT [PK_FACT_GLOBAL01] PRIMARY KEY CLUSTERED ([CLAVE_DOC] ASC)
);

