CREATE TABLE [dbo].[IMG_ARTICULO01] (
    [CVE_ART] VARCHAR (16)  NOT NULL,
    [NUM_IMG] INT           NOT NULL,
    [ID_IMG]  VARCHAR (50)  NULL,
    [NOM_IMG] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_IMG_ARTICULO01] PRIMARY KEY CLUSTERED ([CVE_ART] ASC, [NUM_IMG] ASC)
);

