CREATE TABLE [dbo].[INVE_AMAZON01] (
    [CVE_ART]           VARCHAR (16)   NOT NULL,
    [ASIN]              VARCHAR (20)   NULL,
    [SKU_AM]            VARCHAR (16)   NULL,
    [EDO_PUBL_AM]       VARCHAR (1)    NULL,
    [CONDICION]         VARCHAR (1)    NULL,
    [MOD_ENVIO]         VARCHAR (1)    NULL,
    [STATUS]            VARCHAR (1)    NULL,
    [SUBMIT_ID]         VARCHAR (20)   NULL,
    [TITULOPUB_AM]      VARCHAR (300)  NULL,
    [TITULO_AM]         VARCHAR (40)   NULL,
    [FABRICANTE_AM]     VARCHAR (30)   NULL,
    [MARCA_AM]          VARCHAR (30)   NULL,
    [TIPO_PROD_AM]      VARCHAR (30)   NULL,
    [DESCR_AM]          VARCHAR (2000) NULL,
    [ATRIBUTOS_AM]      TEXT           NULL,
    [CARAC_AM]          TEXT           NULL,
    [DISP_PUBL_AM]      VARCHAR (1)    NULL,
    [F_PUB_AM]          DATETIME       NULL,
    [DISP_OFERTA]       VARCHAR (1)    NULL,
    [F_DES_OF]          DATETIME       NULL,
    [F_HAS_OF]          DATETIME       NULL,
    [STATUS_INV]        VARCHAR (1)    NULL,
    [SUBMIT_INV_ID]     VARCHAR (20)   NULL,
    [STATUS_PRE]        VARCHAR (1)    NULL,
    [SUBMIT_PRE_ID]     VARCHAR (20)   NULL,
    [STATUS_ELIM]       VARCHAR (1)    NULL,
    [SUBMIT_ELIM_ID]    VARCHAR (20)   NULL,
    [FEEDDOCUMENT]      VARCHAR (100)  NULL,
    [FEEDDOCUMENT_INV]  VARCHAR (100)  NULL,
    [FEEDDOCUMENT_PRE]  VARCHAR (100)  NULL,
    [FEEDDOCUMENT_ELIM] VARCHAR (100)  NULL,
    CONSTRAINT [PK_INVE_AMAZON01] PRIMARY KEY CLUSTERED ([CVE_ART] ASC)
);

