CREATE TABLE [dbo].[PAR_PED_TIEND01] (
    [CVE_DOC]     VARCHAR (20) NOT NULL,
    [NUM_PAR]     INT          NOT NULL,
    [CVE_ART]     VARCHAR (16) NULL,
    [CVE_SAE]     VARCHAR (20) NULL,
    [TITULO]      VARCHAR (60) NULL,
    [CATEGORIA]   VARCHAR (25) NULL,
    [CONDICION]   VARCHAR (1)  NULL,
    [CANT]        FLOAT (53)   NULL,
    [PREC]        FLOAT (53)   NULL,
    [CVE_MONED]   VARCHAR (4)  NULL,
    [TOT_PARTIDA] FLOAT (53)   NULL,
    CONSTRAINT [PK_PAR_PED_TIEND01] PRIMARY KEY CLUSTERED ([CVE_DOC] ASC, [NUM_PAR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PAR_PED_TIEND01]
    ON [dbo].[PAR_PED_TIEND01]([CVE_DOC] ASC);

