CREATE TABLE [dbo].[PAR_COMPQ_CLIB01] (
    [CLAVE_DOC] VARCHAR (20) NOT NULL,
    [NUM_PART]  INT          NOT NULL,
    [CAMPLIB1]  VARCHAR (10) NULL,
    [CAMPLIB2]  DATETIME     NULL,
    CONSTRAINT [PK_PAR_COMPQ_CLIB01] PRIMARY KEY CLUSTERED ([CLAVE_DOC] ASC, [NUM_PART] ASC)
);




GO



GO


