CREATE TABLE [dbo].[PARAM_DATOSEMP01] (
    [NUM_EMP]                 INT           NOT NULL,
    [NOMBRE_EMPRESA]          VARCHAR (512) NOT NULL,
    [DIRECCION]               VARCHAR (60)  NULL,
    [POBLACION]               VARCHAR (60)  NULL,
    [RFC]                     VARCHAR (30)  NULL,
    [REG_ESTATAL]             VARCHAR (30)  NULL,
    [LOGO_EMPRESA]            IMAGE         NULL,
    [ASIGNAVALPREDCVEPRODSAT] VARCHAR (1)   NULL,
    [VALPREDCVEPRODUCTOSAT]   VARCHAR (9)   NULL,
    [ASIGNAVALPREDUNIMEDSAT]  VARCHAR (1)   NULL,
    [VALPREDUNIMEDPRODSAT]    VARCHAR (4)   NULL,
    [CLIE_FACTGLOBAL]         VARCHAR (10)  NULL,
    CONSTRAINT [PK_PARAM_DATOSEMP01] PRIMARY KEY CLUSTERED ([NUM_EMP] ASC)
);




GO



GO



GO



GO



GO



GO



GO


