CREATE TABLE [dbo].[PARAM_CODI01] (
    [NUM_EMP]           INT            NOT NULL,
    [ALIAS_CERT]        VARCHAR (100)  NULL,
    [CONFIG_CODI]       VARCHAR (1)    NULL,
    [DIG_VERIF]         VARCHAR (100)  NULL,
    [CERT_CODI]         VARCHAR (1024) NULL,
    [CUENTA_BENEF]      VARCHAR (50)   NULL,
    [CVE_BANCO]         VARCHAR (5)    NULL,
    [KEYSOURCE]         VARCHAR (512)  NULL,
    [CVE_ACCESO_CERT]   VARCHAR (256)  NULL,
    [PRIVATE_KEY]       VARCHAR (1024) NULL,
    [SELLOCERT_ARCH]    IMAGE          NULL,
    [SELLOPRIVKEY_ARCH] IMAGE          NULL,
    [CONTRASENIA]       VARCHAR (255)  NULL,
    [KEYORIGINAL]       VARCHAR (512)  NULL,
    [CODI_NOMBREVEND]   VARCHAR (255)  NULL,
    CONSTRAINT [PK_PARAM_CODI01] PRIMARY KEY CLUSTERED ([NUM_EMP] ASC)
);

