CREATE TABLE [SONDA].[ERP_TB_PRICE_LIST_BY_SKU_PACK_SCALE] (
    [CODE_ROUTE]     VARCHAR (50)    NULL,
    [CODE_CUSTOMER]  VARCHAR (50)    NULL,
    [CODE_SKU]       VARCHAR (50)    NULL,
    [CODE_PACK_UNIT] VARCHAR (50)    NULL,
    [LIMIT]          NUMERIC (18)    NULL,
    [COST]           NUMERIC (18, 6) NULL
);

