CREATE TABLE [wms].[OP_BASC_IMGS_X_DOC] (
    [DOC_ID]          NUMERIC (18)  NULL,
    [FORM_CODE]       VARCHAR (50)  NULL,
    [IMG_ID]          NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [IMG_PIC]         IMAGE         NULL,
    [IMG_TITLE]       VARCHAR (150) NULL,
    [IMG_COMMENTS]    VARCHAR (150) NULL,
    [TAKEN_TIMESTAMP] DATETIME      NULL,
    [TAKEN_BY]        VARCHAR (25)  NULL,
    CONSTRAINT [_PK_OP_BASC_IMGS_X_DOC] PRIMARY KEY CLUSTERED ([IMG_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_OP_BASC_IMGS_X_DOC]
    ON [wms].[OP_BASC_IMGS_X_DOC]([DOC_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_OP_BASC_IMGS_X_DOC_1]
    ON [wms].[OP_BASC_IMGS_X_DOC]([FORM_CODE] ASC) WITH (FILLFACTOR = 80);

