CREATE TABLE [wms].[OP_BASC_DOCS] (
    [DOC_ID]            NUMERIC (18)  NOT NULL,
    [RESPONSE_ID]       NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [FORM_CODE]         VARCHAR (50)  NOT NULL,
    [QUESTION_ID]       NUMERIC (18)  NOT NULL,
    [QUESTION_RESPONSE] VARCHAR (MAX) NOT NULL,
    [INPUTED_TIMESTAMP] DATETIME      NULL,
    [INPUTED_BY]        VARCHAR (25)  NOT NULL,
    CONSTRAINT [PK_OP_BASC_DOCS] PRIMARY KEY CLUSTERED ([RESPONSE_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_OP_BASC_DOCS]
    ON [wms].[OP_BASC_DOCS]([DOC_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_OP_BASC_DOCS_1]
    ON [wms].[OP_BASC_DOCS]([INPUTED_TIMESTAMP] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_OP_BASC_DOCS_2]
    ON [wms].[OP_BASC_DOCS]([FORM_CODE] ASC, [QUESTION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_OP_BASC_DOCS_3]
    ON [wms].[OP_BASC_DOCS]([DOC_ID] ASC, [QUESTION_ID] ASC) WITH (FILLFACTOR = 80);

