CREATE TABLE [wms].[OP_SETUP_EXTERNAL_SOURCE] (
    [EXTERNAL_SOURCE_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE_NAME]              VARCHAR (50)  NULL,
    [DATA_BASE_NAME]           VARCHAR (50)  NULL,
    [SCHEMA_NAME]              VARCHAR (50)  NULL,
    [COMMENT]                  VARCHAR (250) NULL,
    [INTERFACE_DATA_BASE_NAME] VARCHAR (50)  NULL,
    [READ_ERP]                 INT           DEFAULT ((0)) NOT NULL,
    [IS_SONDA_SD]              INT           CONSTRAINT [DF_OP_SETUP_EXTERNAL_SOURCE_IS_SONDA_SD] DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([EXTERNAL_SOURCE_ID] ASC) WITH (FILLFACTOR = 80)
);

