CREATE TABLE [wms].[OP_SETUP_VERBOUSE] (
    [ERROR_DATETIME] DATETIME     NOT NULL,
    [LOGIN_ID]       VARCHAR (15) NULL,
    [ERROR_TEXT]     TEXT         NULL,
    [SQL_QUERY]      TEXT         NULL,
    CONSTRAINT [PK_OP_SETUP_VERBOUSE] PRIMARY KEY CLUSTERED ([ERROR_DATETIME] ASC) WITH (FILLFACTOR = 80)
);

