CREATE TABLE [wms].[OP_WMS_DISPATCH_FROM_EXTERNAL] (
    [LOGIN_ID]       VARCHAR (25)  NULL,
    [MATERIAL_ID]    VARCHAR (50)  NULL,
    [MATERIAL_NAME]  VARCHAR (150) NULL,
    [QTY_REQUESTED]  FLOAT (53)    NULL,
    [QTY_ONHAND]     FLOAT (53)    NULL,
    [PROCESS_RESULT] VARCHAR (200) NULL,
    [PROCESS_STAMP]  DATETIME      NULL,
    [READY_TO_GO]    INT           CONSTRAINT [DF_OP_WMS_DISPATCH_FROM_EXTERNAL_READY_TO_GO] DEFAULT ((0)) NULL
);

