CREATE TABLE [wms].[OP_WMS_SUPERVISIONS_DETAIL] (
    [SUPER_ID]    INT             NOT NULL,
    [CODE]        VARCHAR (50)    NOT NULL,
    [DESCRIPTION] VARCHAR (200)   NULL,
    [QTY]         DECIMAL (18, 2) NULL,
    [COST]        MONEY           NULL,
    CONSTRAINT [PK_OP_WMS_SUPERVISIONS_DETAIL] PRIMARY KEY CLUSTERED ([SUPER_ID] ASC, [CODE] ASC) WITH (FILLFACTOR = 80)
);

