CREATE TABLE [wms].[OP_WMS_TRANSFER_REQUEST_HEADER] (
    [TRANSFER_REQUEST_ID] INT           IDENTITY (1, 1) NOT NULL,
    [REQUEST_TYPE]        VARCHAR (50)  NOT NULL,
    [WAREHOUSE_FROM]      VARCHAR (25)  NOT NULL,
    [WAREHOUSE_TO]        VARCHAR (25)  NOT NULL,
    [REQUEST_DATE]        DATETIME      DEFAULT (getdate()) NOT NULL,
    [DELIVERY_DATE]       DATETIME      NULL,
    [COMMENT]             VARCHAR (250) NULL,
    [STATUS]              VARCHAR (25)  NOT NULL,
    [CREATED_BY]          VARCHAR (25)  NOT NULL,
    [LAST_UPDATE]         DATETIME      DEFAULT (getdate()) NOT NULL,
    [LAST_UPDATE_BY]      VARCHAR (25)  NOT NULL,
    [OWNER]               VARCHAR (50)  NULL,
    [DOC_NUM]             NUMERIC (18)  NULL,
    [DOC_ENTRY]           NUMERIC (18)  NULL,
    [IS_FROM_ERP]         INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_WMS_TRANSFER_REQUEST_HEADER] PRIMARY KEY CLUSTERED ([TRANSFER_REQUEST_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_TRANSFER_REQUEST_HEADER_REQUEST_DATE_TRANSFER_REQUEST_ID_WAREHOUSE_TO]
    ON [wms].[OP_WMS_TRANSFER_REQUEST_HEADER]([REQUEST_DATE] ASC, [TRANSFER_REQUEST_ID] ASC, [WAREHOUSE_TO] ASC)
    INCLUDE([WAREHOUSE_FROM], [CREATED_BY], [DELIVERY_DATE], [DOC_ENTRY], [DOC_NUM], [IS_FROM_ERP]) WITH (FILLFACTOR = 80);

