CREATE TABLE [wms].[OP_WMS_LOG_MATERIAL_PRINT] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [MATERIAL_ID] VARCHAR (50) NOT NULL,
    [LOG_DATE]    DATETIME     NOT NULL,
    [LOGIN_ID]    VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

