CREATE TABLE [wms].[OP_WMS_PHYSICAL_COUNTS_HEADER] (
    [PHYSICAL_COUNT_HEADER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [TASK_ID]                  INT           NULL,
    [REGIMEN]                  VARCHAR (50)  NULL,
    [DISTRIBUTION_CENTER]      VARCHAR (200) NULL,
    [STATUS]                   VARCHAR (25)  NULL,
    [TASK_SUBTYPE]             VARCHAR (25)  NULL,
    [IS_AUTHORIZED]            INT           NULL,
    CONSTRAINT [PK__OP_WMS_P__21DD382068B64B68] PRIMARY KEY CLUSTERED ([PHYSICAL_COUNT_HEADER_ID] ASC) WITH (FILLFACTOR = 80)
);

