CREATE TABLE [wms].[OP_WMS_TARIFICADOR_HEADER] (
    [ACUERDO_COMERCIAL_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [ACUERDO_COMERCIAL_NOMBRE] VARCHAR (50)  NULL,
    [VALID_FROM]               DATE          NULL,
    [VALID_TO]                 DATE          NULL,
    [EXPIRES]                  INT           NULL,
    [CURRENCY]                 VARCHAR (20)  NULL,
    [STATUS]                   VARCHAR (20)  NULL,
    [WAREHOUSE_WEATHER]        VARCHAR (20)  NULL,
    [LAST_UPDATED]             DATETIME      NULL,
    [LAST_UPDATED_BY]          VARCHAR (25)  NULL,
    [LAST_UPDATED_AUTH_BY]     VARCHAR (25)  NULL,
    [COMMENTS]                 VARCHAR (MAX) NULL,
    [REGIMEN]                  VARCHAR (25)  NULL,
    [AUTHORIZER]               VARCHAR (25)  NULL,
    [DEFAULT]                  INT           CONSTRAINT [DF_OP_WMS_TARIFICADOR_HEADER_DEFAULT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_WMS_TARIFICADOR_HEADER] PRIMARY KEY CLUSTERED ([ACUERDO_COMERCIAL_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_TARIFICADOR_HEADER_ACUERDO_COMERCIAL_ID_VALID_FROM_VALID_TO]
    ON [wms].[OP_WMS_TARIFICADOR_HEADER]([ACUERDO_COMERCIAL_ID] ASC)
    INCLUDE([VALID_FROM], [VALID_TO]) WITH (FILLFACTOR = 80);


GO
CREATE STATISTICS [20150916]
    ON [wms].[OP_WMS_TARIFICADOR_HEADER]([ACUERDO_COMERCIAL_ID], [ACUERDO_COMERCIAL_NOMBRE]);

