CREATE TABLE [wms].[OP_WMS_UNITS_X_PACKAGE] (
    [ERP_DOC]        VARCHAR (25)  NOT NULL,
    [BOX_ID]         VARCHAR (25)  NOT NULL,
    [MATERIAL_ID]    VARCHAR (25)  NOT NULL,
    [MATERIAL_NAME]  VARCHAR (200) NULL,
    [QUANTITY_UNITS] NUMERIC (18)  NULL,
    [TRANS_OWNER]    NUMERIC (18)  NULL,
    CONSTRAINT [PK_OP_WMS_UNITS_BY_PACKAGE] PRIMARY KEY CLUSTERED ([BOX_ID] ASC, [MATERIAL_ID] ASC) WITH (FILLFACTOR = 80)
);

