CREATE TABLE [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] (
    [PICKING_DEMAND_DETAIL_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PICKING_DEMAND_HEADER_ID] INT             NOT NULL,
    [MATERIAL_ID]              VARCHAR (50)    NOT NULL,
    [QTY]                      DECIMAL (18, 4) NULL,
    [LINE_NUM]                 INT             DEFAULT ((-1)) NOT NULL,
    [ERP_OBJECT_TYPE]          INT             NULL,
    [PRICE]                    NUMERIC (18, 6) DEFAULT ((0.0)) NOT NULL,
    [WAS_IMPLODED]             INT             DEFAULT ((0)) NOT NULL,
    [QTY_IMPLODED]             INT             DEFAULT ((0)) NOT NULL,
    [MASTER_ID_MATERIAL]       VARCHAR (50)    NULL,
    [MATERIAL_OWNER]           VARCHAR (50)    NULL,
    [ATTEMPTED_WITH_ERROR]     INT             DEFAULT ((0)) NOT NULL,
    [IS_POSTED_ERP]            INT             DEFAULT ((0)) NOT NULL,
    [POSTED_ERP]               DATETIME        NULL,
    [ERP_REFERENCE]            VARCHAR (50)    NULL,
    [POSTED_STATUS]            VARCHAR (50)    NULL,
    [POSTED_RESPONSE]          VARCHAR (4000)  NULL,
    [INNER_SALE_STATUS]        VARCHAR (50)    NULL,
    [INNER_SALE_RESPONSE]      VARCHAR (1000)  NULL,
    [TONE]                     VARCHAR (20)    NULL,
    [CALIBER]                  VARCHAR (20)    NULL,
    [DISCOUNT]                 DECIMAL (18, 6) DEFAULT ((0)) NOT NULL,
    [IS_BONUS]                 INT             DEFAULT ((0)) NOT NULL,
    [DISCOUNT_TYPE]            VARCHAR (50)    NULL,
    [UNIT_MEASUREMENT]         VARCHAR (250)   NULL,
    [STATUS_CODE]              VARCHAR (50)    NULL,
    [CURRENT_COST_BY_PRODUCT]  FLOAT (53)      NULL,
    PRIMARY KEY CLUSTERED ([PICKING_DEMAND_DETAIL_ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_HEADER_ID]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([ERP_OBJECT_TYPE], [LINE_NUM], [MASTER_ID_MATERIAL], [MATERIAL_ID], [MATERIAL_OWNER], [PICKING_DEMAND_DETAIL_ID], [PRICE], [QTY], [QTY_IMPLODED], [WAS_IMPLODED], [ERP_REFERENCE], [POSTED_RESPONSE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_PICKING_DEMAND_DETAIL_IS_POSTED_ERP]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [IS_POSTED_ERP], [POSTED_ERP], [POSTED_STATUS]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_OWNER_PICKING_DEMAND_HEADER_ID]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_OWNER] ASC, [PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [PICKING_DEMAND_DETAIL_ID], [POSTED_RESPONSE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_HEADER_ID_MATERIAL_ID_LINE_NUM]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [MATERIAL_ID] ASC, [LINE_NUM] ASC)
    INCLUDE([QTY]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_IS_POSTED_ERP_PICKING_DEMAND_HEADER_ID]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([IS_POSTED_ERP] ASC, [PICKING_DEMAND_HEADER_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_ID_PICKING_DEMAND_HEADER_ID_PICKING_DEMAND_HEADER_ID]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_ID] ASC, [PICKING_DEMAND_HEADER_ID] ASC, [MASTER_ID_MATERIAL] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [ERP_OBJECT_TYPE], [ERP_REFERENCE], [IS_POSTED_ERP], [LINE_NUM], [POSTED_ERP], [POSTED_RESPONSE], [POSTED_STATUS], [PRICE], [QTY], [WAS_IMPLODED], [PICKING_DEMAND_DETAIL_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_ID_PICKING_DEMAND_HEADER_ID_PICKING_DEMAND_HEADER_ID_MATERIAL_OWNER]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_ID] ASC, [PICKING_DEMAND_HEADER_ID] ASC, [MASTER_ID_MATERIAL] ASC, [MATERIAL_OWNER] ASC)
    INCLUDE([POSTED_ERP], [POSTED_RESPONSE], [POSTED_STATUS], [PRICE], [QTY], [WAS_IMPLODED], [ATTEMPTED_WITH_ERROR], [ERP_OBJECT_TYPE], [ERP_REFERENCE], [IS_POSTED_ERP], [LINE_NUM], [PICKING_DEMAND_DETAIL_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_PICKING_DEMAND_HEADER_ID_INNER_SALE_STATUS]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [INNER_SALE_STATUS] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_PICKING_DEMAND_HEADER_ID_MATERIAL_OWNER]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [MATERIAL_OWNER] ASC)
    INCLUDE([INNER_SALE_RESPONSE], [INNER_SALE_STATUS], [PICKING_DEMAND_DETAIL_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_MANIFEST_HEADER_PICKING_DEMAND_HEADER]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([LINE_NUM], [MATERIAL_ID], [QTY]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_PICKING_DEMAND_DETAIL_ID]
    ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_DETAIL_ID] ASC)
    INCLUDE([CALIBER], [TONE], [INNER_SALE_STATUS], [INNER_SALE_RESPONSE], [QTY_IMPLODED]) WITH (FILLFACTOR = 80);


GO


CREATE TRIGGER [wms].[Duplicatesremoval] ON [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]
FOR INSERT
AS

IF (EXISTS(SELECT 1 FROM inserted))
 BEGIN
    DELETE FROM [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] where MATERIAL_ID IN (SELECT MATERIAL_ID FROM inserted) AND QTY IN (SELECT QTY FROM  inserted)
	AND PICKING_DEMAND_HEADER_ID IN (SELECT PICKING_DEMAND_HEADER_ID FROM  inserted)
    INSERT INTO [wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]
	([PICKING_DEMAND_HEADER_ID]
      ,[MATERIAL_ID]
      ,[QTY]
      ,[LINE_NUM]
      ,[ERP_OBJECT_TYPE]
      ,[PRICE]
      ,[WAS_IMPLODED]
      ,[QTY_IMPLODED]
      ,[MASTER_ID_MATERIAL]
      ,[MATERIAL_OWNER]
      ,[ATTEMPTED_WITH_ERROR]
      ,[IS_POSTED_ERP]
      ,[POSTED_ERP]
      ,[ERP_REFERENCE]
      ,[POSTED_STATUS]
      ,[POSTED_RESPONSE]
      ,[INNER_SALE_STATUS]
      ,[INNER_SALE_RESPONSE]
      ,[TONE]
      ,[CALIBER]
      ,[DISCOUNT]
      ,[IS_BONUS]
      ,[DISCOUNT_TYPE]
      ,[UNIT_MEASUREMENT]
      ,[STATUS_CODE]
      ,[CURRENT_COST_BY_PRODUCT])
    SELECT [PICKING_DEMAND_HEADER_ID]
      ,[MATERIAL_ID]
      ,[QTY]
      ,[LINE_NUM]
      ,[ERP_OBJECT_TYPE]
      ,[PRICE]
      ,[WAS_IMPLODED]
      ,[QTY_IMPLODED]
      ,[MASTER_ID_MATERIAL]
      ,[MATERIAL_OWNER]
      ,[ATTEMPTED_WITH_ERROR]
      ,[IS_POSTED_ERP]
      ,[POSTED_ERP]
      ,[ERP_REFERENCE]
      ,[POSTED_STATUS]
      ,[POSTED_RESPONSE]
      ,[INNER_SALE_STATUS]
      ,[INNER_SALE_RESPONSE]
      ,[TONE]
      ,[CALIBER]
      ,[DISCOUNT]
      ,[IS_BONUS]
      ,[DISCOUNT_TYPE]
      ,[UNIT_MEASUREMENT]
      ,[STATUS_CODE]
      ,[CURRENT_COST_BY_PRODUCT] FROM inserted
END


GO
GRANT SELECT
    ON OBJECT::[wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] TO [Uwms]
    AS [wms];

