CREATE TABLE [wms].[OP_WMS_MATERIALS_JOIN_SPOTS_vaci] (
    [MATERIAL_ID]      VARCHAR (25) NOT NULL,
    [WAREHOUSE_PARENT] VARCHAR (25) NOT NULL,
    [LOCATION_SPOT]    VARCHAR (25) NOT NULL,
    [LAST_UPDATED]     DATETIME     CONSTRAINT [DF_OP_WMS_MATERIALS_JOIN_SPOTS_LAST_UPDATED] DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]  VARCHAR (25) NULL,
    [MAX_QUANTITY]     NUMERIC (18) NULL,
    [MIN_QUANTITY]     NUMERIC (18) NULL,
    [TMP_MIN]          NUMERIC (18) NULL,
    [TMP_MAX]          NUMERIC (18) NULL,
    CONSTRAINT [PK_OP_WMS_MATERIALS_JOIN_SPOTS] PRIMARY KEY CLUSTERED ([MATERIAL_ID] ASC, [WAREHOUSE_PARENT] ASC, [LOCATION_SPOT] ASC)
);

