CREATE TABLE [wms].[OP_WMS_INV_X_LICENSE_HIST] (
    [DDMMYYYY]        CHAR (10)       NOT NULL,
    [PK_LINE]         NUMERIC (18)    NOT NULL,
    [LICENSE_ID]      NUMERIC (18)    NOT NULL,
    [MATERIAL_ID]     VARCHAR (50)    NOT NULL,
    [MATERIAL_NAME]   VARCHAR (150)   NULL,
    [QTY]             NUMERIC (18)    NOT NULL,
    [VOLUME_FACTOR]   NUMERIC (18)    NULL,
    [WEIGTH]          NUMERIC (18, 2) NULL,
    [SERIAL_NUMBER]   VARCHAR (50)    NULL,
    [COMMENTS]        VARCHAR (250)   NULL,
    [LAST_UPDATED]    DATETIME        NULL,
    [LAST_UPDATED_BY] VARCHAR (25)    NULL,
    [BARCODE_ID]      VARCHAR (25)    NULL,
    [TERMS_OF_TRADE]  VARCHAR (50)    NOT NULL,
    [STATUS]          VARCHAR (25)    NULL,
    [CREATED_DATE]    DATETIME        NULL,
    [DATE_EXPIRATION] DATE            NULL,
    [BATCH]           VARCHAR (50)    NULL,
    CONSTRAINT [PK_OP_WMS_INV_X_LICENSE_HIST] PRIMARY KEY CLUSTERED ([DDMMYYYY] ASC, [PK_LINE] ASC) WITH (FILLFACTOR = 80)
);

