CREATE TABLE [wms].[OP_WMS_SERVICES_TO_BILL] (
    [SERVICES_TO_BILL_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [QTY]                     NUMERIC (18, 2) NOT NULL,
    [TRANSACTION_TYPE]        VARCHAR (25)    NOT NULL,
    [PRICE]                   NUMERIC (18, 2) NOT NULL,
    [TOTAL_AMOUNT]            NUMERIC (18, 2) NOT NULL,
    [PROCESS_DATE]            DATETIME        NOT NULL,
    [CREATED_DATE]            DATETIME        NOT NULL,
    [LAST_UPDATED_DATE]       DATETIME        NULL,
    [LAST_UPDATED_BY]         VARCHAR (25)    NOT NULL,
    [TYPE_CHARGE_ID]          INT             NULL,
    [TYPE_CHARGE_DESCRIPTION] VARCHAR (250)   NULL,
    [CLIENT_CODE]             VARCHAR (25)    NULL,
    [CLIENT_NAME]             VARCHAR (250)   NULL,
    [IS_CHARGED]              INT             NULL,
    [INVOICE_REFERENCE]       VARCHAR (30)    NULL,
    [CHARGED_DATE]            DATETIME        NULL,
    [LICENSE_ID]              NUMERIC (9)     NULL,
    [LOCATION]                VARCHAR (25)    NULL,
    [SERVICE_ID]              INT             NULL,
    [SERVICE_CODE]            VARCHAR (25)    NULL,
    [SERVICE_DESCRIPTION]     VARCHAR (250)   NULL,
    [REGIMEN]                 VARCHAR (25)    NULL,
    [DOC_NUM]                 INT             NULL,
    [TRANSACTION_ID]          INT             NULL,
    [HAS_ADJUST]              INT             DEFAULT ((0)) NULL,
    [BILLING_FRECUENCY]       INT             DEFAULT ((0)) NULL,
    [ACUERDO_COMERCIAL]       INT             NULL,
    PRIMARY KEY CLUSTERED ([SERVICES_TO_BILL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_SERVICES_TO_BILL_ACUERDO_COMERCIAL] FOREIGN KEY ([ACUERDO_COMERCIAL]) REFERENCES [wms].[OP_WMS_TARIFICADOR_HEADER] ([ACUERDO_COMERCIAL_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_CLIENT_CODE]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([CLIENT_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_TRANSACTION_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([TRANSACTION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_CLIENT_CODE_TRANSACTION_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([CLIENT_CODE] ASC, [TRANSACTION_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_REGIMEN]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([REGIMEN] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_CLIENT_CODE_REGIMEN]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([CLIENT_CODE] ASC, [REGIMEN] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_DOC_NUM]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([DOC_NUM] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_TYPE_CHARGE_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([TYPE_CHARGE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_CLIENT_CODE_TYPE_CHARGE_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([CLIENT_CODE] ASC, [TYPE_CHARGE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_LICENSE_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([LICENSE_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICES_TO_BILL_CLIENT_CODE_LICENSE_ID]
    ON [wms].[OP_WMS_SERVICES_TO_BILL]([CLIENT_CODE] ASC, [LICENSE_ID] ASC) WITH (FILLFACTOR = 80);

