CREATE TABLE [wms].[OP_WMS_AUDIT_DISPATCH_SKUS] (
    [AUDIT_ID]        NUMERIC (18)  NOT NULL,
    [CODIGO_POLIZA]   VARCHAR (50)  NOT NULL,
    [MATERIAL_ID]     VARCHAR (50)  NOT NULL,
    [BATCH]           VARCHAR (50)  NOT NULL,
    [DATE_EXPIRATION] DATE          NOT NULL,
    [BARCODE_ID]      VARCHAR (50)  NULL,
    [MATERIAL_NAME]   VARCHAR (250) NULL,
    [SCANNED_COUNT]   NUMERIC (18)  NULL,
    [INPUTED_COUNT]   NUMERIC (18)  NULL,
    [LAST_UPDATED]    DATETIME      NULL,
    [LAST_UPDATED_BY] VARCHAR (25)  NULL,
    CONSTRAINT [PK_OP_WMS_DISPATCH_AUDIT_SKUS] PRIMARY KEY CLUSTERED ([AUDIT_ID] ASC, [CODIGO_POLIZA] ASC, [MATERIAL_ID] ASC, [BATCH] ASC, [DATE_EXPIRATION] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_OP_WMS_AUDIT_DISPATCH_SKUS_BY_ID]
    ON [wms].[OP_WMS_AUDIT_DISPATCH_SKUS]([AUDIT_ID] ASC) WITH (FILLFACTOR = 80);

