CREATE TABLE [wms].[OP_WMS_LOGIN_JOIN_LOCATIONS] (
    [LOGIN_ID]         VARCHAR (25) NOT NULL,
    [LOGIN_NAME]       VARCHAR (50) NOT NULL,
    [WAREHOUSE_PARENT] VARCHAR (25) NOT NULL,
    [LOCATION_SPOT]    VARCHAR (25) NOT NULL,
    [LINE_ID]          VARCHAR (15) NULL,
    [TASK_TYPE]        VARCHAR (25) NULL,
    CONSTRAINT [PK_OP_WMS_LOGIN_JOIN_LOCATIONS] PRIMARY KEY CLUSTERED ([LOGIN_ID] ASC, [LOCATION_SPOT] ASC) WITH (FILLFACTOR = 80)
);

