CREATE TABLE [wms].[OP_WMS_SERVICES_LOG] (
    [CLIENT_ERP_CODE]  VARCHAR (50)    NOT NULL,
    [SERVICE_ID]       VARCHAR (50)    NOT NULL,
    [ACTION_NAME]      VARCHAR (150)   NULL,
    [LAST_QTY]         NUMERIC (18, 2) NULL,
    [LAST_WEIGTH]      NUMERIC (18, 2) NULL,
    [NEW_QTY]          NUMERIC (18, 2) NULL,
    [NEW_WEIGTH]       NUMERIC (18, 2) NULL,
    [CREATED_DATETIME] DATETIME        NULL,
    [CREATED_BY]       VARCHAR (25)    NULL
);

