CREATE TABLE [wms].[OP_WMS_CERTIFICATION_HEADER] (
    [CERTIFICATION_HEADER_ID] INT          IDENTITY (1, 1) NOT NULL,
    [MANIFEST_HEADER_ID]      INT          NOT NULL,
    [CREATE_DATE]             DATETIME     NULL,
    [CREATE_BY]               VARCHAR (25) NULL,
    [STATUS]                  VARCHAR (20) NULL,
    [LAST_UPDATE]             DATETIME     NULL,
    [LAST_UPDATE_BY]          VARCHAR (25) NULL,
    CONSTRAINT [PK_OP_WMS_CERTIFICATION_HEADER_CERTIFICATION_HEADER_ID] PRIMARY KEY CLUSTERED ([CERTIFICATION_HEADER_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IDX_CERTIFICATION_HEADER_MANIFEST_HEADER_ID]
    ON [wms].[OP_WMS_CERTIFICATION_HEADER]([MANIFEST_HEADER_ID] ASC)
    INCLUDE([CERTIFICATION_HEADER_ID], [STATUS]) WITH (FILLFACTOR = 80);

