CREATE TABLE [wms].[OP_WMS_WP_SYS_ACCOUNTS] (
    [ACCOUNT_ID]     VARCHAR (140) NOT NULL,
    [ACCOUNT_NAME]   VARCHAR (100) NULL,
    [STATUS]         VARCHAR (15)  NULL,
    [PWD1]           VARCHAR (70)  NULL,
    [PWD2]           VARCHAR (70)  NULL,
    [LAST_UPDATE]    DATETIME      NULL,
    [LAST_UPDATE_BY] VARCHAR (25)  NULL,
    [LAST_ACTION]    VARCHAR (250) NULL,
    CONSTRAINT [PK_SYS_ACCOUNTS] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC) WITH (FILLFACTOR = 80)
);

