CREATE TABLE [wms].[OP_WMS_HH_BUTTON_ACTION] (
    [BUTTON_ACTION_ID] INT           IDENTITY (1, 1) NOT NULL,
    [CODE_ACTION]      VARCHAR (25)  NOT NULL,
    [DESCRIPTION]      VARCHAR (125) NOT NULL,
    PRIMARY KEY CLUSTERED ([BUTTON_ACTION_ID] ASC) WITH (FILLFACTOR = 80),
    UNIQUE NONCLUSTERED ([CODE_ACTION] ASC) WITH (FILLFACTOR = 80)
);

