CREATE TABLE [wms].[OP_WMS_INSURANCE_LOG] (
    [DOC_ID]           INT             NULL,
    [LAST_UPDATED_BY]  VARCHAR (25)    NULL,
    [LAST_UPDATED]     DATETIME        NULL,
    [LAST_AMOUNT]      NUMERIC (18, 2) NULL,
    [LAST_COVERAGE]    VARCHAR (250)   NULL,
    [CURRENT_AMOUNT]   NUMERIC (18, 2) NULL,
    [CURRENT_CIVERAGE] VARCHAR (250)   NULL
);

