CREATE TABLE [wms].[OP_WMS_QUERY_LIST] (
    [ID]    INT           IDENTITY (1, 1) NOT NULL,
    [NAME]  VARCHAR (150) NULL,
    [QUERY] VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

