CREATE TABLE [wms].[OP_WMS_SECURITY_LICENSE] (
    [ID_LICENSE]    INT           NOT NULL,
    [LICENSE]       VARCHAR (MAX) NULL,
    [CREATION_DATE] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ID_LICENSE] ASC)
);

