CREATE TABLE [wms].[OP_WMS_LICENSES] (
    [LICENSE_ID]                        NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [CLIENT_OWNER]                      VARCHAR (25)    NULL,
    [CODIGO_POLIZA]                     VARCHAR (25)    NULL,
    [CURRENT_WAREHOUSE]                 VARCHAR (25)    NULL,
    [CURRENT_LOCATION]                  VARCHAR (25)    NULL,
    [LAST_LOCATION]                     VARCHAR (25)    NULL,
    [LAST_UPDATED]                      DATETIME        NULL,
    [LAST_UPDATED_BY]                   VARCHAR (15)    NULL,
    [STATUS]                            VARCHAR (15)    NULL,
    [REGIMEN]                           VARCHAR (50)    NULL,
    [CREATED_DATE]                      DATETIME        NULL,
    [USED_MT2]                          NUMERIC (18, 2) NULL,
    [CODIGO_POLIZA_RECTIFICACION]       VARCHAR (25)    NULL,
    [PICKING_DEMAND_HEADER_ID]          INT             NULL,
    [WAVE_PICKING_ID]                   INT             NULL,
    [TARGET_LOCATION_REPLENISHMENT]     VARCHAR (30)    NULL,
    [LAST_LICENSE_USED_IN_FAST_PICKING] NUMERIC (18)    NULL,
    CONSTRAINT [PK_OP_WMS_LICENCIAS] PRIMARY KEY CLUSTERED ([LICENSE_ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_LICENSES_CODIGO_POLIZA]
    ON [wms].[OP_WMS_LICENSES]([CODIGO_POLIZA] ASC)
    INCLUDE([LICENSE_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_OP_WMS_LICENSES_CURRENT_WAREHOUSE]
    ON [wms].[OP_WMS_LICENSES]([CURRENT_WAREHOUSE] ASC)
    INCLUDE([LICENSE_ID], [REGIMEN], [CLIENT_OWNER], [CODIGO_POLIZA], [CURRENT_LOCATION]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_LICENSES_REGIMEN]
    ON [wms].[OP_WMS_LICENSES]([REGIMEN] ASC)
    INCLUDE([CLIENT_OWNER], [CODIGO_POLIZA], [CURRENT_LOCATION], [CURRENT_WAREHOUSE], [LAST_UPDATED_BY], [LICENSE_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_LICENSES_CURRENT_WAREHOUSE]
    ON [wms].[OP_WMS_LICENSES]([CURRENT_WAREHOUSE] ASC)
    INCLUDE([CLIENT_OWNER], [CODIGO_POLIZA], [CURRENT_LOCATION], [LAST_UPDATED_BY], [LICENSE_ID], [REGIMEN], [USED_MT2]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_OP_WMS_LICENSES_LICENSE_ID]
    ON [wms].[OP_WMS_LICENSES]([LICENSE_ID] ASC)
    INCLUDE([CLIENT_OWNER], [CURRENT_WAREHOUSE], [REGIMEN]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_CURRENT_LOCATION_LICENSES]
    ON [wms].[OP_WMS_LICENSES]([CURRENT_LOCATION] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [I_OP_WMS_LICENSE_PD_INC_LOC]
    ON [wms].[OP_WMS_LICENSES]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([CURRENT_LOCATION]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_LICENSE_WAVE_PICKING]
    ON [wms].[OP_WMS_LICENSES]([WAVE_PICKING_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [licences_w]
    ON [wms].[OP_WMS_LICENSES]([CURRENT_WAREHOUSE] ASC, [REGIMEN] ASC)
    INCLUDE([CLIENT_OWNER], [CODIGO_POLIZA], [CURRENT_LOCATION]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [idx_licen_clieow]
    ON [wms].[OP_WMS_LICENSES]([CLIENT_OWNER] ASC, [REGIMEN] ASC)
    INCLUDE([CODIGO_POLIZA], [CURRENT_WAREHOUSE], [CURRENT_LOCATION]);

