CREATE TABLE [wms].[OP_WMS_MATERIAL_PROPERTY_OPTION] (
    [MATERIAL_PROPERTY_ID] INT           NOT NULL,
    [VALUE]                VARCHAR (250) NOT NULL,
    [TEXT]                 VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_OP_WMS_MATERIAL_PROPERTY_OPTION] PRIMARY KEY CLUSTERED ([MATERIAL_PROPERTY_ID] ASC, [VALUE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_OP_WMS_MATERIAL_PROPERTY_OPTION_MATERIAL_PROPERTY_ID] FOREIGN KEY ([MATERIAL_PROPERTY_ID]) REFERENCES [wms].[OP_WMS_MATERIAL_PROPERTY] ([MATERIAL_PROPERTY_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_PROPERTY_OPTION_MATERIAL_PROPERTY_ID]
    ON [wms].[OP_WMS_MATERIAL_PROPERTY_OPTION]([MATERIAL_PROPERTY_ID] ASC)
    INCLUDE([VALUE], [TEXT]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_PROPERTY_OPTION_TEXT]
    ON [wms].[OP_WMS_MATERIAL_PROPERTY_OPTION]([TEXT] ASC)
    INCLUDE([VALUE], [MATERIAL_PROPERTY_ID]) WITH (FILLFACTOR = 80);

