CREATE TABLE [wms].[OP_WMS_MATERIAL_INTERCOMPANY] (
    [MASTER_ID] VARCHAR (50) NOT NULL,
    [ITEM_CODE] VARCHAR (50) NOT NULL,
    [SOURCE]    VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([MASTER_ID] ASC, [ITEM_CODE] ASC, [SOURCE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_INTERCOMPANY_SOURCE_ITEM_CODE]
    ON [wms].[OP_WMS_MATERIAL_INTERCOMPANY]([SOURCE] ASC, [ITEM_CODE] ASC)
    INCLUDE([MASTER_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_INTERCOMPANY_SOURCE_MASTER_ID]
    ON [wms].[OP_WMS_MATERIAL_INTERCOMPANY]([SOURCE] ASC, [MASTER_ID] ASC)
    INCLUDE([ITEM_CODE]) WITH (FILLFACTOR = 80);

