CREATE TABLE [wms].[OP_WMS_CHECKPOINTS] (
    [CHECK_ID]        VARCHAR (50)   NOT NULL,
    [CATEGORY]        VARCHAR (25)   NOT NULL,
    [DESCRIPTION]     VARCHAR (150)  NOT NULL,
    [PARENT]          VARCHAR (50)   NULL,
    [ACCESS]          VARCHAR (25)   NOT NULL,
    [MPC_1]           NUMERIC (18)   NULL,
    [MPC_2]           NUMERIC (18)   NULL,
    [MPC_3]           VARCHAR (50)   NULL,
    [MPC_4]           NUMERIC (18)   NULL,
    [MPC_5]           VARCHAR (50)   NULL,
    [TARGET_LOCATION] VARCHAR (126)  NULL,
    [ORDER]           INT            DEFAULT ((0)) NULL,
    [TYPE]            VARCHAR (26)   NULL,
    [PATH_IMAGE]      VARCHAR (1000) NULL,
    CONSTRAINT [PK_OP_WMS_CHECKPOINTS] PRIMARY KEY CLUSTERED ([CHECK_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CHECKPOINTS_PARENT_CATEGORY]
    ON [wms].[OP_WMS_CHECKPOINTS]([PARENT] ASC, [CATEGORY] ASC)
    INCLUDE([CHECK_ID], [DESCRIPTION], [MPC_1], [MPC_2], [MPC_3], [MPC_4], [MPC_5], [ACCESS]) WITH (FILLFACTOR = 80);

