CREATE TABLE [wms].[OP_WMS_SLOTTING_ZONE_BY_SUB_CLASS] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [ID_SLOTTING_ZONE] UNIQUEIDENTIFIER NOT NULL,
    [SUB_CLASS_ID]     INT              NOT NULL,
    [SUB_CLASS_NAME]   VARCHAR (50)     NULL,
    CONSTRAINT [PK_OP_WMS_SLOTTING_ZONE_BY_SUB_CLASS_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_SLOTTINGZONEBYSUBCLASS_SLOTTINGHEADER] FOREIGN KEY ([ID_SLOTTING_ZONE]) REFERENCES [wms].[OP_WMS_SLOTTING_ZONE] ([ID]),
    UNIQUE NONCLUSTERED ([ID_SLOTTING_ZONE] ASC, [SUB_CLASS_ID] ASC) WITH (FILLFACTOR = 80)
);

