CREATE TABLE [wms].[OP_WMS_MASTER_PACK_DETAIL] (
    [MASTER_PACK_DETAIL_ID] INT           IDENTITY (1, 1) NOT NULL,
    [MASTER_PACK_HEADER_ID] INT           NOT NULL,
    [MATERIAL_ID]           VARCHAR (50)  NOT NULL,
    [QTY]                   INT           NOT NULL,
    [BATCH]                 VARCHAR (50)  NULL,
    [DATE_EXPIRATION]       DATETIME      NULL,
    [POSTED_STATUS]         INT           NULL,
    [POSTED_ERP]            DATETIME      NULL,
    [POSTED_RESPONSE]       VARCHAR (500) NULL,
    [ERP_REFERENCE]         VARCHAR (50)  NULL,
    [IS_POSTED_ERP]         INT           NULL,
    [ATTEMPTED_WITH_ERROR]  INT           NULL,
    CONSTRAINT [PK_OP_WMS_MASTER_PACK_DETAIL] PRIMARY KEY CLUSTERED ([MASTER_PACK_DETAIL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_OP_WMS_MASTER_PACK_DETAIL_MASTER_PACK_HEADER_ID] FOREIGN KEY ([MASTER_PACK_HEADER_ID]) REFERENCES [wms].[OP_WMS_MASTER_PACK_HEADER] ([MASTER_PACK_HEADER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MASTER_PACK_DETAIL_HEADER_ID]
    ON [wms].[OP_WMS_MASTER_PACK_DETAIL]([MASTER_PACK_HEADER_ID] ASC)
    INCLUDE([MATERIAL_ID], [QTY]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MASTER_PACK_DETAIL_MASTER_PACK_HEADER_ID]
    ON [wms].[OP_WMS_MASTER_PACK_DETAIL]([MASTER_PACK_HEADER_ID] ASC)
    INCLUDE([MATERIAL_ID], [QTY], [BATCH], [DATE_EXPIRATION]) WITH (FILLFACTOR = 80);

