CREATE TABLE [wms].[OP_WMS_PRICE_LIST_FOR_INTERCOMPANY] (
    [MASTER_ID_CUSTOMER] VARCHAR (50)    NOT NULL,
    [PRICE_LIST]         VARCHAR (10)    NOT NULL,
    [MATERIAL_ID]        VARCHAR (50)    NOT NULL,
    [PRICE]              NUMERIC (18, 6) NOT NULL,
    [SOURCE]             VARCHAR (50)    NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PRICE_LIST_FOR_INTERCOMPANY_SOURCE_MATERIAL_ID]
    ON [wms].[OP_WMS_PRICE_LIST_FOR_INTERCOMPANY]([SOURCE] ASC, [MATERIAL_ID] ASC)
    INCLUDE([MASTER_ID_CUSTOMER], [PRICE], [PRICE_LIST]) WITH (FILLFACTOR = 80);

