CREATE TABLE [wms].[OP_WMS_TRANSPORT_COMPANY] (
    [TRANSPORT_COMPANY_CODE] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                   VARCHAR (250) NOT NULL,
    [ADDRESS]                VARCHAR (250) NULL,
    [TELEPHONE]              VARCHAR (25)  NULL,
    [CONTACT]                VARCHAR (50)  NULL,
    [MAIL]                   VARCHAR (100) NULL,
    [LAST_UPDATE]            DATETIME      DEFAULT (getdate()) NULL,
    [LAST_UPDATE_BY]         VARCHAR (25)  NULL,
    [IS_OWN]                 INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_WMS_TRANSPORT_COMPANY_TRANSPORT_COMPANY_CODE] PRIMARY KEY CLUSTERED ([TRANSPORT_COMPANY_CODE] ASC) WITH (FILLFACTOR = 80)
);

