CREATE TABLE [wms].[OP_WMS_TASK_LIST_BU] (
    [SERIAL_NUMBER]                NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [WAVE_PICKING_ID]              NUMERIC (18)    NULL,
    [TRANS_OWNER]                  NUMERIC (18)    NULL,
    [TASK_TYPE]                    VARCHAR (25)    NOT NULL,
    [TASK_SUBTYPE]                 VARCHAR (25)    NOT NULL,
    [TASK_OWNER]                   VARCHAR (25)    NOT NULL,
    [TASK_ASSIGNEDTO]              VARCHAR (25)    NOT NULL,
    [TASK_COMMENTS]                VARCHAR (150)   NULL,
    [ASSIGNED_DATE]                DATETIME        NOT NULL,
    [QUANTITY_PENDING]             NUMERIC (18, 4) NOT NULL,
    [QUANTITY_ASSIGNED]            NUMERIC (18, 4) NOT NULL,
    [CODIGO_POLIZA_SOURCE]         VARCHAR (25)    NULL,
    [CODIGO_POLIZA_TARGET]         VARCHAR (25)    NULL,
    [LICENSE_ID_SOURCE]            NUMERIC (18)    NULL,
    [REGIMEN]                      VARCHAR (50)    NULL,
    [IS_COMPLETED]                 NUMERIC (18)    NULL,
    [IS_DISCRETIONAL]              INT             NOT NULL,
    [IS_PAUSED]                    NUMERIC (18)    NULL,
    [IS_CANCELED]                  NUMERIC (18)    NULL,
    [MATERIAL_ID]                  VARCHAR (25)    NOT NULL,
    [BARCODE_ID]                   VARCHAR (50)    NOT NULL,
    [ALTERNATE_BARCODE]            VARCHAR (50)    NULL,
    [MATERIAL_NAME]                VARCHAR (200)   NOT NULL,
    [WAREHOUSE_SOURCE]             VARCHAR (25)    NULL,
    [WAREHOUSE_TARGET]             VARCHAR (25)    NULL,
    [LOCATION_SPOT_SOURCE]         VARCHAR (25)    NULL,
    [LOCATION_SPOT_TARGET]         VARCHAR (25)    NULL,
    [CLIENT_OWNER]                 VARCHAR (25)    NULL,
    [CLIENT_NAME]                  VARCHAR (150)   NULL,
    [ACCEPTED_DATE]                DATETIME        NULL,
    [COMPLETED_DATE]               DATETIME        NULL,
    [CANCELED_DATETIME]            DATETIME        NULL,
    [CANCELED_BY]                  VARCHAR (25)    NULL,
    [MATERIAL_SHORT_NAME]          VARCHAR (200)   NULL,
    [IS_lOCKED]                    VARCHAR (1)     NULL,
    [IS_DISCRETIONARY]             INT             NOT NULL,
    [TYPE_DISCRETIONARY]           VARCHAR (100)   NULL,
    [LINE_NUMBER_POLIZA_SOURCE]    INT             NULL,
    [LINE_NUMBER_POLIZA_TARGET]    INT             NULL,
    [DOC_ID_SOURCE]                NUMERIC (18)    NULL,
    [DOC_ID_TARGET]                NUMERIC (18)    NULL,
    [IS_ACCEPTED]                  INT             NULL,
    [IS_FROM_SONDA]                INT             NULL,
    [IS_FROM_ERP]                  INT             NOT NULL,
    [PRIORITY]                     INT             NOT NULL,
    [REPLENISH_MATERIAL_ID_TARGET] VARCHAR (25)    NULL
);

