CREATE TABLE [wms].[OP_WMS_POLIZA_CHECKLOG] (
    [CODIGO_POLIZA]      VARCHAR (15) NOT NULL,
    [NUMERO_ORDEN]       VARCHAR (25) NULL,
    [FECHA_HORA_INGRESO] DATETIME     NULL,
    CONSTRAINT [PK_OP_WMS_POLIZA_CHECKLOG] PRIMARY KEY CLUSTERED ([CODIGO_POLIZA] ASC) WITH (FILLFACTOR = 80)
);

