CREATE TABLE [wms].[OP_WMS_CUSTOMER_INTERCOMPANY] (
    [MASTER_ID]  VARCHAR (50)  NOT NULL,
    [CARD_CODE]  VARCHAR (50)  NOT NULL,
    [SOURCE]     VARCHAR (50)  NOT NULL,
    [CARD_NAME]  VARCHAR (250) NOT NULL,
    [LICTRADNUM] VARCHAR (25)  NOT NULL,
    PRIMARY KEY CLUSTERED ([MASTER_ID] ASC, [CARD_CODE] ASC, [SOURCE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CUSTOMER_INTERCOMPANY_SOURCE_CARD_CODE]
    ON [wms].[OP_WMS_CUSTOMER_INTERCOMPANY]([SOURCE] ASC, [CARD_CODE] ASC)
    INCLUDE([MASTER_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CUSTOMER_INTERCOMPANY_SOURCE_MASTER_ID]
    ON [wms].[OP_WMS_CUSTOMER_INTERCOMPANY]([SOURCE] ASC, [MASTER_ID] ASC)
    INCLUDE([CARD_CODE]) WITH (FILLFACTOR = 80);

