CREATE TABLE [wms].[OP_WMS_REALLOCS_X_LICENSE] (
    [SERIAL_NUMBER]   NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [LICENSE_ID]      NUMERIC (18) NULL,
    [SOURCE_LOCATION] VARCHAR (50) NULL,
    [TARGET_LOCATION] VARCHAR (50) NULL,
    [TRANS_TYPE]      VARCHAR (25) NULL,
    [LAST_UPDATED]    DATETIME     NULL,
    [LAST_UPDATED_BY] VARCHAR (25) NULL,
    CONSTRAINT [PK_OP_WMS_REALLOCS_X_LICENSE] PRIMARY KEY CLUSTERED ([SERIAL_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

