CREATE TABLE [wms].[OP_WMS_PICKING_LABELS_BY_SERIAL_NUMBER] (
    [LABEL_ID]        INT          NULL,
    [SERIAL_NUMBER]   VARCHAR (50) NULL,
    [BATCH]           VARCHAR (50) NULL,
    [DATE_EXPIRATION] DATE         NULL
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_LABELS_BY_SERIAL_NUMBER_LABEL_ID]
    ON [wms].[OP_WMS_PICKING_LABELS_BY_SERIAL_NUMBER]([LABEL_ID] ASC)
    INCLUDE([SERIAL_NUMBER]) WITH (FILLFACTOR = 80);

