CREATE TABLE [wms].[OP_WMS_DEMAND_TO_PICK] (
    [ERP_DOCUMENT]     VARCHAR (15)  NOT NULL,
    [ERP_DOC_DATE]     DATETIME      NULL,
    [LOADED_DATE]      DATETIME      NOT NULL,
    [CLIENT_ID]        VARCHAR (15)  NULL,
    [CLIENT_NAME]      VARCHAR (150) NULL,
    [CLIENT_ROUTE]     VARCHAR (15)  NULL,
    [MATERIAL_ID]      VARCHAR (25)  NOT NULL,
    [MATERIAL_NAME]    VARCHAR (150) NULL,
    [QTY]              NUMERIC (18)  NOT NULL,
    [IS_ASSIGNED]      NUMERIC (18)  CONSTRAINT [DF_OP_WMS_DEMAND_TO_PICK_STATUS] DEFAULT ((0)) NULL,
    [ASSIGNED_BY]      VARCHAR (25)  NULL,
    [CLIENT_REGION]    VARCHAR (15)  NULL,
    [ASSIGNED_DATE]    DATETIME      NULL,
    [ALLOWED_TO_PICK]  NUMERIC (18)  NULL,
    [ASSIGNED_TO_LINE] VARCHAR (15)  NULL,
    [POSICION]         INT           NOT NULL,
    [VOIDED_DATE]      DATETIME      NULL,
    CONSTRAINT [PK_OP_WMS_DEMAND_TO_PICK] PRIMARY KEY CLUSTERED ([ERP_DOCUMENT] ASC, [MATERIAL_ID] ASC, [POSICION] ASC) WITH (FILLFACTOR = 80)
);

