CREATE TABLE [wms].[OP_WMS_TYPE_CHARGE] (
    [TYPE_CHARGE_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [CHARGE]            VARCHAR (100) NULL,
    [DESCRIPTION]       VARCHAR (250) NULL,
    [WAREHOUSE_WEATHER] VARCHAR (60)  NULL,
    [REGIMEN]           VARCHAR (25)  NULL,
    [COMMENT]           VARCHAR (200) NULL,
    [DAY_TRIP]          VARCHAR (40)  NULL,
    [SERVICE_CODE]      VARCHAR (25)  NULL,
    [TO_MOVIL]          NUMERIC (18)  NULL,
    CONSTRAINT [PK_OP_WMS_TYPE_CHARGE] PRIMARY KEY NONCLUSTERED ([TYPE_CHARGE_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE CLUSTERED INDEX [INDEX_TYPE_CHANGE]
    ON [wms].[OP_WMS_TYPE_CHARGE]([CHARGE] ASC) WITH (FILLFACTOR = 80);

