CREATE TABLE [wms].[OP_WMS_CONFIGURATIONS] (
    [PARAM_TYPE]          VARCHAR (25)    NOT NULL,
    [PARAM_GROUP]         VARCHAR (25)    NOT NULL,
    [PARAM_GROUP_CAPTION] VARCHAR (100)   NOT NULL,
    [PARAM_NAME]          VARCHAR (50)    NOT NULL,
    [PARAM_CAPTION]       VARCHAR (100)   NULL,
    [NUMERIC_VALUE]       DECIMAL (18)    NULL,
    [MONEY_VALUE]         MONEY           NULL,
    [TEXT_VALUE]          VARCHAR (200)   NULL,
    [DATE_VALUE]          DATETIME        NULL,
    [RANGE_NUM_START]     DECIMAL (18)    NULL,
    [RANGE_NUM_END]       DECIMAL (18)    NULL,
    [RANGE_DATE_START]    DATETIME        NULL,
    [RANGE_DATE_END]      DATETIME        NULL,
    [SPARE1]              VARCHAR (50)    NULL,
    [SPARE2]              VARCHAR (50)    NULL,
    [DECIMAL_VALUE]       DECIMAL (18, 6) NULL,
    [SPARE3]              VARCHAR (50)    NULL,
    [SPARE4]              VARCHAR (50)    NULL,
    [SPARE5]              VARCHAR (50)    NULL,
    [COLOR]               VARCHAR (50)    NULL,
    CONSTRAINT [PK_OP_WMS_CONFIGURATIONS] PRIMARY KEY CLUSTERED ([PARAM_TYPE] ASC, [PARAM_GROUP] ASC, [PARAM_NAME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAM_TYPE]
    ON [wms].[OP_WMS_CONFIGURATIONS]([PARAM_TYPE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAM_GROUP]
    ON [wms].[OP_WMS_CONFIGURATIONS]([PARAM_GROUP] ASC, [PARAM_NAME] ASC)
    INCLUDE([COLOR], [DECIMAL_VALUE], [NUMERIC_VALUE], [PARAM_CAPTION], [PARAM_TYPE], [SPARE1], [SPARE2], [SPARE3], [SPARE4], [SPARE5], [TEXT_VALUE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CONFIGURATIONS_PARAM_TYPE_PARAM_GROUP]
    ON [wms].[OP_WMS_CONFIGURATIONS]([PARAM_TYPE] ASC, [PARAM_GROUP] ASC)
    INCLUDE([NUMERIC_VALUE], [PARAM_CAPTION], [TEXT_VALUE], [PARAM_NAME]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CONFIGURATIONS_PARAM_GROUP]
    ON [wms].[OP_WMS_CONFIGURATIONS]([PARAM_GROUP] ASC)
    INCLUDE([COLOR], [DATE_VALUE], [DECIMAL_VALUE], [MONEY_VALUE], [NUMERIC_VALUE], [PARAM_CAPTION], [PARAM_GROUP_CAPTION], [PARAM_NAME], [PARAM_TYPE], [RANGE_DATE_END], [RANGE_DATE_START], [RANGE_NUM_END], [RANGE_NUM_START], [SPARE1], [SPARE2], [SPARE3], [SPARE4], [SPARE5], [TEXT_VALUE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_VALUE_TEXT_CONFIGURATIONS]
    ON [wms].[OP_WMS_CONFIGURATIONS]([PARAM_NAME] ASC)
    INCLUDE([TEXT_VALUE]) WITH (FILLFACTOR = 80);

