CREATE TABLE [wms].[OP_WMS_CLIENTS] (
    [CLIENT_CODE]     VARCHAR (25)  NOT NULL,
    [CLIENT_NAME]     VARCHAR (200) NOT NULL,
    [CLIENT_ROUTE]    VARCHAR (25)  NULL,
    [CLIENT_CLASS]    VARCHAR (25)  NULL,
    [CLIENT_STATUS]   INT           NULL,
    [CLIENT_REGION]   VARCHAR (25)  NULL,
    [CLIENT_ADDRESS]  VARCHAR (200) NULL,
    [CLIENT_PHONE]    VARCHAR (15)  NULL,
    [CLIENT_CA]       VARCHAR (25)  NULL,
    [CLIENT_ERP_CODE] VARCHAR (25)  NULL,
    CONSTRAINT [PK_OP_WMS_CLIENTS] PRIMARY KEY NONCLUSTERED ([CLIENT_CODE] ASC) WITH (FILLFACTOR = 80)
);

