CREATE TABLE [wms].[OP_WMS_CLASS] (
    [CLASS_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [CLASS_NAME]        VARCHAR (50)  NOT NULL,
    [CLASS_DESCRIPTION] VARCHAR (250) NOT NULL,
    [CLASS_TYPE]        VARCHAR (50)  NOT NULL,
    [CREATED_BY]        VARCHAR (50)  NOT NULL,
    [CREATED_DATETIME]  DATETIME      NOT NULL,
    [LAST_UPDATED_BY]   VARCHAR (50)  NOT NULL,
    [LAST_UPDATED]      DATETIME      NOT NULL,
    [PRIORITY]          INT           DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CLASS_ID] ASC) WITH (FILLFACTOR = 80),
    UNIQUE NONCLUSTERED ([CLASS_NAME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CLASS_CLASS_NAME]
    ON [wms].[OP_WMS_CLASS]([CLASS_NAME] ASC)
    INCLUDE([CLASS_DESCRIPTION], [CLASS_ID], [CLASS_TYPE], [CREATED_BY], [CREATED_DATETIME], [LAST_UPDATED], [LAST_UPDATED_BY], [PRIORITY]) WITH (FILLFACTOR = 80);

