CREATE TABLE [wms].[OP_WMS_PICKING_LABELS] (
    [LABEL_ID]            INT             IDENTITY (1, 1) NOT NULL,
    [LOGIN_ID]            VARCHAR (25)    NULL,
    [LICENSE_ID]          DECIMAL (18)    NULL,
    [MATERIAL_ID]         VARCHAR (50)    NULL,
    [MATERIAL_NAME]       VARCHAR (150)   NULL,
    [QTY]                 DECIMAL (18, 4) NULL,
    [CODIGO_POLIZA]       VARCHAR (25)    NULL,
    [SOURCE_LOCATION]     VARCHAR (25)    NULL,
    [TARGET_LOCATION]     VARCHAR (25)    NULL,
    [TRANSIT_LOCATION]    VARCHAR (25)    NULL,
    [BATCH]               VARCHAR (50)    NULL,
    [VIN]                 VARCHAR (40)    NULL,
    [TONE]                VARCHAR (20)    NULL,
    [CALIBER]             VARCHAR (20)    NULL,
    [SERIAL_NUMBER]       VARCHAR (50)    NULL,
    [STATUS]              VARCHAR (25)    NULL,
    [WEIGHT]              NUMERIC (18, 2) NULL,
    [WAVE_PICKING_ID]     INT             NULL,
    [TASK_SUBT_YPE]       VARCHAR (25)    NULL,
    [WAREHOUSE_TARGET]    VARCHAR (25)    NULL,
    [CLIENT_NAME]         VARCHAR (150)   NULL,
    [CLIENT_CODE]         VARCHAR (50)    NULL,
    [STATE_CODE]          INT             NULL,
    [REGIMEN]             VARCHAR (50)    NULL,
    [TRANSFER_REQUEST_ID] INT             NULL,
    [BARCODE]             VARCHAR (50)    NULL,
    [LABEL_STATUS]        VARCHAR (50)    DEFAULT ('PICKED') NOT NULL,
    CONSTRAINT [PK_OP_WMS_PICKING_LABELS_LABEL_ID] PRIMARY KEY CLUSTERED ([LABEL_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_LABELS_MATERIAL_ID]
    ON [wms].[OP_WMS_PICKING_LABELS]([MATERIAL_ID] ASC)
    INCLUDE([LABEL_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_LABELS_BARCODE]
    ON [wms].[OP_WMS_PICKING_LABELS]([BARCODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_LABELS_WAVE_PICKING_ID]
    ON [wms].[OP_WMS_PICKING_LABELS]([WAVE_PICKING_ID] ASC)
    INCLUDE([LABEL_ID], [LABEL_STATUS], [MATERIAL_ID], [TARGET_LOCATION]) WITH (FILLFACTOR = 80);

