CREATE TABLE [wms].[OP_WMS_TRANSFER_REQUEST_DETAIL] (
    [TRANSFER_REQUEST_ID] INT             NOT NULL,
    [MATERIAL_ID]         VARCHAR (50)    NOT NULL,
    [MATERIAL_NAME]       VARCHAR (200)   NOT NULL,
    [IS_MASTERPACK]       INT             NOT NULL,
    [QTY]                 NUMERIC (18, 6) NOT NULL,
    [STATUS]              VARCHAR (25)    NOT NULL,
    [QTY_PROCESSED]       NUMERIC (18, 6) DEFAULT ((0)) NOT NULL,
    [STATUS_CODE]         VARCHAR (25)    NULL,
    CONSTRAINT [FK_OP_WMS_TRANSFER_REQUEST_DETAIL_OP_WMS_TRANSFER_REQUEST_HEADER_TRANSFER_REQUEST_ID] FOREIGN KEY ([TRANSFER_REQUEST_ID]) REFERENCES [wms].[OP_WMS_TRANSFER_REQUEST_HEADER] ([TRANSFER_REQUEST_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_TRANSFER_REQUEST_DETAIL_TRANSFER_REQUEST_ID]
    ON [wms].[OP_WMS_TRANSFER_REQUEST_DETAIL]([TRANSFER_REQUEST_ID] ASC)
    INCLUDE([IS_MASTERPACK], [MATERIAL_ID], [MATERIAL_NAME], [QTY], [STATUS]) WITH (FILLFACTOR = 80);


GO


CREATE TRIGGER [wms].[transdupremoval] ON [wms].[OP_WMS_TRANSFER_REQUEST_DETAIL]
FOR INSERT
AS

IF (EXISTS(SELECT 1 FROM inserted))
 BEGIN
    DELETE FROM [wms].[OP_WMS_TRANSFER_REQUEST_DETAIL] where MATERIAL_ID IN (SELECT MATERIAL_ID FROM inserted) AND QTY IN (SELECT QTY FROM  inserted)
	AND [TRANSFER_REQUEST_ID] IN (SELECT [TRANSFER_REQUEST_ID] FROM  inserted)
    INSERT INTO [wms].[OP_WMS_TRANSFER_REQUEST_DETAIL]
	([TRANSFER_REQUEST_ID]
      ,[MATERIAL_ID]
      ,[MATERIAL_NAME]
      ,[IS_MASTERPACK]
      ,[QTY]
      ,[STATUS]
      ,[QTY_PROCESSED]
      ,[STATUS_CODE])
    SELECT [TRANSFER_REQUEST_ID]
      ,[MATERIAL_ID]
      ,[MATERIAL_NAME]
      ,[IS_MASTERPACK]
      ,[QTY]
      ,[STATUS]
      ,[QTY_PROCESSED]
      ,[STATUS_CODE] FROM inserted
END

