CREATE TABLE [wms].[OP_WMS_SUB_CLASS] (
    [SUB_CLASS_ID]     INT          IDENTITY (1, 1) NOT NULL,
    [SUB_CLASS_NAME]   VARCHAR (50) NOT NULL,
    [CREATED_BY]       VARCHAR (50) NOT NULL,
    [CREATED_DATETIME] DATETIME     NOT NULL,
    [LAST_UPDATED_BY]  VARCHAR (50) NOT NULL,
    [LAST_UPDATED]     DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([SUB_CLASS_ID] ASC) WITH (FILLFACTOR = 80),
    UNIQUE NONCLUSTERED ([SUB_CLASS_NAME] ASC) WITH (FILLFACTOR = 80)
);

