CREATE TABLE [wms].[OP_WMS_CHARGE_EXTERNAL_INVENTORY] (
    [CLIENTE]          VARCHAR (25)    NOT NULL,
    [CODIGO]           VARCHAR (25)    NULL,
    [DESCRIPCION]      VARCHAR (100)   NULL,
    [UNIDAD_MEDIDA]    VARCHAR (25)    NULL,
    [QTY]              NUMERIC (18, 2) NULL,
    [PPRECIO_UNITARIO] NUMERIC (18, 2) NULL,
    [COSTO_TOTAL]      NUMERIC (18, 2) NULL
);

