CREATE TABLE [wms].[OP_WMS3PL_DOCS_REFERENCIA] (
    [DOC_ID]           NUMERIC (18)  NOT NULL,
    [NUMERO_DUA]       VARCHAR (15)  NULL,
    [NUMERO_DOCUMENTO] VARCHAR (50)  NOT NULL,
    [TIPO_DOCUMENTO]   VARCHAR (15)  NOT NULL,
    [FECHA_DOCUMENTO]  DATE          NULL,
    [OBSERVACIONES]    VARCHAR (250) NULL,
    [LAST_UPDATED_BY]  VARCHAR (25)  NULL,
    [LAST_UPDATED]     DATE          NULL,
    CONSTRAINT [PK_OP_WMS3PL_DOCS_REFERENCIA] PRIMARY KEY CLUSTERED ([DOC_ID] ASC, [NUMERO_DOCUMENTO] ASC, [TIPO_DOCUMENTO] ASC) WITH (FILLFACTOR = 80)
);

