CREATE TABLE [wms].[OP_WMS_CERTIFICATION_DETAIL] (
    [CERTIFICATION_DETAIL_ID] INT             IDENTITY (1, 1) NOT NULL,
    [CERTIFICATION_HEADER_ID] INT             NOT NULL,
    [LABEL_ID]                INT             NULL,
    [MATERIAL_ID]             VARCHAR (50)    NULL,
    [QTY]                     DECIMAL (18, 4) NULL,
    [CERTIFICATION_TYPE]      VARCHAR (50)    NULL,
    [LAST_UPDATED]            DATETIME        NULL,
    [LAST_UPDATED_BY]         VARCHAR (25)    NULL,
    [BOX_BARCODE]             VARCHAR (50)    NULL,
    CONSTRAINT [PK_OP_WMS_CERTIFICATION_DETAIL_CERTIFICATION_DETAIL_ID] PRIMARY KEY CLUSTERED ([CERTIFICATION_DETAIL_ID] ASC),
    FOREIGN KEY ([CERTIFICATION_HEADER_ID]) REFERENCES [wms].[OP_WMS_CERTIFICATION_HEADER] ([CERTIFICATION_HEADER_ID]),
    FOREIGN KEY ([LABEL_ID]) REFERENCES [wms].[OP_WMS_PICKING_LABELS] ([LABEL_ID])
);




GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CERTIFICATION_DETAIL_CERTIFICATION_HEADER_ID]
    ON [wms].[OP_WMS_CERTIFICATION_DETAIL]([CERTIFICATION_HEADER_ID] ASC)
    INCLUDE([CERTIFICATION_DETAIL_ID], [CERTIFICATION_TYPE], [MATERIAL_ID], [QTY]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CERTIFICATION_DETAIL_BOX_BARCODE]
    ON [wms].[OP_WMS_CERTIFICATION_DETAIL]([BOX_BARCODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CERTIFICATION_DETAIL_CERTIFICATION_HEADER_ID_LABEL_ID]
    ON [wms].[OP_WMS_CERTIFICATION_DETAIL]([CERTIFICATION_HEADER_ID] ASC, [LABEL_ID] ASC)
    INCLUDE([CERTIFICATION_DETAIL_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CERTIFICATION_DETAIL_CERTIFICATION_HEADER_ID_BOX_BARCODE]
    ON [wms].[OP_WMS_CERTIFICATION_DETAIL]([CERTIFICATION_HEADER_ID] ASC, [BOX_BARCODE] ASC) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[wms].[OP_WMS_CERTIFICATION_DETAIL] TO [Uwms]
    AS [wms];

