CREATE TABLE [wms].[OP_WMS_SUPERVISIONS] (
    [SUPER_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [AUDIT_ADDRESS]    VARCHAR (150) NULL,
    [AUDITED_BY]       VARCHAR (25)  NULL,
    [COMMENTS]         VARCHAR (100) NULL,
    [IS_INITIAL]       INT           NULL,
    [CLIENT_OWHEN]     VARCHAR (50)  NULL,
    [WAREHOUSE_OWHEN]  VARCHAR (10)  NULL,
    [CREATED_DATETIME] DATETIME      NULL,
    [STATUS]           VARCHAR (10)  NULL,
    CONSTRAINT [PK_OP_WMS_SUPERVISIONS] PRIMARY KEY CLUSTERED ([SUPER_ID] ASC) WITH (FILLFACTOR = 80)
);

