CREATE TABLE [wms].[OP_WMS_INVENTORY_RESERVED_BY_PROJECT] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [PROJECT_ID]       UNIQUEIDENTIFIER NOT NULL,
    [PK_LINE]          NUMERIC (18)     NOT NULL,
    [LICENSE_ID]       NUMERIC (18)     NOT NULL,
    [MATERIAL_ID]      VARCHAR (50)     NOT NULL,
    [MATERIAL_NAME]    VARCHAR (150)    NULL,
    [QTY_LICENSE]      NUMERIC (18, 4)  NOT NULL,
    [QTY_RESERVED]     NUMERIC (18, 4)  NOT NULL,
    [QTY_DISPATCHED]   NUMERIC (18, 4)  NOT NULL,
    [RESERVED_PICKING] NUMERIC (18, 4)  DEFAULT ((0)) NOT NULL,
    [TONE]             VARCHAR (20)     NULL,
    [CALIBER]          VARCHAR (20)     NULL,
    [BATCH]            VARCHAR (50)     NULL,
    [DATE_EXPIRATION]  DATE             NULL,
    [STATUS_CODE]      VARCHAR (100)    NULL,
    [CLIENT_CODE]      VARCHAR (25)     NULL,
    [CLIENT_NAME]      VARCHAR (50)     NULL,
    [MOBILE]           INT              NULL,
    CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PK_LINE_OP_INV_X_LICENSE_PK_LINE] FOREIGN KEY ([PK_LINE]) REFERENCES [wms].[OP_WMS_INV_X_LICENSE] ([PK_LINE]),
    CONSTRAINT [FK_PROJECT_ID_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [wms].[OP_WMS_PROJECT] ([ID])
);

