CREATE TABLE [wms].[OP_WMS_INSURANCE_DOCS] (
    [DOC_ID]           INT           IDENTITY (1, 1) NOT NULL,
    [COMPANY_ID]       VARCHAR (50)  NULL,
    [AMOUNT]           MONEY         NULL,
    [AVAILABLE]        MONEY         NULL,
    [LAST_TXN_DATE]    DATETIME      NULL,
    [CREATED_DATE]     DATETIME      NULL,
    [CREATED_BY]       VARCHAR (25)  NULL,
    [LAST_UPDATED]     DATETIME      NULL,
    [LAST_UPDATED_BY]  VARCHAR (25)  NULL,
    [CLIENT_CODE]      VARCHAR (25)  NULL,
    [COVERAGE]         VARCHAR (250) NULL,
    [VALIN_FROM]       DATE          NULL,
    [VALIN_TO]         DATE          NULL,
    [POLIZA_INSURANCE] VARCHAR (50)  NULL,
    [INSURANCE_OWHEN]  VARCHAR (50)  NULL,
    CONSTRAINT [PK_OP_WMS_INSUNANCE_DOCS] PRIMARY KEY CLUSTERED ([DOC_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IDX_CLIENT_CODE]
    ON [wms].[OP_WMS_INSURANCE_DOCS]([CLIENT_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_COMPANY_ID]
    ON [wms].[OP_WMS_INSURANCE_DOCS]([COMPANY_ID] ASC) WITH (FILLFACTOR = 80);

