CREATE TABLE [wms].[OP_WMS_LOGINS] (
    [LOGIN_ID]               VARCHAR (25)  NOT NULL,
    [ROLE_ID]                VARCHAR (25)  NOT NULL,
    [LOGIN_NAME]             VARCHAR (50)  NOT NULL,
    [LOGIN_TYPE]             VARCHAR (25)  NULL,
    [LOGIN_STATUS]           VARCHAR (10)  NULL,
    [LOGIN_PWD]              VARCHAR (75)  NULL,
    [LOGIN_PWD_ALTERNATE]    VARCHAR (75)  NULL,
    [LICENSE_SERIAL]         VARCHAR (MAX) NULL,
    [ENVIRONMENT]            VARCHAR (50)  NULL,
    [GUI_LAYOUT]             VARCHAR (50)  NULL,
    [IS_LOGGED]              INT           NULL,
    [LAST_LOGGED]            DATETIME      NULL,
    [DEFAULT_WAREHOUSE_ID]   VARCHAR (25)  NULL,
    [CONSOLIDATION_TERMINAL] NUMERIC (18)  NULL,
    [GENERATE_TASKS]         VARCHAR (50)  NULL,
    [LOADING_GATE]           VARCHAR (50)  NULL,
    [LINE_ID]                VARCHAR (25)  NULL,
    [3PL_WAREHOUSE]          VARCHAR (25)  NULL,
    [EMAIL]                  VARCHAR (50)  NULL,
    [AUTHORIZER]             INT           NULL,
    [IS_EXTERNAL]            INT           NULL,
    [RELATED_CLIENT]         VARCHAR (25)  NULL,
    [NOTIFY_LETTER_QUOTA]    NUMERIC (18)  NULL,
    [DISTRIBUTION_CENTER_ID] VARCHAR (50)  NULL,
    [CAN_RELOCATE]           INT           NULL,
    [LINE_POSITION]          VARCHAR (10)  NULL,
    [SPOT_COLUMN]            VARCHAR (25)  NULL,
    [TERMINAL_IP]            VARCHAR (50)  NULL,
    [EXTERNAL_USER_LOGIN]    VARCHAR (50)  NULL,
    [EXTERNAL_NAME_USER]     VARCHAR (50)  NULL,
    [DOMAIN_ID]              INT           NULL,
    [LICENSE]                VARCHAR (400) NULL,
    CONSTRAINT [PK_OP_WMS_LOGINS] PRIMARY KEY CLUSTERED ([LOGIN_ID] ASC),
    CONSTRAINT [FK_OP_WMS_LOGINS_OP_WMS_DOMAINS] FOREIGN KEY ([DOMAIN_ID]) REFERENCES [dbo].[OP_WMS_DOMAINS] ([ID])
);




GO
CREATE NONCLUSTERED INDEX [IDX_LOGINS_USER_X_PILOT]
    ON [wms].[OP_WMS_LOGINS]([LOGIN_ID] ASC, [ROLE_ID] ASC)
    INCLUDE([3PL_WAREHOUSE], [AUTHORIZER], [CAN_RELOCATE], [CONSOLIDATION_TERMINAL], [DEFAULT_WAREHOUSE_ID], [DISTRIBUTION_CENTER_ID], [EMAIL], [ENVIRONMENT], [GENERATE_TASKS], [GUI_LAYOUT], [IS_EXTERNAL], [IS_LOGGED], [LAST_LOGGED], [LICENSE_SERIAL], [LINE_ID], [LINE_POSITION], [LOADING_GATE], [LOGIN_NAME], [LOGIN_PWD], [LOGIN_PWD_ALTERNATE], [LOGIN_STATUS], [LOGIN_TYPE], [NOTIFY_LETTER_QUOTA], [RELATED_CLIENT], [SPOT_COLUMN], [TERMINAL_IP]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_LOGINS_DISTRIBUTION_CENTER_ID_LOGIN_ID_LOGIN_STATUS_ROLE_ID]
    ON [wms].[OP_WMS_LOGINS]([DISTRIBUTION_CENTER_ID] ASC, [LOGIN_ID] ASC, [LOGIN_STATUS] ASC, [ROLE_ID] ASC)
    INCLUDE([LOGIN_NAME]) WITH (FILLFACTOR = 80);


GO
GRANT SELECT
    ON OBJECT::[wms].[OP_WMS_LOGINS] TO [Uwms]
    AS [wms];

