CREATE TABLE [wms].[OP_WMS_AUDIT_DISPATCH_SERIES] (
    [AUDIT_ID]      NUMERIC (18) NOT NULL,
    [SERIAL_NUMBER] VARCHAR (50) NOT NULL,
    [MATERIAL_ID]   VARCHAR (50) NOT NULL,
    [LAST_UPDATED]  DATETIME     NULL,
    CONSTRAINT [PK_OP_WMS_AUDIT_DISPATCH_DETAIL] PRIMARY KEY CLUSTERED ([AUDIT_ID] ASC, [SERIAL_NUMBER] ASC, [MATERIAL_ID] ASC) WITH (FILLFACTOR = 80)
);

