CREATE TABLE [wms].[OP_WMS_INSURANCE_COMPANIES] (
    [COMPANY_ID]   VARCHAR (50)  NOT NULL,
    [COMPANY_NAME] VARCHAR (150) NULL,
    [CREATED_DATE] DATETIME      NULL,
    [CREATED_BY]   VARCHAR (25)  NULL,
    CONSTRAINT [PK_OP_WMS_INSUNANCE_COMPANIES] PRIMARY KEY CLUSTERED ([COMPANY_ID] ASC) WITH (FILLFACTOR = 80)
);

