CREATE TABLE [wms].[OP_WMS_MAIN_REPORTS_FIELDS] (
    [REPORT_ID]           VARCHAR (50) NOT NULL,
    [FIELD_NAME]          VARCHAR (50) NOT NULL,
    [FIELD_NAME_ID]       VARCHAR (50) NULL,
    [FIELD_CAPTION]       VARCHAR (50) NULL,
    [FIELD_FORMAT_TYPE]   VARCHAR (50) NULL,
    [FIELD_FORMAT_STRING] VARCHAR (50) NULL,
    [FIELD_INITIAL_AREA]  VARCHAR (50) NULL,
    [SUMMARY_TYPE]        VARCHAR (50) NULL,
    [ALLOWED_AREAS]       VARCHAR (50) NULL,
    CONSTRAINT [PK_MAIN_REPORTS_FIELDS] PRIMARY KEY CLUSTERED ([REPORT_ID] ASC, [FIELD_NAME] ASC) WITH (FILLFACTOR = 80)
);

