CREATE TABLE [wms].[OP_WMS_PICKING_ERP_DOCUMENT] (
    [PICKING_ERP_DOCUMENT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [WAVE_PICKING_ID]         INT           NOT NULL,
    [CODE_WAREHOUSE]          VARCHAR (25)  NOT NULL,
    [ATTEMPTED_WITH_ERROR]    INT           CONSTRAINT [DF__OP_WMS_PI__ATTEM__0DB9F9A8] DEFAULT ((0)) NOT NULL,
    [IS_POSTED_ERP]           INT           CONSTRAINT [DF__OP_WMS_PI__IS_PO__0EAE1DE1] DEFAULT ((0)) NOT NULL,
    [POSTED_ERP]              DATETIME      NULL,
    [POSTED_RESPONSE]         VARCHAR (500) NULL,
    [ERP_REFERENCE]           VARCHAR (50)  NULL,
    [ERP_REFERENCE_DOC_NUM]   VARCHAR (200) NULL,
    [IS_AUTHORIZED]           INT           CONSTRAINT [DF__OP_WMS_PI__IS_AU__1A1FD08D] DEFAULT ((0)) NOT NULL,
    [CREATED_DATE]            DATETIME      CONSTRAINT [DF__OP_WMS_PI__CREAT__1B13F4C6] DEFAULT (getdate()) NOT NULL,
    [LAST_UPDATED]            DATETIME      CONSTRAINT [DF__OP_WMS_PI__LAST___1C0818FF] DEFAULT (getdate()) NOT NULL,
    [LAST_UPDATED_BY]         VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK__OP_WMS_P__980C0DAE50D0F115] PRIMARY KEY CLUSTERED ([PICKING_ERP_DOCUMENT_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PICKING_ERP_DOCUMENT_IS_POSTED_ERP]
    ON [wms].[OP_WMS_PICKING_ERP_DOCUMENT]([WAVE_PICKING_ID] ASC, [PICKING_ERP_DOCUMENT_ID] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [IS_AUTHORIZED], [IS_POSTED_ERP]) WITH (FILLFACTOR = 80);

