CREATE TABLE [wms].[OP_WMS_PHYSICAL_COUNTS_EXECUTION] (
    [PHYSICAL_COUNTS_EXECUTION_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PHYSICAL_COUNT_DETAIL_ID]     INT             NOT NULL,
    [LOCATION]                     VARCHAR (25)    NOT NULL,
    [LICENSE_ID]                   INT             NOT NULL,
    [MATERIAL_ID]                  VARCHAR (25)    NULL,
    [QTY_SCANNED]                  NUMERIC (18, 4) NOT NULL,
    [QTY_EXPECTED]                 NUMERIC (18, 4) NOT NULL,
    [HIT_OR_MISS]                  VARCHAR (2)     NOT NULL,
    [EXECUTED]                     DATETIME        NULL,
    [EXECUTED_BY]                  VARCHAR (25)    NULL,
    [EXPIRATION_DATE]              DATE            NULL,
    [BATCH]                        VARCHAR (50)    NULL,
    [SERIAL]                       VARCHAR (50)    NULL,
    [EXPIRATION_DATE_EXPECTED]     DATE            NULL,
    [BATCH_EXPECTED]               VARCHAR (50)    NULL,
    [SERIAL_EXPECTED]              VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([PHYSICAL_COUNTS_EXECUTION_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PHYSICAL_COUNTS_EXECUTION_LOGIN] FOREIGN KEY ([EXECUTED_BY]) REFERENCES [wms].[OP_WMS_LOGINS] ([LOGIN_ID]),
    CONSTRAINT [FK_PHYSICAL_COUNTS_EXECUTION_PHYSICAL_COUNTS_DETAIL] FOREIGN KEY ([PHYSICAL_COUNT_DETAIL_ID]) REFERENCES [wms].[OP_WMS_PHYSICAL_COUNTS_DETAIL] ([PHYSICAL_COUNT_DETAIL_ID])
);

