CREATE TABLE [wms].[OP_WMS_BONDS] (
    [CERTIFICATE_ID]        INT          NOT NULL,
    [BOND_ID]               VARCHAR (20) NOT NULL,
    [AMOUNT]                MONEY        NULL,
    [INSURANCES_COMPANY_ID] VARCHAR (50) NULL,
    [CURRENCY]              VARCHAR (50) NULL,
    CONSTRAINT [PK_OP_WMS_BONDS] PRIMARY KEY CLUSTERED ([CERTIFICATE_ID] ASC) WITH (FILLFACTOR = 80)
);

