CREATE TABLE [wms].[OP_WMS_TEMP_TOCOUNT] (
    [CLIENT_CODE]      VARCHAR (25)  NULL,
    [MATERIAL_ID]      VARCHAR (50)  NULL,
    [BARCODE_ID]       VARCHAR (50)  NULL,
    [MATERIAL_NAME]    VARCHAR (150) NULL,
    [REGIMEN]          VARCHAR (50)  NULL,
    [CODIGO_POLIZA]    VARCHAR (25)  NULL,
    [CURRENT_LOCATION] VARCHAR (25)  NULL,
    [WAREHOUSE_ID]     VARCHAR (25)  NULL
);

