CREATE TABLE [wms].[OP_WMS3PL_SECURITY_CHECKPOINT] (
    [CHECKPOINT_ID]   NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [DOC_ID]          NUMERIC (18)  NULL,
    [CODIGO_POLIZA]   VARCHAR (15)  NULL,
    [CLIENT_CODE]     VARCHAR (25)  NULL,
    [CLIENT_NAME]     VARCHAR (200) NULL,
    [ENTRY_DATETIME]  DATETIME      NULL,
    [EXIT_DATETIME]   DATETIME      NULL,
    [LAST_UPDATED_BY] VARCHAR (25)  NULL,
    [LAST_UPDATED]    DATETIME      NULL,
    [PASS_ID]         NUMERIC (18)  NULL,
    CONSTRAINT [PK_OP_WMS3PL_SECURITY_CHECKPOINT] PRIMARY KEY CLUSTERED ([CHECKPOINT_ID] ASC) WITH (FILLFACTOR = 80)
);

