CREATE TABLE [wms].[OP_WMS_PARAMETER] (
    [IDENTITY]     INT           IDENTITY (1, 1) NOT NULL,
    [GROUP_ID]     VARCHAR (250) NOT NULL,
    [PARAMETER_ID] VARCHAR (250) NOT NULL,
    [VALUE]        VARCHAR (MAX) NULL,
    [LABEL]        VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([IDENTITY] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CH_OP_WMS_PARAMETER_VALUE_LABEL] CHECK ([VALUE] IS NOT NULL OR [LABEL] IS NOT NULL)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UC_OP_WMS_PARAMETER_GROUP_ID_PARAMETER_ID]
    ON [wms].[OP_WMS_PARAMETER]([GROUP_ID] ASC, [PARAMETER_ID] ASC)
    INCLUDE([LABEL], [VALUE]) WITH (FILLFACTOR = 80);

