CREATE TABLE [wms].[OP_WMS3PL_POLIZA_TRANS_MATCH] (
    [CODIGO_POLIZA]        VARCHAR (25)    NOT NULL,
    [TRANS_ID]             NUMERIC (18)    NOT NULL,
    [LINENO_POLIZA]        NUMERIC (18)    NOT NULL,
    [DOC_ID]               NUMERIC (18)    NULL,
    [SKU_DESCRIPTION]      VARCHAR (250)   NULL,
    [MATERIAL_CODE]        VARCHAR (25)    NOT NULL,
    [MATERIAL_DESCRIPTION] VARCHAR (200)   NULL,
    [QTY_TRANS]            NUMERIC (18, 4) NULL,
    [QTY_POLIZA]           NUMERIC (18, 4) NULL,
    [BULTOS_POLIZA]        NUMERIC (18, 4) NULL,
    [LAST_UPDATED_BY]      VARCHAR (25)    NULL,
    [LAST_UPDATED]         DATE            NULL,
    [QTY]                  NUMERIC (18, 4) NULL,
    [COMMENTS]             VARCHAR (MAX)   NULL,
    [LICENSE_ID]           INT             NULL,
    CONSTRAINT [PK_OP_WMS3PL_POLIZA_TRANS_MATCH] PRIMARY KEY CLUSTERED ([CODIGO_POLIZA] ASC, [TRANS_ID] ASC, [LINENO_POLIZA] ASC, [MATERIAL_CODE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [OP_WMS3PL_POLIZA_TRANS_MATCH_IDX01]
    ON [wms].[OP_WMS3PL_POLIZA_TRANS_MATCH]([CODIGO_POLIZA] ASC, [LAST_UPDATED] ASC) WITH (FILLFACTOR = 80);


GO
CREATE STATISTICS [20150916]
    ON [wms].[OP_WMS3PL_POLIZA_TRANS_MATCH]([CODIGO_POLIZA]);

