CREATE TABLE [wms].[OP_WMS_ZONE_TO_REPLENISH_IN_ZONE_3006] (
    [ZONE_TO_REPLENISH_IN_ZONE_ID] INT IDENTITY (1, 1) NOT NULL,
    [ZONE_ID]                      INT NOT NULL,
    [REPLENISH_ZONE_ID]            INT NOT NULL
);

