CREATE TABLE [wms].[OP_WMS_INSURANCE_DOCS_LOG] (
    [INSURANCE_LOG]     INT           IDENTITY (1, 1) NOT NULL,
    [INSURANCE_DOCS_ID] INT           NULL,
    [UPDATED]           DATETIME      NULL,
    [UPDATED_BY]        VARCHAR (20)  NULL,
    [OLD_VALIN_FROM]    DATE          NULL,
    [OLD_VALIN_TO]      DATE          NULL,
    [NEW_VALID_FROM]    DATE          NULL,
    [NEW_VALID_TO]      DATE          NULL,
    [COMMENT]           VARCHAR (250) NULL,
    [AUTHORIZED_BY]     VARCHAR (25)  NULL,
    CONSTRAINT [PK_OP_WMS_INSURANCE_DOCS_LOG] PRIMARY KEY CLUSTERED ([INSURANCE_LOG] ASC) WITH (FILLFACTOR = 80)
);

