CREATE TABLE [wms].[OP_WMS_MANIFEST_HEADER] (
    [MANIFEST_HEADER_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [DRIVER]                INT           NOT NULL,
    [VEHICLE]               INT           NOT NULL,
    [DISTRIBUTION_CENTER]   VARCHAR (50)  NOT NULL,
    [CREATED_DATE]          DATETIME      NOT NULL,
    [STATUS]                VARCHAR (50)  DEFAULT ('CREATED') NOT NULL,
    [LAST_UPDATE]           DATETIME      NOT NULL,
    [LAST_UPDATE_BY]        VARCHAR (50)  NOT NULL,
    [MANIFEST_TYPE]         VARCHAR (50)  NULL,
    [TRANSFER_REQUEST_ID]   INT           NULL,
    [PLATE_NUMBER]          VARCHAR (10)  NULL,
    [SOURCE]                VARCHAR (50)  DEFAULT ('MANIFESTO_DE_CARGA') NOT NULL,
    [CAI]                   VARCHAR (100) NULL,
    [CAI_SERIE]             VARCHAR (50)  NULL,
    [CAI_NUMERO]            VARCHAR (50)  NULL,
    [CAI_RANGO_INICIAL]     FLOAT (53)    NULL,
    [CAI_RANGO_FINAL]       FLOAT (53)    NULL,
    [CAI_FECHA_VENCIMIENTO] DATE          NULL,
    PRIMARY KEY CLUSTERED ([MANIFEST_HEADER_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MANIFEST_HEADER_TRANSFER_REQUEST_ID_MANIFEST_HEADER_ID]
    ON [wms].[OP_WMS_MANIFEST_HEADER]([TRANSFER_REQUEST_ID] ASC, [MANIFEST_HEADER_ID] ASC)
    INCLUDE([CREATED_DATE], [DRIVER], [VEHICLE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MANIFEST_HEADER_MANIFEST_HEADER_ID_TRANSFER_REQUEST_ID]
    ON [wms].[OP_WMS_MANIFEST_HEADER]([MANIFEST_HEADER_ID] ASC, [TRANSFER_REQUEST_ID] ASC)
    INCLUDE([CREATED_DATE], [DRIVER], [VEHICLE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_MANIFES_HEADER_ID_STATUS]
    ON [wms].[OP_WMS_MANIFEST_HEADER]([MANIFEST_HEADER_ID] ASC)
    INCLUDE([STATUS]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_MANIFES_HEADER_VEHICLE]
    ON [wms].[OP_WMS_MANIFEST_HEADER]([VEHICLE] ASC)
    INCLUDE([CREATED_DATE], [DISTRIBUTION_CENTER], [DRIVER], [LAST_UPDATE], [LAST_UPDATE_BY], [MANIFEST_HEADER_ID], [MANIFEST_TYPE], [PLATE_NUMBER], [STATUS], [TRANSFER_REQUEST_ID]) WITH (FILLFACTOR = 80);

