CREATE TABLE [wms].[OP_WMS_TYPE_CHARGE_X_LICENSE] (
    [DOC_ID]          NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [LICENCESE_ID]    NUMERIC (18) NULL,
    [TYPE_CHARGE_ID]  INT          NULL,
    [QTY]             NUMERIC (18) NULL,
    [LAST_UPDATED]    DATETIME     NULL,
    [LAST_UPDATED_BY] VARCHAR (25) NULL,
    [TYPE_TRANS]      VARCHAR (25) NULL,
    CONSTRAINT [PK_OP_WMS_TYPE_CHARGE_X_LICENSE] PRIMARY KEY CLUSTERED ([DOC_ID] ASC) WITH (FILLFACTOR = 80)
);

