CREATE TABLE [wms].[OP_WMS_MATERIALS_WITH_CATEGORY] (
    [CODE]          INT           IDENTITY (1, 1) NOT NULL,
    [ITEM_CODE]     VARCHAR (50)  NULL,
    [ITEM_NAME]     VARCHAR (200) NULL,
    [CATEGORY_CODE] VARCHAR (50)  NULL,
    [CATEGORY_NAME] VARCHAR (50)  NULL,
    CONSTRAINT [PK_OP_WMS_MATERIALS_WITH_CATEGORY_CODE] PRIMARY KEY CLUSTERED ([CODE] ASC) WITH (FILLFACTOR = 80)
);

