CREATE TABLE [wms].[OP_WMS_MAIN_REPORTS] (
    [REPORT_ID]    VARCHAR (50)   NOT NULL,
    [GROUP_NAME]   VARCHAR (50)   NULL,
    [REPORT_NAME]  VARCHAR (50)   NULL,
    [REPORT_QUERY] VARCHAR (5000) NULL,
    CONSTRAINT [PK_OP_WMS_MAIN_REPORTS] PRIMARY KEY CLUSTERED ([REPORT_ID] ASC) WITH (FILLFACTOR = 80)
);

