CREATE TABLE [wms].[OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE] (
    [MATERIAL_PROPERTY_ID] INT           NOT NULL,
    [WAREHOUSE_ID]         VARCHAR (25)  NOT NULL,
    [MATERIAL_ID]          VARCHAR (50)  NOT NULL,
    [VALUE]                VARCHAR (250) NOT NULL,
    [CREATED_BY]           VARCHAR (50)  NULL,
    [CREATED_DATETIME]     DATETIME      DEFAULT (getdate()) NULL,
    [LAST_UPDATE_BY]       VARCHAR (50)  NULL,
    [LAST_UPDATE]          DATETIME      DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE] PRIMARY KEY CLUSTERED ([MATERIAL_PROPERTY_ID] ASC, [WAREHOUSE_ID] ASC, [MATERIAL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE_MATERIAL_PROPERTY_ID] FOREIGN KEY ([MATERIAL_PROPERTY_ID]) REFERENCES [wms].[OP_WMS_MATERIAL_PROPERTY] ([MATERIAL_PROPERTY_ID]),
    CONSTRAINT [FK_OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE_WAREHOUSE_ID] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [wms].[OP_WMS_WAREHOUSES] ([WAREHOUSE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE_WAREHOUSE]
    ON [wms].[OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE]([WAREHOUSE_ID] ASC)
    INCLUDE([MATERIAL_PROPERTY_ID], [MATERIAL_ID], [VALUE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSEMATERIAL_ID]
    ON [wms].[OP_WMS_MATERIAL_PROPERTY_BY_WAREHOUSE]([MATERIAL_ID] ASC)
    INCLUDE([WAREHOUSE_ID], [MATERIAL_PROPERTY_ID], [VALUE]) WITH (FILLFACTOR = 80);

