CREATE TABLE [wms].[OP_WMS_MATERIALS_DETALLES] (
    [CLIENT_OWNER]               VARCHAR (25)    NOT NULL,
    [MATERIAL_ID]                VARCHAR (50)    NOT NULL,
    [BARCODE_ID]                 VARCHAR (25)    NOT NULL,
    [ALTERNATE_BARCODE]          VARCHAR (25)    NULL,
    [MATERIAL_NAME]              VARCHAR (200)   NOT NULL,
    [SHORT_NAME]                 VARCHAR (200)   NOT NULL,
    [VOLUME_FACTOR]              DECIMAL (18, 4) NULL,
    [MATERIAL_CLASS]             VARCHAR (25)    NULL,
    [HIGH]                       NUMERIC (18, 3) NULL,
    [LENGTH]                     NUMERIC (18, 3) NULL,
    [WIDTH]                      NUMERIC (18, 3) NULL,
    [MAX_X_BIN]                  NUMERIC (18)    NULL,
    [SCAN_BY_ONE]                NUMERIC (18)    NULL,
    [REQUIRES_LOGISTICS_INFO]    NUMERIC (18)    NULL,
    [WEIGTH]                     DECIMAL (18, 6) NULL,
    [IMAGE_1]                    IMAGE           NULL,
    [IMAGE_2]                    IMAGE           NULL,
    [IMAGE_3]                    IMAGE           NULL,
    [LAST_UPDATED]               DATETIME        NULL,
    [LAST_UPDATED_BY]            VARCHAR (25)    NULL,
    [IS_CAR]                     NUMERIC (18)    NULL,
    [MT3]                        NUMERIC (18, 2) NULL,
    [BATCH_REQUESTED]            NUMERIC (18)    NULL,
    [SERIAL_NUMBER_REQUESTS]     NUMERIC (18)    NULL,
    [IS_MASTER_PACK]             INT             NOT NULL,
    [ERP_AVERAGE_PRICE]          NUMERIC (18, 6) NOT NULL,
    [WEIGHT_MEASUREMENT]         VARCHAR (50)    NULL,
    [EXPLODE_IN_RECEPTION]       INT             NOT NULL,
    [HANDLE_TONE]                INT             NOT NULL,
    [HANDLE_CALIBER]             INT             NOT NULL,
    [USE_PICKING_LINE]           INT             NOT NULL,
    [ITEM_CODE_ERP]              VARCHAR (50)    NULL,
    [NON_STORAGE]                INT             NOT NULL,
    [ALLOW_DECIMAL_VALUE]        INT             NOT NULL,
    [QUALITY_CONTROL]            INT             NOT NULL,
    [PREFIX_CORRELATIVE_SERIALS] VARCHAR (20)    NULL,
    [HANDLE_CORRELATIVE_SERIALS] INT             NOT NULL,
    [BASE_MEASUREMENT_UNIT]      VARCHAR (50)    NULL
);

