CREATE TABLE [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL] (
    [ERP_RECEPTION_DOCUMENT_DETAIL_ID] INT             IDENTITY (1, 1) NOT NULL,
    [ERP_RECEPTION_DOCUMENT_HEADER_ID] INT             NULL,
    [MATERIAL_ID]                      VARCHAR (50)    NULL,
    [QTY]                              NUMERIC (18, 6) NULL,
    [LINE_NUM]                         INT             DEFAULT ((0)) NOT NULL,
    [ERP_OBJECT_TYPE]                  INT             DEFAULT ((0)) NOT NULL,
    [ATTEMPTED_WITH_ERROR]             INT             DEFAULT ((0)) NOT NULL,
    [IS_POSTED_ERP]                    INT             DEFAULT ((0)) NOT NULL,
    [POSTED_ERP]                       DATETIME        NULL,
    [POSTED_RESPONSE]                  VARCHAR (500)   NULL,
    [ERP_REFERENCE]                    VARCHAR (15)    NULL,
    [ERP_REFERENCE_DOC_NUM]            VARCHAR (15)    NULL,
    [WAREHOUSE_CODE]                   VARCHAR (25)    NULL,
    [CURRENCY]                         VARCHAR (50)    NULL,
    [RATE]                             NUMERIC (18, 6) NULL,
    [TAX_CODE]                         VARCHAR (50)    NULL,
    [VAT_PERCENT]                      NUMERIC (18, 6) NULL,
    [PRICE]                            NUMERIC (18, 6) NULL,
    [DISCOUNT]                         NUMERIC (18, 6) NULL,
    [COST_CENTER]                      VARCHAR (25)    NULL,
    [QTY_ASSIGNED]                     INT             DEFAULT ((0)) NULL,
    [UNIT]                             VARCHAR (100)   NULL,
    [UNIT_DESCRIPTION]                 VARCHAR (100)   NULL,
    [QTY_CONFIRMED]                    NUMERIC (19, 6) NULL,
    [IS_CONFIRMED]                     INT             DEFAULT ((0)) NOT NULL,
    [STATUS_CODE]                      VARCHAR (50)    NULL,
    [COST_BY_MATERIAL]                 FLOAT (53)      NULL,
    PRIMARY KEY CLUSTERED ([ERP_RECEPTION_DOCUMENT_DETAIL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_RECEPTION_DOCUMENT_DETAIL_HEADER] FOREIGN KEY ([ERP_RECEPTION_DOCUMENT_HEADER_ID]) REFERENCES [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] ([ERP_RECEPTION_DOCUMENT_HEADER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ERP_RECEPTION_DOCUMENT_DETAIL_ID_ERP_RECEPTIONS]
    ON [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL]([ERP_RECEPTION_DOCUMENT_HEADER_ID] ASC)
    INCLUDE([ERP_OBJECT_TYPE], [ERP_RECEPTION_DOCUMENT_DETAIL_ID], [LINE_NUM], [MATERIAL_ID], [QTY]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL_HEADER_ID_MATERIAL_ID_IS_POSTED_ERP]
    ON [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL]([ERP_RECEPTION_DOCUMENT_HEADER_ID] ASC, [MATERIAL_ID] ASC, [IS_POSTED_ERP] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL_ERP_RECEPTION_DOCUMENT_HEADER_ID_MATERIAL_ID]
    ON [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL]([ERP_RECEPTION_DOCUMENT_HEADER_ID] ASC, [MATERIAL_ID] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [POSTED_ERP], [POSTED_RESPONSE], [ERP_REFERENCE], [ERP_REFERENCE_DOC_NUM], [IS_POSTED_ERP], [LINE_NUM]) WITH (FILLFACTOR = 80);

