CREATE TABLE [wms].[OP_WMS_AUDIT_RECEPTION_SUMMARY] (
    [CODIGO_POLIZA]  VARCHAR (50)    NOT NULL,
    [MPC01]          NUMERIC (18, 2) NULL,
    [MPC02]          NUMERIC (18, 2) NULL,
    [MPC03]          NUMERIC (18, 2) NULL,
    [MPC04]          NUMERIC (18, 2) NULL,
    [MPC01_DESC]     VARCHAR (50)    NULL,
    [MPC02_DESC]     VARCHAR (50)    NULL,
    [MPC03_DESC]     VARCHAR (50)    NULL,
    [MPC04_DESC]     VARCHAR (50)    NULL,
    [LAST_UPDATE]    DATETIME        CONSTRAINT [DF_OP_WMS_AUDIT_RECEPTION_SUMMARY_LAST_UPDATE] DEFAULT (getdate()) NULL,
    [LAST_UPDATE_BY] NCHAR (10)      NULL
);

