CREATE TABLE [wms].[OP_WMS_SLOTTING_ZONE_BY_CLASS] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [ID_SLOTTING_ZONE] UNIQUEIDENTIFIER NOT NULL,
    [CLASS_ID]         INT              NOT NULL,
    [CLASS_NAME]       VARCHAR (50)     NULL,
    CONSTRAINT [PK_OP_WMS_SLOTTING_DETAIL_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_SLOTTINGDETAIL_SLOTTINGHEADER] FOREIGN KEY ([ID_SLOTTING_ZONE]) REFERENCES [wms].[OP_WMS_SLOTTING_ZONE] ([ID]),
    UNIQUE NONCLUSTERED ([ID_SLOTTING_ZONE] ASC, [CLASS_ID] ASC) WITH (FILLFACTOR = 80)
);

