CREATE TABLE [wms].[OP_WMS_CLASS_ASSOCIATION] (
    [CLASS_ID]            INT NOT NULL,
    [CLASS_ASSOCIATED_ID] INT NOT NULL,
    CONSTRAINT [PK_OP_WMS_CLASS_ASSOCIATION] PRIMARY KEY CLUSTERED ([CLASS_ID] ASC, [CLASS_ASSOCIATED_ID] ASC) WITH (FILLFACTOR = 80),
    FOREIGN KEY ([CLASS_ASSOCIATED_ID]) REFERENCES [wms].[OP_WMS_CLASS] ([CLASS_ID]),
    FOREIGN KEY ([CLASS_ID]) REFERENCES [wms].[OP_WMS_CLASS] ([CLASS_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CLASS_ASSOCIATION_CLASS_ID]
    ON [wms].[OP_WMS_CLASS_ASSOCIATION]([CLASS_ID] ASC)
    INCLUDE([CLASS_ASSOCIATED_ID]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_CLASS_ASSOCIATION_CLASS_ASSOCIATED_ID]
    ON [wms].[OP_WMS_CLASS_ASSOCIATION]([CLASS_ASSOCIATED_ID] ASC)
    INCLUDE([CLASS_ID]) WITH (FILLFACTOR = 80);

