CREATE TABLE [wms].[OP_WMS_COUNTING] (
    [COUNT_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CREATED_BY]     VARCHAR (25)   NULL,
    [CREATED_DATE]   DATETIME       NULL,
    [COUNT_TYPE]     VARCHAR (25)   NULL,
    [ACCURACY]       NUMERIC (5, 2) NULL,
    [COMPLETED_DATE] DATETIME       NULL,
    [CANCELED_DATE]  DATETIME       NULL,
    [PROGRESS]       NUMERIC (5)    NULL,
    [LAST_UPDATE]    DATETIME       NULL,
    [LAST_UPDATE_BY] VARCHAR (25)   NULL,
    CONSTRAINT [PK_COUNTING] PRIMARY KEY CLUSTERED ([COUNT_ID] ASC) WITH (FILLFACTOR = 80)
);

