CREATE TABLE [wms].[OP_WMS_DOCUMENT_HEADER] (
    [ERP_LEGACY_ID] VARCHAR (25) NOT NULL,
    [QTY_BOXES]     INT          NULL,
    CONSTRAINT [PK_OP_WMS_DOCUMENT_HEADER] PRIMARY KEY CLUSTERED ([ERP_LEGACY_ID] ASC) WITH (FILLFACTOR = 80)
);

