CREATE TABLE [wms].[OP_WMS_BROADCAST] (
    [ID_BROADCAST]   INT           IDENTITY (1, 1) NOT NULL,
    [STATUS]         VARCHAR (100) NOT NULL,
    [LOGIN_ID]       VARCHAR (25)  NOT NULL,
    [OPERATION_TYPE] VARCHAR (50)  NOT NULL,
    [CREATED_BY]     VARCHAR (50)  NOT NULL,
    [LAST_UPDATE_BY] VARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_BROADCAST] ASC) WITH (FILLFACTOR = 80)
);

