CREATE TABLE [wms].[OP_WMS_MAIN_PROFILES] (
    [PROFILE_NAME]      VARCHAR (100) NOT NULL,
    [PROFILE_USER]      VARCHAR (50)  NOT NULL,
    [PROFILE_LAYOUT_ID] VARCHAR (MAX) NULL,
    [PROFILE_MODULE_ID] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_OP_WMS_MAIN_PROFILES_1] PRIMARY KEY CLUSTERED ([PROFILE_NAME] ASC, [PROFILE_USER] ASC, [PROFILE_MODULE_ID] ASC) WITH (FILLFACTOR = 80)
);

