CREATE TABLE [wms].[OP_WMS_MATERIAL_PROPERTY] (
    [MATERIAL_PROPERTY_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]                 VARCHAR (50)  NOT NULL,
    [DATA_TYPE]            VARCHAR (50)  NOT NULL,
    [DESCRIPTION]          VARCHAR (250) NULL,
    CONSTRAINT [PK_OP_WMS_MATERIAL_PROPERTY] PRIMARY KEY CLUSTERED ([MATERIAL_PROPERTY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UC_OP_WMS_MATERIAL_PROPERTY_NAME] UNIQUE NONCLUSTERED ([NAME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_PROPERTY_NAME]
    ON [wms].[OP_WMS_MATERIAL_PROPERTY]([NAME] ASC)
    INCLUDE([MATERIAL_PROPERTY_ID], [DATA_TYPE], [DESCRIPTION]) WITH (FILLFACTOR = 80);

