CREATE TABLE [wms].[OP_WMS_MATERIAL_X_SERIAL_NUMBER] (
    [CORRELATIVE]           INT           IDENTITY (1, 1) NOT NULL,
    [LICENSE_ID]            NUMERIC (18)  NOT NULL,
    [MATERIAL_ID]           VARCHAR (250) NULL,
    [SERIAL]                VARCHAR (50)  NULL,
    [BATCH]                 VARCHAR (50)  NULL,
    [DATE_EXPIRATION]       DATE          NULL,
    [STATUS]                INT           DEFAULT ((1)) NOT NULL,
    [ASSIGNED_TO]           VARCHAR (25)  NULL,
    [WAVE_PICKING_ID]       NUMERIC (18)  NULL,
    [SERIAL_PREFIX]         VARCHAR (20)  NULL,
    [SERIAL_CORRELATIVE]    NUMERIC (18)  NULL,
    [SERIAL_CORRELATIVE_ID] VARCHAR (20)  NULL,
    [RECEPTION_HEADER_ID]   INT           NULL,
    [RECEPTION_LINE_NUM]    INT           NULL,
    [PICKING_HEADER_ID]     INT           NULL,
    [PICKING_LINE_NUM]      INT           NULL,
    PRIMARY KEY CLUSTERED ([CORRELATIVE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UK_OP_WMS_MATERIAL_X_SERIAL_NUMBER_MATERIAL_SERIAL_NUMBER] UNIQUE NONCLUSTERED ([MATERIAL_ID] ASC, [SERIAL] ASC, [LICENSE_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_X_SERIAL_NUMBER_MATERIAL_ID_SERIAL]
    ON [wms].[OP_WMS_MATERIAL_X_SERIAL_NUMBER]([MATERIAL_ID] ASC, [SERIAL] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_X_SERIAL_NUMBER_LICENSE_ID_MATERIAL_ID]
    ON [wms].[OP_WMS_MATERIAL_X_SERIAL_NUMBER]([LICENSE_ID] ASC, [MATERIAL_ID] ASC)
    INCLUDE([BATCH], [DATE_EXPIRATION], [SERIAL], [STATUS]) WITH (FILLFACTOR = 80);

