CREATE TABLE [wms].[OP_WMS_UNIT_MEASUREMENT_BY_MATERIAL] (
    [MEASUREMENT_UNIT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]           VARCHAR (25)  NULL,
    [MATERIAL_ID]         VARCHAR (50)  NULL,
    [MEASUREMENT_UNIT]    VARCHAR (50)  NULL,
    [QTY]                 INT           NULL,
    [BARCODE]             VARCHAR (100) NULL,
    [ALTERNATIVE_BARCODE] VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([MEASUREMENT_UNIT_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UC_OP_WMS_UNIT_MEASUREMENT_BY_MATERIAL_BARCODE] UNIQUE NONCLUSTERED ([CLIENT_ID] ASC, [BARCODE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UC_OP_WMS_UNIT_MEASUREMENT_BY_MATERIAL_MEASUREMENT_UNIT] UNIQUE NONCLUSTERED ([CLIENT_ID] ASC, [MATERIAL_ID] ASC, [MEASUREMENT_UNIT] ASC) WITH (FILLFACTOR = 80)
);

