CREATE TABLE [wms].[OP_WMS_KARDEX] (
    [KARDEX_ID]       INT             IDENTITY (1, 1) NOT NULL,
    [CERTIFATE_ID]    INT             NULL,
    [SKU]             VARCHAR (50)    NULL,
    [SKU_DESCRIPTION] VARCHAR (100)   NULL,
    [LAST_UPDATED]    DATETIME        CONSTRAINT [DF_OP_WMS_KARDEX_LAST_UPDATED] DEFAULT (getdate()) NULL,
    [CURRENT_BALACE]  NUMERIC (18, 2) NULL,
    [COST]            MONEY           NULL,
    CONSTRAINT [PK_OP_WMS_KARDEX] PRIMARY KEY CLUSTERED ([KARDEX_ID] ASC) WITH (FILLFACTOR = 80)
);

