CREATE TABLE [wms].[OP_WMS_COMPANY] (
    [COMPANY_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [COMPANY_NAME]          VARCHAR (50)  NOT NULL,
    [CLIENT_CODE]           VARCHAR (25)  NOT NULL,
    [MASTER_ID_CLIENT_CODE] VARCHAR (25)  NOT NULL,
    [MASTER_ID_SUPPLIER]    VARCHAR (25)  NOT NULL,
    [CODE_PRICE_LIST]       VARCHAR (25)  NOT NULL,
    [TAX_ID]                VARCHAR (25)  NOT NULL,
    [TAX_NAME]              VARCHAR (250) NOT NULL,
    [EXTERNAL_SOURCE_ID]    INT           NOT NULL,
    [ERP_DATABASE]          VARCHAR (50)  DEFAULT ('') NOT NULL,
    [FACT_SERIE]            VARCHAR (25)  DEFAULT ('') NOT NULL,
    [DEFAULT_WAREHOUSE]     VARCHAR (25)  NULL,
    CONSTRAINT [PK_OP_WMS_COMPANY] PRIMARY KEY CLUSTERED ([COMPANY_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_OP_WMS_COMPANY_OP_SETUP_EXTERNAL_SOURCE_EXTERNAL_SOURCE_ID] FOREIGN KEY ([EXTERNAL_SOURCE_ID]) REFERENCES [wms].[OP_SETUP_EXTERNAL_SOURCE] ([EXTERNAL_SOURCE_ID]),
    CONSTRAINT [UC_OP_WMS_COMPANY] UNIQUE NONCLUSTERED ([COMPANY_NAME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_COMPANY_COMPANY_NAME,EXTERNAL_SOURCE_ID]
    ON [wms].[OP_WMS_COMPANY]([COMPANY_NAME] ASC, [EXTERNAL_SOURCE_ID] ASC)
    INCLUDE([CLIENT_CODE], [ERP_DATABASE], [MASTER_ID_CLIENT_CODE], [MASTER_ID_SUPPLIER]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_COMPANY_COMPANY_NAME]
    ON [wms].[OP_WMS_COMPANY]([COMPANY_NAME] ASC)
    INCLUDE([FACT_SERIE]) WITH (FILLFACTOR = 80);

