CREATE TABLE [wms].[OP_WMS3PL_POLIZA_X_PASS] (
    [PASS_ID]         NUMERIC (18) NOT NULL,
    [CODE_POLIZA]     VARCHAR (15) NOT NULL,
    [LAST_UPDATED_BY] VARCHAR (25) NULL,
    [LAST_UPDATED]    DATETIME     NULL,
    CONSTRAINT [PK_OP_WMS3PL_POLIZA_X_PASS] PRIMARY KEY CLUSTERED ([PASS_ID] ASC, [CODE_POLIZA] ASC) WITH (FILLFACTOR = 80)
);

