CREATE TABLE [wms].[OP_WMS_VEHICLE] (
    [VEHICLE_CODE]               INT             IDENTITY (1, 1) NOT NULL,
    [BRAND]                      VARCHAR (50)    NULL,
    [LINE]                       VARCHAR (50)    NULL,
    [MODEL]                      VARCHAR (10)    NULL,
    [COLOR]                      VARCHAR (25)    NULL,
    [CHASSIS_NUMBER]             VARCHAR (50)    NULL,
    [ENGINE_NUMBER]              VARCHAR (50)    NULL,
    [VIN_NUMBER]                 VARCHAR (50)    NULL,
    [PLATE_NUMBER]               VARCHAR (10)    NULL,
    [TRANSPORT_COMPANY_CODE]     INT             NULL,
    [WEIGHT]                     NUMERIC (18, 6) NULL,
    [HIGH]                       NUMERIC (18, 6) NULL,
    [WIDTH]                      NUMERIC (18, 6) NULL,
    [DEPTH]                      NUMERIC (18, 6) NULL,
    [VOLUME_FACTOR]              NUMERIC (18, 6) NULL,
    [LAST_UPDATE]                DATETIME        DEFAULT (getdate()) NULL,
    [LAST_UPDATE_BY]             VARCHAR (25)    NULL,
    [PILOT_CODE]                 INT             NULL,
    [RATING]                     DECIMAL (18, 6) DEFAULT ((0)) NOT NULL,
    [IS_ACTIVE]                  INT             DEFAULT ((1)) NOT NULL,
    [STATUS]                     VARCHAR (50)    DEFAULT ('DISPONIBLE') NOT NULL,
    [FILL_RATE]                  DECIMAL (18, 6) DEFAULT ((100)) NOT NULL,
    [VEHICLE_AXLES]              INT             NULL,
    [INSURANCE_DOC_ID]           INT             NULL,
    [AVERAGE_COST_PER_KILOMETER] NUMERIC (18, 6) NULL,
    [VEHICLE_EXTERNAL_ID]        INT             NULL,
    CONSTRAINT [PK_OP_WMS_VEHICLE_VEHICLE_CODE] PRIMARY KEY CLUSTERED ([VEHICLE_CODE] ASC) WITH (FILLFACTOR = 80),
    CHECK ([FILL_RATE]>=(0) AND [FILL_RATE]<=(100)),
    FOREIGN KEY ([INSURANCE_DOC_ID]) REFERENCES [wms].[OP_WMS_INSURANCE_DOCS] ([DOC_ID]),
    FOREIGN KEY ([PILOT_CODE]) REFERENCES [wms].[OP_WMS_PILOT] ([PILOT_CODE]),
    FOREIGN KEY ([TRANSPORT_COMPANY_CODE]) REFERENCES [wms].[OP_WMS_TRANSPORT_COMPANY] ([TRANSPORT_COMPANY_CODE])
);


GO
CREATE NONCLUSTERED INDEX [IDX_VEHICLE_CODE_PILOT_CODE_TRANSPORT_COMPANY_CODE]
    ON [wms].[OP_WMS_VEHICLE]([VEHICLE_CODE] ASC, [TRANSPORT_COMPANY_CODE] ASC, [PILOT_CODE] ASC)
    INCLUDE([BRAND], [CHASSIS_NUMBER], [COLOR], [DEPTH], [ENGINE_NUMBER], [HIGH], [LAST_UPDATE], [LAST_UPDATE_BY], [LINE], [MODEL], [VIN_NUMBER], [VOLUME_FACTOR], [WEIGHT], [WIDTH], [PLATE_NUMBER]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_PILOT_CODE_VEHICLE]
    ON [wms].[OP_WMS_VEHICLE]([PILOT_CODE] ASC)
    INCLUDE([BRAND], [CHASSIS_NUMBER], [COLOR], [DEPTH], [ENGINE_NUMBER], [HIGH], [LAST_UPDATE], [LAST_UPDATE_BY], [LINE], [MODEL], [PLATE_NUMBER], [VIN_NUMBER], [VOLUME_FACTOR], [WEIGHT], [WIDTH]) WITH (FILLFACTOR = 80);

