CREATE TABLE [wms].[TAB_USERS] (
    [USER_ID]    NCHAR (10) NOT NULL,
    [PWD]        NCHAR (10) NULL,
    [NAME]       NCHAR (10) NULL,
    [TYPE]       NCHAR (10) NULL,
    [STATUS]     NCHAR (10) NULL,
    [PHONE]      NCHAR (10) NULL,
    [EMAIL]      NCHAR (10) NULL,
    [LAST_LOGON] NCHAR (10) NULL,
    [COUNTRY]    NCHAR (10) NULL,
    CONSTRAINT [PK_TAB_USERS] PRIMARY KEY CLUSTERED ([USER_ID] ASC) WITH (FILLFACTOR = 80)
);

