

CREATE VIEW [dbo].[SONDA_VIEW_PENDING_MANIFESTS]
AS
SELECT 
	MANIFEST_ID, 
	DELIVERY_VEHICULE_PLATES,
	DELIVERY_DRIVER_NAME,
	TOTAL_BOXES, TOTAL_PRIZES, TOTAL_BULTOS
FROM dbo.SONDA_LOADING_MANIFEST
WHERE STATUS = 1