CREATE VIEW V_ANALISIS_LOG AS
select TRANS_DATE,TASK_ID, LOGIN_ID,LOGIN_NAME,TRANS_TYPE,TRANS_DESCRIPTION,
ISNULL(SOURCE_WAREHOUSE,TARGET_WAREHOUSE) BODEGA,MATERIAL_CODE,MATERIAL_DESCRIPTION,
QUANTITY_UNITS,TARGET_WAREHOUSE,TRANS_SUBTYPE,    STATUS,STATUS_CODE
	from wms.OP_WMS_TRANS
where TRANS_TYPE not in( 'REUBICACION_COMPLETA','CONTEO_FISICO','REUBICACION_PARCIAL')
AND MATERIAL_CODE IS NOT NULL
AND MATERIAL_CODE <>''
AND TASK_ID IS NOT NULL