CREATE VIEW  V_TAREAS_LOG AS
select   TASK_TYPE,TASK_SUBTYPE,TASK_OWNER,TASK_ASSIGNEDTO,ASSIGNED_DATE,ASSIGNED_DATE FECHA,QUANTITY_PENDING,
IS_COMPLETED,IS_CANCELED,WAREHOUSE_SOURCE,COMPLETED_DATE
from  wms.OP_WMS_TASK_LIST
WHERE  CONVERT(varchar(10),DATEPART(YYYY, ASSIGNED_DATE)) +CONVERT(varchar(10),DATEPART(mm, ASSIGNED_DATE)) = '20215'