CREATE TABLE [dbo].[SWIFT_LOG] (
    [LOG_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [TYPE]            VARCHAR (50)  NOT NULL,
    [CODE_ENTERPRISE] NVARCHAR (50) NOT NULL,
    [USER]            VARCHAR (50)  NOT NULL,
    [LOG_STAMP]       DATETIME      NOT NULL,
    [IP_ADDRESS]      VARCHAR (50)  NULL,
    CONSTRAINT [PK__SWIFT_LO__4364C882700A6687] PRIMARY KEY CLUSTERED ([LOG_ID] ASC)
);

