CREATE TABLE [dbo].[SWIFT_EXTERNAL_USER] (
    [CORRELATIVE]       INT           IDENTITY (1, 1) NOT NULL,
    [CODE_ENTERPRISE]   VARCHAR (50)  NULL,
    [NAME_ENTERPRISE]   VARCHAR (50)  NULL,
    [NUMBER_OF_USERS]   INT           NULL,
    [CONNECTION_STRING] VARCHAR (150) NULL,
    [LAST_UPDATE]       DATETIME      NULL,
    [LAST_UPDATE_BY]    VARCHAR (50)  NULL,
    [USER]              VARCHAR (50)  NULL,
    [PASS]              VARCHAR (50)  NULL,
    [IMAGE]             VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([CORRELATIVE] ASC)
);

