
CREATE PROCEDURE wms.OP_WMS_SP_ALTER_CC @ACCOUNT_ID VARCHAR(140),
@ACCOUNT_NAME VARCHAR(100),
@ADUANA_INGRESO VARCHAR(200),
@AGENTE_ADUANA VARCHAR(15),
@AGENTE_ADUANA_NOMBRE VARCHAR(200),
@NUMEROS_POLIZA VARCHAR(500),
@UNIDAD_MEDIDA VARCHAR(15),
@CANTIDAD NUMERIC(18, 2),
@DESCRIPCION VARCHAR(1500),
@CONTENEDOR VARCHAR(150),
@CIF NUMERIC(18, 2),
@LAST_UPDATE_BY VARCHAR(25),
@LAST_ACTION VARCHAR(50),
@STATUS VARCHAR(25),
@pResult VARCHAR(250) OUTPUT

AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRAN
  BEGIN
    INSERT INTO [wms].[OP_WMS_CARTAS_CUPO] ([ACCOUNT_ID]
    , [ACCOUNT_NAME]
    , [ADUANA_INGRESO]
    , [AGENTE_ADUANA]
    , [AGENTE_ADUANA_NOMBRE]
    , [NUMEROS_POLIZA]
    , [UNIDAD_MEDIDA]
    , [CANTIDAD]
    , [DESCRIPCION]
    , [CONTENEDOR]
    , [CIF]
    , [LAST_UPDATE]
    , [LAST_UPDATE_BY]
    , [LAST_ACTION]
    , [STATUS])
      VALUES (@ACCOUNT_ID, @ACCOUNT_NAME, @ADUANA_INGRESO, @AGENTE_ADUANA, @AGENTE_ADUANA_NOMBRE, @NUMEROS_POLIZA, @UNIDAD_MEDIDA, @CANTIDAD, @DESCRIPCION, @CONTENEDOR, @CIF, CURRENT_TIMESTAMP, @LAST_UPDATE_BY, @LAST_ACTION, @STATUS)

  END

  IF @@error = 0
  BEGIN
    SELECT
      @pResult = 'OK'
    COMMIT TRAN
  END
  ELSE
  BEGIN
    ROLLBACK TRAN
    SELECT
      @pResult = ERROR_MESSAGE()
  END

END