CREATE PROCEDURE [wms].[OP_WMS_SP_GET_ASSIGNED_ACUERDOS_X_CLIENTE]		
	@CLIENT_ID VARCHAR(50),	
	@pResult varchar(250) OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON;	
	BEGIN TRAN
		BEGIN
			SELECT *
			FROM [wms].OP_WMS_ACUERDOS_X_CLIENTE 
			INNER JOIN [wms].OP_WMS_TARIFICADOR_HEADER ON ACUERDO_COMERCIAL_ID = ACUERDO_COMERCIAL
			WHERE CLIENT_ID = @CLIENT_ID
		END	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN
	END
	ELSE
		BEGIN
			ROLLBACK TRAN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
		
END