-- =============================================
-- Autor:                 marvin.solares
-- Fecha de Creacion:   2018-06-06 @ GForce Team Sprint Dinosaurio
-- Description:          SP que obtiene el detalle de las recepciones erp.
/*
-- Ejemplo de Ejecucion:
		EXEC [wms].[OP_WMS_SP_GET_RECEPTION_ERP_DOCUMENT_DETAIL] @SERIAL_NUMBER = 284952          
		
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_RECEPTION_ERP_DOCUMENT_DETAIL] (@SERIAL_NUMBER INT)
AS
BEGIN
	SELECT
		[ERPD].[ERP_RECEPTION_DOCUMENT_DETAIL_ID]
		,[ERPH].[DOC_NUM]
		,[ERPD].[ERP_RECEPTION_DOCUMENT_HEADER_ID]
		,[ERPD].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[ERPD].[QTY]
		,[ERPD].[LINE_NUM]
		,[ERPD].[ERP_OBJECT_TYPE]
		,[ERPD].[ATTEMPTED_WITH_ERROR]
		,[ERPD].[IS_POSTED_ERP]
		,[ERPD].[POSTED_ERP]
		,[ERPD].[POSTED_RESPONSE]
		,[ERPD].[ERP_REFERENCE]
		,[ERPD].[ERP_REFERENCE_DOC_NUM]
		,[ERPD].[WAREHOUSE_CODE]
		,[ERPD].[CURRENCY]
		,[ERPD].[RATE]
		,[ERPD].[TAX_CODE]
		,[ERPD].[VAT_PERCENT]
		,[ERPD].[PRICE]
		,[ERPD].[DISCOUNT]
		,[ERPD].[COST_CENTER]
		,[ERPD].[QTY_ASSIGNED]
		,ISNULL([ERPD].[QTY_CONFIRMED], 0) [QTY_CONFIRMED]
		,[ERPD].[QTY] - ISNULL([ERPD].[QTY_CONFIRMED], 0) [PENDING]
		,ISNULL([ERPD].[UNIT], 'Unidad Base') [UNIT]
		,ISNULL([ERPD].[UNIT_DESCRIPTION], 'Unidad Base') [UNIT_DESCRIPTION]
		,ISNULL([UMM].[QTY], 1) [QTY_FACTOR]
		, [ERPD].[WAREHOUSE_CODE] 
	FROM
		[wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL] [ERPD]
	INNER JOIN [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] [ERPH] ON [ERPH].[ERP_RECEPTION_DOCUMENT_HEADER_ID] = [ERPD].[ERP_RECEPTION_DOCUMENT_HEADER_ID]
	INNER JOIN [wms].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [ERPD].[MATERIAL_ID]
	LEFT JOIN [wms].[OP_WMS_UNIT_MEASUREMENT_BY_MATERIAL] [UMM] ON [UMM].[MATERIAL_ID] = [ERPD].[MATERIAL_ID]
											AND [ERPD].[UNIT] = [UMM].[MEASUREMENT_UNIT]
	WHERE
		[ERPH].[TASK_ID] = @SERIAL_NUMBER;

END;