-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	13-Jul-17 @ Nexus TEAM Sprint AgeOfEmpires
-- Description:			SP que obtiene el picking para enviar al ERP

/*
-- Ejemplo de Ejecucion:
				EXEC [wms].[OP_WMS_SP_GET_INVENTORY_TRANSACTION_HEADER_ERP_BY_PICKING]
					@PICKING_DEMAND_HEADER_ID = 4182
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_INVENTORY_TRANSACTION_HEADER_ERP_BY_PICKING](
	@PICKING_DEMAND_HEADER_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE 
		@SERIES_ENTRADA VARCHAR(50)
		,@SERIES_SALIDA VARCHAR(50)
		,@PRICE_LIST VARCHAR(50)
	--
	SELECT @SERIES_ENTRADA = [TEXT_VALUE]
	FROM [wms].OP_WMS_CONFIGURATIONS
	WHERE PARAM_TYPE = 'SISTEMA'
	AND PARAM_GROUP = 'MASTER_PACK_ERP_SETTINGS'
	AND [PARAM_NAME] = 'SERIES_ENTRADA_INVENTARIO'
	--
	SELECT @SERIES_SALIDA = [TEXT_VALUE]
	FROM [wms].OP_WMS_CONFIGURATIONS
	WHERE PARAM_TYPE = 'SISTEMA'
	AND PARAM_GROUP = 'MASTER_PACK_ERP_SETTINGS'
	AND [PARAM_NAME] = 'SERIES_SALIDA_INVENTARIO'
	--
	SELECT @PRICE_LIST = [TEXT_VALUE]
	FROM [wms].OP_WMS_CONFIGURATIONS
	WHERE PARAM_TYPE = 'SISTEMA'
	AND PARAM_GROUP = 'MASTER_PACK_ERP_SETTINGS'
	AND [PARAM_NAME] = 'PRICE_LIST'
	--
	SELECT
		[H].[PICKING_DEMAND_HEADER_ID] AS DocNum
		,[H].[CLIENT_CODE] AS CardCode
		,@SERIES_ENTRADA AS SeriesEntrada
		,@SERIES_SALIDA AS SeriesSalida
		,GETDATE() AS DocDate
		,GETDATE() AS TaxDate
		,CAST([H].[PICKING_DEMAND_HEADER_ID] AS VARCHAR) AS Ref2
		,@PRICE_LIST AS PriceList
		,ISNULL([C].[CLIENT_NAME],'') CardName
	FROM [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [H]
	LEFT JOIN [wms].[OP_WMS_VIEW_CLIENTS] [C] ON ([C].[CLIENT_CODE] = [H].[CLIENT_CODE])
	WHERE [H].[PICKING_DEMAND_HEADER_ID] = @PICKING_DEMAND_HEADER_ID
END