CREATE PROCEDURE [wms].[OP_WMS_SP_CREATE_ALL_ACUERDOS_X_CLIENTE]
	@CLIENT_ID VARCHAR(50),	
	@pResult varchar(250) OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON;	
	BEGIN TRAN
		BEGIN
			INSERT INTO [wms].OP_WMS_ACUERDOS_X_CLIENTE
			(
				  CLIENT_ID
				, ACUERDO_COMERCIAL
			)
			SELECT @CLIENT_ID, ACUERDO_COMERCIAL_ID
			FROM [wms].OP_WMS_TARIFICADOR_HEADER
			WHERE NOT EXISTS(SELECT 1
							FROM [wms].OP_WMS_ACUERDOS_X_CLIENTE
							WHERE ACUERDO_COMERCIAL_ID = ACUERDO_COMERCIAL
							AND CLIENT_ID = @CLIENT_ID)
			--VALUES
			--(				  
			--	  @CLIENT_ID
			--	, @ACUERDO_COMERCIAL
			--)						
		END	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN
	END
	ELSE
		BEGIN
			ROLLBACK TRAN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
		
END