-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	4/27/2018 @ GForce-Team Sprint Capibara
-- Description:			Obtiene el formato de impresion de licencia

/*
-- Ejemplo de Ejecucion:
				EXEC [wms].[OP_WMS_SP_GET_LICENSE_PRINT_FORMAT]
					@LICENSE_ID = 90
					,@LOGIN = 'ACAMACHO'
					,@REIMPRESION = 1
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_LICENSE_PRINT_FORMAT] (
		@LICENSE_ID INT
		,@LOGIN VARCHAR(25)
		,@REIMPRESION INT
	)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE
		@COMPANY VARCHAR(100)
		,@REGIMEN VARCHAR(50)
		,@OWNER VARCHAR(50)
		,@PICKING_DEMAND_HEADER_ID INT;

	SELECT TOP 1
		@COMPANY = [COMPANY_CODE]
	FROM
		[wms].[OP_SETUP_COMPANY];

	SELECT TOP 1
		@REGIMEN = [l].[REGIMEN]
		,@PICKING_DEMAND_HEADER_ID = [l].[PICKING_DEMAND_HEADER_ID]
		,@COMPANY =  UPPER(ISNULL([c].[CLIENT_CODE],[l].CLIENT_OWNER))+'-'+ ISNULL([c].[COMPANY_NAME],@COMPANY)
		,@OWNER = C.CLIENT_CODE
	FROM
		[wms].[OP_WMS_LICENSES] [l]
	LEFT JOIN [wms].[OP_WMS_COMPANY] [c] ON [c].[CLIENT_CODE] = [l].[CLIENT_OWNER]
	WHERE
		[l].[LICENSE_ID] = @LICENSE_ID;

	IF @PICKING_DEMAND_HEADER_ID IS NOT NULL
	BEGIN
		SELECT
			@REGIMEN = CASE	WHEN ISNULL([PROJECT], '') = ''
							THEN [CLIENT_CODE]
							ELSE [PROJECT]
						END
		FROM
			[wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER]
		WHERE
			[PICKING_DEMAND_HEADER_ID] = @PICKING_DEMAND_HEADER_ID;
	END;

	DECLARE	@LABEL_SIZE VARCHAR(25);
	SELECT
		@LABEL_SIZE = [VALUE]
	FROM
		[wms].[OP_WMS_PARAMETER]
	WHERE
		[PARAMETER_ID] = 'LABEL_SIZE';

	IF @LABEL_SIZE = '3X2'
	BEGIN
		SELECT
			'! 0 50 50 436 1
! U1 LMARGIN 0
! U1 PAGE-WIDTH 1400
CENTER 570 T 0 5 3 0 ' + @COMPANY + '
CENTER 570 T 0 5 0 50 ' + @REGIMEN + '
BARCODE 128 1 1 130 20 90 ' + CAST(@LICENSE_ID AS VARCHAR)
			+ '-
CENTER 570 T 0 6 0 225 ' + CAST(@LICENSE_ID AS VARCHAR)+'
'
			+ CASE	WHEN @REIMPRESION = 1
					THEN 'CENTER 570 T 0 4 0 280 *REIMPRESION*'
					ELSE ''
				END + '
LINE 0 300 570 300 2
LINE 0 35 570 35 2
CENTER 570 T 0 2 0 310 ' + @LOGIN + ' / '
			+ CONVERT(VARCHAR(50), GETDATE()) + '
CENTER 570 T 0 1 0 340 www.procesoseficientes.com
L 5 T 0 2 0 130
PRINT
! U1 getvar "device.host_status"
' AS [FORMAT];
	END;

	ELSE
	BEGIN 
	
		SELECT
			N'! 0 50 50 635 1 
! U1 LMARGIN 10
! U1 PAGE-WIDTH 1400
CENTER 570 T 0 3 0 0 ' + @COMPANY + '
CENTER 570 T 0 5 0 70 ' + CASE	WHEN ISNULL(@OWNER, '') = ''
							THEN 'LICENCIA'
							ELSE @REGIMEN
						END + '
LINE 0 35 570 35 2
BARCODE 128 3 1 200 20 140 ' + CAST(@LICENSE_ID AS VARCHAR)
			+ '-
CENTER 570 T 0 6 0 400 ' + CAST(@LICENSE_ID AS VARCHAR) + '
'
			+ CASE	WHEN @REIMPRESION = 1
					THEN 'CENTER 570 T 0 4 0 460 *REIMPRESION*'
					ELSE ''
				END + '
LINE 0 500 570 500 2
CENTER 570 T 0 2 0 510 ' + @LOGIN + ' / '
			+ CONVERT(VARCHAR(50), GETDATE()) + '
CENTER 570 T 0 1 0 550 www.procesoseficientes.com
L 5 T 0 2 0 130 
PRINT
! U1 getvar "device.host_status"
' AS [FORMAT];
	END; 

END;