
CREATE PROCEDURE [wms].[OP_WMS_SP_EMAIL_CHECKER]
@CLIENT_CODE NVARCHAR(15),
@TASK_LIST_ID NUMERIC(18,0),
@pResult VARCHAR(250) OUTPUT,
@pFactor NUMERIC(38,6) OUTPUT
AS

BEGIN TRY

	DECLARE @FACTOR NUMERIC(38,6)
	DECLARE @PERCENT FLOAT

	SELECT @FACTOR = FACTOR3 FROM [wms].[OP_WMS_VIEW_CLIENT_FACTORS] WHERE CLIENT_CODE = @CLIENT_CODE AND TASK_LIST_ID = @TASK_LIST_ID
	SELECT	@pFactor	=	@FACTOR

	IF (@FACTOR > 0)
	BEGIN
		--SE EJECUTA CUANDO QUEDA MAS DEL 30% DE MERCADERIA POSITIVA Y DESBLOQUEA EL PICKING
		SELECT @PERCENT = ((FACTOR3 / FACTOR2) * 100) FROM [wms].[OP_WMS_VIEW_CLIENT_FACTORS] WHERE CLIENT_CODE = @CLIENT_CODE AND TASK_LIST_ID = @TASK_LIST_ID
		IF(@PERCENT > 30)
		BEGIN
			PRINT 'PICKING DESBLOQUEADO, PERMITE PASAR'
			UPDATE [wms].[OP_WMS_TASK_LIST] SET [IS_lOCKED] = '1' WHERE [WAVE_PICKING_ID] = @TASK_LIST_ID
			IF @@ERROR = 0 BEGIN
				SELECT	@pResult	= 'PICKING DESBLOQUEADO, PERMITE PASAR'
			END 
			ELSE BEGIN
				SELECT	@pResult	= ERROR_MESSAGE()
			END
		END
		--SE EJECUTA SI QUEDA MENOS DEL 30% DE MERCADERIA Y ENVIA CORREO
		ELSE
		BEGIN
			PRINT 'QUEDA MENOS DEL 30% DE MERCADERIA'
			SELECT [EMAIL] FROM [wms].[OP_WMS_LOGINS] WHERE AUTHORIZER = 1
			SELECT [CLIENT_NAME] FROM [wms].[OP_WMS_VIEW_CLIENTS] WHERE CLIENT_CODE = @CLIENT_CODE
			UPDATE [wms].[OP_WMS_TASK_LIST] SET [IS_lOCKED] = '0' WHERE [IS_lOCKED] = '1' AND [WAVE_PICKING_ID] = @TASK_LIST_ID
			IF @@ERROR = 0 BEGIN
				SELECT	@pResult	= 'QUEDA MENOS DEL 30% DE MERCADERIA'
			END 
			ELSE BEGIN
				SELECT	@pResult	= ERROR_MESSAGE()
			END
		END
	END

	--SI EL VALOR ES NEGATIVO ENVIA CORREO PARA SU APROVACION
	IF (@FACTOR < 0)
	BEGIN
		PRINT 'PICKING BLOQUEADO, ENVIO DE CORREO'
		SELECT [EMAIL] FROM [wms].[OP_WMS_LOGINS] WHERE AUTHORIZER = 1
		SELECT [CLIENT_NAME] FROM [wms].[OP_WMS_VIEW_CLIENTS] WHERE CLIENT_CODE = @CLIENT_CODE
		UPDATE [wms].[OP_WMS_TASK_LIST] SET [IS_lOCKED] = '0' WHERE [IS_lOCKED] = '1' AND [WAVE_PICKING_ID] = @TASK_LIST_ID
		IF @@ERROR = 0 BEGIN
			SELECT	@pResult	= 'PICKING BLOQUEADO, ENVIO DE CORREO'
		END 
		ELSE BEGIN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
	END

	--SI EL VALOR ES 0 DESBLOQUEA EL PICKING
	IF(@FACTOR = 0)
	BEGIN
		PRINT '0 DEUDA, PICKING DESBLOQUEADO'
		UPDATE [wms].[OP_WMS_TASK_LIST] SET [IS_lOCKED] = '1' WHERE [WAVE_PICKING_ID] = @TASK_LIST_ID
		IF @@ERROR = 0 BEGIN
			SELECT	@pResult	= '0 DEUDA, PICKING DESBLOQUEADO'
		END 
		ELSE BEGIN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
	END

	END TRY

BEGIN CATCH
	SELECT	@pResult	= ERROR_MESSAGE()
END CATCH