-- =============================================
-- Autor:				marvin.solares
-- Autor2:				Diego Espinoza
-- Fecha de Creacion: 	21-Ago-2019 @ G-Force-Team Sprint FlorencioVarela
-- Fecha Creacion 2:		Mayo 25 - 2020
-- Description:          SP que obtiene el detalle de la ola de picking por licencias
-- Description2:		Obtener el detalle de Ordenes segun Procedimiento padre por Fecha.

/*|
-- TEST:
       EXEC wms.OP_WMS_SP_GET_TASK_DETAIL_FOR_WAVE_PICKING_Ranges_DEM '2020-05-15', '2020-05-25'
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_TASK_DETAIL_FOR_WAVE_PICKING_Ranges_DEM] 
	(
		@FechaInicial	DATE, 
		@FechaFinal		DATE
	)
AS

	CREATE TABLE #OlasPicking
	(
	  WavePickingId INT
	)
	
	INSERT #OlasPicking 
	EXEC [wms].[OP_WMS_GET_TASK_BASIC_VIEW_DEM_WaveDetail] 
		@START_DATETIME = @FechaInicial,
		@END_DATETIME = @FechaFinal,
		@USERS = N'ACABRERA|BDUBON|CLAUDIOLPYS|CBARRERA|CENRIQUES|DROMERO|DVEGA|JPINEDA|JFLORES|JLOPEZ|JCRUZTGU|JBARDALESPYS|JSORIANO|KALVA|KELVINAPYS|KLOPEZPYS|LLOPEZTGU|LGODOY|LLUNAPYS|MVELASQUEZ|MZELAYA|MPEREZ|OPER1|OTURCIOSTGU|RRIVERA|SHERNANDEZ', 
		@TYPES = N'TAREA_ALMACENAJE|TAREA_CONTEO_FISICO|TAREA_PICKING|TAREA_REABASTECIMIENTO|TAREA_RECEPCION|TAREA_REUBICACION', 
		@LOGIN = 'ADMIN';

	SELECT
	[TL].[SERIAL_NUMBER]
	,[TL].[WAVE_PICKING_ID]
	,[TL].[MATERIAL_ID]
	,[TL].[MATERIAL_NAME]
	,[TL].[COMPLETED_DATE] AS [COMPLETED_DATE]
	,CASE	WHEN [PDH].[PICKING_DEMAND_HEADER_ID] IS NULL
			THEN [TL].[CLIENT_NAME]
			WHEN [PDH].[IS_CONSOLIDATED] = 1
			THEN 'CONSOLIDADO'
			ELSE [PDH].[CLIENT_NAME]
		END [CLIENT_NAME]
	,CASE	WHEN [PDH].[PICKING_DEMAND_HEADER_ID] IS NULL
			THEN '0'
			WHEN [PDH].[IS_CONSOLIDATED] = 1 THEN '0'
			ELSE [PDH].[DOC_NUM]
		END [DOC_NUM]
	,[TL].[LICENSE_ID_SOURCE]
	,[TL].[LICENSE_ID_TARGET]
	,[IL].[BATCH]
	,[IL].[DATE_EXPIRATION]
	,[SML].[STATUS_CODE]
	,[TCL].[TONE]
	,[TCL].[CALIBER]
	,[TL].[LOCATION_SPOT_SOURCE]
	,[TL].[LOCATION_SPOT_TARGET]
	,[TL].[QUANTITY_PENDING]
	,[TL].[QUANTITY_ASSIGNED]
	,(CASE [TL].[IS_CANCELED]
		WHEN 1 THEN 'CANCELADA'
		WHEN 0
		THEN (CASE [TL].[IS_COMPLETED]
				WHEN 0 THEN CASE [TL].[IS_ACCEPTED]
								WHEN 0 THEN 'INCOMPLETA'
								WHEN 1 THEN 'ACEPTADA'
							END
				ELSE 'COMPLETA'
				END)
		END) AS [STATUS]
	,[TL].[IS_CANCELED]
	,[TL].[WAVE_PICKING_ID]
FROM
	[wms].[OP_WMS_TASK_LIST] [TL]
INNER JOIN [wms].[OP_WMS_INV_X_LICENSE] [IL] ON [TL].[LICENSE_ID_SOURCE] = [IL].[LICENSE_ID]
											AND [TL].[MATERIAL_ID] = [IL].[MATERIAL_ID]
LEFT JOIN [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH] ON ([TL].[WAVE_PICKING_ID] = [PDH].[WAVE_PICKING_ID])
LEFT JOIN [wms].[OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE] [SML] ON [IL].[STATUS_ID] = [SML].[STATUS_ID]
LEFT JOIN [wms].[OP_WMS_TONE_AND_CALIBER_BY_MATERIAL] [TCL] ON [TCL].[TONE_AND_CALIBER_ID] = [IL].[TONE_AND_CALIBER_ID]
WHERE
	[TL].[WAVE_PICKING_ID] IN 
	(
		SELECT WavePickingId FROM #OlasPicking
	)
ORDER BY [TL].[WAVE_PICKING_ID] ASC

DROP TABLE #OlasPicking
