CREATE PROC [wms].[OP_WMS_SP_UPDATE_SAT_SERVICE_STATUS]
@ACUSE_DOC_ID NUMERIC(18,0),
@STATUS VARCHAR(10),
@pResult VARCHAR(200) OUTPUT
AS
UPDATE [wms].[OP_WMS_SAT_SERVICES]
   SET 
	   [STATUS] =  @STATUS      
      ,[UPDATE_DATE] = CURRENT_TIMESTAMP      
 WHERE ACUSE_DOC_ID = @ACUSE_DOC_ID