-- =================================================
-- Autor:				MICHAEL.MAZARIEGOS
-- Fecha de creacion:	12/6/2019 @ G-Force - TEAM Sprint Magadascar
-- Historia/Bug:		Product Backlog Item 33265: Tareas de usuarios por bodega
-- Descripcion:			12/6/2019 - Obtiene el nombre, cantidad de tareas pendientes y completadas del usuario logeado.

/*
-- Ejemplo de Ejecucion:
	EXEC [wms].[OP_WMS_SP_GET_TASKS_BY_USER_SUPER]
	@LOGIN_PARAMETER = 'Marvin'
*/
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_TASKS_BY_USER_SUPER]
(
	@LOGIN_PARAMETER VARCHAR(100)
)
AS
BEGIN
    SET NOCOUNT ON;
	-- -----------------------------------------------------------------------------------
    -- SE OBTIENEN LOS USUARIO Y LAS BODEGAS ASIGNADAS AL MISMO.
    -- -----------------------------------------------------------------------------------

	DECLARE @TEMP_WAREHOUSE_MY_USER AS TABLE
	(
		ID INT IDENTITY(1, 1),
		WAREHOUSE_ID VARCHAR(25)
	);

	INSERT INTO @TEMP_WAREHOUSE_MY_USER
	(
		WAREHOUSE_ID
	)
	SELECT WAREHOUSE_ID
	FROM wms.OP_WMS_WAREHOUSE_BY_USER
	WHERE LOGIN_ID = @LOGIN_PARAMETER;

	-- INGRESAMOS LOS USUARIOS DE NUESTRAS BODEGAS ASOCIADAS
	DECLARE @TEMP_TASKS_PENDING AS TABLE (
		IS_ASSIGNED VARCHAR(25),
		QTY_PENDING INT NOT NULL,
		WAREHOUSE_SOURCE VARCHAR(25)
	)

	INSERT INTO @TEMP_TASKS_PENDING
	(
	    IS_ASSIGNED,
	    QTY_PENDING,
	    WAREHOUSE_SOURCE
	)
	SELECT WTL.TASK_ASSIGNEDTO, SUM(WTL.IS_ACCEPTED)IS_ACCEPTED
		,WTL.WAREHOUSE_SOURCE
	FROM wms.OP_WMS_TASK_LIST [WTL]
		INNER JOIN @TEMP_WAREHOUSE_MY_USER [TWU]
			ON (TWU.WAREHOUSE_ID = WTL.WAREHOUSE_SOURCE)
			WHERE WTL.IS_CANCELED = 0 AND WTL.IS_COMPLETED = 0 AND WTL.IS_PAUSED = 0
	GROUP BY 
		WTL.TASK_ASSIGNEDTO
		,WTL.WAREHOUSE_SOURCE


	SELECT DISTINCT WTL.TASK_ASSIGNEDTO, SUM(WTL.IS_COMPLETED) IS_COMPLETED, SUM(WTL.IS_CANCELED)IS_CANCELED
		, TP.QTY_PENDING
				,WTL.WAREHOUSE_SOURCE
	FROM wms.OP_WMS_TASK_LIST [WTL]
		INNER JOIN @TEMP_WAREHOUSE_MY_USER [TWU]
			ON (TWU.WAREHOUSE_ID = WTL.WAREHOUSE_SOURCE)
			INNER JOIN @TEMP_TASKS_PENDING [TP]
				ON (TP.WAREHOUSE_SOURCE = WTL.WAREHOUSE_SOURCE AND TP.IS_ASSIGNED = WTL.TASK_ASSIGNEDTO)
	GROUP BY 
		WTL.TASK_ASSIGNEDTO
		,WTL.WAREHOUSE_SOURCE,
		TP.QTY_PENDING
	--SELECT * FROM @TEMP_USERS
END

	--EXECUTE wms.OP_WMS_SP_GET_TASKS_BY_USER_SUPER @LOGIN_PARAMETER = 'MARVIN' -- varchar(100)