-- =============================================
-- Autor:	        hector.gonzalez
-- Fecha de Creacion: 	2017-02-23 @ Team ERGON - Sprint ERGON 
-- Description:	     

-- Autor:	        marvin.solares
-- Fecha de Creacion: 	20180705 GForce@Elefante
-- Description: Se agrega columna material_name en consulta de retorno del sp

/*
-- Ejemplo de Ejecucion:
			EXEC [wms].[OP_WMS_SP_GET_PHYSICAL_COUNTS] @START_DATETIME = '2016-02-24'
                                                 ,@END_DATETIME = '2017-02-25'
                                                 ,@USERS_ASSIGNED_TO = 'ACAMACHO'
                                                 ,@CODE_WAREHOUSE = 'BODEGA_01'  
												 ,@LOGIN_ID = 'ADMIN'
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_PHYSICAL_COUNTS] (
		@START_DATETIME DATETIME
		,@END_DATETIME DATETIME
		,@USERS_ASSIGNED_TO VARCHAR(MAX) = NULL
		,@CODE_WAREHOUSE VARCHAR(MAX) = NULL
		,@LOGIN_ID VARCHAR(MAX)
	)
AS
BEGIN
	SET NOCOUNT ON;
  --
	SELECT
		[W].[VALUE] [CODE_WAREHOUSE]
	INTO
		[#WAREHOUSE]
	FROM
		[wms].[OP_WMS_FN_SPLIT](@CODE_WAREHOUSE, '|') [W];

	SELECT
		[L].[VALUE] [LOGIN]
	INTO
		[#LOGIN]
	FROM
		[wms].[OP_WMS_FN_SPLIT](@USERS_ASSIGNED_TO, '|') [L];

	SELECT
		[H].[PHYSICAL_COUNT_HEADER_ID]
		,[H].[TASK_ID]
		,[T].[ACCEPTED_DATE]
		,[T].[COMPLETED_DATE]
		,[T].[ASSIGNED_DATE]
		,[T].[TASK_ASSIGNED_TO]
		,[H].[REGIMEN]
		,[H].[STATUS]
		,COUNT([E].[PHYSICAL_COUNTS_EXECUTION_ID])
		/ CAST(COUNT([D].[PHYSICAL_COUNT_DETAIL_ID]) AS NUMERIC(8,
											4)) * 100 [PorcentajeCompletado]
		,SUM(CASE [E].[HIT_OR_MISS]
				WHEN 'H' THEN 1
				ELSE 0
				END)
		/ CAST(CASE COUNT([E].[PHYSICAL_COUNTS_EXECUTION_ID])
					WHEN 0 THEN 1
					WHEN NULL THEN 1
					ELSE COUNT([E].[PHYSICAL_COUNTS_EXECUTION_ID])
				END AS NUMERIC(8, 4)) * 100 [PORCENTAJE_EXACTITUD]
		,COUNT([E].[QTY_SCANNED]) [TOTAL_CONTADOS]
		,SUM(CASE [E].[HIT_OR_MISS]
				WHEN 'H' THEN 1
				ELSE 0
				END) [TOTAL_HITS]
		,SUM(CASE [E].[HIT_OR_MISS]
				WHEN 'M' THEN 1
				ELSE 0
				END) [TOTAL_MISSES]
	INTO
		[#COUNTING_HEADER]
	FROM
		[wms].[OP_WMS_PHYSICAL_COUNTS_HEADER] [H]
	INNER JOIN [wms].[OP_WMS_TASK] [T] ON [H].[TASK_ID] = [T].[TASK_ID]
	INNER JOIN [wms].[OP_WMS_PHYSICAL_COUNTS_DETAIL] [D] ON [H].[PHYSICAL_COUNT_HEADER_ID] = [D].[PHYSICAL_COUNT_HEADER_ID]
	LEFT JOIN [wms].[OP_WMS_PHYSICAL_COUNTS_EXECUTION] [E] ON [D].[PHYSICAL_COUNT_DETAIL_ID] = [E].[PHYSICAL_COUNT_DETAIL_ID]
	WHERE
		[T].[ASSIGNED_DATE] BETWEEN @START_DATETIME
							AND		@END_DATETIME
	GROUP BY
		[H].[PHYSICAL_COUNT_HEADER_ID]
		,[H].[TASK_ID]
		,[T].[ACCEPTED_DATE]
		,[T].[COMPLETED_DATE]
		,[T].[ASSIGNED_DATE]
		,[T].[TASK_ASSIGNED_TO]
		,[H].[REGIMEN]
		,[H].[STATUS];

	SELECT
		[H].[PHYSICAL_COUNT_HEADER_ID]
		,[H].[TASK_ID]
		,[H].[ACCEPTED_DATE]
		,[H].[COMPLETED_DATE]
		,[H].[TASK_ASSIGNED_TO]
		,[H].[ASSIGNED_DATE]
		,[H].[REGIMEN]
		,[H].[STATUS] [TASK_STATUS]
		,CONVERT(DECIMAL(18, 2), [H].[PorcentajeCompletado]) [PERCENT_COMPLETED]
		,CONVERT(DECIMAL(18, 2), [H].[PORCENTAJE_EXACTITUD]) [ACCURACY]
		,[H].[TOTAL_CONTADOS] [TOTAL_COUNT]
		,[H].[TOTAL_HITS]
		,[H].[TOTAL_MISSES]
		,[D].[WAREHOUSE_ID]
		,[D].[STATUS] [LOCATION_STATUS]
		,[D].[LOCATION]
		,ISNULL([E].[MATERIAL_ID], [D].[MATERIAL_ID]) [MATERIAL_ID]
		,ISNULL([ME].[MATERIAL_NAME], [MD].[MATERIAL_NAME]) [MATERIAL_NAME]
		,[D].[ASSIGNED_TO] [COUNT_ASSIGNED_TO]
		,[E].[QTY_SCANNED]
		,[E].[QTY_EXPECTED] - [E].[QTY_SCANNED] [DIFFERENCE]
		,[E].[LICENSE_ID]
		,[E].[QTY_EXPECTED]
		,[E].[HIT_OR_MISS]
		,[E].[EXECUTED]
		,[E].[EXECUTED_BY]
		,[E].[EXPIRATION_DATE]
		,[E].[BATCH]
		,[E].[SERIAL]
		,[E].[EXPIRATION_DATE_EXPECTED]
		,[E].[BATCH_EXPECTED]
		,[E].[SERIAL_EXPECTED]
	FROM
		[#COUNTING_HEADER] [H]
	INNER JOIN [wms].[OP_WMS_PHYSICAL_COUNTS_DETAIL] [D] ON [D].[PHYSICAL_COUNT_HEADER_ID] = [H].[PHYSICAL_COUNT_HEADER_ID]
	INNER JOIN [wms].[OP_WMS_WAREHOUSE_BY_USER] [WU] ON [WU].[WAREHOUSE_ID] = [D].[WAREHOUSE_ID]
	LEFT JOIN [#WAREHOUSE] [W] ON [W].[CODE_WAREHOUSE] = [D].[WAREHOUSE_ID]
	LEFT JOIN [#LOGIN] [L] ON [L].[LOGIN] = [D].[ASSIGNED_TO]
	LEFT JOIN [wms].[OP_WMS_PHYSICAL_COUNTS_EXECUTION] [E] ON [D].[PHYSICAL_COUNT_DETAIL_ID] = [E].[PHYSICAL_COUNT_DETAIL_ID]
											AND (
											[D].[MATERIAL_ID] IS NULL
											OR [D].[MATERIAL_ID] = [E].[MATERIAL_ID]
											)
	LEFT JOIN [wms].[OP_WMS_MATERIALS] [MD] ON [MD].[MATERIAL_ID] = [D].[MATERIAL_ID]
	LEFT JOIN [wms].[OP_WMS_MATERIALS] [ME] ON [ME].[MATERIAL_ID] = [E].[MATERIAL_ID]
	WHERE
		(
			@CODE_WAREHOUSE IS NULL
			OR [W].[CODE_WAREHOUSE] IS NOT NULL
		)
		AND (
				@USERS_ASSIGNED_TO IS NULL
				OR [L].[LOGIN] IS NOT NULL
			)
		AND [WU].[LOGIN_ID] = @LOGIN_ID;



END;