-- =============================================
-- Autor:					pablo.aguilar
-- Fecha de Creacion: 		17-Jan-18 @ Nexus Team Sprint @Jumanji
-- Description:			    Se crea SP para obtener poliza header para el movil.

/*
-- Ejemplo de Ejecucion:
        SELECT CODIGO_POLIZA, NUMERO_ORDEN, TIPO, WAREHOUSE_REGIMEN  FROM [wms].[OP_WMS_POLIZA_HEADER] order by 1 desc 
		EXEC [wms].[OP_WMS_SP_GET_POLIZA_HEADER] @CODE_POLICY = 'ZUPMGAP7Z', -- varchar(25)
				@TYPE = 'EGRESO', -- varchar(25)
				@ORDER = '2606500991', -- varchar(25)
				@OPERATOR = NULL, -- varchar(25)
				@REGIME = NULL -- varchar(25)
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_POLIZA_HEADER] (
		@CODE_POLICY VARCHAR(25)
		,@TYPE VARCHAR(25)
		,@ORDER VARCHAR(25) = NULL
		,@OPERATOR VARCHAR(25) = NULL
		,@REGIME VARCHAR(25) = NULL  
	)
AS
BEGIN

	SELECT
		[P].[DOC_ID]
		,[P].[NUMERO_ORDEN]
		,[P].[ADUANA_ENTRADA_SALIDA]
		,[P].[NUMERO_DUA]
		,[P].[FECHA_ACEPTACION_DMY]
		,[P].[ADUANA_DESPACHO_DESTINO]
		,[P].[REGIMEN]
		,[P].[CLASE]
		,[P].[PAIS_PROCEDENCIA]
		,[P].[NATURALEZA_TRANS]
		,[P].[DEPOSITO_FISCAL_ZF]
		,[P].[MODO]
		,[P].[FECHA_LLEGADA]
		,[P].[TIPO_CAMBIO]
		,[P].[TOTAL_VALOR_ADUANA]
		,[P].[TOTAL_NUMERO_LINEAS]
		,[P].[TOTAL_BULTOS]
		,[P].[TOTAL_PESO_BRUTO_KG]
		,[P].[TOTAL_FOB_USD]
		,[P].[TOTAL_FLETE_USD]
		,[P].[TOTAL_SEGURO_USD]
		,[P].[TOTAL_OTROS_USD]
		,[P].[NUMERO_SAT]
		,[P].[TIPO_IMPORTADOR]
		,[P].[ID_TRIB_IMPORTADOR]
		,[P].[PAIS_IMPORTADOR]
		,[P].[RAZON_SOCIAL_IMPORTADOR]
		,[P].[DOMICILIO_IMPORTADOR]
		,[P].[TIPO_REPRESENTANTE]
		,[P].[ID_TRIB_REPRESENTANTE]
		,[P].[PAIS_REPRESENTANTE]
		,[P].[TIPO_DECLARANTE_REPRESENTANTE]
		,[P].[RAZON_SOCIAL_REPRESENTANTE]
		,[P].[DOMICILIO_REPRESENTANTE]
		,[P].[TIPO_CONTENEDOR]
		,[P].[NUMERO_CONTENEDOR]
		,[P].[ENTIDAD_CONTENEDOR]
		,[P].[NUMERO_MARCHAMO_CONTENEDOR]
		,[P].[TOTAL_LIQUIDAR]
		,[P].[TOTAL_OTROS]
		,[P].[TOTAL_GENERAL]
		,[P].[CODIGO_POLIZA]
		,[P].[LAST_UPDATED_BY]
		,[P].[LAST_UPDATED]
		,[P].[STATUS]
		,[P].[ACUERDO_COMERCIAL]
		,[P].[WAREHOUSE_REGIMEN]
		,[P].[CLIENT_CODE]
		,[P].[FECHA_DOCUMENTO]
		,[P].[TIPO]
		,[P].[REFERENCIA_EXTRA]
		,[P].[POLIZA_ASEGURADA]
		,[P].[POLIZA_ASSIGNEDTO]
		,[P].[TRANSLATION]
		,[P].[PENDIENTE_RECTIFICACION]
		,[P].[CODIGO_POLIZA_RECTIFICACION]
		,[P].[COMENTARIO_RECTIFICACION]
		,[P].[CLASE_POLIZA_RECTIFICACION]
		,[P].[DOC_ID_RECTIFICACION]
		,[P].[COMENTARIO_RECTIFICADO]
		,[P].[IS_EXTERNAL_INVENTORY]
		,[P].[IS_BLOCKED]
		,[P].[DOCUMENTO_DESBLOQUEO]
		,[P].[COMENTARIO_DESBLOQUEO]
		,[P].[USUARIO_DESBLOQUEO]
		,[P].[FECHA_DESBLOQUEO]
		,[P].[BLOCKED_STATUS]
		,(SELECT TOP 1
				[b].[CLIENT_NAME]
			FROM
				[wms].[OP_WMS_VIEW_CLIENTS] [b]
			WHERE
				[b].[CLIENT_CODE] = [P].[CLIENT_CODE] COLLATE DATABASE_DEFAULT)
		+ CHAR(13) + CHAR(10)
		+ CASE	WHEN [RDH].[NAME_SUPPLIER] IS NULL THEN ''
				ELSE 'Proveedor: ' + [RDH].[NAME_SUPPLIER]
			END AS [CLIENT_NAME]
		,ISNULL((SELECT TOP 1
						ISNULL([CONTENEDOR], 'N/A')
					FROM
						[wms].[OP_WMS_AUDIT_RECEPTION_CONTROL]
					WHERE
						(
							[CODIGO_POLIZA] = @CODE_POLICY
							OR [NUMERO_ORDEN] = @CODE_POLICY
						)
						AND [STATUS] = 'CREATED'), 'N/A') AS [CONTENEDOR_EN_CONTEO]
	FROM
		[wms].[OP_WMS_POLIZA_HEADER] [P]
	LEFT JOIN [wms].[OP_WMS_TASK_LIST] [TL] ON ([P].[DOC_ID] = [TL].[DOC_ID_SOURCE])
	LEFT JOIN [wms].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] [RDH] ON ([RDH].[TASK_ID] = [TL].[SERIAL_NUMBER])
	WHERE
		([P].[CODIGO_POLIZA] = @CODE_POLICY)
		AND [P].[TIPO] = @TYPE
		AND (
				@ORDER IS NULL
				OR [P].[NUMERO_ORDEN] = @ORDER
			)
		AND (
				@REGIME IS NULL
				OR [P].[WAREHOUSE_REGIMEN] = @REGIME
			)
		AND (
				@OPERATOR IS NULL
				OR [P].[POLIZA_ASSIGNEDTO] = @OPERATOR
			); 
END;