CREATE PROCEDURE [wms].[OP_WMS_SP_GET_TASK_PICKING]		
	@OlaPicking  NUMERIC(18,0),
	@MaterialId varchar(25),
	@QTY NUMERIC(18,0),
	@pResult varchar(250) OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON;
					
	BEGIN TRAN
		BEGIN
		
			SELECT TL.*
				, SS.SPOT_TYPE
				, (SELECT TOP 1 IV.QTY 
						FROM [wms].[OP_WMS_INV_X_LICENSE] IV 
						WHERE IV.LICENSE_ID = TL.LICENSE_ID_SOURCE 
						AND IV.MATERIAL_ID = TL.MATERIAL_ID) AS LICENSE_QTY
				, (SELECT TOP 1 L.USED_MT2
						FROM [wms].[OP_WMS_LICENSES] L
						WHERE L.LICENSE_ID = TL.LICENSE_ID_SOURCE) AS USED_MT2
				, ISNULL((SELECT 1
					FROM [wms].[OP_WMS_POLIZA_HEADER]
					WHERE CODIGO_POLIZA = TL.CODIGO_POLIZA_TARGET
					AND [TIPO] = 'INGRESO'
					AND WAREHOUSE_REGIMEN = 'GENERAL'), 0) EXIST_POLIZA
				
				, (SELECT TOP 1 IV.BATCH 
					FROM [wms].[OP_WMS_INV_X_LICENSE] IV 
					WHERE IV.LICENSE_ID = TL.LICENSE_ID_SOURCE 
					AND IV.MATERIAL_ID = TL.MATERIAL_ID) AS BATCH
				, (SELECT TOP 1 IV.DATE_EXPIRATION 
					FROM [wms].[OP_WMS_INV_X_LICENSE] IV 
					WHERE IV.LICENSE_ID = TL.LICENSE_ID_SOURCE 
					AND IV.MATERIAL_ID = TL.MATERIAL_ID) AS DATE_EXPIRATION

				, (SELECT ACUERDO_COMERCIAL
					FROM [wms].[OP_WMS_POLIZA_HEADER]
					WHERE CODIGO_POLIZA = TL.CODIGO_POLIZA_TARGET
					AND [TIPO] = 'INGRESO'
					AND WAREHOUSE_REGIMEN = 'GENERAL') ACUERDO_COMERCIAL_ID
			FROM [wms].[OP_WMS_TASK_LIST] TL
				INNER JOIN [wms].[OP_WMS_SHELF_SPOTS] SS ON(SS.LOCATION_SPOT = TL.LOCATION_SPOT_SOURCE)
			WHERE [WAVE_PICKING_ID] = @OlaPicking
			AND [MATERIAL_ID] = @MaterialId
			AND [QUANTITY_ASSIGNED] = @QTY
			AND 0 < (SELECT TOP 1 IV.QTY 
						FROM [wms].[OP_WMS_INV_X_LICENSE] IV 
						WHERE IV.LICENSE_ID = TL.LICENSE_ID_SOURCE 
						AND IV.MATERIAL_ID = TL.MATERIAL_ID)

		END	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN
	END
	ELSE
		BEGIN
			ROLLBACK TRAN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
		
END