-- =============================================
-- Autor:	        hector.gonzalez
-- Fecha de Creacion: 	2017-03-24 @ Team ERGON - Sprint ERGON Hyper
-- Description:	        trae las polizas por cliente y bodega

-- Modificacion 18-Jul-17 @ Nexus Team Sprint AgeOfEmpires
					-- alberto.ruiz
					-- Se agregan columnas de vencimiento y se elimino la llamada al SP [OP_WMS_SP_GET_WAREHOUSE_ASSOCIATED_WITH_USER] porque el resultado lo ingresaba en una tabla temporal donde estaba comentado el join a la misma

/*
-- Ejemplo de Ejecucion:
			EXEC  [wms].[OP_WMS_SP_GET_POLIZA_BY_CLIENT_AND_WAREHOUSE_REGIMEN]
				@CLIENT_CODE = 'C01096'
                ,@WHAREHOUSE_REGIMEN = 'GENERAL'
				,@LOGIN = 'ADMIN'
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_POLIZA_BY_CLIENT_AND_WAREHOUSE_REGIMEN] (
	@CLIENT_CODE VARCHAR(25)
	,@WHAREHOUSE_REGIMEN VARCHAR(25)
	,@LOGIN VARCHAR(25)
) AS
BEGIN
	SET NOCOUNT ON;
	--
	SELECT
		[P].[DOC_ID]
		,[P].[NUMERO_ORDEN]
		,[P].[ADUANA_ENTRADA_SALIDA]
		,[P].[NUMERO_DUA]
		,[P].[FECHA_ACEPTACION_DMY]
		,[P].[ADUANA_DESPACHO_DESTINO]
		,[P].[REGIMEN]
		,[P].[CLASE]
		,[P].[PAIS_PROCEDENCIA]
		,[P].[NATURALEZA_TRANS]
		,[P].[DEPOSITO_FISCAL_ZF]
		,[P].[MODO]
		,[P].[FECHA_LLEGADA]
		,[P].[TIPO_CAMBIO]
		,[P].[TOTAL_VALOR_ADUANA]
		,[P].[TOTAL_NUMERO_LINEAS]
		,[P].[TOTAL_BULTOS]
		,[P].[TOTAL_PESO_BRUTO_KG]
		,[P].[TOTAL_FOB_USD]
		,[P].[TOTAL_FLETE_USD]
		,[P].[TOTAL_SEGURO_USD]
		,[P].[TOTAL_OTROS_USD]
		,[P].[NUMERO_SAT]
		,[P].[TIPO_IMPORTADOR]
		,[P].[ID_TRIB_IMPORTADOR]
		,[P].[PAIS_IMPORTADOR]
		,[P].[RAZON_SOCIAL_IMPORTADOR]
		,[P].[DOMICILIO_IMPORTADOR]
		,[P].[TIPO_REPRESENTANTE]
		,[P].[ID_TRIB_REPRESENTANTE]
		,[P].[PAIS_REPRESENTANTE]
		,[P].[TIPO_DECLARANTE_REPRESENTANTE]
		,[P].[RAZON_SOCIAL_REPRESENTANTE]
		,[P].[DOMICILIO_REPRESENTANTE]
		,[P].[TIPO_CONTENEDOR]
		,[P].[NUMERO_CONTENEDOR]
		,[P].[ENTIDAD_CONTENEDOR]
		,[P].[NUMERO_MARCHAMO_CONTENEDOR]
		,[P].[TOTAL_LIQUIDAR]
		,[P].[TOTAL_OTROS]
		,[P].[TOTAL_GENERAL]
		,[P].[CODIGO_POLIZA]
		,[P].[LAST_UPDATED_BY]
		,[P].[LAST_UPDATED]
		,[P].[STATUS]
		,[P].[ACUERDO_COMERCIAL]
		,[P].[WAREHOUSE_REGIMEN]
		,[P].[CLIENT_CODE]
		,[P].[FECHA_DOCUMENTO]
		,[P].[TIPO]
		,[P].[REFERENCIA_EXTRA]
		,[P].[POLIZA_ASEGURADA]
		,[P].[POLIZA_ASSIGNEDTO]
		,[P].[TRANSLATION]
		,[P].[PENDIENTE_RECTIFICACION]
		,[P].[CODIGO_POLIZA_RECTIFICACION]
		,[P].[COMENTARIO_RECTIFICACION]
		,[P].[CLASE_POLIZA_RECTIFICACION]
		,[P].[DOC_ID_RECTIFICACION]
		,[P].[COMENTARIO_RECTIFICADO]
		,CASE [P].[WAREHOUSE_REGIMEN]
			WHEN 'FISCAL' THEN [wms].[OP_WMS_FN_GET_DAYS_BY_REGIMEN]([P].[REGIMEN]) 
			ELSE NULL
		END [DIAS_REGIMEN]
		,CASE [P].[WAREHOUSE_REGIMEN]
			WHEN 'FISCAL' THEN DATEDIFF(DAY,GETDATE(),[wms].[OP_WMS_FN_GET_EXPIRATION_DATE_FOR_POLIZA]([P].[CODIGO_POLIZA])) 
			ELSE NULL
		END [DIAS_PARA_VENCER]
		,CASE [P].[WAREHOUSE_REGIMEN]
			WHEN 'FISCAL' THEN [wms].[OP_WMS_FN_GET_EXPIRATION_DATE_FOR_POLIZA]([P].[CODIGO_POLIZA]) 
			ELSE NULL
		END [FECHA_VENCIMIENTO]
		,CASE 
			WHEN [P].[WAREHOUSE_REGIMEN] = 'FISCAL' AND DATEDIFF(DAY,GETDATE(),[wms].[OP_WMS_FN_GET_EXPIRATION_DATE_FOR_POLIZA]([P].[CODIGO_POLIZA])) < 1 THEN 'Bloqueado'
			ELSE 'Libre'
		END [ESTADO_REGIMEN]
	FROM [wms].[OP_WMS_POLIZA_HEADER] [P]
	WHERE [P].[CLIENT_CODE] = @CLIENT_CODE
		AND [P].[WAREHOUSE_REGIMEN] = @WHAREHOUSE_REGIMEN;
END;