CREATE PROC [wms].OP_WMS_SP_DELETE_QUOTA_LETTER
@DOC_ID NUMERIC(18,0),
@pResult VARCHAR(200) OUTPUT
AS
DECLARE @STATUS VARCHAR(20)
BEGIN TRY
	SET @STATUS = (SELECT [STATUS] FROM [wms].OP_WMS_QUOTA_LETTER WHERE DOC_ID = @DOC_ID)

	IF @STATUS <> 'SOLICITADA'
	BEGIN
		SET @pResult = 'NO SE PUEDE ELIMINAR PORQUE YA FUE APROBADA'
	END
	IF @STATUS = 'SOLICITADA'
	BEGIN
		DELETE FROM [wms].[OP_WMS_QUOTA_LETTER]
		  WHERE DOC_ID = @DOC_ID AND [STATUS] = 'SOLICITADA'
		SET @pResult = 'OK'
	END
 END TRY
	
BEGIN CATCH
	ROLLBACK TRAN;
	SELECT @pResult = ERROR_MESSAGE()
END CATCH