CREATE PROC [wms].[OP_WMS_SP_UPDATE_SAT_SERVICE]
@ID NUMERIC(18,0),
@STATUS VARCHAR(10),
@MESSAGE varchar(250),
@MESSAGE_CODE varchar(15),
@NUMBER_OF_ATTEMPTS INT,
@pResult VARCHAR(200) OUTPUT
AS
UPDATE [wms].[OP_WMS_SAT_SERVICES]
   SET 
	   [STATUS] =  @STATUS
      ,[MESSAGE] = @MESSAGE
      ,[MESSAGE_CODE] = @MESSAGE_CODE
      ,[UPDATE_DATE] = CURRENT_TIMESTAMP
      ,[NUMBER_OF_ATTEMPTS] = @NUMBER_OF_ATTEMPTS
 WHERE ID = @ID