CREATE PROCEDURE [wms].[OP_WMS_SP_UPDATE_TARIFICADOR_HEADER]	
	@ACUERDO_COMERCIAL_ID INT, 
	@ACUERDO_COMERCIAL_NOMBRE VARCHAR(50),
	@VALID_FROM DATE,
	@VALID_TO DATE, 
	@EXPIRES INT,
	@CURRENCY VARCHAR(20),
	@STATUS VARCHAR(20),
	@WAREHOUSE_WEATHER VARCHAR(20),	
	@LAST_UPDATED_BY VARCHAR(25),
	@COMMENTS VARCHAR(MAX),
	@REGIMEN VARCHAR(25),
	@AUTHORIZER VARCHAR(25),
	@pResult varchar(250) OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON;	
	BEGIN TRAN
		BEGIN
			UPDATE [wms].OP_WMS_TARIFICADOR_HEADER SET
			  ACUERDO_COMERCIAL_NOMBRE = @ACUERDO_COMERCIAL_NOMBRE
			, VALID_FROM = @VALID_FROM
			, VALID_TO = @VALID_TO
			, EXPIRES = @EXPIRES
			, CURRENCY = @CURRENCY
			, [STATUS] = @STATUS
			, WAREHOUSE_WEATHER = @WAREHOUSE_WEATHER
			, LAST_UPDATED = GETDATE()
			, LAST_UPDATED_BY = @LAST_UPDATED_BY
			, COMMENTS = @COMMENTS
			, REGIMEN = @REGIMEN
			, AUTHORIZER = @AUTHORIZER
			WHERE ACUERDO_COMERCIAL_ID = @ACUERDO_COMERCIAL_ID
		END	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN
	END
	ELSE
		BEGIN
			ROLLBACK TRAN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
		
END