-- =============================================
-- Autor:	        hector.gonzalez
-- Fecha de Creacion: 	2017-10-18 @ Team REBORN - Sprint Drache
-- Description:	        SP que desasocia un demanda de despacho de un manifiesto 

/*
-- Ejemplo de Ejecucion:
			EXEC [wms].OP_WMS_SP_DISASSOCIATE_PICKING_DEMAND_OF_MANIFEST @PICKING_DEMAND_HEADER_IDS = '32|65|7|', @MANIFEST_HEADER_ID = 3
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_DISASSOCIATE_PICKING_DEMAND_OF_MANIFEST] (
		@PICKING_DEMAND_HEADER_IDS VARCHAR(MAX)
		,@MANIFEST_HEADER_ID INT
	)
AS
BEGIN
	SET NOCOUNT ON;
  --
	BEGIN TRY

		DECLARE
			@DELIMITER AS NCHAR(1) = '|'
			,@MANIFEST_DETAIL_ID INT
			,@IS_STATUS_CREATED INT = 0;

		SELECT
			@IS_STATUS_CREATED = 1
		FROM
			[wms].[OP_WMS_MANIFEST_HEADER] [M]
		WHERE
			[M].[MANIFEST_HEADER_ID] = @MANIFEST_HEADER_ID
			AND (
					[M].[STATUS] = 'CREATED'
					OR [M].[STATUS] = 'CANCELED'
					OR [M].[STATUS] = 'IN_PICKING'
				);

		IF @IS_STATUS_CREATED = 0
		BEGIN
			RAISERROR ('No puede desasociar pickings de un manifiesto ya procesado o cancelado', 16, 1);
		END;

		DECLARE	@PICKING_DEMAND_IDS TABLE (
				[PICKING_DEMAND_HEADER_ID] INT
				,UNIQUE ([PICKING_DEMAND_HEADER_ID])
			);

		DECLARE	@MANIFEST_DETAIL TABLE (
				[MANIFEST_DETAIL_ID] INT
				,UNIQUE ([MANIFEST_DETAIL_ID])
			);

		DECLARE	@LABELS TABLE (
				[LABEL_ID] INT
				,[MANIFEST_DETAIL_ID] INT
				,[MATERIAL_ID] VARCHAR(50)
				,[QTY_LABEL] DECIMAL(18, 4)
			);

		INSERT	INTO @PICKING_DEMAND_IDS
				(
					[PICKING_DEMAND_HEADER_ID]
				)
		SELECT DISTINCT
			[P].[VALUE]
		FROM
			[wms].[OP_WMS_FUNC_SPLIT_3](@PICKING_DEMAND_HEADER_IDS,
											@DELIMITER) [P];

		INSERT	INTO @MANIFEST_DETAIL
				(
					[MANIFEST_DETAIL_ID]
				)
		SELECT DISTINCT
			[MD].[MANIFEST_DETAIL_ID]
		FROM
			[wms].[OP_WMS_MANIFEST_DETAIL] [MD]
		INNER JOIN @PICKING_DEMAND_IDS ON [MD].[PICKING_DEMAND_HEADER_ID] = [@PICKING_DEMAND_IDS].[PICKING_DEMAND_HEADER_ID];


		WHILE EXISTS ( SELECT TOP 1
							1
						FROM
							@MANIFEST_DETAIL )
		BEGIN

			SELECT
				@MANIFEST_DETAIL_ID = [MANIFEST_DETAIL_ID]
			FROM
				@MANIFEST_DETAIL;

			DELETE
				[wms].[OP_WMS_PICKING_LABEL_BY_MANIFEST]
			WHERE
				[MANIFEST_DETAIL_ID] = @MANIFEST_DETAIL_ID;

			DELETE
				@MANIFEST_DETAIL
			WHERE
				[MANIFEST_DETAIL_ID] = @MANIFEST_DETAIL_ID;
		END;

		DELETE
			[MD]
		FROM
			@PICKING_DEMAND_IDS [P]
		INNER JOIN [wms].[OP_WMS_MANIFEST_DETAIL] [MD] ON [MD].[PICKING_DEMAND_HEADER_ID] = [P].[PICKING_DEMAND_HEADER_ID]
		INNER JOIN [wms].[OP_WMS_MANIFEST_HEADER] [MH] ON [MD].[MANIFEST_HEADER_ID] = [MH].[MANIFEST_HEADER_ID]
		WHERE
			[MH].[STATUS] = 'CREATED';


		SELECT
			1 AS [Resultado]
			,'Proceso Exitoso' [Mensaje]
			,0 [Codigo]
			,CAST(@MANIFEST_HEADER_ID AS VARCHAR) [DbData];

	END TRY
	BEGIN CATCH
		SELECT
			-1 AS [Resultado]
			,ERROR_MESSAGE() [Mensaje]
			,@@ERROR [Codigo];
	END CATCH;


END;