


CREATE PROCEDURE [wms].[OP_WMS_SP_PASS_SET_DETAIL_BY_POLIZA]
	@PASS_ID NUMERIC(18,0),
	@CODE_POLIZA VARCHAR(15),
	@LAST_UPDATED_BY VARCHAR(25),
	@PRESULT VARCHAR(4000) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			INSERT INTO [wms].OP_WMS3PL_POLIZA_X_PASS
				(PASS_ID, CODE_POLIZA, LAST_UPDATED_BY, LAST_UPDATED)
			VALUES
				(@PASS_ID, @CODE_POLIZA, @LAST_UPDATED_BY, GETDATE());
				
		COMMIT TRAN
		
		SELECT @PRESULT = 'OK';
	END TRY
	
	BEGIN CATCH
		ROLLBACK TRAN;
		SELECT @PRESULT = ERROR_MESSAGE()
	END CATCH
END