CREATE PROC [wms].[OP_WMS_SP_CREATE_INSURANCE_DOCS_LOG]			
	@INSURANCE_DOCS_ID INT
	,@UPDATE_BY VARCHAR(20)	
	,@NEW_VALID_FROM DATE
	,@NEW_VALID_TO DATE
	,@COMMENT VARCHAR(250)
	,@AUTHORIZED_BY VARCHAR(25)	
	,@pResult varchar(200) OUTPUT		   
AS
	if not exists(SELECT 1 FROM [wms].OP_WMS_INSURANCE_DOCS	WHERE DOC_ID = @INSURANCE_DOCS_ID)BEGIN
		SELECT @pResult = 'No se encontro el numero de documento'
		RETURN -1
	END
	
	DECLARE @OLD_VALIN_FROM DATE;
	DECLARE @OLD_VALIN_TO DATE;
	
	SELECT @OLD_VALIN_FROM = VALIN_FROM, @OLD_VALIN_TO = VALIN_TO
	FROM [wms].OP_WMS_INSURANCE_DOCS
	WHERE DOC_ID = @INSURANCE_DOCS_ID	

	BEGIN TRY
		INSERT INTO [wms].[OP_WMS_INSURANCE_DOCS_LOG]
				   ( 			   
					INSURANCE_DOCS_ID
					,UPDATED
					,UPDATED_BY
					,OLD_VALIN_FROM
					,OLD_VALIN_TO
					,NEW_VALID_FROM
					,NEW_VALID_TO
					,COMMENT
					,AUTHORIZED_BY				  
				   )
			 VALUES
				   (			   
					@INSURANCE_DOCS_ID
					,GETDATE()
					,@UPDATE_BY
					,@OLD_VALIN_FROM
					,@OLD_VALIN_TO
					,@NEW_VALID_FROM
					,@NEW_VALID_TO
					,@COMMENT
					,@AUTHORIZED_BY 
				   )
			UPDATE [wms].OP_WMS_INSURANCE_DOCS SET
			VALIN_FROM = @NEW_VALID_FROM
			, VALIN_TO = @NEW_VALID_TO
			WHERE DOC_ID = @INSURANCE_DOCS_ID
			
			SELECT @pResult = 'OK'
	END TRY	
	BEGIN CATCH	
		SELECT @pResult = ERROR_MESSAGE()
	END CATCH