-- =============================================
-- Autor:				marvin.solares
-- Fecha de Creacion: 	20181012 GForce@Langosta
-- Description:	        Sp que trae el detalle de un Picking wms para enviarlo a R3

-- Autor:				marvin.solares
-- Fecha de Creacion: 	20181114 GForce@Narwhal
-- Description:	        Modificación para que separe la obtención de series en otro sp

/*
-- Ejemplo de Ejecucion:
			select * from [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER]
			--
			EXEC [wms].[OP_WMS_SP_GET_NEXT_PICKING_DEMAND_DETAIL_FOR_R3] 
				@PICKING_DEMAND_HEADER_ID = 27
*/
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_GET_NEXT_PICKING_DEMAND_DETAIL_FOR_R3] (
		@PICKING_DEMAND_HEADER_ID INT
	)
AS
BEGIN
	SET NOCOUNT ON;
  --
	DECLARE
		@TAX_CODE VARCHAR(50)
		,@INTERNAL_SALE VARCHAR(50)
		,@IS_INTERNAL_SALE INT = 0
		,@QUERY NVARCHAR(4000)
		,@PICKING_OWNER VARCHAR(50);
  --


  --
	SELECT
		@PICKING_OWNER = CASE [PDH].[OWNER]
							WHEN NULL
							THEN CASE [PDH].[SELLER_OWNER]
									WHEN NULL
									THEN [PDH].[CLIENT_OWNER]
									ELSE [PDH].[SELLER_OWNER]
									END
							ELSE [PDH].[OWNER]
							END
	FROM
		[wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH]
	WHERE
		[PDH].[PICKING_DEMAND_HEADER_ID] = @PICKING_DEMAND_HEADER_ID;
  --
	SELECT TOP 1
		@TAX_CODE = [C].[TEXT_VALUE]
	FROM
		[wms].[OP_WMS_CONFIGURATIONS] [C]
	WHERE
		[C].[PARAM_TYPE] = 'SISTEMA'
		AND [C].[PARAM_GROUP] = 'ERP_PARAMS'
		AND [C].[PARAM_NAME] = 'TAX_CODE_ERP';
  --
	SELECT TOP 1
		@INTERNAL_SALE = [C].[TEXT_VALUE]
	FROM
		[wms].[OP_WMS_CONFIGURATIONS] [C]
	WHERE
		[C].[PARAM_TYPE] = 'SISTEMA'
		AND [C].[PARAM_GROUP] = 'INTERCOMPANY'
		AND [C].[PARAM_NAME] = 'INTERNAL_SALE';
  --
	SELECT TOP 1
		@IS_INTERNAL_SALE = 1
	FROM
		[wms].[OP_WMS_FUNC_SPLIT_3](@INTERNAL_SALE, '|')
	WHERE
		[VALUE] = @PICKING_OWNER;
  --

	SELECT TOP 1
		[T].[WAVE_PICKING_ID]
		,[T].[TASK_OWNER]
		,ISNULL([T].[DISPATCH_LICENSE_EXIT_BY],
				[T].[TASK_ASSIGNEDTO]) [DISPATCH_LICENSE_EXIT_BY]
	INTO
		[#TASK]
	FROM
		[wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH]
	INNER JOIN [wms].[OP_WMS_TASK_LIST] [T] ON [PDH].[WAVE_PICKING_ID] = [T].[WAVE_PICKING_ID]
	WHERE
		[PDH].[PICKING_DEMAND_HEADER_ID] = @PICKING_DEMAND_HEADER_ID;

  
	SELECT
		'OR' [INPUT_TYPE]
		,CAST([SO].[VBELN] AS VARCHAR(200)) [VBELN]
		,[SO].[KUNNR] [KUNNR]
		,[SO].[VKGRP] [VKGRP]
		,[SO].[NETWR] [NETWR]
		,CASE	WHEN [SO].[LGORT] = '' THEN '0001'
				ELSE [SO].[LGORT]
			END [LGORT]
		,[SO].[NAME1_KUNNR] [NAME1_KUNNR]
		,[SO].[ERDAT] [ERDAT]
		,[SO].[MATNR] [MATNR]
		,[PDD].[QTY] [MENGE]
		,CAST([PDD].[LINE_NUM] AS NUMERIC(18, 0)) [POSNR]
		,[SO].[MEINS] [MEINS]
		,[SO].[MSEHL] [MSEHL]
		,[SO].[PRICE] [PRICE]
		,[SO].[WERKS] [WERKS]
		,[SO].[AUART] [AUART]
		,[SO].[ADDRESS_CUSTOMER] [ADDRESS_CUSTOMER]
		,[SO].[DISCOUNT] [DISCOUNT]
		,[SO].[IS_FOR_DELIVERY_IMMEDIATE] [IS_FOR_DELIVERY_IMMEDIATE]
		,[SO].[DEMAND_DELIVERY_DATE] [DEMAND_DELIVERY_DATE]
		,'Asignada Por: '
		+ CAST([T].[TASK_OWNER] AS VARCHAR) [XBLNR]
		,'Operada Por: ' + [T].[DISPATCH_LICENSE_EXIT_BY] [BKTXT]
		,'Ola Swift 3PL: '
		+ CAST([T].[WAVE_PICKING_ID] AS VARCHAR) [FRBNR]
		,ROW_NUMBER() OVER (ORDER BY [PDD].[LINE_NUM] ASC) AS [ROW_NUMBER]
	INTO
		[#PICKING_SO]
	FROM
		[wms].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] [PDD]
	INNER JOIN [wms].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PDH] ON [PDH].[PICKING_DEMAND_HEADER_ID] = [PDD].[PICKING_DEMAND_HEADER_ID]
	INNER JOIN [wms].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [PDD].[MATERIAL_ID]
	INNER JOIN [SWIFT_R3_INTER].[dbo].[RFC_SALE_ORDER] [SO] ON [PDH].[DOC_ENTRY] = [SO].[VBELN]
											AND [SO].[POSNR] = [PDD].[LINE_NUM]
	INNER JOIN [#TASK] [T] ON [T].[WAVE_PICKING_ID] = [PDH].[WAVE_PICKING_ID]
	WHERE
		[PDD].[QTY] > 0
		AND [PDH].[PICKING_DEMAND_HEADER_ID] = @PICKING_DEMAND_HEADER_ID
		AND [PDH].[TYPE_DEMAND_CODE] IN (0, 2)
	ORDER BY
		[PDD].[LINE_NUM] ASC;

	SELECT
		*
	FROM
		[#PICKING_SO]
	ORDER BY
		[ROW_NUMBER] ASC;

END;

