-- =============================================
-- Author:		Elder Lucas
-- Create date: 2022.07.26
-- Description:	Sp que obtiene el detalle de la tarea de masterpack

--ejemplo: exec wms.[OP_WMS_GET_DETAIL_MASTERPACK_TASK] @SERIAL_NUMBER = 810410
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_GET_DETAIL_MASTERPACK_TASK] (@SERIAL_NUMBER INT)
	-- Add the parameters for the stored procedure here
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	--SELECT TOP 100 * FROM WMS.OP_WMS_LICENSES ORDER BY 1 DESC

	--SELECT TOP 100 * FROM WMS.OP_WMS_TASK_LIST ORDER BY 1 DESC


	--SELECT TOP 100 * FROM WMS.OP_WMS_MASTER_PACK_HEADER WHERE MASTER_PACK_HEADER_ID = 8187

	--SELECT TOP 1000 * FROM WMS.OP_WMS_MASTER_PACK_DETAIL ORDER BY 1 DESC


	SELECT 
	M.MATERIAL_ID,
	M.MATERIAL_NAME,
	IXL.QTY,
	0 QTY_DOC,
	0 QTY_DIFFERENCE,
	CAST(TL.SERIAL_NUMBER AS VARCHAR) TASK_COMMENTS,
	M.BARCODE_ID,
	TL.SERIAL_NUMBER,
	L.CODIGO_POLIZA CODIGO_POLIZA_SOURCE,
	L.CODIGO_POLIZA CODIGO_POLIZA_TARGET
	FROM WMS.OP_WMS_MASTER_PACK_DETAIL MPD
	INNER JOIN WMS.OP_WMS_MASTER_PACK_HEADER MPH ON MPH.MASTER_PACK_HEADER_ID = MPD.MASTER_PACK_HEADER_ID
	INNER JOIN WMS.OP_WMS_LICENSES L ON L.LICENSE_ID = MPH.LICENSE_ID
	INNER JOIN WMS.OP_WMS_INV_X_LICENSE IXL ON IXL.LICENSE_ID = L.LICENSE_ID AND MPD.MATERIAL_ID = IXL.MATERIAL_ID
	INNER JOIN WMS.OP_WMS_MATERIALS M ON M.MATERIAL_ID = MPD.MATERIAL_ID
	INNER JOIN WMS.OP_WMS_TASK_LIST TL ON CAST(MPH.MASTER_PACK_HEADER_ID AS VARCHAR) = TL.ORDER_NUMBER AND TL.SERIAL_NUMBER = @SERIAL_NUMBER


    -- Insert statements for procedure here

END