


CREATE PROCEDURE [wms].[OP_WMS_SP_DELETE_PASS_DETAIL]
	@PASS_ID NUMERIC(18,0),
	@AUDIT_ID NUMERIC(18,0),	
	@PRESULT VARCHAR(4000) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			
			DELETE [wms].OP_WMS3PL_AUDITS_X_PASS
			WHERE PASS_ID = @PASS_ID
			AND AUDIT_ID = @AUDIT_ID
			
			UPDATE [wms].OP_WMS_AUDIT_DISPATCH_CONTROL SET
			PASS_DATE = NULL
			, PASS = 0
			WHERE AUDIT_ID = @AUDIT_ID
						
		COMMIT TRAN
		
		SELECT @PRESULT = 'OK';
	END TRY
	
	BEGIN CATCH
		ROLLBACK TRAN;
		SELECT @PRESULT = ERROR_MESSAGE()
	END CATCH
END