-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_REPORTES_MOV_X_SKU]
	-- Add the parameters for the stored procedure here
	
	@FECFIN varchar(250),
	@FECINI varchar(250),
	
	@MATERIAL_NAME AS VARCHAR(250)=null,
	@MATERIAL_ID AS VARCHAR(250)=null,
	@CLIENT_NAME AS VARCHAR(250)=null,
	
	@REGIMEN AS VARCHAR(15)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    
SELECT
A.SERIAL_NUMBER,A.TRANS_DATE,A.TRANS_DESCRIPTION,A.CODIGO_POLIZA,C.NUMERO_ORDEN, A.CLIENT_NAME,
C.REGIMEN,A.MATERIAL_BARCODE,A.MATERIAL_DESCRIPTION,A.QUANTITY_UNITS AS ENTRADA,
'0 ' AS SALIDA
FROM
[wms].OP_WMS_TRANS A
LEFT JOIN [wms].OP_WMS_LICENSES B ON A.LICENSE_ID=B.LICENSE_ID
LEFT JOIN [wms].OP_WMS_POLIZA_HEADER C ON B.CODIGO_POLIZA=C.CODIGO_POLIZA AND B.REGIMEN=C.WAREHOUSE_REGIMEN
LEFT JOIN [wms].OP_WMS_MATERIALS D on A.MATERIAL_BARCODE= D.ALTERNATE_BARCODE
WHERE MATERIAL_NAME =ISNULL(@MATERIAL_NAME,MATERIAL_NAME) 
AND MATERIAL_ID=isnull(@MATERIAL_ID,MATERIAL_ID)
AND CLIENT_NAME =ISNULL(@CLIENT_NAME,CLIENT_NAME)
and B.REGIMEN=@REGIMEN
AND/**/ A.TRANS_DESCRIPTION LIKE 'IN%'
AND   TRANS_DATE  BETWEEN cast( @FECINI +' 00:00:00.000' as DATE) AND  cast(@FECFIN +' 23:59:59.999' as DATE)
UNION
SELECT
A.SERIAL_NUMBER,A.TRANS_DATE,A.TRANS_DESCRIPTION,A.CODIGO_POLIZA,
C.NUMERO_ORDEN,A.CLIENT_NAME,C.REGIMEN,A.MATERIAL_BARCODE,A.MATERIAL_DESCRIPTION,
'0',A.QUANTITY_UNITS AS SALIDA
FROM
[wms].OP_WMS_TRANS A
LEFT JOIN [wms].OP_WMS_LICENSES B ON A.LICENSE_ID=B.LICENSE_ID
LEFT JOIN [wms].OP_WMS_POLIZA_HEADER C ON A.CODIGO_POLIZA=C.CODIGO_POLIZA AND B.REGIMEN=C.WAREHOUSE_REGIMEN
LEFT JOIN [wms].OP_WMS_MATERIALS D on A.MATERIAL_BARCODE= D.ALTERNATE_BARCODE
WHERE MATERIAL_NAME =ISNULL(@MATERIAL_NAME,MATERIAL_NAME) 
AND MATERIAL_ID=isnull(@MATERIAL_ID,MATERIAL_ID)
AND CLIENT_NAME =ISNULL(@CLIENT_NAME,CLIENT_NAME)
and B.REGIMEN=@REGIMEN/*    */AND/**/(A.TRANS_DESCRIPTION LIKE 'TRA%' OR A.TRANS_DESCRIPTION LIKE 'DES%')
AND   TRANS_DATE  BETWEEN cast(@FECINI  + ' 00:00:00.000' as DATE) AND  cast(@FECFIN +' 23:59:59.999' as DATE)
     
END