
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [wms].[OP_WMS_SP_AUDIT_DISPATCH_START] 
	@pCOUNTING_METHOD	VARCHAR(10),
	@pCODIGO_POLIZA		VARCHAR(50),
	@pCONTENEDOR		VARCHAR(50),
	@pLOGIN_ID			VARCHAR(25),
	@pCREATED_AUDIT_ID	NUMERIC(18,0) OUTPUT,
	@pResult			varchar(250) OUTPUT
AS
BEGIN
	BEGIN TRY
	BEGIN
	
	IF EXISTS(SELECT 1 FROM 
				[wms].OP_WMS_AUDIT_DISPATCH_CONTROL 
				WHERE STATUS = 'CREATED' AND 
				LAST_UPDATED_BY	=	@pLOGIN_ID AND
				CODIGO_POLIZA	=	@pCODIGO_POLIZA	) BEGIN
				
				SELECT @pCREATED_AUDIT_ID = (SELECT ISNULL(AUDIT_ID,0)  FROM 
						[wms].OP_WMS_AUDIT_DISPATCH_CONTROL 
						WHERE STATUS = 'CREATED' AND 
						LAST_UPDATED_BY	=	@pLOGIN_ID AND
						CODIGO_POLIZA	=	@pCODIGO_POLIZA	)
				
				IF @@ERROR = 0	SELECT	@pResult	= 'OK'
				ELSE			SELECT	@pResult	= 'OP_WMS_SP_AUDIT_DISPATCH_START(0):'+ERROR_MESSAGE()
				
		
	END
	ELSE
		BEGIN
	
			INSERT INTO [wms].[OP_WMS_AUDIT_DISPATCH_CONTROL]
				   ([CODIGO_POLIZA]
				   ,[COUNTING_METHOD]
				   ,[STATUS]
				   ,[LAST_UPDATED]
				   ,[LAST_UPDATED_BY],NUMERO_ORDEN)
			 VALUES
				   (@pCODIGO_POLIZA
				   ,@pCOUNTING_METHOD
				   ,'CREATED'
				   ,CURRENT_TIMESTAMP
				   ,@pLOGIN_ID, ISNULL((SELECT TOP 1 A.NUMERO_ORDEN FROM [wms].OP_WMS_POLIZA_HEADER A WHERE A.CODIGO_POLIZA = @pCODIGO_POLIZA),'N/A'))

			SELECT @pCREATED_AUDIT_ID = IDENT_CURRENT('wms.OP_WMS_AUDIT_DISPATCH_CONTROL')
			SELECT @pCREATED_AUDIT_ID = MAX(AUDIT_ID) FROM [wms].[OP_WMS_AUDIT_DISPATCH_CONTROL]
							   
				   
			IF @@ERROR = 0 BEGIN
				SELECT	@pResult	= 'OK'
			END
			ELSE
				SELECT	@pResult	= 'OP_WMS_SP_AUDIT_DISPATCH_START(1):'+ERROR_MESSAGE()
			END
		END
	END TRY
	BEGIN CATCH
		SELECT	@pResult	= 'OP_WMS_SP_AUDIT_DISPATCH_START(2):'+ERROR_MESSAGE()
	END CATCH
END