CREATE PROCEDURE [wms].[OP_WMS_SP_UPDATE_TYPE_CHANGE]	
	@TYPE_CHARGE_ID INT,
	@CHARGE varchar(100),	
	@DESCRIPTION varchar(250),
	@WAREHOUSE_WEATHER varchar(60),
	@REGIMEN varchar(25),
	@COMMENT varchar(200),
	@DAY_TRIP VARCHAR(40),
	@SERVICE_CODE varchar(25),
	@TO_MOVIL NUMERIC(18,0),
	@pResult varchar(250) OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON;	
	BEGIN TRAN
		BEGIN
			UPDATE [wms].OP_WMS_TYPE_CHARGE SET
			  CHARGE = @CHARGE
			, [DESCRIPTION] = @DESCRIPTION
			, WAREHOUSE_WEATHER = @WAREHOUSE_WEATHER
			, REGIMEN = @REGIMEN
			, COMMENT = @COMMENT
			, DAY_TRIP = @DAY_TRIP
			, SERVICE_CODE = @SERVICE_CODE
			, TO_MOVIL = @TO_MOVIL
			WHERE TYPE_CHARGE_ID = @TYPE_CHARGE_ID					   
		END	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN
	END
	ELSE
		BEGIN
			ROLLBACK TRAN
			SELECT	@pResult	= ERROR_MESSAGE()
		END
		
END