


CREATE PROCEDURE [wms].[OP_WMS_SP_DELETE_PASS_DETAIL_BY_POLIZA]
	@PASS_ID NUMERIC(18,0),
	@CODE_POLIZA VARCHAR(15),	
	@PRESULT VARCHAR(4000) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			
			DELETE [wms].OP_WMS3PL_POLIZA_X_PASS
			WHERE PASS_ID = @PASS_ID
			AND CODE_POLIZA = @CODE_POLIZA		
			
		COMMIT TRAN
		
		SELECT @PRESULT = 'OK';
	END TRY
	
	BEGIN CATCH
		ROLLBACK TRAN;
		SELECT @PRESULT = ERROR_MESSAGE()
	END CATCH
END