
CREATE PROCEDURE [wms].[sp_OP_WMS3PL_SECURITY_CHECKPOINT]
@CHECKPOINT_ID int = NULL OUTPUT,
@DOC_ID numeric(18,0),
@ISPASS numeric(1),
@UPDATED_BY varchar(25)
AS
--declaramos las variables a utilizar
DECLARE @retCode int
DECLARE @CLIENT_CODE varchar(25)
DECLARE @CLIENT_NAME varchar(200)
DECLARE @ENTRY_DATETIME datetime
DECLARE @EXIT_DATETIME datetime
DECLARE @CODIGO_POLIZA varchar(15)
DECLARE @TIPO_DOC int

IF NOT EXISTS(SELECT * FROM [wms].OP_WMS3PL_SECURITY_CHECKPOINT WHERE CHECKPOINT_ID = @CHECKPOINT_ID)
	BEGIN
	---DETERMINAMOS QUE TIPO DE DOCUMENTO NOS ESCANEARON BUSCANDO EN LAS POSIBLES TABLAS
	IF @ISPASS = 1
		BEGIN
			SELECT @CLIENT_CODE = CLIENT_CODE FROM [wms].OP_WMS3PL_PASSES
			
			SET @EXIT_DATETIME = GETDATE()
		END
	ELSE
		BEGIN
			SELECT @CODIGO_POLIZA = CODIGO_POLIZA,@CLIENT_CODE =  CLIENT_CODE FROM [wms].OP_WMS_POLIZA_HEADER
			
			SET @ENTRY_DATETIME = GETDATE()
		END
		
		SELECT @CLIENT_NAME = CLIENT_NAME FROM [wms].OP_WMS_VIEW_CLIENTS WHERE CLIENT_CODE = @CLIENT_CODE COLLATE DATABASE_DEFAULT
		
		BEGIN TRANSACTION
			INSERT INTO [wms].OP_WMS3PL_SECURITY_CHECKPOINT (DOC_ID,CODIGO_POLIZA,CLIENT_CODE,CLIENT_NAME,
						PASS_ID,ENTRY_DATETIME,EXIT_DATETIME)
			VALUES (@DOC_ID,@CODIGO_POLIZA,@CLIENT_CODE,@CLIENT_NAME,
					@DOC_ID,@ENTRY_DATETIME,@EXIT_DATETIME)
			SET @CHECKPOINT_ID = SCOPE_IDENTITY()
			IF @@ERROR <> 0
				BEGIN
					ROLLBACK TRANSACTION
					SELECT @retCode = 0
					RETURN @retCode
				END
			ELSE
				BEGIN
					COMMIT TRANSACTION
					SELECT @retCode = 1
					RETURN @retCode
				END
		END
ELSE
	BEGIN
		---DETERMINAMOS QUE TIPO DE DOCUMENTO NOS ESCANEARON BUSCANDO EN LAS POSIBLES TABLAS
		IF @ISPASS = 1
			BEGIN
				SELECT @CLIENT_CODE = CLIENT_CODE FROM [wms].OP_WMS3PL_PASSES WHERE PASS_ID = @DOC_ID
			
			END
		ELSE
			BEGIN
				SELECT @CODIGO_POLIZA = CODIGO_POLIZA,@CLIENT_CODE =  CLIENT_CODE FROM [wms].OP_WMS_POLIZA_HEADER
			
			END
			SELECT @CLIENT_NAME = CLIENT_NAME FROM [wms].OP_WMS_VIEW_CLIENTS WHERE CLIENT_CODE = @CLIENT_CODE COLLATE DATABASE_DEFAULT
			
			BEGIN TRANSACTION
			UPDATE [wms].OP_WMS3PL_SECURITY_CHECKPOINT
			SET DOC_ID = @DOC_ID
			  ,CODIGO_POLIZA = @CODIGO_POLIZA
			  ,CLIENT_CODE = @CLIENT_CODE
			  ,CLIENT_NAME = @CLIENT_NAME
			  ,ENTRY_DATETIME = @ENTRY_DATETIME
			  ,EXIT_DATETIME = @EXIT_DATETIME
			  ,PASS_ID = @DOC_ID
			WHERE CHECKPOINT_ID = @CHECKPOINT_ID
			IF @@ERROR <> 0
				BEGIN
					ROLLBACK TRANSACTION
					SELECT @retCode = 0
					RETURN @retCode
				END
			ELSE
				BEGIN
					COMMIT TRANSACTION
					SELECT @retCode = 2
					RETURN @retCode
				END

	END