-- =============================================
-- Autor:				        rudi.garcia
-- Fecha de Creacion: 	07-07-2016 Sprint ζ
-- Description:			    Se agrego los campos de rectificacion

-- Modificación: pablo.aguilar
-- Fecha de Modificación: 2017-08-22 Nexus@CommandAndConquer
-- Description:	 Se agrega que en el update si el parámetro no trae valor no lo actualize si no deje el mismo.   

-- Modificacion 10/9/2017 @ Reborn-Team Sprint Drache
					-- diego.as
				-- Se ajusta SP para que valide si el numero de poliza que se esta enviando ya existe en la BD y en base a esto decida, si existe emitir un error indicando que la poliza ya existe, si no existe permitir grabar y/o actualizar

-- Autor:				    henry.rodriguez
-- Fecha de Creacion: 		19/Dic/2019 G-Force@Napoles-Swift
-- Description:			    Se agrega codigo de ticket para la poliza.

/*
-- Ejemplo de Ejecucion:
			declare @p1 int
set @p1=443156
exec [wms].sp_OP_WMS_POLIZA_HEADER @DOC_ID=@p1 output,@NUMERO_ORDEN='',@ADUANA_ENTRADA_SALIDA='',@NUMERO_DUA='',@FECHA_ACEPTACION_DMY='',@ADUANA_DESPACHO_DESTINO='',@REGIMEN='',@CLASE='',@PAIS_PROCEDENCIA='',@NATURALEZA_TRANS='',@DEPOSITO_FISCAL_ZF='',@MODO=0,@FECHA_LLEGADA='2017-08-21 12:57:33',@TIPO_CAMBIO=0,@TOTAL_VALOR_ADUANA=0,@TOTAL_NUMERO_LINEAS=0,@TOTAL_BULTOS=0,@TOTAL_PESO_BRUTO_KG=0,@TOTAL_FOB_USD=0,@TOTAL_FLETE_USD=0,@TOTAL_SEGURO_USD=0,@TOTAL_OTROS_USD=0,@NUMERO_SAT='',@TIPO_IMPORTADOR='',@ID_TRIB_IMPORTADOR='',@PAIS_IMPORTADOR='',@RAZON_SOCIAL_IMPORTADOR='',@DOMICILIO_IMPORTADOR='',@TIPO_REPRESENTANTE='',@ID_TRIB_REPRESENTANTE='',@PAIS_REPRESENTANTE='',@TIPO_DECLARANTE_REPRESENTANTE='',@RAZON_SOCIAL_REPRESENTANTE='',@DOMICILIO_REPRESENTANTE='',@TIPO_CONTENEDOR=0,@NUMERO_CONTENEDOR='',@ENTIDAD_CONTENEDOR='',@NUMERO_MARCHAMO_CONTENEDOR='',@TOTAL_LIQUIDAR=0,@TOTAL_OTROS=0,@TOTAL_GENERAL=0,@CODIGO_POLIZA='443156',@LAST_UPDATED_BY='PABS',@LAST_UPDATED='2017-08-22 10:29:36',@STATUS='COSTED',@CLIENT_CODE='arium',@WAREHOUSE_REGIMEN='GENERAL',@FECHA_DOCUMENTO='2017-08-21 12:57:33',@ACUERDO_COMERCIAL='12',@TIPO='INGRESO',@POLIZAASEGURADA='205010',@POLIZAASSIGNEDTO='ACAMACHO',@TRANSLATION='NO'
select @p1
*/
-- =============================================
CREATE PROCEDURE [wms].[sp_OP_WMS_POLIZA_HEADER]
	@DOC_ID INT = NULL OUTPUT
	,@NUMERO_ORDEN VARCHAR(25)
	,@ADUANA_ENTRADA_SALIDA VARCHAR(25)
	,@NUMERO_DUA VARCHAR(50)
	,@FECHA_ACEPTACION_DMY VARCHAR(25)
	,@ADUANA_DESPACHO_DESTINO VARCHAR(25)
	,@REGIMEN VARCHAR(15)
	,@CLASE VARCHAR(5)
	,@PAIS_PROCEDENCIA VARCHAR(6)
	,@NATURALEZA_TRANS VARCHAR(5)
	,@DEPOSITO_FISCAL_ZF VARCHAR(15)
	,@MODO NUMERIC(18 ,0)
	,@FECHA_LLEGADA DATETIME
	,@TIPO_CAMBIO NUMERIC(18 ,5)
	,@TOTAL_VALOR_ADUANA NUMERIC(18 ,2)
	,@TOTAL_NUMERO_LINEAS NUMERIC(18 ,0)
	,@TOTAL_BULTOS NUMERIC(18 ,0)
	,@TOTAL_PESO_BRUTO_KG NUMERIC(18 ,2)
	,@TOTAL_FOB_USD NUMERIC(18 ,2)
	,@TOTAL_FLETE_USD NUMERIC(18 ,2)
	,@TOTAL_SEGURO_USD NUMERIC(18 ,2)
	,@TOTAL_OTROS_USD NUMERIC(18 ,2)
	,@NUMERO_SAT VARCHAR(25)
	,@TIPO_IMPORTADOR VARCHAR(5)
	,@ID_TRIB_IMPORTADOR VARCHAR(25)
	,@PAIS_IMPORTADOR VARCHAR(5)
	,@RAZON_SOCIAL_IMPORTADOR VARCHAR(250)
	,@DOMICILIO_IMPORTADOR VARCHAR(250)
	,@TIPO_REPRESENTANTE VARCHAR(5)
	,@ID_TRIB_REPRESENTANTE VARCHAR(5)
	,@PAIS_REPRESENTANTE VARCHAR(5)
	,@TIPO_DECLARANTE_REPRESENTANTE VARCHAR(5)
	,@RAZON_SOCIAL_REPRESENTANTE VARCHAR(250)
	,@DOMICILIO_REPRESENTANTE VARCHAR(250)
	,@TIPO_CONTENEDOR NUMERIC(18 ,0)
	,@NUMERO_CONTENEDOR VARCHAR(50)
	,@ENTIDAD_CONTENEDOR VARCHAR(5)
	,@NUMERO_MARCHAMO_CONTENEDOR VARCHAR(50)
	,@TOTAL_LIQUIDAR NUMERIC(18 ,2)
	,@TOTAL_OTROS NUMERIC(18 ,2)
	,@TOTAL_GENERAL NUMERIC(18 ,2)
	,@CODIGO_POLIZA VARCHAR(15)
	,@LAST_UPDATED_BY VARCHAR(25)
	,@LAST_UPDATED DATETIME
	,@STATUS VARCHAR(15)
	,@CLIENT_CODE VARCHAR(25)
	,@WAREHOUSE_REGIMEN VARCHAR(15)
	,@FECHA_DOCUMENTO DATETIME
	,@ACUERDO_COMERCIAL VARCHAR(50)
	,@TIPO VARCHAR(25) = 'INGRESO'
	,@POLIZAASEGURADA VARCHAR(25)
	,@POLIZAASSIGNEDTO VARCHAR(25)
	,@TRANSLATION VARCHAR(10)
	,@TICKET_NUMBER BIGINT = NULL
AS --declaramos las variables a utilizar
	DECLARE	@retCode INT;

	IF NOT EXISTS ( SELECT
						*
					FROM
						[wms].[OP_WMS_POLIZA_HEADER]
					WHERE
						[DOC_ID] = @DOC_ID )
	BEGIN
		IF (
			SELECT TOP 1
				1
			FROM
				[wms].[OP_WMS_POLIZA_HEADER]
			WHERE
				[CODIGO_POLIZA] = @CODIGO_POLIZA
			) IS NULL
		BEGIN

			BEGIN TRANSACTION;
			INSERT	INTO [wms].[OP_WMS_POLIZA_HEADER]
					(
						[NUMERO_ORDEN]
						,[ADUANA_ENTRADA_SALIDA]
						,[NUMERO_DUA]
						,[FECHA_ACEPTACION_DMY]
						,[ADUANA_DESPACHO_DESTINO]
						,[REGIMEN]
						,[CLASE]
						,[PAIS_PROCEDENCIA]
						,[NATURALEZA_TRANS]
						,[DEPOSITO_FISCAL_ZF]
						,[MODO]
						,[FECHA_LLEGADA]
						,[TIPO_CAMBIO]
						,[TOTAL_VALOR_ADUANA]
						,[TOTAL_NUMERO_LINEAS]
						,[TOTAL_BULTOS]
						,[TOTAL_PESO_BRUTO_KG]
						,[TOTAL_FOB_USD]
						,[TOTAL_FLETE_USD]
						,[TOTAL_SEGURO_USD]
						,[TOTAL_OTROS_USD]
						,[NUMERO_SAT]
						,[TIPO_IMPORTADOR]
						,[ID_TRIB_IMPORTADOR]
						,[PAIS_IMPORTADOR]
						,[RAZON_SOCIAL_IMPORTADOR]
						,[DOMICILIO_IMPORTADOR]
						,[TIPO_REPRESENTANTE]
						,[ID_TRIB_REPRESENTANTE]
						,[PAIS_REPRESENTANTE]
						,[TIPO_DECLARANTE_REPRESENTANTE]
						,[RAZON_SOCIAL_REPRESENTANTE]
						,[DOMICILIO_REPRESENTANTE]
						,[TIPO_CONTENEDOR]
						,[NUMERO_CONTENEDOR]
						,[ENTIDAD_CONTENEDOR]
						,[NUMERO_MARCHAMO_CONTENEDOR]
						,[TOTAL_LIQUIDAR]
						,[TOTAL_OTROS]
						,[TOTAL_GENERAL]
						,[CODIGO_POLIZA]
						,[LAST_UPDATED_BY]
						,[LAST_UPDATED]
						,[STATUS]
						,[CLIENT_CODE]
						,[WAREHOUSE_REGIMEN]
						,[FECHA_DOCUMENTO]
						,[ACUERDO_COMERCIAL]
						,[TIPO]
						,[POLIZA_ASEGURADA]
						,[POLIZA_ASSIGNEDTO]
						,[TRANSLATION]
					)
			VALUES
					(
						@NUMERO_ORDEN
						,@ADUANA_ENTRADA_SALIDA
						,@NUMERO_DUA
						,@FECHA_ACEPTACION_DMY
						,@ADUANA_DESPACHO_DESTINO
						,@REGIMEN
						,@CLASE
						,@PAIS_PROCEDENCIA
						,@NATURALEZA_TRANS
						,@DEPOSITO_FISCAL_ZF
						,@MODO
						,@FECHA_LLEGADA
						,@TIPO_CAMBIO
						,@TOTAL_VALOR_ADUANA
						,@TOTAL_NUMERO_LINEAS
						,@TOTAL_BULTOS
						,@TOTAL_PESO_BRUTO_KG
						,@TOTAL_FOB_USD
						,@TOTAL_FLETE_USD
						,@TOTAL_SEGURO_USD
						,@TOTAL_OTROS_USD
						,@NUMERO_SAT
						,@TIPO_IMPORTADOR
						,@ID_TRIB_IMPORTADOR
						,@PAIS_IMPORTADOR
						,@RAZON_SOCIAL_IMPORTADOR
						,@DOMICILIO_IMPORTADOR
						,@TIPO_REPRESENTANTE
						,@ID_TRIB_REPRESENTANTE
						,@PAIS_REPRESENTANTE
						,@TIPO_DECLARANTE_REPRESENTANTE
						,@RAZON_SOCIAL_REPRESENTANTE
						,@DOMICILIO_REPRESENTANTE
						,@TIPO_CONTENEDOR
						,@NUMERO_CONTENEDOR
						,@ENTIDAD_CONTENEDOR
						,@NUMERO_MARCHAMO_CONTENEDOR
						,@TOTAL_LIQUIDAR
						,@TOTAL_OTROS
						,@TOTAL_GENERAL
						,@CODIGO_POLIZA
						,@LAST_UPDATED_BY
						,@LAST_UPDATED
						,@STATUS
						,@CLIENT_CODE
						,@WAREHOUSE_REGIMEN
						,@FECHA_DOCUMENTO
						,@ACUERDO_COMERCIAL
						,@TIPO
						,@POLIZAASEGURADA
						,@POLIZAASSIGNEDTO
						,@TRANSLATION
					);
			SET @DOC_ID = SCOPE_IDENTITY();

			IF @CODIGO_POLIZA = '0'
			BEGIN
				UPDATE
					[wms].[OP_WMS_POLIZA_HEADER]
				SET	
					[CODIGO_POLIZA] = @DOC_ID
				WHERE
					[DOC_ID] = @DOC_ID;
			END;

        ---------------------------------------------------------------------------------
        -- ASOCIAMOS LA POLIZA AL TICKET
        ---------------------------------------------------------------------------------

			IF @TICKET_NUMBER IS NOT NULL
			BEGIN
				UPDATE [wms].[OP_WMS_TICKETS]
				SET [POLIZA_DOC_ID] = @DOC_ID,
					[STATUS] = 'ASSOCIATED'
				WHERE [TICKET_NUMBER] = @TICKET_NUMBER;
			END;

		END;
		ELSE
		BEGIN
			SELECT
				@retCode = 4; --YA EXISTE EL CODIGO DE POLIZA
			RETURN @retCode;
		END;
		IF @@ERROR <> 0
		BEGIN
			ROLLBACK TRANSACTION;
			SELECT
				@retCode = 0;
			RETURN @retCode;
		END;
		ELSE
		BEGIN
			COMMIT TRANSACTION;
			SELECT
				@retCode = 1;
			RETURN @retCode;
		END;
	END;
	ELSE
	BEGIN
		IF (
			SELECT TOP 1
				1
			FROM
				[wms].[OP_WMS_POLIZA_HEADER]
			WHERE
				[CODIGO_POLIZA] = @CODIGO_POLIZA
			) = 1
		BEGIN
			BEGIN TRANSACTION;
			UPDATE
				[wms].[OP_WMS_POLIZA_HEADER]
			SET	
				[NUMERO_ORDEN] = CASE	WHEN @NUMERO_ORDEN IS NULL
											OR @NUMERO_ORDEN = ''
									THEN [NUMERO_ORDEN]
									ELSE @NUMERO_ORDEN
								END
				,[ADUANA_ENTRADA_SALIDA] = CASE	WHEN @ADUANA_ENTRADA_SALIDA IS NULL
														OR @ADUANA_ENTRADA_SALIDA = ''
												THEN [ADUANA_ENTRADA_SALIDA]
												ELSE @ADUANA_ENTRADA_SALIDA
											END
				,[NUMERO_DUA] = CASE	WHEN @NUMERO_DUA IS NULL
											OR @NUMERO_DUA = '' THEN [NUMERO_DUA]
									ELSE @NUMERO_DUA
								END
				,[FECHA_ACEPTACION_DMY] = CASE	WHEN @FECHA_ACEPTACION_DMY IS NULL
														OR @FECHA_ACEPTACION_DMY = ''
												THEN [FECHA_ACEPTACION_DMY]
												ELSE @FECHA_ACEPTACION_DMY
										END
				,[ADUANA_DESPACHO_DESTINO] = CASE	WHEN @ADUANA_DESPACHO_DESTINO IS NULL
														OR @ADUANA_DESPACHO_DESTINO = ''
												THEN [ADUANA_DESPACHO_DESTINO]
												ELSE @ADUANA_DESPACHO_DESTINO
											END
				,[REGIMEN] = CASE	WHEN @REGIMEN IS NULL
										OR @REGIMEN = '' THEN [REGIMEN]
								ELSE @REGIMEN
							END
				,[CLASE] = CASE	WHEN @CLASE IS NULL
										OR @CLASE = '' THEN [CLASE]
								ELSE @CLASE
							END
				,[PAIS_PROCEDENCIA] = CASE	WHEN @PAIS_PROCEDENCIA IS NULL
													OR @PAIS_PROCEDENCIA = ''
											THEN [PAIS_PROCEDENCIA]
											ELSE @PAIS_PROCEDENCIA
									END
				,[NATURALEZA_TRANS] = CASE	WHEN @NATURALEZA_TRANS IS NULL
													OR @NATURALEZA_TRANS = ''
											THEN [NATURALEZA_TRANS]
											ELSE @NATURALEZA_TRANS
									END
				,[DEPOSITO_FISCAL_ZF] = CASE	WHEN @DEPOSITO_FISCAL_ZF IS NULL
													OR @DEPOSITO_FISCAL_ZF = ''
											THEN [DEPOSITO_FISCAL_ZF]
											ELSE @DEPOSITO_FISCAL_ZF
										END
				,[MODO] = CASE	WHEN @MODO IS NULL
										OR @MODO = 0 THEN [MODO]
								ELSE @MODO
						END
				,[FECHA_LLEGADA] = CASE	WHEN @FECHA_LLEGADA IS NULL
										THEN [FECHA_LLEGADA]
										ELSE @FECHA_LLEGADA
									END
				,[TIPO_CAMBIO] = CASE	WHEN @TIPO_CAMBIO IS NULL
											OR @TIPO_CAMBIO = 0 THEN [TIPO_CAMBIO]
									ELSE @TIPO_CAMBIO
								END
				,[TOTAL_VALOR_ADUANA] = CASE	WHEN @TOTAL_VALOR_ADUANA IS NULL
													OR @TOTAL_VALOR_ADUANA = 0
											THEN [TOTAL_VALOR_ADUANA]
											ELSE @TOTAL_VALOR_ADUANA
										END
				,[TOTAL_NUMERO_LINEAS] = CASE	WHEN @TOTAL_NUMERO_LINEAS IS NULL
													OR @TOTAL_NUMERO_LINEAS = 0
											THEN [TOTAL_NUMERO_LINEAS]
											ELSE @TOTAL_NUMERO_LINEAS
										END
				,[TOTAL_BULTOS] = CASE	WHEN @TOTAL_BULTOS IS NULL
												OR @TOTAL_BULTOS = 0
										THEN [TOTAL_BULTOS]
										ELSE @TOTAL_BULTOS
								END
				,[TOTAL_PESO_BRUTO_KG] = CASE	WHEN @TOTAL_PESO_BRUTO_KG IS NULL
													OR @TOTAL_PESO_BRUTO_KG = 0
											THEN [TOTAL_PESO_BRUTO_KG]
											ELSE @TOTAL_PESO_BRUTO_KG
										END
				,[TOTAL_FOB_USD] = CASE	WHEN @TOTAL_FOB_USD IS NULL
												OR @TOTAL_FOB_USD = 0
										THEN [TOTAL_FOB_USD]
										ELSE @TOTAL_FOB_USD
									END
				,[TOTAL_FLETE_USD] = CASE	WHEN @TOTAL_FLETE_USD IS NULL
												OR @TOTAL_FLETE_USD = 0
										THEN [TOTAL_FLETE_USD]
										ELSE @TOTAL_FLETE_USD
									END
				,[TOTAL_SEGURO_USD] = CASE	WHEN @TOTAL_SEGURO_USD IS NULL
													OR @TOTAL_SEGURO_USD = 0
											THEN [TOTAL_SEGURO_USD]
											ELSE @TOTAL_SEGURO_USD
									END
				,[TOTAL_OTROS_USD] = CASE	WHEN @TOTAL_OTROS_USD IS NULL
												OR @TOTAL_OTROS_USD = 0
										THEN [TOTAL_OTROS_USD]
										ELSE @TOTAL_OTROS_USD
									END
				,[NUMERO_SAT] = CASE	WHEN @NUMERO_SAT IS NULL
											OR @NUMERO_SAT = '' THEN [NUMERO_SAT]
									ELSE @NUMERO_SAT
								END
				,[TIPO_IMPORTADOR] = CASE	WHEN @TIPO_IMPORTADOR IS NULL
												OR @TIPO_IMPORTADOR = ''
										THEN [TIPO_IMPORTADOR]
										ELSE @TIPO_IMPORTADOR
									END
				,[ID_TRIB_IMPORTADOR] = CASE	WHEN @ID_TRIB_IMPORTADOR IS NULL
													OR @ID_TRIB_IMPORTADOR = ''
											THEN [ID_TRIB_IMPORTADOR]
											ELSE @ID_TRIB_IMPORTADOR
										END
				,[PAIS_IMPORTADOR] = CASE	WHEN @PAIS_IMPORTADOR IS NULL
												OR @PAIS_IMPORTADOR = ''
										THEN [PAIS_IMPORTADOR]
										ELSE @PAIS_IMPORTADOR
									END
				,[RAZON_SOCIAL_IMPORTADOR] = CASE	WHEN @RAZON_SOCIAL_IMPORTADOR IS NULL
														OR @RAZON_SOCIAL_IMPORTADOR = ''
												THEN [RAZON_SOCIAL_IMPORTADOR]
												ELSE @RAZON_SOCIAL_IMPORTADOR
											END
				,[DOMICILIO_IMPORTADOR] = CASE	WHEN @DOMICILIO_IMPORTADOR IS NULL
														OR @DOMICILIO_IMPORTADOR = ''
												THEN [DOMICILIO_IMPORTADOR]
												ELSE @DOMICILIO_IMPORTADOR
										END
				,[TIPO_REPRESENTANTE] = CASE	WHEN @TIPO_REPRESENTANTE IS NULL
													OR @TIPO_REPRESENTANTE = ''
											THEN [TIPO_REPRESENTANTE]
											ELSE @TIPO_REPRESENTANTE
										END
				,[ID_TRIB_REPRESENTANTE] = CASE	WHEN @ID_TRIB_REPRESENTANTE IS NULL
														OR @ID_TRIB_REPRESENTANTE = ''
												THEN [ID_TRIB_REPRESENTANTE]
												ELSE @ID_TRIB_REPRESENTANTE
											END
				,[PAIS_REPRESENTANTE] = CASE	WHEN @PAIS_REPRESENTANTE IS NULL
													OR @PAIS_REPRESENTANTE = ''
											THEN [PAIS_REPRESENTANTE]
											ELSE @PAIS_REPRESENTANTE
										END
				,[TIPO_DECLARANTE_REPRESENTANTE] = CASE	WHEN @TIPO_DECLARANTE_REPRESENTANTE IS NULL
																OR @TIPO_DECLARANTE_REPRESENTANTE = ''
														THEN [TIPO_DECLARANTE_REPRESENTANTE]
														ELSE @TIPO_DECLARANTE_REPRESENTANTE
													END
				,[RAZON_SOCIAL_REPRESENTANTE] = CASE	WHEN @RAZON_SOCIAL_REPRESENTANTE IS NULL
															OR @RAZON_SOCIAL_REPRESENTANTE = ''
													THEN [RAZON_SOCIAL_REPRESENTANTE]
													ELSE @RAZON_SOCIAL_REPRESENTANTE
												END
				,[DOMICILIO_REPRESENTANTE] = CASE	WHEN @DOMICILIO_REPRESENTANTE IS NULL
														OR @DOMICILIO_REPRESENTANTE = ''
												THEN [DOMICILIO_REPRESENTANTE]
												ELSE @DOMICILIO_REPRESENTANTE
											END
				,[TIPO_CONTENEDOR] = CASE	WHEN @TIPO_CONTENEDOR IS NULL
												OR @TIPO_CONTENEDOR = 0
										THEN [TIPO_CONTENEDOR]
										ELSE @TIPO_CONTENEDOR
									END
				,[NUMERO_CONTENEDOR] = CASE	WHEN @NUMERO_CONTENEDOR IS NULL
													OR @NUMERO_CONTENEDOR = ''
											THEN [NUMERO_CONTENEDOR]
											ELSE @NUMERO_CONTENEDOR
										END
				,[ENTIDAD_CONTENEDOR] = CASE	WHEN @ENTIDAD_CONTENEDOR IS NULL
													OR @ENTIDAD_CONTENEDOR = ''
											THEN [ENTIDAD_CONTENEDOR]
											ELSE @ENTIDAD_CONTENEDOR
										END
				,[NUMERO_MARCHAMO_CONTENEDOR] = CASE	WHEN @NUMERO_MARCHAMO_CONTENEDOR IS NULL
															OR @NUMERO_MARCHAMO_CONTENEDOR = ''
													THEN [NUMERO_MARCHAMO_CONTENEDOR]
													ELSE @NUMERO_MARCHAMO_CONTENEDOR
												END
				,[TOTAL_LIQUIDAR] = CASE	WHEN @TOTAL_LIQUIDAR IS NULL
												OR @TOTAL_LIQUIDAR = 0
										THEN [TOTAL_LIQUIDAR]
										ELSE @TOTAL_LIQUIDAR
									END
				,[TOTAL_OTROS] = CASE	WHEN @TOTAL_OTROS IS NULL
											OR @TOTAL_OTROS = 0 THEN [TOTAL_OTROS]
									ELSE @TOTAL_OTROS
								END
				,[TOTAL_GENERAL] = CASE	WHEN @TOTAL_GENERAL IS NULL
												OR @TOTAL_GENERAL = 0
										THEN [TOTAL_GENERAL]
										ELSE @TOTAL_GENERAL
									END
				,[CODIGO_POLIZA] = CASE	WHEN @CODIGO_POLIZA IS NULL
												OR @CODIGO_POLIZA = ''
										THEN [CODIGO_POLIZA]
										ELSE @CODIGO_POLIZA
									END
				,[LAST_UPDATED_BY] = CASE	WHEN @LAST_UPDATED_BY IS NULL
												OR @LAST_UPDATED_BY = ''
										THEN [LAST_UPDATED_BY]
										ELSE @LAST_UPDATED_BY
									END
				,[LAST_UPDATED] = CASE	WHEN @LAST_UPDATED IS NULL
										THEN [LAST_UPDATED]
										ELSE @LAST_UPDATED
								END
				,[STATUS] = CASE	WHEN @STATUS IS NULL
											OR @STATUS = '' THEN [STATUS]
									ELSE @STATUS
							END
				,[CLIENT_CODE] = CASE	WHEN @CLIENT_CODE IS NULL
											OR @CLIENT_CODE = ''
									THEN [CLIENT_CODE]
									ELSE @CLIENT_CODE
								END
				,[WAREHOUSE_REGIMEN] = CASE	WHEN @WAREHOUSE_REGIMEN IS NULL
													OR @WAREHOUSE_REGIMEN = ''
											THEN [WAREHOUSE_REGIMEN]
											ELSE @WAREHOUSE_REGIMEN
										END
				,[FECHA_DOCUMENTO] = CASE	WHEN @FECHA_DOCUMENTO IS NULL
										THEN [FECHA_DOCUMENTO]
										ELSE @FECHA_DOCUMENTO
									END
				,[ACUERDO_COMERCIAL] = CASE	WHEN @ACUERDO_COMERCIAL IS NULL
													OR @ACUERDO_COMERCIAL = ''
											THEN [ACUERDO_COMERCIAL]
											ELSE @ACUERDO_COMERCIAL
										END
				,[TIPO] = CASE	WHEN @TIPO IS NULL
										OR @TIPO = '' THEN [TIPO]
								ELSE @TIPO
						END
				,[POLIZA_ASEGURADA] = CASE	WHEN @POLIZAASEGURADA IS NULL
													OR @POLIZAASEGURADA = ''
											THEN [POLIZA_ASEGURADA]
											ELSE @POLIZAASEGURADA
									END
				,[POLIZA_ASSIGNEDTO] = CASE	WHEN @POLIZAASSIGNEDTO IS NULL
													OR @POLIZAASSIGNEDTO = ''
											THEN [POLIZA_ASSIGNEDTO]
											ELSE @POLIZAASSIGNEDTO
										END
				,[TRANSLATION] = CASE	WHEN @TRANSLATION IS NULL
											OR @TRANSLATION = ''
									THEN [TRANSLATION]
									ELSE @TRANSLATION
								END
			WHERE
				[DOC_ID] = @DOC_ID;

			IF @CODIGO_POLIZA = '0'
			BEGIN
				UPDATE
					[wms].[OP_WMS_POLIZA_HEADER]
				SET	
					[CODIGO_POLIZA] = @DOC_ID
				WHERE
					[DOC_ID] = @DOC_ID;
			END;

		END;
		ELSE
		BEGIN 
			SELECT
				@retCode = 5; --EL CODIGO DE POLIZA NO COINCIDE CON EL INGRESADO EN LA BD
			RETURN @retCode;
		END;

		IF @@ERROR <> 0
		BEGIN
			ROLLBACK TRANSACTION;
			SELECT
				@retCode = 0;
			RETURN @retCode;
		END;
		ELSE
		BEGIN
			COMMIT TRANSACTION;
			SELECT
				@retCode = 2;
			RETURN @retCode;
		END;

	END;