


CREATE PROCEDURE [wms].[sp_OP_WMS3PL_POLIZAS_X_PASSES]
@PASS_ID         NUMERIC(18,0),
@CODIGO_POLIZA   VARCHAR(15), 
@DOC_ID          NUMERIC(18,0),
@LAST_UPDATED_BY VARCHAR(25),
@NUMERO_ORDEN    VARCHAR(50),
@NUMERO_DUA      VARCHAR(50),
@CLIENT_NAME     VARCHAR(250),
@CLIENT_CODE     VARCHAR(25),
@PRESULT         VARCHAR(4000) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS (SELECT * FROM [wms].OP_WMS3PL_POLIZAS_X_PASSES WHERE PASS_ID = @PASS_ID AND CODIGO_POLIZA = @CODIGO_POLIZA)
				BEGIN
					INSERT INTO [wms].OP_WMS3PL_POLIZAS_X_PASSES
					   (PASS_ID, CODIGO_POLIZA, DOC_ID, LAST_UPDATED_BY, LAST_UPDATED, NUMERO_ORDEN, NUMERO_DUA, CLIENT_NAME, CLIENT_CODE)
					VALUES
					   (@PASS_ID, @CODIGO_POLIZA, @DOC_ID, @LAST_UPDATED_BY, GETDATE(), @NUMERO_ORDEN, @NUMERO_DUA, @CLIENT_NAME, @CLIENT_CODE);
					   
				END
			ELSE
				BEGIN
					DELETE [wms].OP_WMS3PL_POLIZAS_X_PASSES WHERE PASS_ID = @PASS_ID AND CODIGO_POLIZA = @CODIGO_POLIZA;
					
					INSERT INTO [wms].OP_WMS3PL_POLIZAS_X_PASSES
					   (PASS_ID, CODIGO_POLIZA, DOC_ID, LAST_UPDATED_BY, LAST_UPDATED, NUMERO_ORDEN, NUMERO_DUA, CLIENT_NAME, CLIENT_CODE)
					VALUES
					   (@PASS_ID, @CODIGO_POLIZA, @DOC_ID, @LAST_UPDATED_BY, GETDATE(), @NUMERO_ORDEN, @NUMERO_DUA, @CLIENT_NAME, @CLIENT_CODE);
					   
				END
				
		COMMIT TRAN
		SELECT @PRESULT = 'OK';
	END TRY
	
	BEGIN CATCH
		ROLLBACK TRAN;
		SELECT @PRESULT = ERROR_MESSAGE()
	END CATCH
END