-- =============================================
-- Autor:	        hector.gonzalez
-- Fecha de Creacion: 	2017-07-09 @ Team REBORN - Sprint 
-- Description:	        

/*
-- Ejemplo de Ejecucion:
			EXEC  
*/
-- =============================================
CREATE PROCEDURE [SONDA].SONDA_SP_SET_DAILY_ROUTE_INFO
AS
BEGIN
  SET NOCOUNT ON;
  --

  BEGIN TRY


    DECLARE @LOG_ID INT

           ,@CODE_ROUTE VARCHAR(50)
           ,@LOG_DATETIME DATETIME
           ,@SEVERITY_CODE INT
           ,@LOGIN VARCHAR(50)
           ,@ID INT
           ,@TRANSACTIONS INT
           ,@MIN_BATT DECIMAL
           ,@MAX_BATT DECIMAL
           ,@TOTAL_AMOUNT MONEY
           ,@FIRST_TXN DATETIME
           ,@LAST_TXN DATETIME
           ,@LOG_DATETIME_START DATETIME

    INSERT INTO [SONDA].[SONDA_SERVER_ERROR_LOG] ([LOG_DATETIME], [CODE_ROUTE], [LOGIN], [SOURCE_ERROR], [DOC_RESOLUTION], [DOC_SERIE], [DOC_NUM], [MESSAGE_ERROR], [SEVERITY_CODE], [TYPE])
      VALUES (GETDATE(), '[SONDA_SP_SET_DAILY_ROUTE_INFO]', 'ADMIN', 'INICIO', 'N/A', 'N/A', 0, 'INICIO DE RESUMEN DE RUTA', -50, 'INFO');

    DELETE [SONDA].[SONDA_WEEKLY_SUMMARIE]
    WHERE CAST([ROUTE_STARTED_AT] AS DATE) = CAST(GETDATE() AS DATE)

    SELECT
      [SL].[LOG_ID]
     ,[SL].[LOG_DATETIME]
     ,[SL].[CODE_ROUTE]
     ,[SL].[LOGIN]
     ,[SL].[SEVERITY_CODE] INTO #SERVER_LOG
    FROM [SONDA].[SONDA_SERVER_ERROR_LOG] [SL]
    WHERE CAST([SL].[LOG_DATETIME] AS DATE) = CAST(GETDATE() AS DATE)
    AND [SL].[SEVERITY_CODE] IN (-100, -90)
    ORDER BY [SL].[LOG_DATETIME], [SL].[CODE_ROUTE]

    WHILE EXISTS (SELECT TOP 1
          1
        FROM #SERVER_LOG)
    BEGIN

      SELECT TOP 1
        @LOG_ID = [sl].[LOG_ID]
       ,@CODE_ROUTE = [sl].[CODE_ROUTE]
       ,@LOG_DATETIME = [sl].[LOG_DATETIME]
       ,@SEVERITY_CODE = [sl].[SEVERITY_CODE]
       ,@LOGIN = [sl].[LOGIN]
      FROM [#SERVER_LOG] [sl]
      ORDER BY [sl].[LOG_DATETIME], [sl].[CODE_ROUTE]

      IF @SEVERITY_CODE = -90
      BEGIN
        INSERT INTO [SONDA].[SONDA_WEEKLY_SUMMARIE] ([CODE_ROUTE], [ROUTE_STARTED_AT], [ROUTE_FINISHED_AT], [TRANSACTIONS], [MIN_BATT], [MAX_BATT], [TOTAL_AMOUNT], [FIRST_TXN], [LAST_TXN], [WEEK_NUMBER], [LOGIN_ID])
          VALUES (@CODE_ROUTE, @LOG_DATETIME, GETDATE(), 0, 0, 0, 0, GETDATE(), GETDATE(), DATEPART(WEEK, GETDATE()), @LOGIN);
        SET @ID = SCOPE_IDENTITY()
        SET @LOG_DATETIME_START = @LOG_DATETIME
      END

      IF @SEVERITY_CODE = -100
      BEGIN
        SELECT
          @TRANSACTIONS = COUNT(1)
         ,@MIN_BATT = MIN([SH].[DEVICE_BATTERY_FACTOR])
         ,@MAX_BATT = MAX([SH].[DEVICE_BATTERY_FACTOR])
         ,@TOTAL_AMOUNT = SUM([SH].[TOTAL_AMOUNT])
         ,@FIRST_TXN = MIN([SH].[POSTED_DATETIME])
         ,@LAST_TXN = MAX([SH].[POSTED_DATETIME])
        FROM [SONDA].[SONDA_SALES_ORDER_HEADER] [SH]
        WHERE [SH].[POS_TERMINAL] = @CODE_ROUTE
        AND [SH].[POSTED_DATETIME] BETWEEN @LOG_DATETIME_START AND @LOG_DATETIME
        AND [SH].[IS_VOID] = 0


        UPDATE [SONDA].[SONDA_WEEKLY_SUMMARIE]
        SET [ROUTE_FINISHED_AT] = @LOG_DATETIME
           ,[TRANSACTIONS] = @TRANSACTIONS
           ,[MIN_BATT] = @MIN_BATT
           ,[MAX_BATT] = @MAX_BATT
           ,[TOTAL_AMOUNT] = @TOTAL_AMOUNT
           ,[FIRST_TXN] = @FIRST_TXN
           ,[LAST_TXN] = @LAST_TXN
        WHERE [SUMMARIZE_ID] = @ID
      END

      DELETE #SERVER_LOG
      WHERE [LOG_ID] = @LOG_ID

    END

    INSERT INTO [SONDA].[SONDA_SERVER_ERROR_LOG] ([LOG_DATETIME], [CODE_ROUTE], [LOGIN], [SOURCE_ERROR], [DOC_RESOLUTION], [DOC_SERIE], [DOC_NUM], [MESSAGE_ERROR], [SEVERITY_CODE], [TYPE])
      VALUES (GETDATE(), '[SONDA_SP_SET_DAILY_ROUTE_INFO]', 'ADMIN', 'FIN', 'N/A', 'N/A', 0, 'FIN DE RESUMEN DE RUTA', -55, 'INFO');
  END TRY

  BEGIN CATCH

    INSERT INTO [SONDA].[SONDA_SERVER_ERROR_LOG] ([LOG_DATETIME], [CODE_ROUTE], [LOGIN], [SOURCE_ERROR], [DOC_RESOLUTION], [DOC_SERIE], [DOC_NUM], [MESSAGE_ERROR], [SEVERITY_CODE], [TYPE])
      VALUES (GETDATE(), '[SONDA_SP_SET_DAILY_ROUTE_INFO]', 'ADMIN', '[SONDA_SP_SET_DAILY_ROUTE_INFO]', 'N/A', 'N/A', 0, ERROR_MESSAGE(), -55, 'INFO');
    PRINT 'ERROR [SONDA_SP_SET_DAILY_ROUTE_INFO]: ' + ERROR_MESSAGE()
  END CATCH
END
