-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	10-02-2016
-- Description:			Cancela el invetario recervado por una orden de venta cancelada

/*
-- Ejemplo de Ejecucion:
				DECLARE 
					@CODE_WAREHOUSE VARCHAR(50) = 'C002'
					,@CODE_SKU VARCHAR(50) = '100017'
					,@QTY INT = 1
				--
				SELECT * FROM [SONDA].[SONDA_IS_COMITED_BY_WAREHOUSE] WHERE CODE_WAREHOUSE = @CODE_WAREHOUSE AND CODE_SKU = @CODE_SKU
				--
				EXEC [SONDA].[SONDA_SP_VOID_COMMITED_INVENTORY]
					@CODE_WAREHOUSE = @CODE_WAREHOUSE
					,@CODE_SKU = @CODE_SKU
					,@QTY = @QTY
				--
				SELECT * FROM [SONDA].[SONDA_IS_COMITED_BY_WAREHOUSE] WHERE CODE_WAREHOUSE = @CODE_WAREHOUSE AND CODE_SKU = @CODE_SKU
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SONDA_SP_VOID_COMMITED_INVENTORY]
(	
	@CODE_WAREHOUSE VARCHAR(50)
	,@CODE_SKU VARCHAR(50)
	,@QTY INT
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRAN
	BEGIN TRY
		UPDATE [SONDA].[SONDA_IS_COMITED_BY_WAREHOUSE]
		SET IS_COMITED = (IS_COMITED - @QTY)
		WHERE CODE_WAREHOUSE = @CODE_WAREHOUSE
			AND CODE_SKU = @CODE_SKU

		PRINT 'COMMIT'
		--
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		DECLARE @ERROR VARCHAR(1000) = ERROR_MESSAGE()
		PRINT 'CATCH: ' + @ERROR
		RAISERROR (@ERROR,16,1)
	END CATCH
END
