-- =============================================
-- Autor:				diego.as
-- Fecha de Creacion: 	10/24/2017 @ Reborn-TEAM Sprint Drache  
-- Description:			SP que obtiene los registros de la tabla OP_WMS_MANIFEST_DETAIL de la BD de 3PL

/*
-- Ejemplo de Ejecucion:
				EXEC [SONDA].[SONDA_SP_GET_3PL_MANIFEST_DETAIL_BY_MANIFEST_HEADER_ID]
				@MANIFEST_HEADER_ID = 1108
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SONDA_SP_GET_3PL_MANIFEST_DETAIL_BY_MANIFEST_HEADER_ID](
	@MANIFEST_HEADER_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE @DATABASE_NAME VARCHAR(50)
	,@SCHEMA_NAME VARCHAR(50)
	,@QUERY VARCHAR(MAX);

	SELECT @DATABASE_NAME = ES.[DATABASE_NAME], @SCHEMA_NAME = ES.[SCHEMA_NAME] FROM [SONDA].[SWIFT_SETUP_EXTERNAL_SOURCE] AS ES WHERE ES.[EXTERNAL_SOURCE_ID] > 0;

	SELECT @QUERY = '
		SELECT [MANIFEST_DETAIL_ID]
			,[MANIFEST_HEADER_ID]
			,[CODE_ROUTE]
			,[CLIENT_CODE]
			,[WAVE_PICKING_ID]
			,[MATERIAL_ID]
			,[QTY]
			,[STATUS]
			,[LAST_UPDATE]
			,[LAST_UPDATE_BY]
			,[ADDRESS_CUSTOMER]
			,[CLIENT_NAME]
			,[LINE_NUM]
			,[PICKING_DEMAND_HEADER_ID]
			,[STATE_CODE]
			,[CERTIFICATION_TYPE] 
		FROM ' + @DATABASE_NAME + '.' + @SCHEMA_NAME + '.[OP_WMS_MANIFEST_DETAIL] 
		WHERE [MANIFEST_HEADER_ID] = ' + CAST(@MANIFEST_HEADER_ID AS VARCHAR) + '
		AND MANIFEST_DETAIL_ID > 0;
	';
	EXEC(@QUERY);

END
