-- =============================================
-- Autor:				diego.as
-- Fecha de Creacion: 	10/24/2017 @ Drache-TEAM Sprint Drache  
-- Description:			SP que obtiene los registros de la tabla OP_WMS_MANIFEST_HEADER de la BD de 3PL

/*
-- Ejemplo de Ejecucion:
				EXEC [SONDA].[SONDA_SP_GET_3PL_MANIFEST_HEADER_BY_MANIFEST_HEADER_ID]
				@MANIFEST_HEADER_ID = 1108
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SONDA_SP_GET_3PL_MANIFEST_HEADER_BY_MANIFEST_HEADER_ID](
	@MANIFEST_HEADER_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE @DATABASE_NAME VARCHAR(50)
	,@SCHEMA_NAME VARCHAR(50)
	,@QUERY VARCHAR(MAX);

	SELECT @DATABASE_NAME = ES.[DATABASE_NAME], @SCHEMA_NAME = ES.[SCHEMA_NAME] FROM [SONDA].[SWIFT_SETUP_EXTERNAL_SOURCE] AS ES WHERE ES.[EXTERNAL_SOURCE_ID] > 0;

	SELECT @QUERY = '
		SELECT [MANIFEST_HEADER_ID]
			,[DRIVER]
			,[VEHICLE]
			,[DISTRIBUTION_CENTER]
			,[CREATED_DATE]
			,[STATUS]
			,[LAST_UPDATE]
			,[LAST_UPDATE_BY]
			,[MANIFEST_TYPE]
			,[TRANSFER_REQUEST_ID]
			,[PLATE_NUMBER] 
		FROM ' + @DATABASE_NAME + '.' + @SCHEMA_NAME + '.[OP_WMS_MANIFEST_HEADER] 
		WHERE [MANIFEST_HEADER_ID] = ' + CAST(@MANIFEST_HEADER_ID AS VARCHAR) + ';
	';
	EXEC(@QUERY);

END
