-- =============================================
-- Autor:				Christian Hernandez 
-- Fecha de Creacion: 	07-13-2018
-- Description:			Selecciona las facturas vencidas detalladamente
--                      
/*
-- Ejemplo de Ejecucion:				
--exec [SONDA].[SWFT_SP_GET_RECEIPTS_BY_ROUTE] '2017-05-31 17:13:17.000','2019-05-31 17:13:17.000','gerente@SONDA'
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SWFT_SP_GET_RECEIPTS_BY_ROUTE]
	@DATEFROM AS DATETIME
	,@DATETO AS DATETIME
	,@USER_ID AS VARCHAR(50)
AS
	SELECT
		DISTINCT
		[SIH].[ID]
		,[SIH].[DOC_NUM]
		,[SIH].[DOC_SERIE]
		,[SIH].[CODE_CUSTOMER]
		,[SC].[NAME_CUSTOMER]
		,[SIH].[CREATED_DATE]
		,[SIH].[PAYMENT_AMOUNT]
		,[SIH].[CODE_ROUTE]
		,[SIH].[LOGIN_ID] AS [CODE_SELLER]
		,[US].[NAME_USER]
		,[SUP].[NAME_USER] AS [USER]
		,CASE [SIH].[IS_POSTED_ERP]
			WHEN 1 THEN 'ENVIADO'
			ELSE 'NO ENVIADO'
			END AS [STATE]
		,[SIH].[POSTED_DATETIME_ERP] AS [POSTED_DATE]
		,[SIH].[POSTING_RESPONSE] AS [SENDRESPONSE]
		,[ST].[NAME_TEAM]
	FROM
		[SONDA].[SONDA_OVERDUE_INVOICE_PAYMENT_HEADER] [SIH]
	INNER JOIN [SONDA].[USERS] [US]
	ON	[US].[SELLER_ROUTE] = [SIH].[CODE_ROUTE]
	INNER JOIN [SONDA].[SWIFT_VIEW_ALL_COSTUMER] [SC]
	ON	[SC].[CODE_CUSTOMER] = [SIH].[CODE_CUSTOMER]
	INNER JOIN [SONDA].[SWIFT_USER_BY_TEAM] [SUT]
	ON	[US].[CORRELATIVE] = [SUT].[USER_ID]
	INNER JOIN [SONDA].[SWIFT_TEAM] [ST]
	ON	[ST].[TEAM_ID] = [SUT].[TEAM_ID]
	INNER JOIN [SONDA].[USERS] [SUP]
	ON	[SUP].[CORRELATIVE] = [ST].[SUPERVISOR]
	WHERE
		[SIH].[CREATED_DATE] BETWEEN @DATEFROM AND @DATETO
		AND [SUP].[LOGIN] = @USER_ID;
