CREATE PROCEDURE [SONDA].[SWIFT_SP_DELETELOCATION]
@CODE_LOCATION VARCHAR(50),
@pResult varchar(250) OUTPUT
AS
/*DECLARE @CODE_LOCATION VARCHAR(50)
SET @CODE_LOCATION = (SELECT CODE_LOCATION FROM [SONDA].SWIFT_LOCATIONS WHERE LOCATION = @LOCATION)*/
IF ((SELECT COUNT(A.LOCATION) FROM [SONDA].SWIFT_CYCLE_COUNT_DETAIL AS A WHERE A.LOCATION = @CODE_LOCATION )
--+ (SELECT COUNT(B.LOCATION) FROM [SONDA].SWIFT_HIST_INVENTORY AS B WHERE B.LOCATION = @LOCATION  )
+ (SELECT COUNT(C.LOCATION) FROM [SONDA].SWIFT_INVENTORY AS C WHERE C.LOCATION = @CODE_LOCATION  )

) = 0
BEGIN 
	DELETE FROM [SONDA].SWIFT_LOCATIONS WHERE CODE_LOCATION=@CODE_LOCATION
	SELECT @pResult = ''
END
ELSE
	BEGIN
		SELECT @pResult = 'El dato no se puede eliminar debido a que está siendo utilizado'
	END
