CREATE PROC [SONDA].[SWIFT_SP_DELETE_ALL_TRANSFER_DETAIL]
	@TRANSFER_ID NUMERIC(18,0)	
AS

BEGIN TRY
BEGIN	
	BEGIN TRAN t1
		BEGIN		

			DELETE [SONDA].[SWIFT_TRANSFER_DETAIL]
			WHERE [TRANSFER_ID] = @TRANSFER_ID
						
		END
	IF @@error = 0 BEGIN
		COMMIT TRAN t1
		SELECT  1 as Resultado , 'Proceso Exitoso' Mensaje ,  0 Codigo
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo
	END
END
END TRY
BEGIN CATCH
     ROLLBACK TRAN t1
	 SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo 
END CATCH
