-- Autor:				pedro.loukota
-- Fecha de Creacion: 	11-11-2015
-- Description:			Obtiene Bodegas no asignadas a clientes
/*
-- Ejemplo de Ejecucion:				
				select [SONDA].SWIFT_SP_GET_NOTASIGN_WAREHOUSES
*/
CREATE PROCEDURE [SONDA].SWIFT_SP_GET_NOTASIGN_WAREHOUSES

@LOGIN varchar(50)
AS
BEGIN

DECLARE @TOTALASSIGN INT 

SELECT @TOTALASSIGN =  COUNT(*) FROM [SONDA].[SWIFT_WAREHOUSES] 
	
			WHERE [SONDA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [SONDA].[USERS] WHERE [SONDA].[USERS].CORRELATIVE != @LOGIN OR [SONDA].[USERS].LOGIN = NULL)


IF @TOTALASSIGN > 0
 BEGIN

		    SELECT  * FROM [SONDA].[SWIFT_WAREHOUSES] 
	
			WHERE [SONDA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [SONDA].[USERS] WHERE [SONDA].[USERS].CORRELATIVE != @LOGIN OR [SONDA].[USERS].LOGIN = NULL)

		UNION	
			SELECT  * FROM [SONDA].[SWIFT_WAREHOUSES] 
	
			WHERE [SONDA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE]  IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [SONDA].[USERS] WHERE [SONDA].[USERS].CORRELATIVE = @LOGIN)
			
		ORDER BY [SONDA].[SWIFT_WAREHOUSES].[DESCRIPTION_WAREHOUSE]			
			
END


IF @TOTALASSIGN = 0
 BEGIN

		    SELECT  * FROM [SONDA].[SWIFT_WAREHOUSES] 
	
END


END
