CREATE PROCEDURE [SONDA].[SWIFT_GET_INCOME_PANEL_RECEPTION]
@INCOMEHEADER INT
AS
SELECT DISTINCT
	  A.TYPE_RECEPTION AS NAME_CLASSIFICATION
	, COALESCE(B.NAME_PROVIDER,C.NAME_CUSTOMER) AS 'NAME_PROVIDER'
	, A.CODE_USER AS [LOGIN]
	, A.REFERENCE
	, A.DOC_SAP_RECEPTION
	, A.COMMENTS
	, D.SCANNING_STATUS
	, D.ALLOW_STORAGE_ON_DIFF
	, D.TASK_ID
FROM
	[SONDA].SWIFT_RECEPTION_HEADER AS A
	left JOIN [SONDA].SWIFT_VIEW_ALL_PROVIDERS B on(A.CODE_PROVIDER = B.CODE_PROVIDER)
	left JOIN [SONDA].SWIFT_VIEW_ALL_COSTUMER C on(A.CODE_PROVIDER = C.CODE_CUSTOMER)
	left JOIN [SONDA].SWIFT_TASKS D on(A.RECEPTION_HEADER = D.RECEPTION_NUMBER)
WHERE A.RECEPTION_HEADER = @INCOMEHEADER
--AND A.CODE_USER = D.LOGIN
------

SELECT DISTINCT z.RECEPTION_DETAIL, Z.CODE_SKU,Z.DESCRIPTION_SKU,Z.EXPECTED,( Z.SCANNED - Z.EXPECTED) AS DIFFERENCE,
CASE 
            WHEN (Z.SCANNED - Z.EXPECTED) > 0
               THEN 'DE MAS'
            WHEN (Z.SCANNED - Z.EXPECTED) < 0
               THEN 'DE MENOS'
            WHEN (Z.SCANNED - Z.EXPECTED) = 0
               THEN 'ESPERADO'
END AS RESULT,
--ABS( Z.SCANNED - Z.EXPECTED) AS DIFFERENCE,

z.SCANNED 
FROM [SONDA].SWIFT_RECEPTION_DETAIL Z
WHERE Z.RECEPTION_HEADER=@INCOMEHEADER
