CREATE PROCEDURE [SONDA].SWIFT_SP_GET_NEXT_PICKING_LOCATION
    @pSKU		VARCHAR(50),
    @pResult	varchar(250) OUTPUT
AS
    DECLARE @lSKU	VARCHAR(75);
    DECLARE @lHANDLE_BATCH INT;
      
	SELECT @lSKU = ISNULL((SELECT CODE_SKU FROM SWIFT_VIEW_SKU  WHERE (CODE_SKU = UPPER(@pSKU) OR BARCODE_SKU = UPPER(@pSKU))),'N/F')
	SELECT @lHANDLE_BATCH	= ISNULL((SELECT Z.HANDLE_BATCH			FROM SWIFT_VIEW_SKU Z WHERE Z.CODE_SKU = @lSKU),0)

	IF (@lSKU='N/F') BEGIN
		SELECT @pResult = 'ERROR, SKU '+ @pSKU + ' NO EXISTE';
		return -10;
	END


	BEGIN TRY
		IF(@lHANDLE_BATCH = 1) BEGIN
		
			SELECT TOP 1 
				A.WAREHOUSE, 
				A.LOCATION, 
				(SELECT 
					VALUE_TEXT_CLASSIFICATION 
					FROM 
						SWIFT_CLASSIFICATION 
					WHERE 
						CLASSIFICATION = C.CLASSIFICATION_LOCATION AND 
						GROUP_CLASSIFICATION = 'LOCATION') AS LOCATION_TYPE,
				A.BATCH_ID
				--B.EXP_DATE
			FROM 
				SWIFT_INVENTORY A,
				--SWIFT_BATCHES B,
				SWIFT_LOCATIONS C
			WHERE 
				A.SKU = @lSKU AND
				--B.BATCH_ID = A.BATCH_ID AND
				C.CODE_LOCATION = A.LOCATION AND 
				C.ALLOW_PICKING = 'SI'
			ORDER BY 
				--B.EXP_DATE,
				A.ON_HAND
				
			SELECT @pResult = 'OK';
			
			RETURN 0;
			
		END ELSE BEGIN
		
			SELECT TOP 1 
				A.WAREHOUSE, 
				A.LOCATION, 
				(SELECT 
					VALUE_TEXT_CLASSIFICATION 
					FROM 
						SWIFT_CLASSIFICATION 
					WHERE 
						CLASSIFICATION = B.CLASSIFICATION_LOCATION AND 
						GROUP_CLASSIFICATION = 'LOCATION') AS LOCATION_TYPE
			FROM 
				SWIFT_INVENTORY A, 
				SWIFT_LOCATIONS B
			WHERE 
				A.SKU = @lSKU AND A.ON_HAND > 0 AND
				B.CODE_LOCATION = A.LOCATION AND 
				B.ALLOW_PICKING = 'SI'
				
			ORDER BY 
				A.ON_HAND
				
			SELECT @pResult = 'OK';
			
			RETURN 0;
		END

	END TRY
		BEGIN CATCH
			SELECT	@pResult	= ERROR_MESSAGE()
			RETURN -9997
	END CATCH
