CREATE PROC [SONDA].[SWIFT_SP_INSERT_CUSTOMER_BY_PAYMENT_METHOD]
	@CODE_PAYMENT VARCHAR(25)	
	, @CODE_CUSTOMER VARCHAR(50)
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			DELETE [SONDA].[SWIFT_PAYMENT_METHODS_BY_CUSTOMER]
			WHERE [CODE_CUSTOMER] = @CODE_CUSTOMER AND CODE_PAYMENT = @CODE_PAYMENT;
		
			INSERT INTO [SONDA].[SWIFT_PAYMENT_METHODS_BY_CUSTOMER](
				[CODE_PAYMENT]
				, [CODE_CUSTOMER]
			)
			VALUES(
				@CODE_PAYMENT
				, @CODE_CUSTOMER
			);
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
