CREATE PROC [SONDA].[SWIFT_SP_GET_PAYMENT_METHOD_CUSTOMER_AVAILABLE]
	@CODE_PAYMENT VARCHAR(50)
AS
	SELECT *
	FROM [SONDA].SWIFT_VIEW_ALL_COSTUMER C
	WHERE NOT EXISTS(SELECT 1
					FROM [SONDA].[SWIFT_PAYMENT_METHODS_BY_CUSTOMER] PC
					WHERE C.CODE_CUSTOMER = PC.CODE_CUSTOMER
					AND PC.CODE_PAYMENT = @CODE_PAYMENT
	)
