-- =============================================
-- Autor:                rudi.garcia
-- Fecha de Creacion:     18-Sep-2018 @ A-TEAM Sprint G-Force@Jaguar
-- Description:            SP que obtiene los primeros 5 documentos de facturas a pagar
 
/*
-- Ejemplo de Ejecucion:
                EXEC [SONDA].SWIFT_SP_GET_TOP5_INVOICE_PAYMENTS
*/
-- =============================================
CREATE PROCEDURE [SONDA].SWIFT_SP_GET_TOP5_INVOICE_PAYMENTS
AS
BEGIN
  SET NOCOUNT ON;
  --
  DECLARE @SHIPPING_ATTEMPTS VARCHAR(100)
         ,@CASH_ACCOUNT_IN_ERP VARCHAR(100)
         ,@CHECK_ACCOUNT_IN_ERP VARCHAR(100)
         ,@DEPOSIT_ACCOUNT_IN_ERP VARCHAR(100)
         ,@GENERATE_PAYMENT VARCHAR(100) = 'NO';
 
  SELECT
    @SHIPPING_ATTEMPTS = [SONDA].[SWIFT_FN_GET_PARAMETER]('PAYMENT',
    'SHIPPING_ATTEMPTS')
   ,@CASH_ACCOUNT_IN_ERP = [SONDA].[SWIFT_FN_GET_PARAMETER]('PAYMENT',
    'CASH_ACCOUNT_IN_ERP')
   ,@CHECK_ACCOUNT_IN_ERP = [SONDA].[SWIFT_FN_GET_PARAMETER]('PAYMENT',
    'CHECK_ACCOUNT_IN_ERP')
   ,@DEPOSIT_ACCOUNT_IN_ERP = [SONDA].[SWIFT_FN_GET_PARAMETER]('PAYMENT',
    'DEPOSIT_ACCOUNT_IN_ERP')
   ,@GENERATE_PAYMENT = [SONDA].[SWIFT_FN_GET_PARAMETER]('INVOICE',
    'GENERATE_PAYMENT');
 
  SELECT TOP 5
    [IH].[ID] AS [ID]
   ,[IH].[CLIENT_ID] AS [CODE_CUSTOMER]
   ,[IH].[INVOICE_ID] AS [DOC_NUM]
   ,[IH].[CDF_SERIE] AS [DOC_SERIE]
   ,[IH].[INVOICED_DATETIME] AS [POSTED_DATE]
   ,[IH].[POS_TERMINAL] AS [CODE_ROUTE]
   ,[IH].[POSTED_BY] AS [LOGIN_ID]
   ,[IH].[CASH_AMOUNT] AS [PAYMENT_AMOUNT]
   ,'' AS [COMMENT]
   ,[IH].[IS_POSTED_ERP_PAYMENT] AS [IS_POSTED_ERP]
   ,[IH].[POSTED_ERP_PAYMENT] AS [POSTED_DATETIME_ERP]
   ,[IH].[POSTED_RESPONSE_ERP_PAYMENT] AS [POSTING_RESPONSE]
   ,[IH].[ATTEMPTED_WITH_ERROR_PAYMENT] [ATTEMPTED_WITH_ERROR]
   ,[IH].[ERP_REFERENCE] AS [ERP_REFERENCE]
   ,'C' AS DOC_TYPE
   ,@CASH_ACCOUNT_IN_ERP AS CASH_ACCOUNT_IN_ERP
   ,@CHECK_ACCOUNT_IN_ERP AS CHECK_ACCOUNT_IN_ERP
   ,@DEPOSIT_ACCOUNT_IN_ERP AS DEPOSIT_ACCOUNT_IN_ERP
   ,[IH].[CDF_DOCENTRY]
   ,([IH].[CDF_SERIE] + '-' + CAST([IH].[INVOICE_ID] AS VARCHAR(250))) AS U_N_RECIBO
   ,CASE
      WHEN [IH].[CREDIT_AMOUNT] > 0 THEN 0
      ELSE 1
    END AS [FULL_CASH_PAYMENT]
  FROM [SONDA].[SONDA_POS_INVOICE_HEADER] AS [IH]
  WHERE [IH].[IS_POSTED_ERP] = 1 AND [IH].[ID] IN (150,174,187)
  AND [IH].[TOTAL_AMOUNT] <> [IH].[CREDIT_AMOUNT]
  AND [IH].[CASH_AMOUNT] > 0
  AND (@GENERATE_PAYMENT = 'SI'
  OR @GENERATE_PAYMENT = '1')
  AND (ISNULL([IH].[ATTEMPTED_WITH_ERROR_PAYMENT],0) < CAST(@SHIPPING_ATTEMPTS AS INT))
  AND ISNULL([IH].[IS_POSTED_ERP_PAYMENT],0) <> 1
  ORDER BY [IH].[INVOICED_DATETIME] ASC
 
END;
