CREATE PROCEDURE [SONDA].[SWIFT_SP_INSERT_TEMP_HEADER_PICKING]
@CLASSIFICATIONPICKING VARCHAR(50),
@CODECOSTUMER VARCHAR(50),
@CODEOPERATOR VARCHAR(50),
@REFERENCE VARCHAR(50),
@DOC_SAP_RECEPTION VARCHAR(150),
@LASTUPDATEBY VARCHAR(50),
@SCHEDULE_FOR DATE,
@SEQ INT
AS
INSERT INTO SWIFT_TEMP_PICKING_HEADER(CLASSIFICATION_PICKING,CODE_CLIENT,CODE_USER,REFERENCE,DOC_SAP_RECEPTION,LAST_UPDATE_BY,LAST_UPDATE,STATUS,SCHEDULE_FOR,SEQ)
VALUES (@CLASSIFICATIONPICKING,@CODECOSTUMER,@CODEOPERATOR,@REFERENCE,@DOC_SAP_RECEPTION,@LASTUPDATEBY,GETDATE(),'ASSIGNED',@SCHEDULE_FOR,@SEQ)
