-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	6/13/2017 @ A-TEAM Sprint Jibade 
-- Description:			Obtiene los registros de la tabla SWIFT_PROMO_BONUS_BY_MULTIPLE filtrados por PROMO_ID

/*
-- Ejemplo de Ejecucion:
				EXEC [SONDA].[SWIFT_SP_GET_BONUS_FROM_PROMO_OF_BONUS_BY_MULTIPLE]
					@PROMO_ID = 5
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_BONUS_FROM_PROMO_OF_BONUS_BY_MULTIPLE](
	@PROMO_ID INT = NULL	
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	SELECT [PBM].[PROMO_BONUS_BY_MULTIPLE_ID]
			,[PBM].[PROMO_ID]
			,[PBM].[CODE_SKU]
			,[VAS1].[DESCRIPTION_SKU]
			,[PBM].[PACK_UNIT]
			,[PU1].[DESCRIPTION_PACK_UNIT]
			,[PBM].[MULTIPLE]
			,[PBM].[CODE_SKU_BONUS]
			,[VAS2].[DESCRIPTION_SKU] [DESCRIPTION_BONUS_SKU]
			,[PBM].[PACK_UNIT_BONUS] 
			,[PU2].[DESCRIPTION_PACK_UNIT] [DESCRIPTION_PACK_UNIT_BONUS]
			,[PBM].[BONUS_QTY]
	FROM [SONDA].[SWIFT_PROMO_BONUS_BY_MULTIPLE] [PBM]
		INNER JOIN [SONDA].[SWIFT_VIEW_ALL_SKU] [VAS1] ON [VAS1].[CODE_SKU] = [PBM].[CODE_SKU]
		INNER JOIN [SONDA].[SWIFT_VIEW_ALL_SKU] [VAS2] ON [VAS2].[CODE_SKU] = [PBM].[CODE_SKU_BONUS]
		INNER JOIN [SONDA].[SONDA_PACK_UNIT] [PU1] ON [PU1].[PACK_UNIT] = [PBM].[PACK_UNIT]
		INNER JOIN [SONDA].[SONDA_PACK_UNIT] [PU2] ON [PU2].[PACK_UNIT] = [PBM].[PACK_UNIT_BONUS]
	WHERE [PBM].[PROMO_ID] = @PROMO_ID OR @PROMO_ID IS NULL 
END
