CREATE PROCEDURE [SONDA].SWIFT_SP_INSERT_HIST_INVENTORY
AS
  INSERT INTO [SONDA].SWIFT_HIST_INVENTORY
    SELECT
      SERIAL_NUMBER
     ,WAREHOUSE
     ,LOCATION
     ,SKU
     ,SKU_DESCRIPTION
     ,ON_HAND
     ,BATCH_ID
     ,LAST_UPDATE
     ,LAST_UPDATE_BY
     ,PROC_DATE
     ,INV_DATE
     ,COST
     ,TOTAL
    FROM (SELECT
       I.SERIAL_NUMBER
      ,I.WAREHOUSE
      ,I.LOCATION
      ,I.SKU
      ,I.SKU_DESCRIPTION
      ,I.ON_HAND
      ,I.BATCH_ID
      ,I.LAST_UPDATE
      ,I.LAST_UPDATE_BY
      ,I.INVENTORY
      FROM [SONDA].SWIFT_INVENTORY I) T1
    INNER JOIN (SELECT
        A.INVENTORY
       ,GETDATE() AS PROC_DATE
       ,CONVERT(DATE, GETDATE() - 1) AS INV_DATE
       ,B.COST AS 'COST'
       ,(B.COST * A.ON_HAND) AS TOTAL
      FROM [SONDA].SWIFT_INVENTORY AS A
          ,[SONDA].SWIFT_VIEW_ALL_SKU AS B
      WHERE A.SKU = B.CODE_SKU) T2
      ON T1.INVENTORY = T2.INVENTORY
    WHERE T2.INV_DATE NOT IN (SELECT
        INV_DATE
      FROM [SONDA].SWIFT_HIST_INVENTORY
      WHERE INV_DATE = CONVERT(DATE, GETDATE() - 1))
