CREATE PROC [SONDA].[SWIFT_SP_INSERT_COUNT_DETAIL]
@COUNT_ID INT,
@LOCATION VARCHAR(50),
@COUNT_OPERATOR VARCHAR(50),
@COUNT_SKU VARCHAR(50),
@COUNT_SKU_DESCRIPTION VARCHAR(MAX),
@COUNT_BATCH_ID VARCHAR(50)
AS

INSERT into [SONDA].SWIFT_CYCLE_COUNT_DETAIL(COUNT_ID,LOCATION,COUNT_OPERATOR,COUNT_POSTED,COUNT_SKU,COUNT_SKU_DESCRIPTION,COUNT_BATCH_ID,COUNT_STATUS)

VALUES (@COUNT_ID, @LOCATION, @COUNT_OPERATOR, GETDATE(), @COUNT_SKU, @COUNT_SKU_DESCRIPTION, @COUNT_BATCH_ID, 'PENDING')
