CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_CUSTOMER_ASSOCIATE]	
@ID_FREQUENCY INTEGER
AS
	SELECT F.ID_FREQUENCY, C.CODE_CUSTOMER, NAME_CUSTOMER, F.[PRIORITY]
	FROM [SONDA].[SWIFT_FREQUENCY_X_CUSTOMER] AS F  
		INNER JOIN [SONDA].[SWIFT_VIEW_ALL_COSTUMER] AS C ON (F.CODE_CUSTOMER = C.CODE_CUSTOMER)
	WHERE F.ID_FREQUENCY = @ID_FREQUENCY
	ORDER BY F.[PRIORITY]
