-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	12/27/2016 @ A-TEAM Sprint  
-- Description:			Obtiene todas las bodegas que tienen el centro de distribucion @DISTRIBUTION_CENTER_ID

/*
-- Ejemplo de Ejecucion:
				EXEC [SONDA].[SWIFT_SP_GET_WAREHOUSE_ASSOCIATE_BY_DISTRIBUTION_CENTER]
					@DISTRIBUTION_CENTER_ID = 1
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_WAREHOUSE_ASSOCIATE_BY_DISTRIBUTION_CENTER](
	 @DISTRIBUTION_CENTER_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	SELECT 
		[W].[WAREHOUSE]
		,[W].[CODE_WAREHOUSE]
		,[W].[DESCRIPTION_WAREHOUSE]
		,[W].[WEATHER_WAREHOUSE]
		,[W].[STATUS_WAREHOUSE]
		,[W].[LAST_UPDATE]
		,[W].[LAST_UPDATE_BY]
		,[W].[IS_EXTERNAL]
		,[W].[BARCODE_WAREHOUSE]
		,[W].[SHORT_DESCRIPTION_WAREHOUSE]
		,[W].[TYPE_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
		,[W].[ADDRESS_WAREHOUSE]
		,[W].[GPS_WAREHOUSE]
	FROM [SONDA].[SWIFT_WAREHOUSE_X_DISTRIBUTION_CENTER] AS [SWDC] 
		INNER JOIN [SONDA].[SWIFT_WAREHOUSES] [W] ON [W].[CODE_WAREHOUSE] = [SWDC].[CODE_WAREHOUSE]
	WHERE @DISTRIBUTION_CENTER_ID = [SWDC].[DISTRIBUTION_CENTER_ID]

END
