CREATE PROCEDURE [SONDA].[SWIFT_GET_ULTIMATE_VALUE_IN_HEADER]
@HEADER_NUMBER_TEMP INT
AS
DECLARE @HEADERNUMBER INT
--OBTENER EL ULTIMO VALOR
SELECT TOP 1 @HEADERNUMBER  = RECEPTION_HEADER FROM SWIFT_RECEPTION_HEADER ORDER BY RECEPTION_HEADER DESC
print '@HEADERNUMBER' print @HEADERNUMBER
--ACTUALIZAR EL REGISTRO
UPDATE SWIFT_RECEPTION_DETAIL SET RECEPTION_HEADER = @HEADERNUMBER WHERE RECEPTION_HEADER = @HEADER_NUMBER_TEMP
 
 
--select RECEPTION_HEADER FROM [SONDA].SWIFT_RECEPTION_HEADER ORDER BY RECEPTION_HEADER ASC
