CREATE PROCEDURE [SONDA].[SWIFT_SP_DELETECUSTOMER]
@CUSTOMER INT,
@pResult varchar(250) OUTPUT
AS
IF ((SELECT COUNT(A.CODE_CLIENT) FROM [SONDA].SWIFT_PICKING_HEADER AS A WHERE A.CODE_CLIENT =(SELECT CODE_CUSTOMER FROM [SONDA].SWIFT_CUSTOMERS WHERE CUSTOMER =  @CUSTOMER ))
+ (SELECT COUNT(B.COSTUMER_CODE) FROM [SONDA].SWIFT_TASKS AS B WHERE B.COSTUMER_CODE = (SELECT CODE_CUSTOMER FROM [SONDA].SWIFT_CUSTOMERS WHERE CUSTOMER =  @CUSTOMER )  )
--+ (SELECT COUNT(C.COSTUMER_CODE) FROM [SONDA].SWIFT_TXNS AS C WHERE C.COSTUMER_CODE = (SELECT CODE_CUSTOMER FROM [SONDA].SWIFT_CUSTOMERS WHERE CUSTOMER =  @CUSTOMER )  )
+ (SELECT COUNT(D.CODE_CUSTOMER) FROM [SONDA].SWIFT_MANIFEST_DETAIL AS D WHERE D.CODE_CUSTOMER = (SELECT CODE_CUSTOMER FROM [SONDA].SWIFT_CUSTOMERS WHERE CUSTOMER =  @CUSTOMER )  )
) = 0
BEGIN 
	DELETE FROM SWIFT_CUSTOMERS WHERE CUSTOMER=@CUSTOMER
	SELECT @pResult = ''
END
ELSE
	BEGIN
		SELECT @pResult = 'El dato no se puede eliminar debido a que está siendo utilizado'
	END
