create PROCEDURE [SONDA].[SWIFT_SP_INSERT_DETAIL_PICKING]
@PICKINGHEADER INT,
@CODE_SKU VARCHAR(50),
@DISPATCH FLOAT,
@DESCRIPTION_SKU VARCHAR(MAX)
AS
 
DECLARE @PICKINGDETAIL INT
DECLARE @MARCADORSKU INT
SET @MARCADORSKU = 0
DECLARE @CODEDETAIL INT
 
IF EXISTS (SELECT CODE_SKU FROM [SONDA].SWIFT_TEMP_PICKING_DETAIL WHERE CODE_SKU = @CODE_SKU AND PICKING_HEADER = @PICKINGHEADER)
            BEGIN
            SELECT @CODEDETAIL =  PICKING_DETAIL FROM SWIFT_TEMP_PICKING_DETAIL WHERE PICKING_HEADER=@PICKINGHEADER AND CODE_SKU=@CODE_SKU
            UPDATE SWIFT_TEMP_PICKING_DETAIL SET DISPATCH = DISPATCH + @DISPATCH WHERE   PICKING_DETAIL = @CODEDETAIL
print 'entroIf'
            END
ELSE
            BEGIN
  INSERT INTO SWIFT_TEMP_PICKING_DETAIL(PICKING_HEADER,CODE_SKU,DISPATCH,SCANNED,DIFFERENCE,DESCRIPTION_SKU)
            VALUES(@PICKINGHEADER,@CODE_SKU,@DISPATCH,0,0,@DESCRIPTION_SKU)
            print 'entroElse'
            END
           
SELECT  TOP 1 @PICKINGDETAIL =  PICKING_DETAIL FROM SWIFT_TEMP_PICKING_DETAIL ORDER BY PICKING_DETAIL DESC
 
print '@PICKINGDETAIL' print @PICKINGDETAIL
print '@DISPATCH' print @DISPATCH
 
 
UPDATE SWIFT_TEMP_PICKING_DETAIL
SET DIFFERENCE = (SELECT DISPATCH - SCANNED FROM SWIFT_TEMP_PICKING_DETAIL WHERE PICKING_DETAIL=@PICKINGDETAIL)
WHERE PICKING_DETAIL = @PICKINGDETAIL
