CREATE PROCEDURE [SONDA].[SWIFT_SP_DELETEWAREHOUSE]
@CODE_WAREHOUSE VARCHAR(50),
@pResult varchar(250) OUTPUT
AS
IF ((SELECT COUNT(A.WAREHOUSE) FROM [SONDA].SWIFT_INVENTORY AS A WHERE A.WAREHOUSE =  @CODE_WAREHOUSE )
) = 0
BEGIN
	DELETE FROM SWIFT_LOCATIONS WHERE CODE_WAREHOUSE=@CODE_WAREHOUSE
	DELETE FROM SWIFT_WAREHOUSES WHERE CODE_WAREHOUSE=@CODE_WAREHOUSE
	SELECT @pResult = ''
END
ELSE
	BEGIN
		SELECT @pResult = 'El dato no se puede eliminar debido a que está siendo utilizado'
	END

--INVENTORY
