CREATE PROCEDURE [SONDA].[SWIFT_INSERT_IN_TRANSAXION_AND_TASK_PICKING]
AS
DECLARE  @HEADER_NUMBER INT
DECLARE @CLIENT_CODE VARCHAR(25)
DECLARE @CLIENT_NAME VARCHAR(250)
DECLARE @OPERATOR_ID varchar(150)
DECLARE @OPERATOR_NAME VARCHAR(250)
DECLARE @SAP_REFERENCE VARCHAR(150)
DECLARE @REFERENCE VARCHAR(50)
DECLARE @SCHEDULE_FOR DATE
DECLARE @SEQ INT
DECLARE @TASK_COMMENTS VARCHAR(50) 
 
 
 SELECT @TASK_COMMENTS = NAME_CLASSIFICATION FROM SWIFT_CLASSIFICATION WHERE CLASSIFICATION = (SELECT TOP 1 CLASSIFICATION_PICKING FROM SWIFT_PICKING_HEADER ORDER BY PICKING_HEADER DESC)


SELECT TOP 1 @HEADER_NUMBER = PICKING_HEADER FROM SWIFT_PICKING_HEADER ORDER BY PICKING_HEADER DESC
PRINT '@HEADER_NUMBER' PRINT @HEADER_NUMBER
SELECT @CLIENT_CODE = CODE_CLIENT FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@@CLIENT_CODE' PRINT @CLIENT_CODE
SELECT @CLIENT_NAME = NAME_CUSTOMER FROM SWIFT_VIEW_ALL_COSTUMER WHERE CODE_CUSTOMER = @CLIENT_CODE
PRINT '@PROVIER_NAME' PRINT @CLIENT_NAME
SELECT @OPERATOR_ID = CODE_USER FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@OPERATOR_ID' PRINT @OPERATOR_ID
--SELECT @OPERATOR_NAME = NAME_USER FROM USERS WHERE CORRELATIVE = @OPERATOR_ID
--PRINT '@OPERATOR_NAME' PRINT @OPERATOR_NAME
SELECT @REFERENCE = REFERENCE FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@REFERENCE' PRINT @REFERENCE
SELECT @SAP_REFERENCE = DOC_SAP_RECEPTION FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@SAP_REFERENCE' PRINT @SAP_REFERENCE
SELECT @SCHEDULE_FOR = SCHEDULE_FOR FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@SCHEDULE_FOR' PRINT  @SCHEDULE_FOR
SELECT @SEQ = SEQ FROM SWIFT_PICKING_HEADER WHERE PICKING_HEADER = @HEADER_NUMBER
PRINT '@SEQ' PRINT @SEQ
--INSERCION EN TRANSAXION
--INSERT INTO SWIFT_TXNS(REFERENCE_NUMBER,COSTUMER_CODE,COSTUMER_NAME,TXN_TYPE,TXN_DESCRIPTION,TXN_CREATED_STAMP,TXN_OPERATOR_ID,TXN_OPERATOR_NAME,SCHEDULE_FOR,)
--VALUES(@HEADER_NUMBER,@CLIENT_CODE,@CLIENT_NAME,'PICKING','PICKING',GETDATE(),@OPERATOR_ID,@OPERATOR_NAME)
 
--INSERCION EN TASK
INSERT INTO SWIFT_TASKS(TASK_TYPE,TASK_DATE,CREATED_STAMP,ASSIGEND_TO,ASSIGNED_STAMP,COSTUMER_CODE,COSTUMER_NAME,REFERENCE,SAP_REFERENCE,PICKING_NUMBER,SCHEDULE_FOR,TASK_SEQ,ACTION,TASK_COMMENTS,TASK_STATUS,SCANNING_STATUS)
VALUES('PICKING',GETDATE(),GETDATE(),@OPERATOR_ID,GETDATE(),@CLIENT_CODE,@CLIENT_NAME,@REFERENCE,@SAP_REFERENCE,@HEADER_NUMBER,@SCHEDULE_FOR,@SEQ,'PLAY',@TASK_COMMENTS,'ASSIGNED','PENDING')
