CREATE PROC [SONDA].[SWIFT_SP_INSERTVEHICLE]
@CODE_VEHICLE VARCHAR(50),
@PLATE_VEHICLE VARCHAR(50),
@CLASSIFICATION_VEHICLE VARCHAR(50),
@MAXIMUM_WEIGHT FLOAT,
@BRAND VARCHAR(20),
@UNIT VARCHAR(20),
@LAST_UPDATE DATETIME,
@LAST_UPDATE_BY VARCHAR(50)
AS
INSERT INTO SWIFT_VEHICLES (CODE_VEHICLE,PLATE_VEHICLE,CLASSIFICATION_VEHICLE,
MAXIMUM_WEIGHT,BRAND,UNIT,LAST_UPDATE,LAST_UPDATE_BY) VALUES (@CODE_VEHICLE,
@PLATE_VEHICLE,
@CLASSIFICATION_VEHICLE,
@MAXIMUM_WEIGHT,
@BRAND,
@UNIT,
@LAST_UPDATE,
@LAST_UPDATE_BY)
