-- =============================================
-- Author:         rudi.garcia
-- Create date:    19-05-2016
-- Description:    Obtiene las tomas de inventario del cliente por un rango de fecha.

/*
Ejemplo de Ejecucion:
		EXEC [SONDA].[SWIFT_SP_GET_TAKE_INVENTORY_BY_CUSTOMER] @CODE_CUSTUMER = '1000', @DATE_START = '2016-05-19', @DATE_END = '2016-05-20'
				
*/
-- =============================================

CREATE PROCEDURE [SONDA].SWIFT_SP_GET_TAKE_INVENTORY_BY_CUSTOMER
  @CODE_CUSTUMER VARCHAR(50)
  ,@DATE_START DATE
  ,@DATE_END DATE
AS 
  SELECT 
    H.TAKE_INVENTORY_ID
    , H.CLIENT_ID
    , C.NAME_CUSTOMER
    , H.POSTED_DATETIME
    , H.POSTED_BY
    , D.CODE_SKU
    , S.DESCRIPTION_SKU
    , D.CODE_PACK_UNIT
    , D.QTY
    , D.LAST_QTY
  FROM [SONDA].SONDA_TAKE_INVENTORY_DETAIL D
  INNER JOIN [SONDA].SONDA_TAKE_INVENTORY_HEADER H ON (D.TAKE_INVENTORY_ID = H.TAKE_INVENTORY_ID)
  INNER JOIN [SONDA].SWIFT_VIEW_ALL_COSTUMER C ON (H.CLIENT_ID = C.CODE_CUSTOMER)
  INNER JOIN [SONDA].SWIFT_VIEW_ALL_SKU S ON (D.CODE_SKU = S.CODE_SKU)
  WHERE H.CLIENT_ID = @CODE_CUSTUMER
  AND CONVERT(DATE, H.POSTED_DATETIME) BETWEEN @DATE_START AND @DATE_END
