-- =============================================
-- Autor:				diego.as
-- Fecha de Creacion: 	7/26/2017 @ Reborn-TEAM Sprint Bearbeitung
-- Description:			Obtiene los registros de la tabla SWIFT_PROMO_SKU_SALES_BY_MULTIPLE por el PROMO_ID

/*
-- Ejemplo de Ejecucion:
		EXEC [SONDA].[SWIFT_SP_GET_SKU_OF_SALE_BY_MULTIPLE_ASSOCIATED_TO_PROMOTION_OF_SALE_BY_MULTIPLE]
		@PROMO_ID = 9
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_SKU_OF_SALE_BY_MULTIPLE_ASSOCIATED_TO_PROMOTION_OF_SALE_BY_MULTIPLE](
	@PROMO_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	SELECT SBM.[SWIFT_PROMO_SKU_SALES_BY_MULTIPLE_ID]
			,SBM.[PROMO_ID]
			,SBM.[CODE_SKU]
			,[VSKU].[DESCRIPTION_SKU]
			,SBM.[PACK_UNIT]
			,PU.[DESCRIPTION_PACK_UNIT]
			,(CASE WHEN FSKU.[CODE_FAMILY_SKU] IS NULL THEN 'SIN FAMILIA' ELSE FSKU.[CODE_FAMILY_SKU] END) AS  CODE_FAMILY_SKU
			,(CASE WHEN [FSKU].[DESCRIPTION_FAMILY_SKU] IS NULL THEN	'SIN DESCRIPCION' ELSE [FSKU].[DESCRIPTION_FAMILY_SKU] END) AS DESCRIPTION_FAMILY_SKU
			,SBM.[MULTIPLE]
	FROM [SONDA].[SWIFT_PROMO_SKU_SALES_BY_MULTIPLE] SBM
	INNER JOIN [SONDA].[SONDA_PACK_UNIT] AS PU ON(
		SBM.[PACK_UNIT] = PU.[PACK_UNIT]
	)
	INNER JOIN [SONDA].[SWIFT_VIEW_ALL_SKU] VSKU ON(
		SBM.[CODE_SKU] = [VSKU].[CODE_SKU]
	)
	LEFT JOIN [SONDA].[SWIFT_FAMILY_SKU] AS FSKU ON(
		VSKU.[CODE_FAMILY_SKU] = [FSKU].[CODE_FAMILY_SKU]
	)
	WHERE @PROMO_ID = [PROMO_ID]
END
