CREATE PROC [SONDA].[SWIFT_SP_INSERT_PICKING_HEADER_FF]
@CLASSIFICATION_PICKING VARCHAR(50),
@CODE_CLIENT VARCHAR(50),
@CODE_USER VARCHAR(50),
@REFERENCE VARCHAR(50),
@DOC_SAP_RECEPTION VARCHAR(150)
AS
declare @headerid int
declare @table TABLE(ID INT)
BEGIN
INSERT INTO [SONDA].SWIFT_PICKING_HEADER(
	CLASSIFICATION_PICKING,
	CODE_CLIENT,
	CODE_USER,
	REFERENCE,
	DOC_SAP_RECEPTION,
	[STATUS],
	LAST_UPDATE,
	SCHEDULE_FOR,
	SEQ,
	FF,
	FF_STATUS)
VALUES(
	@CLASSIFICATION_PICKING,
	@CODE_CLIENT,
	@CODE_USER,
	@REFERENCE,
	@DOC_SAP_RECEPTION,
	'ASSIGNED',
	GETDATE(),
	GETDATE(),
	2,
	'1',
	'PENDING')
END
BEGIN
	SELECT @headerid = scope_identity() FROM [SONDA].SWIFT_PICKING_HEADER
	INSERT INTO @table (ID) VALUES (@headerid)
	SELECT * FROM @table
	INSERT INTO [SONDA].SWIFT_TASKS (TASK_TYPE,TASK_DATE,SCHEDULE_FOR,CREATED_STAMP,ASSIGEND_TO,ASSIGNED_BY,ASSIGNED_STAMP,PICKING_NUMBER,
	ACTION,TASK_COMMENTS,COSTUMER_NAME,COSTUMER_CODE,TASK_SEQ,TASK_STATUS,REFERENCE,SAP_REFERENCE,SCANNING_STATUS)
	VALUES ('PICKING',GETDATE(),GETDATE(),GETDATE(),@CODE_USER,'SISTEMA',GETDATE(),@headerid,'PLAY'
	,@CLASSIFICATION_PICKING,(SELECT DISTINCT TOP 1 NAME_CUSTOMER FROM [SONDA].SWIFT_VIEW_ALL_COSTUMER WHERE CODE_CUSTOMER = @CODE_CLIENT),@CODE_CLIENT,2,'ASSIGNED',@REFERENCE,@DOC_SAP_RECEPTION,'PENDING')
END
