CREATE PROCEDURE [SONDA].[SWIFT_INSERT_IN_PICKING_DETAIL]
@PICKING_HEADER INT
AS
INSERT INTO [SONDA].SWIFT_PICKING_DETAIL(PICKING_HEADER,CODE_SKU,DESCRIPTION_SKU,DISPATCH,SCANNED,RESULT,LAST_UPDATE,DIFFERENCE)
SELECT PICKING_HEADER,CODE_SKU,DESCRIPTION_SKU,DISPATCH,SCANNED,RESULT,LAST_UPDATE,DIFFERENCE FROM SWIFT_TEMP_PICKING_DETAIL WHERE PICKING_HEADER=@PICKING_HEADER
