CREATE PROC [SONDA].[SWIFT_SP_GET_TASK_PRESALE]
@DATE VARCHAR(150)
AS
SELECT 
	A.COMPLETED_STAMP,
	A.ACCEPTED_STAMP,
	A.TASK_ID,
	A.COSTUMER_CODE AS CUSTOMER_CODE,
	A.COSTUMER_NAME AS CUSTOMER_NAME,
	A.TASK_ADDRESS,
	CASE A.TASK_STATUS
		WHEN 'ASSIGNED' THEN 'Asignada'
		WHEN 'CANCELLED' THEN 'Cancelada'
		WHEN 'ACCEPTED' THEN 'Aceptada'
		WHEN 'COMPLETED' THEN 'Finalizada'
		WHEN 'CLOSED' THEN 'Finalizada'
	END AS TASK_STATUS,
	A.SCHEDULE_FOR,
	CONVERT(TIME,A.VISIT_HOUR) AS VISIT_HOUR,
	A.ASSIGEND_TO AS SELLER,
	--(SELECT DISTINCT SELLER_DEFAULT_CODE FROM [SONDA].SWIFT_VIEW_ALL_COSTUMER WHERE CODE_CUSTOMER = A.COSTUMER_CODE) AS SELLER,
	A.TASK_SEQ,
	A.EXPECTED_GPS,
	A.EMAIL_TO_CONFIRM,
	A.TASK_COMMENTS,
	A.[ACTION],
	CASE 
            WHEN A.TASK_TYPE = 'PRESALE'
               THEN (SELECT ISNULL([VALUE_TEXT_CLASSIFICATION],'Preventa') FROM [SONDA].[SWIFT_CLASSIFICATION] WHERE [NAME_CLASSIFICATION] = 'PRE')
            WHEN A.TASK_TYPE = 'SALE'
               THEN (SELECT ISNULL([VALUE_TEXT_CLASSIFICATION],'Venta Directa') FROM [SONDA].[SWIFT_CLASSIFICATION] WHERE [NAME_CLASSIFICATION] = 'VEN')
			WHEN A.TASK_TYPE = 'DELIVERY'
               THEN 'Entrega'
	END AS TASK_TYPE
FROM 
	[SONDA].SWIFT_TASKS A 
WHERE 
	(A.TASK_TYPE = 'PRESALE' OR A.TASK_TYPE = 'SALE' OR A.TASK_TYPE = 'DELIVERY')
	AND SCHEDULE_FOR = CONVERT(DATE,@DATE)
