CREATE PROCEDURE [SONDA].SWIFT_SP_INSERT_CUSTOMER_FREQUENCY_TASK
AS
BEGIN
declare @columName varchar(10)

declare @CLIENT_CODE varchar(25)
declare @NAME_CLIENT varchar(250)
declare @RELATED_CLIENT_PHONE_1 varchar(25)
DECLARE @USER_ROLE VARCHAR(50)
DECLARE @LAST_DATE_VISITED DATETIME

SELECT @columName = UPPER( DATENAME(WEEKDAY, GETDATE()))
SELECT    TOP 1
	@CLIENT_CODE =  A.CODE_CUSTOMER,
	@NAME_CLIENT = A.NAME_CUSTOMER,
	@RELATED_CLIENT_PHONE_1 = A.PHONE_CUSTOMER ,
	@LAST_DATE_VISITED = B.LAST_DATE_VISITED
FROM  
	[SONDA].SWIFT_VIEW_ALL_COSTUMER  A,
	[SONDA].SWIFT_CUSTOMER_FREQUENCY B
WHERE 
	A.CODE_CUSTOMER = B.CODE_CUSTOMER			
	AND '1' = CASE WHEN @columName = 'MONDAY' THEN B.MONDAY 
				WHEN @columName = 'TUESDAY' THEN B.TUESDAY
				WHEN @columName = 'WEDNESDAY' THEN B.WEDNESDAY
				WHEN @columName = 'THURSDAY' THEN B.THURSDAY
				WHEN @columName = 'FRIDAY' THEN B.FRIDAY
				WHEN @columName = 'SATURDAY' THEN B.SATURDAY
				WHEN @columName = 'SUNDAY' THEN B.SUNDAY
			END
	AND  A.CODE_CUSTOMER NOT IN (SELECT COSTUMER_CODE FROM [SONDA].SWIFT_TASKS WHERE SCHEDULE_FOR = CONVERT(DATE,GETDATE()) AND (TASK_TYPE = 'PRESALE' OR TASK_TYPE = 'SALE') AND TASK_STATUS = 'ASSIGNED')
	AND  CURRENT_TIMESTAMP >= DATEADD(WEEK,CONVERT(INT,B.FREQUENCY_WEEKS), B.LAST_DATE_VISITED)

-------------------------------------------------------------------------------------------------------------------------------------------------------
SET @USER_ROLE = ISNULL((SELECT [USER_TYPE] FROM [SONDA].USERS WHERE RELATED_SELLER = (SELECT SELLER_CODE FROM [SONDA].SWIFT_VIEW_ALL_SELLERS WHERE SELLER_NAME = (SELECT DISTINCT SELLER_DEFAULT_CODE FROM [SONDA].SWIFT_VIEW_ALL_COSTUMER WHERE CODE_CUSTOMER = @CLIENT_CODE))),'NULL')
PRINT @USER_ROLE
PRINT @columName
PRINT @CLIENT_CODE
PRINT @NAME_CLIENT
PRINT @RELATED_CLIENT_PHONE_1

-------------------------------------------------------------------------------------------------------------------------------------------------------
IF (@CLIENT_CODE != 'NULL') BEGIN
--IF (@USER_ROLE = 'PRE' OR @USER_ROLE = 'VEN')
--BEGIN
PRINT 'POR LA INSERCION'
INSERT INTO [SONDA].SWIFT_TASKS (
	COSTUMER_CODE,
	COSTUMER_NAME,
	CUSTOMER_PHONE,
	SCHEDULE_FOR,
	TASK_ADDRESS,
	ASSIGEND_TO,
	TASK_STATUS,
	TASK_SEQ,
	EXPECTED_GPS,
	EMAIL_TO_CONFIRM,
	--POSTED_GPS,
	TASK_COMMENTS,
	TASK_TYPE,
	VISIT_HOUR,
	CREATED_STAMP,
	ASSIGNED_STAMP,
	TASK_DATE,
	ASSIGNED_BY,
	[ACTION],
	ROUTE_IS_COMPLETED)
VALUES(
	@CLIENT_CODE,
	@NAME_CLIENT,
	ISNULL(@RELATED_CLIENT_PHONE_1,'N/A'),
	GETDATE(),
	--MODIFICAR
	ISNULL((SELECT TOP 1 BRANCH_ADDRESS FROM [SONDA].SWIFT_BRANCHES WHERE CUSTOMER_CODE = @CLIENT_CODE AND IS_DEFAULT = 1 ),'N/A'),
	(SELECT [LOGIN] FROM [SONDA].USERS WHERE RELATED_SELLER = (SELECT SELLER_CODE FROM SWIFT_VIEW_ALL_SELLERS WHERE SELLER_NAME = (SELECT DISTINCT SELLER_DEFAULT_CODE FROM [SONDA].SWIFT_VIEW_ALL_COSTUMER WHERE CODE_CUSTOMER = @CLIENT_CODE))),
	'ASSIGNED',
	1,
	'0,0',
	ISNULL((SELECT TOP 1 RECOLLECT_EMAIL FROM [SONDA].SWIFT_BRANCHES WHERE CUSTOMER_CODE = @CLIENT_CODE AND IS_DEFAULT = 1 ),'N/A'),
	--ISNULL((SELECT TOP 1 DELIVERY_EMAIL FROM profisa.SONDA_BRANCHES WHERE CLIENT_CODE = @CLIENT_CODE AND IS_DEFAULT = 1),'n/a'),
	--ISNULL((SELECT TOP 1 GPS_LAT_LON FROM profisa.SONDA_BRANCHES WHERE CLIENT_CODE = @CLIENT_CODE AND IS_DEFAULT = 1),'0,0'),
	'VISITA REGULAR',
	CASE 
            WHEN @USER_ROLE != 'VEN'
               THEN 'PRESALE'
            WHEN @USER_ROLE = 'VEN'
               THEN 'SALE'
	END ,
	'12:00:00',
	GETDATE(),
	GETDATE(),
	GETDATE(),
	'SYS',
	'PLAY',
	0
	)

	UPDATE [SONDA].[SWIFT_CUSTOMER_FREQUENCY]
		SET [LAST_DATE_VISITED] = CURRENT_TIMESTAMP
	WHERE CODE_CUSTOMER = @CLIENT_CODE

	PRINT 'POR EL EXECUTE'
	EXECUTE [SONDA].SWIFT_SP_INSERT_CUSTOMER_FREQUENCY_TASK
END


--END
END
