CREATE PROC [SONDA].[SWIFT_SP_INSERT_PORTFOLIO_BY_SELLER]
	@CODE_PORTFOLIO VARCHAR(25)	
	, @CODE_SELLER VARCHAR(50)
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN TRY
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			DELETE [SONDA].SWIFT_PORTFOLIO_BY_SELLER
			WHERE CODE_SELLER = @CODE_SELLER;
		
			INSERT INTO [SONDA].SWIFT_PORTFOLIO_BY_SELLER(
				CODE_PORTFOLIO
				, CODE_SELLER
			)
			VALUES(
				@CODE_PORTFOLIO
				, @CODE_SELLER
			);
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
END TRY
BEGIN CATCH
     ROLLBACK TRAN t1
	 SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo 
END CATCH
