CREATE PROCEDURE [SONDA].[SWIFT_INSERT_IN_RECEPTION_HEADER]
@RECEPTION_HEADER INT,
@COMMENTS VARCHAR(MAX)
AS
INSERT INTO SWIFT_RECEPTION_HEADER(TYPE_RECEPTION,CODE_PROVIDER,CODE_USER,REFERENCE,DOC_SAP_RECEPTION,STATUS,LAST_UPDATE,SCHEDULE_FOR,SEQ, COMMENTS)
SELECT TYPE_RECEPTION,CODE_PROVIDER,CODE_USER,REFERENCE,DOC_SAP_RECEPTION,STATUS,LAST_UPDATE,SCHEDULE_FOR,SEQ, @COMMENTS FROM SWIFT_TEMP_RECEPTION_HEADER WHERE RECEPTION_HEADER=@RECEPTION_HEADER
