
-- =============================================
-- Autor:				ppablo.loukota
-- Fecha de Creacion: 	11-01-2016
-- Description:			obtiene los pallets que van a expirar y tienen permitido hacer picking

/*
-- Ejemplo de Ejecucion:				
				--
EXECUTE  [SONDA].[SWIFT_SP_GET_EXPIRATION_PALLETS]
			@CODE_SKU='100018',
			@TASK_ID = 14174
				--				
*/
-- =============================================
CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_EXPIRATION_PALLETS]

@CODE_SKU AS [VARCHAR](50) ,
@TASK_ID AS INT

AS
BEGIN 

	SET NOCOUNT ON;
      
	DECLARE @WAREHOUSE VARCHAR(50);
	  
	SET @WAREHOUSE = ( SELECT  PH.[CODE_WAREHOUSE_SOURCE]
	FROM [SONDA].[SWIFT_PICKING_HEADER] PH
	INNER JOIN [SONDA].[SWIFT_TASKS] TK ON (PH.PICKING_HEADER = TK.PICKING_NUMBER)
	AND TK.TASK_ID = @TASK_ID)
    
	SELECT TOP 1
		PA.PALLET_ID
		,PA.QTY
		,PA.LOCATION
		,BC.BATCH_ID
		,BC.BATCH_SUPPLIER
		,BC.BATCH_SUPPLIER_EXPIRATION_DATE
		,SU.CODE_SKU
		,SU.BARCODE_SKU
		,SU.DESCRIPTION_SKU		
		,LO.CODE_WAREHOUSE
	FROM [SONDA].[SWIFT_PALLET] AS PA 
	INNER JOIN [SONDA].[SWIFT_LOCATIONS] AS LO ON (LO.[CODE_LOCATION] = PA.[LOCATION])
	INNER JOIN [SONDA].[SWIFT_BATCH] AS BC ON (PA.[BATCH_ID] = BC.[BATCH_ID])
	INNER JOIN [SONDA].[SWIFT_VIEW_ALL_SKU] AS SU  ON (SU.[CODE_SKU] = BC.[SKU])	
	WHERE PA.QTY > 0	
	AND LO.[ALLOW_PICKING] = 'SI'
	AND LO.CODE_WAREHOUSE = @WAREHOUSE 
	AND SU.[CODE_SKU] = @CODE_SKU OR (SU.BARCODE_SKU = @CODE_SKU)	
	ORDER BY BC.BATCH_SUPPLIER_EXPIRATION_DATE, PA.QTY ASC

END
