CREATE PROC [SONDA].[SWIFT_SP_INSERTDRIVER]
@CODE_DRIVER VARCHAR(50),
@NAME_DRIVER VARCHAR(50),
@LICENSE_DRIVER VARCHAR(50),
@PHONE_DRIVER VARCHAR(20),
@CLASSIFICATION_DRIVER VARCHAR(50),
@LAST_UPDATE VARCHAR(50),
@LAST_UPDATE_BY VARCHAR(50)
AS
INSERT INTO SWIFT_DRIVERS (CODE_DRIVER,NAME_DRIVER,LICENSE_DRIVER,
PHONE_DRIVER,CLASSIFICATION_DRIVER,LAST_UPDATE,LAST_UPDATE_BY) VALUES (@CODE_DRIVER,
@NAME_DRIVER,
@LICENSE_DRIVER,
@PHONE_DRIVER,
@CLASSIFICATION_DRIVER,
GETDATE(),
@LAST_UPDATE_BY)
