-- Modificacion 2/21/2017 @ A-Team Sprint Chatuluka
					-- rodrigo.gomez
					-- Se cambio el join de usuarios a left join
CREATE PROCEDURE [SONDA].[SWIFT_GET_PICKING_PANEL_RECEPTION]
@PICKINGHEADER INT
AS
SELECT DISTINCT  
	A.CLASSIFICATION_PICKING AS NAME_CLASSIFICATION,
	C.CODE_CUSTOMER,
	C.NAME_CUSTOMER ,
	ISNULL(D.LOGIN,'') LOGIN,
	A.REFERENCE,
	A.DOC_SAP_RECEPTION, 
	A.COMMENTS,
	(SELECT TOP 1 SCANNING_STATUS FROM [SONDA].SWIFT_TASKS WHERE PICKING_NUMBER = @PICKINGHEADER) AS SCANNING_STATUS,
	(SELECT TOP 1 ALLOW_STORAGE_ON_DIFF FROM [SONDA].SWIFT_TASKS WHERE PICKING_NUMBER = @PICKINGHEADER) AS ALLOW_STORAGE_ON_DIFF,
	(SELECT TOP 1 TASK_ID FROM [SONDA].SWIFT_TASKS WHERE PICKING_NUMBER = @PICKINGHEADER) AS TASK_ID
FROM 
	[SONDA].SWIFT_PICKING_HEADER A 
	INNER JOIN 
		[SONDA].SWIFT_VIEW_ALL_COSTUMER C ON a.[CODE_CLIENT] = c.[CODE_CUSTOMER]
	LEFT JOIN 
		[SONDA].USERS D ON [A].[CODE_USER] = d.[LOGIN]
WHERE 
	A.PICKING_HEADER = @PICKINGHEADER  
	--AND C.CODE_CUSTOMER = A.CODE_CLIENT
	--AND A.CODE_USER = D.LOGIN
------
SELECT DISTINCT 
	z.PICKING_DETAIL, 
	Z.CODE_SKU,
	Z.DESCRIPTION_SKU,
	Z.DISPATCH,
CASE 
            WHEN (Z.SCANNED - Z.DISPATCH) > 0
               THEN 'DE MAS'
            WHEN (Z.SCANNED - Z.DISPATCH) < 0
               THEN 'DE MENOS'
            WHEN (Z.SCANNED - Z.DISPATCH) = 0
               THEN 'ESPECIFICADO'
END AS RESULT,
	ISNULL(Z.RESULT,0) AS ENTREGADO,
	ISNULL((Z.SCANNED-ISNULL(Z.RESULT,0)),0) AS RESTANTE,
	ISNULL((Z.SCANNED - Z.DISPATCH),0) AS DIFFERENCE,
	Z.SCANNED, CONVERT(FLOAT,0.00) AS 'NUEVO_VALOR'
FROM [SONDA].SWIFT_PICKING_DETAIL Z
WHERE Z.PICKING_HEADER=@PICKINGHEADER
