CREATE PROC [SONDA].[SWIFT_SP_DELETE_ALL_PRICE_LIST_BY_SKU]
	@CODE_PRICE_LIST VARCHAR(25)	
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			
			DELETE [SONDA].SWIFT_PRICE_LIST_BY_SKU
			WHERE CODE_PRICE_LIST = @CODE_PRICE_LIST;
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
