CREATE PROC [SONDA].[SWIFT_SP_GET_PRICE_LIST_SKU_AVAILABLE]
	@CODE_PRICE_LIST VARCHAR(50)
AS
	SELECT *
	FROM [SONDA].SWIFT_VIEW_SKU S
	WHERE NOT EXISTS(SELECT 1
					FROM [SONDA].SWIFT_VIEW_PRICE_LIST_BY_SKU PS
					WHERE S.CODE_SKU = PS.CODE_SKU
					AND PS.CODE_PRICE_LIST = @CODE_PRICE_LIST
	)
