CREATE PROCEDURE [SONDA].SWIFT_SP_GET_TOP_SALE_ORDER_HEADER
AS

  SELECT TOP 1
    
  SALES_ORDER_ID
 ,TERMS
 ,POSTED_DATETIME
 ,CLIENT_ID
 ,POS_TERMINAL
 ,GPS_URL
 ,TOTAL_AMOUNT
 ,STATUS
 ,POSTED_BY
 ,'' IMAGE_1
 ,'' IMAGE_2
 ,'' IMAGE_3
 ,DEVICE_BATTERY_FACTOR
 ,VOID_DATETIME
 ,VOID_REASON
 ,VOID_NOTES
 ,VOIDED
 ,CLOSED_ROUTE_DATETIME
 ,IS_ACTIVE_ROUTE
 ,GPS_EXPECTED
 ,DELIVERY_DATE
 ,SALES_ORDER_ID_HH
 ,ATTEMPTED_WITH_ERROR
 ,IS_POSTED_ERP
 ,POSTED_ERP
 ,POSTED_RESPONSE
 ,IS_PARENT
 ,REFERENCE_ID
 ,WAREHOUSE
 ,TIMES_PRINTED
  FROM [SONDA].[SONDA_SALES_ORDER_HEADER] INNER JOIN 
    [SONDA].SWIFT_VIEW_ALL_COSTUMER svac
    ON CLIENT_ID= svac.CODE_CUSTOMER
  WHERE ISNULL(IS_POSTED_ERP, 0) = 0
    AND ISNULL(ATTEMPTED_WITH_ERROR,0)=0
	AND IS_READY_TO_SEND=1
  ORDER BY ([POSTED_DATETIME]) ASC
