CREATE PROCEDURE [SONDA].[SWIFT_SP_INSERT_CUSTOMER]	
    @CODE_CUSTOMER AS VARCHAR(50),
	@NAME_CUSTOMER AS VARCHAR(50),
	@PHONE_CUSTOMER AS VARCHAR(50),
	@ADRESS_CUSTOMER AS VARCHAR(50),
	@CLASSIFICATION_CUSTOMER AS VARCHAR(50),
	@CONTACT_CUSTOMER AS VARCHAR(50),
	@CODE_ROUTE AS VARCHAR(50),
    @LAST_UPDATED AS DATETIME,
    @LAST_UPDATED_BY AS VARCHAR(50),
    @SELLER_DEFAULT_CODE AS VARCHAR(50),
	@CREDIT_LIMITAS AS FLOAT,
	@GPS AS VARCHAR(MAX) 
AS
BEGIN TRY
DECLARE @return_value int
		, @pID NUMERIC(18, 0)
			EXEC @return_value = [SONDA].[SWIFT_SP_GET_NEXT_SEQUENCE] @SEQUENCE_NAME = N'CUSTOMER', @pRESULT = @pID OUTPUT
			
			
			 INSERT INTO [SONDA].SWIFT_CUSTOMERS
			  (
			 [CUSTOMER]
			 ,[CODE_CUSTOMER]
			 ,[NAME_CUSTOMER] 
			 ,[PHONE_CUSTOMER]
             ,[ADRESS_CUSTOMER]
			 ,[CLASSIFICATION_CUSTOMER]
			 ,[CONTACT_CUSTOMER]
			 ,[CODE_ROUTE]
			 ,[LAST_UPDATE]
			 ,[LAST_UPDATE_BY]
			 ,[SELLER_DEFAULT_CODE]
			 ,[CREDIT_LIMIT]
			 ,[GPS]
			 ) 
			  VALUES 
			  (
		    @pID
		    ,@CODE_CUSTOMER
			,@NAME_CUSTOMER 
			,@PHONE_CUSTOMER 
			,@ADRESS_CUSTOMER 
			,@CLASSIFICATION_CUSTOMER 
			,@CONTACT_CUSTOMER 
			,@CODE_ROUTE 
			,@LAST_UPDATED 
			,@LAST_UPDATED_BY 
			,@SELLER_DEFAULT_CODE 
			,@CREDIT_LIMITAS 
			,@GPS  
			  )
	
	IF @@error = 0 BEGIN		
		SELECT  1 as Resultado , 'Proceso Exitoso' Mensaje ,  0 Codigo, CONVERT(VARCHAR(50),@pID) DbData
	END		
	ELSE BEGIN
		
		SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo
	END

END TRY
BEGIN CATCH     
	 SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo 
END CATCH
