CREATE PROC [SONDA].[SWIFT_GET_SKU_SELLER_BY_SKU]
@CODE_SELLER VARCHAR(40)
AS
SELECT '1' AS VALOR ,CODE_SKU , DESCRIPTION_SKU, LIST_PRICE, COST FROM [SONDA].SWIFT_VIEW_ALL_SKU
WHERE CODE_SKU IN (SELECT CODE_SKU FROM  [SONDA].SWIFT_SELLER_BY_SKU WHERE CODE_SELLER = @CODE_SELLER)
UNION ALL
SELECT '0' AS VALOR ,CODE_SKU , DESCRIPTION_SKU, LIST_PRICE, COST FROM [SONDA].SWIFT_VIEW_ALL_SKU
WHERE CODE_SKU NOT IN (SELECT CODE_SKU FROM  [SONDA].SWIFT_SELLER_BY_SKU WHERE CODE_SELLER = @CODE_SELLER)
