CREATE PROC [SONDA].[SWIFT_SP_UPDATE_ACTION_TASKS]
@TASK_ID int,
@ACTION VARCHAR(50)
AS
IF(@ACTION = 'CLOSED')
BEGIN
UPDATE SWIFT_TASKS SET [ACTION]=@ACTION, TASK_STATUS = 'CLOSED'
WHERE TASK_ID = @TASK_ID AND [TASK_STATUS] != 'CLOSED' AND [TASK_STATUS] != 'COMPLETED' AND [ACTION] != 'CLOSED' AND [ACTION] != 'COMPLETED'
END

IF(@ACTION != 'CLOSED')
BEGIN
UPDATE SWIFT_TASKS SET [ACTION]=@ACTION
WHERE TASK_ID = @TASK_ID AND [TASK_STATUS] != 'CLOSED' AND [TASK_STATUS] != 'COMPLETED' AND [ACTION] != 'CLOSED' AND [ACTION] != 'COMPLETED'
END
