CREATE PROC [SONDA].[SWIFT_SP_DELETE_ALERT]
	@ALERT_NAME VARCHAR(25)	
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			
			DELETE [SONDA].SONDA_ALERTS
			WHERE ALERT_NAME = @ALERT_NAME;
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
