CREATE PROC [SONDA].[SWIFT_SP_GET_SBO_RTD]
@DOC_ENTRY VARCHAR(50)
AS

DECLARE @SQL VARCHAR(8000)

SELECT 
tr.TXN_ID TransactionId, 
rd.RECEPTION_HEADER DocNum,
cast( rd.RECEPTION_HEADER as varchar) DocEntry,
tr.TXN_QTY Quantity ,
tr.TXN_CODE_SKU ItemCode ,
cast( null as varchar) ObjType ,
ROW_NUMBER() OVER(PARTITION  BY rd.RECEPTION_HEADER ORDER BY  rd.RECEPTION_HEADER) AS LineNum,
'01' WarehouseCode, 
'ST'  SalesUnit ,
tr.TXN_QTY QuantityErp ,
rd.RECEPTION_HEADER DocEntryErp
FROM [SONDA].SWIFT_RECEPTION_DETAIL  rd 
INNER JOIN  [SONDA].SWIFT_TXNS  tr 
on tr.HEADER_REFERENCE = rd.RECEPTION_HEADER
 AND tr.TXN_CODE_SKU = rd.CODE_SKU
where  
 rd.RECEPTION_HEADER = @DOC_ENTRY 
 AND TR.TXN_CATEGORY IN ('RT' ,'RR')
 AND TR.TXN_TYPE = 'RETURN'
