CREATE Procedure [SONDA].SWIFT_CUSTOMERS_X_TAGS
AS
BEGIN

DECLARE @Code nvarchar(255);

DECLARE CUSTOMERS_CUR CURSOR FOR 
	SELECT DISTINCT 
		CODE_CUSTOMER
	FROM [SONDA].SWIFT_CUSTOMERS_NEW

	Create Table #Result
	  (   CODE_CUSTOMER		Nvarchar(255)
		  ,NAME_CUSTOMER    Nvarchar(255)
		  ,TAG_VALUE_TEXT	Nvarchar(255)
		  ,TAG_NUMBER		Numeric)
	      
	OPEN CUSTOMERS_CUR

	FETCH NEXT FROM CUSTOMERS_CUR 
	INTO @Code

	WHILE @@FETCH_STATUS = 0
	BEGIN

		INSERT INTO #Result
		SELECT
			T0.CODE_CUSTOMER
			,T0.NAME_CUSTOMER
			,T2.TAG_VALUE_TEXT
			,ROW_NUMBER() OVER (ORDER BY T0.CODE_CUSTOMER ASC ) as TagNumber
		FROM [SONDA].SWIFT_CUSTOMERS_NEW T0
			LEFT JOIN [SONDA].SWIFT_TAG_X_CUSTOMER_NEW T1 ON T0.CODE_CUSTOMER=T1.CUSTOMER
			INNER JOIN [SONDA].SWIFT_TAGS T2 ON T1.TAG_COLOR= T2.TAG_COLOR
			where CODE_CUSTOMER=@Code
	
		FETCH NEXT FROM CUSTOMERS_CUR 
		INTO @Code
	END 
	CLOSE CUSTOMERS_CUR;
	DEALLOCATE CUSTOMERS_CUR;
	
DECLARE @Query AS NVARCHAR(MAX)
DECLARE @ColumnName AS NVARCHAR(MAX)


SELECT @ColumnName= ISNULL(@ColumnName + ',','') + QUOTENAME(TAG_NUMBER)
FROM (SELECT DISTINCT TAG_NUMBER FROM #Result) AS TAGS

SET @Query = N'Select * Into #Reporte From 
				(Select [CODE_CUSTOMER], [NAME_CUSTOMER], [TAG_VALUE_TEXT], [TAG_NUMBER] From #Result) Unidades
                        Pivot ( MAX(TAG_VALUE_TEXT) For [TAG_NUMBER] IN (' + @ColumnName + ') ) as Unidad
						SELECT * FROM #Reporte
						'

EXEC sp_executesql @Query
	
   
END
