CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_TOP_CUSTOMERS_NEW]
@CODE_CUSTOMER varchar(50)
AS

Select  *
From [SONDA].[SWIFT_CUSTOMERS_NEW] CN
WHERE cn.CODE_CUSTOMER=@CODE_CUSTOMER 
Order By (CN.[CUSTOMER]) ASC
