CREATE PROC [SONDA].[SWIFT_SP_UPDATE_ALERT]
	  @ALERT_NAME VARCHAR(50)
	, @ALERT_PERC INT
	, @ALERT_MESSAGE VARCHAR(200)
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN TRY
BEGIN
	BEGIN TRAN t1
		BEGIN
			UPDATE [SONDA].SONDA_ALERTS SET				
				ALERT_NAME = @ALERT_NAME
				, ALERT_PERC = @ALERT_PERC
				, ALERT_MESSAGE =@ALERT_MESSAGE
			WHERE ALERT_NAME = @ALERT_NAME			
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
END TRY
BEGIN CATCH
     ROLLBACK TRAN t1
	 SELECT  -1 as Resultado , ERROR_MESSAGE() Mensaje ,  @@ERROR Codigo 
END CATCH
