CREATE PROC [SONDA].[SWIFT_SP_DELETE_TAG_BY_BATCH]
@BATCH_ID VARCHAR(150),
@TAG_COLOR VARCHAR(8)
AS
DELETE FROM [SONDA].[SWIFT_TAGS_BY_BATCH]
      WHERE [TAG_COLOR] = @TAG_COLOR AND [BATCH_ID] = @BATCH_ID
