CREATE PROC [SONDA].[SWIFT_SP_GET_SBO_RTS]
@DOC_ENTRY VARCHAR(50),
@ITEMCODE VARCHAR(50)
AS
SELECT 
	T.TXN_ID AS TransactionId
	, cast( t.HEADER_REFERENCE as varchar) AS DocEntry
	, t.TXN_CODE_SKU AS ItemCode
	, 0 AS LineNum
	, T.TXN_SERIE
	, TS.Txn_Serie  as TxnSerie
FROM [SONDA].SWIFT_TXNS T
	INNER JOIN [SONDA].SWIFT_TXNS_SERIES TS ON (T.TXN_ID = TS.TXN_ID AND T.TXN_CODE_SKU = TS.TXN_CODE_SKU)
WHERE T.HEADER_REFERENCE  = @DOC_ENTRY
AND T.TXN_CODE_SKU = @ITEMCODE
AND T.TXN_TYPE='RETURN'
AND T.TXN_CATEGORY IN ('RT','RR')
