CREATE VIEW SWIFT_VIEW_FREQUENCY AS
SELECT  ID_FREQUENCY AS ID, CODE_FREQUENCY AS CODE, SUNDAY AS DOM, MONDAY AS LUN, TUESDAY AS MAR, WEDNESDAY AS MIE, THURSDAY AS JUE, FRIDAY AS VIE, SATURDAY AS SAT, FREQUENCY_WEEKS AS FXS, LAST_WEEK_VISITED AS USV, LAST_UPDATED AS UV, LAST_UPDATED_BY AS UVX, CODE_ROUTE AS CR, TYPE_TASK AS TPT
FROM [SONDA].[SWIFT_FREQUENCY]
