-- Modificacion 2/21/2017 @ A-Team Sprint Chatuluka
					-- rodrigo.gomez
					-- Se modifico la condicion para IS_POSTED_ERP
CREATE PROCEDURE [SONDA].[SWIFT_UPDATE_PICKING]
@OBSERVATION VARCHAR(MAX),
@PICKING_HEADER INT
AS
UPDATE [SONDA].SWIFT_PICKING_HEADER SET COMMENTS=@OBSERVATION, STATUS='CLOSED', FF_STATUS='CLOSED', [IS_POSTED_ERP] = 0
WHERE PICKING_HEADER = @PICKING_HEADER AND (IS_POSTED_ERP <> 1 OR [IS_POSTED_ERP] IS NULL)

UPDATE [SONDA].SWIFT_PICKING_HEADER SET FF_STATUS='CLOSED'
WHERE PICKING_HEADER = @PICKING_HEADER AND FF = '1'

UPDATE [SONDA].SWIFT_TASKS SET ACTION='CLOSED'
WHERE PICKING_NUMBER=@PICKING_HEADER

--Elimnia las facturas draft que pudo haber generado
EXEC [SONDA].SWIFT_SP_DELETE_INVOICE_DRAFT @PICKING_HEADER
