CREATE PROC [SONDA].[SWIFT_SP_UPDATEPROVIDER]
@PROVIDER INT,
@NAME_PROVIDER VARCHAR(50),
@CLASSIFICATION_PROVIDER VARCHAR(50),
@CONTACT_PROVIDER VARCHAR(50),
@LAST_UPDATE VARCHAR(50),
@LAST_UPDATE_BY VARCHAR(50)
AS
UPDATE SWIFT_PROVIDERS SET NAME_PROVIDER=@NAME_PROVIDER,
CLASSIFICATION_PROVIDER=@CLASSIFICATION_PROVIDER,CONTACT_PROVIDER=@CONTACT_PROVIDER,
LAST_UPDATE=GETDATE(),
LAST_UPDATE_BY=@LAST_UPDATE_BY
WHERE PROVIDER = @PROVIDER
