CREATE PROC [SONDA].[SWIFT_SP_UPDATEDRIVER]
@DRIVER int,
@NAME_DRIVER VARCHAR(50),
@LICENSE_DRIVER VARCHAR(50),
@PHONE_DRIVER VARCHAR(20),
@CLASSIFICATION_DRIVER VARCHAR(50),
@LAST_UPDATE VARCHAR(50),
@LAST_UPDATE_BY VARCHAR(50)
AS
UPDATE SWIFT_DRIVERS SET NAME_DRIVER=@NAME_DRIVER,
LICENSE_DRIVER=@LICENSE_DRIVER,PHONE_DRIVER=@PHONE_DRIVER,CLASSIFICATION_DRIVER=@CLASSIFICATION_DRIVER,
LAST_UPDATE=GETDATE(),
LAST_UPDATE_BY=@LAST_UPDATE_BY
WHERE DRIVER = @DRIVER
