CREATE PROC [SONDA].[SWIFT_SP_UPDATE_PRICE_LIST]
	@CODE_PRICE_LIST VARCHAR(25)
	, @NAME_PRICE_LIST VARCHAR(50)
	, @COMMENT VARCHAR(250)
	, @LAST_UPDATE_BY VARCHAR(50)
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			UPDATE [SONDA].SWIFT_PRICE_LIST SET				
				NAME_PRICE_LIST = @NAME_PRICE_LIST
				, COMMENT = @COMMENT
				, LAST_UPDATE = GETDATE()
				, LAST_UPDATE_BY = @LAST_UPDATE_BY
			WHERE CODE_PRICE_LIST = @CODE_PRICE_LIST			
		END
	
	
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
