CREATE PROCEDURE [SONDA].SWIFT_SP_UPDATE_CUSTOMER_FREQUENCY (
   @CODE_FREQUENCY INT
   ,@CODE_CUSTOMER VARCHAR(50)
   ,@SUNDAY VARCHAR(10)
   ,@MONDAY VARCHAR(10)
   ,@TUESDAY VARCHAR(10)
   ,@WEDNESDAY VARCHAR(10)
   ,@THURSDAY VARCHAR(10)
   ,@FRIDAY VARCHAR(10)
   ,@SATURDAY VARCHAR(10)
   ,@FREQUENCY_WEEKS VARCHAR(10)
   ,@LAST_DATE_VISITED DATE
   ,@LAST_UPDATED_BY VARCHAR(25)
)
AS
  SET NOCOUNT ON;

  BEGIN TRY
    
    UPDATE [SONDA].SWIFT_CUSTOMER_FREQUENCY SET
      CODE_CUSTOMER =@CODE_CUSTOMER
      ,SUNDAY = @SUNDAY
      ,MONDAY = @MONDAY
      ,TUESDAY = @TUESDAY
      ,WEDNESDAY = @WEDNESDAY
      ,THURSDAY = @THURSDAY
      ,FRIDAY = @FRIDAY
      ,SATURDAY = @SATURDAY
      ,FREQUENCY_WEEKS = @FREQUENCY_WEEKS
      ,LAST_DATE_VISITED = @LAST_DATE_VISITED
      ,LAST_UPDATED_BY = @LAST_UPDATED_BY
      ,LAST_UPDATED = GETDATE()
    WHERE CODE_FREQUENCY = @CODE_FREQUENCY

    IF @@error = 0
    BEGIN
      SELECT 1 AS Resultado, 'Proceso Exitoso' Mensaje
    END
    ELSE
    BEGIN
      SELECT -1 AS Resultado, ERROR_MESSAGE() Mensaje, @@ERROR Codigo
    END
  END TRY
  BEGIN CATCH
    SELECT -1 AS Resultado, ERROR_MESSAGE() Mensaje, @@ERROR Codigo
  END CATCH
