CREATE PROC [SONDA].[SWIFT_SP_VALIDATE_PICKING_UNLOCK]
@USER VARCHAR(50),
@PASS VARCHAR(50),
@pResult VARCHAR(250) OUTPUT
AS
BEGIN TRY
IF NOT EXISTS(SELECT 1 FROM [SONDA].USERS WHERE LOGIN = @USER) BEGIN
	SET @pResult = 'Operador no existe'
END
ELSE IF NOT EXISTS(SELECT 1 FROM [SONDA].USERS WHERE LOGIN = @USER AND PASSWORD = @PASS) BEGIN
	SET @pResult = 'Password incorrecto'
END
ELSE BEGIN
	SELECT A.* 
FROM [SONDA].USERS AS A 
WHERE LOGIN = @USER
AND PASSWORD = @PASS
AND A.USER_ROLE IN (SELECT [ROLE_ID] 
FROM [SONDA].[SWIFT_PRIVILEGES_X_ROLE] 
WHERE PRIVILEGE_ID = (SELECT [ID] FROM [SONDA].[SWIFT_PRIVILEGES] WHERE PRIVILEGE_ID = 'unlockPicking'))
		IF @@ROWCOUNT = 0 BEGIN
			SET @pResult = 'Usuario no tiene permiso de desbloquear'
		END
		ELSE
		BEGIN
			SET @pResult = 'Usuario tiene permiso de desbloquear'
		END
END
END TRY
BEGIN CATCH
	 SET @pResult = ERROR_MESSAGE()
END CATCH
