CREATE PROC [SONDA].[SWIFT_SP_UPDATE_USER_TASKS]
@TASK_ID int,
@CORRELATIVE VARCHAR(50)
AS
UPDATE SWIFT_TASKS SET ASSIGEND_TO=@CORRELATIVE
WHERE TASK_ID = @TASK_ID AND [TASK_STATUS] != 'CLOSED' AND [ACTION] != 'CLOSED'
