-- =============================================
-- Autor:				jose.garcia
-- Fecha de Creacion: 	26-01-2016
-- MODIFICACION:		Se modifico el tipo para el parametro de @TYPE_WAREHOUSE, anteriormente era varchar
--						ahora es un INT

-- Modificacion 12/28/2016 @ A-Team Sprint Balder
					-- rodrigo.gomez
					-- Se agrego el parametro @DISTRIBUTION_CENTER_ID para que se pueda ejecutar el SP SWIFT_SP_SET_WAREHOUSE_TO_DISTRIBUTION_CENTER

-- Modificacion 10/01/2017 @ A-Team Sprint Balder
					-- diego.as
					-- Se agrego el parametro @CODE_WAREHOUSE_3PL para asociarlo a la bodega
  /*
*/
-- =============================================
CREATE PROC [SONDA].SWIFT_SP_UPDATEWAREHOUSE
  @WAREHOUSE int,
  @DESCRIPTION_WAREHOUSE VARCHAR(MAX),
  @WEATHER_WAREHOUSE VARCHAR(50),
  @STATUS_WAREHOUSE VARCHAR(10),
  @LAST_UPDATE VARCHAR(50),
  @LAST_UPDATE_BY VARCHAR(50),
  @IS_EXTERNAL INT,
  @TYPE_WAREHOUSE INT,
  @ERP_WAREHOUSE [varchar](50),
  @ADDRESS_WAREHOUSE [varchar](MAX),
  @BARCODE_WAREHOUSE [varchar](50),
  @SHORT_DESCRIPTION_WAREHOUSE [varchar](MAX),
  @GPS_WAREHOUSE [varchar](50),
  @DISTRIBUTION_CENTER_ID INT,
  @CODE_WAREHOUSE_3PL VARCHAR(50)
AS
UPDATE [SONDA].SWIFT_WAREHOUSES 
  SET 
    DESCRIPTION_WAREHOUSE=@DESCRIPTION_WAREHOUSE
  ,WEATHER_WAREHOUSE=@WEATHER_WAREHOUSE
  ,STATUS_WAREHOUSE=@STATUS_WAREHOUSE
  ,LAST_UPDATE=GETDATE()
  ,LAST_UPDATE_BY=@LAST_UPDATE_BY
  ,IS_EXTERNAL=@IS_EXTERNAL
  ,TYPE_WAREHOUSE=@TYPE_WAREHOUSE
  ,ERP_WAREHOUSE=@ERP_WAREHOUSE
  ,ADDRESS_WAREHOUSE =@ADDRESS_WAREHOUSE
  ,BARCODE_WAREHOUSE=@BARCODE_WAREHOUSE
  ,SHORT_DESCRIPTION_WAREHOUSE= @SHORT_DESCRIPTION_WAREHOUSE
  ,GPS_WAREHOUSE =@GPS_WAREHOUSE
  ,CODE_WAREHOUSE_3PL = @CODE_WAREHOUSE_3PL
WHERE WAREHOUSE = @WAREHOUSE

DECLARE @CODE VARCHAR(50) 
SET @CODE = (SELECT [CODE_WAREHOUSE] FROM [SONDA].[SWIFT_WAREHOUSES] WHERE @WAREHOUSE = [WAREHOUSE])

EXEC [SONDA].[SWIFT_SP_SET_WAREHOUSE_TO_DISTRIBUTION_CENTER] 
	@DISTRIBUTION_CENTER_ID = @DISTRIBUTION_CENTER_ID 
  ,@CODE_WAREHOUSE = @CODE
