CREATE PROC [SONDA].[SWIFT_SP_UPDATECUSTOMER]
@CUSTOMER int,
@NAME_CUSTOMER VARCHAR(50),
@CLASSIFICATION_CUSTOMER VARCHAR(50),
@CONTACT_CUSTOMER VARCHAR(50),
@CODE_ROUTE VARCHAR(50),
@LAST_UPDATE VARCHAR(50),
@LAST_UPDATE_BY VARCHAR(50)
AS
UPDATE SWIFT_CUSTOMERS SET NAME_CUSTOMER=@NAME_CUSTOMER,
CLASSIFICATION_CUSTOMER=@CLASSIFICATION_CUSTOMER,CONTACT_CUSTOMER=@CONTACT_CUSTOMER,CODE_ROUTE=@CODE_ROUTE,
LAST_UPDATE=GETDATE(),
LAST_UPDATE_BY=@LAST_UPDATE_BY
WHERE CUSTOMER = @CUSTOMER
