CREATE PROC [SONDA].[SWIFT_SP_UPDATE_RESOLUTION]
	@AUTH_ID VARCHAR(50)
	, @SERIE VARCHAR(100)		
	, @ASSIGNED_BY VARCHAR(100)
	, @ASSIGNED_TO VARCHAR(100)
	, @pResult VARCHAR(250) OUTPUT
AS
BEGIN
	
	BEGIN TRAN t1
		BEGIN
			UPDATE [SONDA].SONDA_POS_RES_SAT SET
			AUTH_ASSIGNED_DATETIME = GETDATE()
			, AUTH_ASSIGNED_BY = @ASSIGNED_BY
			,  AUTH_ASSIGNED_TO = @ASSIGNED_TO
			WHERE AUTH_ID = @AUTH_ID
			AND AUTH_SERIE = @SERIE
		END		
	IF @@error = 0 BEGIN
		SELECT @pResult = 'OK'
		COMMIT TRAN t1
	END		
	ELSE BEGIN
		ROLLBACK TRAN t1
		SELECT	@pResult	= ERROR_MESSAGE()
	END
END
