CREATE PROC [SONDA].[SWIFT_SP_UPDATEVEHICLE]
@VEHICLE int,
@PLATE_VEHICLE VARCHAR(50),
@CLASSIFICATION_VEHICLE VARCHAR(50),
@MAXIMUM_WEIGHT FLOAT,
@BRAND VARCHAR(20),
@UNIT VARCHAR(20),
@LAST_UPDATE VARCHAR(50),
@LAST_UPDATE_BY VARCHAR(50)
AS
UPDATE SWIFT_VEHICLES SET PLATE_VEHICLE=@PLATE_VEHICLE,
CLASSIFICATION_VEHICLE=@CLASSIFICATION_VEHICLE,MAXIMUM_WEIGHT=@MAXIMUM_WEIGHT,BRAND=@BRAND,UNIT=@UNIT,
LAST_UPDATE=GETDATE(),
LAST_UPDATE_BY=@LAST_UPDATE_BY
WHERE VEHICLE = @VEHICLE
