CREATE TABLE [SONDA].[OP_WMS_WAREHOUSES] (
    [WAREHOUSE_ID]               VARCHAR (25)  NOT NULL,
    [NAME]                       VARCHAR (50)  NOT NULL,
    [COMMENTS]                   VARCHAR (150) NULL,
    [ERP_WAREHOUSE]              VARCHAR (50)  NULL,
    [ALLOW_PICKING]              NUMERIC (18)  NULL,
    [DEFAULT_RECEPTION_LOCATION] VARCHAR (25)  NULL,
    [SHUNT_NAME]                 VARCHAR (25)  NULL,
    [WAREHOUSE_WEATHER]          VARCHAR (50)  NULL,
    [WAREHOUSE_STATUS]           INT           NULL,
    [IS_3PL_WAREHUESE]           INT           NULL,
    [WAHREHOUSE_ADDRESS]         VARCHAR (250) NULL,
    [GPS_URL]                    VARCHAR (100) NULL,
    [DISTRIBUTION_CENTER_ID]     VARCHAR (50)  CONSTRAINT [DF__OP_WMS_WA__DISTR__4183B671] DEFAULT ('') NOT NULL,
    [USE_PICKING_LINE]           INT           CONSTRAINT [DEF_WAREHOUSE_USE_LINE] DEFAULT ((0)) NOT NULL,
    [PICKING_TYPE]               VARCHAR (50)  CONSTRAINT [DEF_PICKING_TYPE] DEFAULT ('Ascendente') NOT NULL
);

