CREATE TABLE [SONDA].[SKU_TEMP] (
    [SKU]                       INT             NULL,
    [CODE_SKU]                  VARCHAR (50)    NULL,
    [DESCRIPTION_SKU]           VARCHAR (MAX)   NULL,
    [VALUE_TEXT_CLASSIFICATION] VARCHAR (50)    NULL,
    [BARCODE_SKU]               VARCHAR (50)    NULL,
    [CODE_PROVIDER]             VARCHAR (50)    NULL,
    [LIST_PRICE]                VARCHAR (MAX)   NULL,
    [COST]                      REAL            NULL,
    [MEASURE]                   VARCHAR (50)    NULL,
    [LAST_UPDATE]               DATETIME        NULL,
    [LAST_UPDATE_BY]            VARCHAR (50)    NULL,
    [HANDLE_SERIAL_NUMBER]      VARCHAR (2)     NULL,
    [HANDLE_BATCH]              VARCHAR (2)     NULL,
    [FROM_ERP]                  INT             NULL,
    [CODE_FAMILY_SKU]           VARCHAR (50)    NULL,
    [CODE_PACK_UNIT]            VARCHAR (25)    NULL,
    [DESCRIPTION_PACK_UNIT]     VARCHAR (250)   NULL,
    [USE_LINE_PICKING]          DECIMAL (18)    NULL,
    [VOLUME_SKU]                DECIMAL (18, 2) NULL,
    [WEIGHT_SKU]                DECIMAL (18, 2) NULL,
    [VOLUME_CODE_UNIT]          VARCHAR (250)   NULL,
    [VOLUME_NAME_UNIT]          VARCHAR (250)   NULL,
    [HANDLE_DIMENSION]          INT             NULL,
    [OWNER]                     VARCHAR (50)    NULL,
    [OWNER_ID]                  VARCHAR (50)    NULL,
    [ART_CODE]                  VARCHAR (20)    NULL,
    [VAT_CODE]                  VARCHAR (20)    NULL
);

