CREATE TABLE [SONDA].[SONDA_WEEKLY_SUMMARIE] (
    [SUMMARIZE_ID]      INT          IDENTITY (1, 1) NOT NULL,
    [CODE_ROUTE]        VARCHAR (50) NULL,
    [ROUTE_STARTED_AT]  DATETIME     NULL,
    [ROUTE_FINISHED_AT] DATETIME     NULL,
    [TRANSACTIONS]      INT          NULL,
    [MIN_BATT]          DECIMAL (18) NULL,
    [MAX_BATT]          DECIMAL (18) NULL,
    [TOTAL_AMOUNT]      MONEY        NULL,
    [FIRST_TXN]         DATETIME     NULL,
    [LAST_TXN]          DATETIME     NULL,
    [WEEK_NUMBER]       INT          NULL,
    [LOGIN_ID]          VARCHAR (50) NULL
);


GO
CREATE NONCLUSTERED INDEX [IN_SONDA_WEEKLY_SUMMARIE_CODE_ROUTE_ROUTE_STARTED_AT]
    ON [SONDA].[SONDA_WEEKLY_SUMMARIE]([CODE_ROUTE] ASC, [ROUTE_STARTED_AT] ASC);

