CREATE TABLE [SONDA].[SONDA_DOC_ROUTE_RETURN_DETAIL] (
    [ID_DOC_RETURN_DETAIL] INT             IDENTITY (1, 1) NOT NULL,
    [ID_DOC_RETURN_HEADER] INT             NOT NULL,
    [CODE_SKU]             VARCHAR (50)    NULL,
    [QTY]                  NUMERIC (18, 6) NULL,
    [DESCRIPTION_SKU]      VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([ID_DOC_RETURN_DETAIL] ASC),
    FOREIGN KEY ([ID_DOC_RETURN_HEADER]) REFERENCES [SONDA].[SONDA_DOC_ROUTE_RETURN_HEADER] ([ID_DOC_RETURN_HEADER]),
    CONSTRAINT [fk_ID_DOC_RETURN_HEADER] FOREIGN KEY ([ID_DOC_RETURN_HEADER]) REFERENCES [SONDA].[SONDA_DOC_ROUTE_RETURN_HEADER] ([ID_DOC_RETURN_HEADER])
);

