CREATE TABLE [SONDA].[SONDA_TAKE_INVENTORY_DETAIL] (
    [TAKE_INVENTORY_ID] INT             NOT NULL,
    [CODE_SKU]          VARCHAR (25)    NOT NULL,
    [QTY]               NUMERIC (18, 6) NULL,
    [POSTED_DATETIME]   DATETIME        NULL,
    [CODE_PACK_UNIT]    VARCHAR (50)    NOT NULL,
    [LAST_QTY]          NUMERIC (18, 6) NULL,
    CONSTRAINT [PK_SONDA_TAKE_INVENTORY_DETAIL] PRIMARY KEY CLUSTERED ([CODE_PACK_UNIT] ASC, [CODE_SKU] ASC, [TAKE_INVENTORY_ID] ASC),
    FOREIGN KEY ([TAKE_INVENTORY_ID]) REFERENCES [SONDA].[SONDA_TAKE_INVENTORY_HEADER] ([TAKE_INVENTORY_ID])
);

