CREATE TABLE [SONDA].[SONDA_PACK_UNIT] (
    [PACK_UNIT]             INT           IDENTITY (1, 1) NOT NULL,
    [CODE_PACK_UNIT]        VARCHAR (25)  NULL,
    [DESCRIPTION_PACK_UNIT] VARCHAR (250) NULL,
    [LAST_UPDATE]           DATETIME      NULL,
    [LAST_UPDATE_BY]        VARCHAR (25)  NULL,
    [UM_ENTRY]              NUMERIC (18)  NULL,
    [ORDER]                 INT           NULL,
    PRIMARY KEY CLUSTERED ([PACK_UNIT] ASC),
    UNIQUE NONCLUSTERED ([CODE_PACK_UNIT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_SONDA_PACK_UNIT_CODE_PACK_UNIT_DESCRIPTION_PACK_UNIT]
    ON [SONDA].[SONDA_PACK_UNIT]([PACK_UNIT] ASC, [DESCRIPTION_PACK_UNIT] ASC);

