CREATE TABLE [SONDA].[SONDA_DOC_ROUTE_RETURN_HEADER] (
    [ID_DOC_RETURN_HEADER] INT           IDENTITY (1, 1) NOT NULL,
    [USER_LOGIN]           VARCHAR (50)  NULL,
    [WAREHOUSE_SOURCE]     VARCHAR (50)  NULL,
    [WAREHOUSE_TARGET]     VARCHAR (50)  NULL,
    [NAME_USER]            VARCHAR (50)  NULL,
    [LAST_UPDATE]          DATETIME      NULL,
    [LAST_UPDATE_BY]       VARCHAR (50)  NULL,
    [STATUS_DOC]           VARCHAR (20)  NULL,
    [ATTEMPTED_WITH_ERROR] INT           NULL,
    [IS_POSTED_ERP]        INT           NULL,
    [POSTED_ERP]           DATETIME      NULL,
    [POSTED_RESPONSE]      VARCHAR (150) NULL,
    [ERP_REFERENCE]        VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([ID_DOC_RETURN_HEADER] ASC)
);

