CREATE TABLE [SONDA].[SONDA_IS_COMITED_BY_WAREHOUSE] (
    [CODE_WAREHOUSE] VARCHAR (50) NOT NULL,
    [CODE_SKU]       VARCHAR (50) NOT NULL,
    [IS_COMITED]     NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_SONDA_PRESALE_SKUS] PRIMARY KEY CLUSTERED ([CODE_WAREHOUSE] ASC, [CODE_SKU] ASC)
);

