CREATE TABLE [SONDA].[SONDA_ALERTS] (
    [ALERT_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [ALERT_NAME]    VARCHAR (50)  NULL,
    [ALERT_PERC]    INT           NULL,
    [ALERT_MESSAGE] VARCHAR (200) NULL,
    CONSTRAINT [PK_SONDA_ALERTS] PRIMARY KEY CLUSTERED ([ALERT_ID] ASC)
);

