CREATE TABLE [SONDA].[SONDA_PACK_CONVERSION] (
    [PACK_CONVERSION]     INT             IDENTITY (1, 1) NOT NULL,
    [CODE_SKU]            VARCHAR (50)    NULL,
    [CODE_PACK_UNIT_FROM] VARCHAR (25)    NULL,
    [CODE_PACK_UNIT_TO]   VARCHAR (25)    NULL,
    [CONVERSION_FACTOR]   NUMERIC (18, 6) NULL,
    [LAST_UPDATE]         DATETIME        NULL,
    [LAST_UPDATE_BY]      VARCHAR (25)    NULL,
    [ORDER]               INT             NULL,
    PRIMARY KEY CLUSTERED ([PACK_CONVERSION] ASC),
    CONSTRAINT [FK_SONDA_PACK_CONVERSION_SONDA_PACK_UNIT_FROM] FOREIGN KEY ([CODE_PACK_UNIT_FROM]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([CODE_PACK_UNIT]),
    CONSTRAINT [FK_SONDA_PACK_CONVERSION_SONDA_PACK_UNIT_TO] FOREIGN KEY ([CODE_PACK_UNIT_TO]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([CODE_PACK_UNIT]),
    CONSTRAINT [UC_SONDA_PACK_CONVERSION] UNIQUE NONCLUSTERED ([CODE_SKU] ASC, [CODE_PACK_UNIT_FROM] ASC, [CODE_PACK_UNIT_TO] ASC)
);

