CREATE TABLE [SONDA].[SONDA_SERVER_ERROR_LOG] (
    [LOG_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [LOG_DATETIME]   DATETIME      DEFAULT (getdate()) NOT NULL,
    [CODE_ROUTE]     VARCHAR (50)  NULL,
    [LOGIN]          VARCHAR (50)  NULL,
    [SOURCE_ERROR]   VARCHAR (250) NULL,
    [DOC_RESOLUTION] VARCHAR (100) NULL,
    [DOC_SERIE]      VARCHAR (100) NULL,
    [DOC_NUM]        INT           NULL,
    [MESSAGE_ERROR]  VARCHAR (MAX) NULL,
    [SEVERITY_CODE]  INT           NULL,
    [TYPE]           VARCHAR (20)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IN_SONDA_SERVER_ERROR_LOG_DOC_SERIE_DOC_NUM]
    ON [SONDA].[SONDA_SERVER_ERROR_LOG]([DOC_SERIE] ASC, [DOC_NUM] ASC)
    INCLUDE([CODE_ROUTE]);


GO
CREATE NONCLUSTERED INDEX [IN_SONDA_SERVER_ERROR_LOG_SEVERITY_CODE_LOG_DATETIME]
    ON [SONDA].[SONDA_SERVER_ERROR_LOG]([SEVERITY_CODE] ASC, [LOG_DATETIME] ASC);

