CREATE TABLE [SONDA].[SWIFT_ORDER_FOR_DISCOUNT_BY_ROUTE] (
    [ORDER_FOR_DISCOUNT_HEADER_ID] INT          NOT NULL,
    [ROUTE_ID]                     VARCHAR (60) NULL,
    CONSTRAINT [UNIQUE_SWIFT_ORDER_FOR_DISCOUNT_BY_ROUTE] UNIQUE NONCLUSTERED ([ORDER_FOR_DISCOUNT_HEADER_ID] ASC, [ROUTE_ID] ASC)
);

