CREATE TABLE [SONDA].[SWIFT_PORTFOLIO_BY_SELLER] (
    [CODE_PORTFOLIO] VARCHAR (25) NOT NULL,
    [CODE_SELLER]    VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SWIFT_PORTFOLIO_BY_SELLER] PRIMARY KEY CLUSTERED ([CODE_SELLER] ASC),
    CONSTRAINT [FK_SWIFT_PORTFOLIO_BY_SELLER_SWIFT_PORTFOLIO] FOREIGN KEY ([CODE_PORTFOLIO]) REFERENCES [SONDA].[SWIFT_PORTFOLIO] ([CODE_PORTFOLIO])
);

