CREATE TABLE [SONDA].[SWIFT_RULE_X_ROUTE] (
    [RULE_ID]    INT          NOT NULL,
    [CODE_ROUTE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SWIFT_EVENT_X_ROUTE] PRIMARY KEY CLUSTERED ([RULE_ID] ASC, [CODE_ROUTE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_SWIFT_RULE_X_ROUTE_RULE_ID_EVENT_ID]
    ON [SONDA].[SWIFT_RULE_X_ROUTE]([RULE_ID] ASC, [CODE_ROUTE] ASC);

