CREATE TABLE [SONDA].[SWIFT_BATCHES] (
    [BATCH]         INT           IDENTITY (1, 1) NOT NULL,
    [BATCH_ID]      VARCHAR (150) NULL,
    [EXP_DATE]      DATETIME      NULL,
    [LAST_UPDATE]   DATETIME      NULL,
    [LAS_UPDATE_BY] VARCHAR (50)  NULL,
    CONSTRAINT [PK_SONDA_SWIFT_BATCHES] PRIMARY KEY CLUSTERED ([BATCH] ASC)
);

