CREATE TABLE [SONDA].[SWIFT_CLASSIFICATION] (
    [CLASSIFICATION]            INT          IDENTITY (1, 1) NOT NULL,
    [GROUP_CLASSIFICATION]      VARCHAR (50) NULL,
    [NAME_CLASSIFICATION]       VARCHAR (50) NULL,
    [PRIORITY_CLASSIFICATION]   INT          NULL,
    [VALUE_TEXT_CLASSIFICATION] VARCHAR (50) NULL,
    [LAST_UPDATE]               DATETIME     NULL,
    [LAST_UPDATE_BY]            VARCHAR (50) NULL,
    [MPC01]                     VARCHAR (50) NULL,
    CONSTRAINT [PK_SWIFT_CLASSIFICATION] PRIMARY KEY CLUSTERED ([CLASSIFICATION] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_NOT_DELIVERY_REASONS]
    ON [SONDA].[SWIFT_CLASSIFICATION]([GROUP_CLASSIFICATION] ASC)
    INCLUDE([NAME_CLASSIFICATION], [PRIORITY_CLASSIFICATION], [VALUE_TEXT_CLASSIFICATION]);

