CREATE TABLE [SONDA].[SWIFT_PROMO_SPECIAL_PRICE_LIST_BY_SCALE] (
    [SPECIAL_PRICE_LIST_BY_SCALE_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]                       INT             NOT NULL,
    [CODE_SKU]                       VARCHAR (50)    NOT NULL,
    [PACK_UNIT]                      INT             NOT NULL,
    [LOW_LIMIT]                      INT             NOT NULL,
    [HIGH_LIMIT]                     INT             NOT NULL,
    [PRICE]                          NUMERIC (18, 6) NOT NULL,
    [LAST_UPDATE]                    DATETIME        DEFAULT (getdate()) NOT NULL,
    [INCLUDE_DISCOUNT]               INT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([SPECIAL_PRICE_LIST_BY_SCALE_ID] ASC),
    FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID]),
    CONSTRAINT [PROMO_ID] FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID])
);


GO
CREATE NONCLUSTERED INDEX [SWIFT_PROMO_SPECIAL_PRICE_LAST_UPDATE]
    ON [SONDA].[SWIFT_PROMO_SPECIAL_PRICE_LIST_BY_SCALE]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [SWIFT_PROMO_SPECIAL_PRICE_T0]
    ON [SONDA].[SWIFT_PROMO_SPECIAL_PRICE_LIST_BY_SCALE]([CODE_SKU] ASC, [PACK_UNIT] ASC, [PROMO_ID] ASC)
    INCLUDE([HIGH_LIMIT], [LOW_LIMIT], [PRICE], [SPECIAL_PRICE_LIST_BY_SCALE_ID]);

