CREATE TABLE [SONDA].[SWIFT_SURVEY_QUESTION] (
    [QUESTION_ID]         NUMERIC (18)  NOT NULL,
    [SURVEY_ID]           NUMERIC (18)  NOT NULL,
    [PAGE_ID]             NUMERIC (18)  NOT NULL,
    [QUESTION_TYPE]       VARCHAR (20)  NOT NULL,
    [QUESTION]            VARCHAR (250) NOT NULL,
    [RELATED_TO_QUESTION] NUMERIC (18)  NULL,
    [RELATED_TO_ANSWER]   NUMERIC (18)  NULL,
    [ORDER]               SMALLINT      NOT NULL,
    CONSTRAINT [PK_SWIFT_SURVEY_QUESTION_1] PRIMARY KEY CLUSTERED ([QUESTION_ID] ASC),
    CONSTRAINT [FK_SWIFT_SURVEY_QUESTION_SWIFT_SURVEY] FOREIGN KEY ([SURVEY_ID]) REFERENCES [SONDA].[SWIFT_SURVEY] ([SURVEY_ID]),
    CONSTRAINT [FK_SWIFT_SURVEY_QUESTION_SWIFT_SURVEY_PAGE] FOREIGN KEY ([PAGE_ID]) REFERENCES [SONDA].[SWIFT_SURVEY_PAGE] ([PAGE_ID])
);

