CREATE TABLE [SONDA].[SWIFT_CUSTOMER_ASSOCIATE_TO_POLYGON] (
    [ASSOCIATE_ID]  INT           IDENTITY (1, 1) NOT NULL,
    [POLYGON_ID]    INT           NULL,
    [POLYGON_NAME]  VARCHAR (250) NULL,
    [POLYGON_TYPE]  VARCHAR (250) NULL,
    [CODE_CUSTOMER] VARCHAR (50)  NULL,
    [GPS_CUSTOMER]  VARCHAR (MAX) NULL,
    [LAST_UPDATE]   DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ASSOCIATE_ID] ASC),
    CONSTRAINT [FK_CUSTOMER_ASSOCIATE_POLYGON] FOREIGN KEY ([POLYGON_ID]) REFERENCES [SONDA].[SWIFT_POLYGON] ([POLYGON_ID])
);

