CREATE TABLE [SONDA].[SWIFT_PROMO_BY_COMBO_PROMO_RULE] (
    [PROMO_RULE_BY_COMBO_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [COMBO_ID]                 INT          NOT NULL,
    [BONUS_TYPE]               VARCHAR (50) DEFAULT ('UNIQUE') NOT NULL,
    [BONUS_SUB_TYPE]           VARCHAR (50) NOT NULL,
    [IS_BONUS_BY_LOW_PURCHASE] INT          DEFAULT ((0)) NOT NULL,
    [IS_BONUS_BY_COMBO]        INT          DEFAULT ((1)) NOT NULL,
    [LOW_QTY]                  INT          NOT NULL,
    [LAST_UPDATE]              DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_RULE_BY_COMBO_ID] ASC),
    FOREIGN KEY ([COMBO_ID]) REFERENCES [SONDA].[SWIFT_COMBO] ([COMBO_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PROMO_BY_COMBO_PROMO_RULE_COMBO_ID]
    ON [SONDA].[SWIFT_PROMO_BY_COMBO_PROMO_RULE]([COMBO_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BY_COMBO_PROMO_RULE_LAST_UPDATE]
    ON [SONDA].[SWIFT_PROMO_BY_COMBO_PROMO_RULE]([LAST_UPDATE] ASC);

