CREATE TABLE [SONDA].[SWIFT_TRADE_AGREEMENT_BY_CHANNEL] (
    [TRADE_AGREEMENT_ID] INT      NOT NULL,
    [CHANNEL_ID]         INT      NOT NULL,
    [LAST_UPDATE]        DATETIME DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_AGREEMENT_ID] ASC, [CHANNEL_ID] ASC),
    CONSTRAINT [FK__SWIFT_TRA__CHANN__4A4F9D4A] FOREIGN KEY ([CHANNEL_ID]) REFERENCES [SONDA].[SWIFT_CHANNEL] ([CHANNEL_ID]),
    CONSTRAINT [FK__SWIFT_TRA__TRADE__495B7911] FOREIGN KEY ([TRADE_AGREEMENT_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT] ([TRADE_AGREEMENT_ID]),
    CONSTRAINT [UC_SWIFT_TRADE_AGREEMENT_BY_CHANNEL_CHANNEL_ID] UNIQUE NONCLUSTERED ([CHANNEL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_TRADE_AGREEMENT_BY_CHANNEL_]
    ON [SONDA].[SWIFT_TRADE_AGREEMENT_BY_CHANNEL]([CHANNEL_ID] ASC, [TRADE_AGREEMENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_TRADE_AGREEMENT_BY_CHANNEL_LAST_UPDATE]
    ON [SONDA].[SWIFT_TRADE_AGREEMENT_BY_CHANNEL]([LAST_UPDATE] ASC);

