CREATE TABLE [SONDA].[SWIFT_FREQUENCY_BY_POLYGON] (
    [POLYGON_ID]   INT NOT NULL,
    [ID_FREQUENCY] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([POLYGON_ID] ASC, [ID_FREQUENCY] ASC),
    FOREIGN KEY ([ID_FREQUENCY]) REFERENCES [SONDA].[SWIFT_FREQUENCY] ([ID_FREQUENCY]),
    FOREIGN KEY ([POLYGON_ID]) REFERENCES [SONDA].[SWIFT_POLYGON] ([POLYGON_ID])
);

