CREATE TABLE [SONDA].[SWIFT_DISTRIBUTION_CENTER] (
    [DISTRIBUTION_CENTER_ID]          INT             IDENTITY (1, 1) NOT NULL,
    [NAME_DISTRIBUTION_CENTER]        VARCHAR (250)   NOT NULL,
    [DESCRIPTION_DISTRIBUTION_CENTER] VARCHAR (250)   NULL,
    [LOGO_IMG]                        VARCHAR (MAX)   NULL,
    [LAST_UPDATE_BY]                  VARCHAR (50)    NOT NULL,
    [LAST_UPDATE_DATETIME]            DATETIME        NOT NULL,
    [ADRESS_DISTRIBUTION_CENTER]      VARCHAR (250)   NOT NULL,
    [LATITUDE]                        NUMERIC (18, 8) NOT NULL,
    [LONGITUDE]                       NUMERIC (18, 8) NOT NULL,
    PRIMARY KEY CLUSTERED ([DISTRIBUTION_CENTER_ID] ASC),
    UNIQUE NONCLUSTERED ([NAME_DISTRIBUTION_CENTER] ASC)
);

