CREATE TABLE [SONDA].[SWIFT_TAG_X_CUSTOMER_NEW] (
    [TAG_COLOR]           VARCHAR (8)  NOT NULL,
    [CUSTOMER]            VARCHAR (50) NOT NULL,
    [DEVICE_NETWORK_TYPE] VARCHAR (15) NULL,
    [IS_POSTED_OFFLINE]   INT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SWIFT_TAG_X_CUSTOMER_NEW] PRIMARY KEY CLUSTERED ([TAG_COLOR] ASC, [CUSTOMER] ASC),
    CONSTRAINT [FK_SWIFT_TAG_X_CUSTOMER_NEW_SWIFT_TAGS] FOREIGN KEY ([TAG_COLOR]) REFERENCES [SONDA].[SWIFT_TAGS] ([TAG_COLOR])
);

