CREATE TABLE [SONDA].[SWIFT_RULE_X_EVENT] (
    [RULE_ID]     INT NOT NULL,
    [EVENT_ID]    INT NOT NULL,
    [EVENT_ORDER] INT NOT NULL,
    CONSTRAINT [PK_SWIFT_RULE_X_EVENT] PRIMARY KEY CLUSTERED ([RULE_ID] ASC, [EVENT_ID] ASC),
    CONSTRAINT [FK_SWIFT_RULE_X_EVENT_SWIFT_EVENT] FOREIGN KEY ([EVENT_ID]) REFERENCES [SONDA].[SWIFT_EVENT] ([EVENT_ID]),
    CONSTRAINT [FK_SWIFT_RULE_X_EVENT_SWIFT_RULE] FOREIGN KEY ([RULE_ID]) REFERENCES [SONDA].[SWIFT_RULE] ([RULE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_RULE_X_EVENT_RULE_ID_EVENT_ID]
    ON [SONDA].[SWIFT_RULE_X_EVENT]([RULE_ID] ASC, [EVENT_ID] ASC)
    INCLUDE([EVENT_ORDER]);

