CREATE TABLE [SONDA].[SWIFT_GEOPOSITION_X_CUSTOMER] (
    [WEIGHT]         DECIMAL (19, 6) NULL,
    [LONGITUDE]      DECIMAL (19, 6) NOT NULL,
    [LATITUDE]       DECIMAL (19, 6) NOT NULL,
    [GEOPOSITION_ID] INT             NOT NULL,
    [CUSTOMER_ID]    VARCHAR (20)    NULL,
    [AVG_VOLUME]     DECIMAL (19, 6) NULL,
    [AREA_ID]        VARCHAR (20)    NULL
);

