CREATE TABLE [SONDA].[SWIFT_UPDATE] (
    [ID_UPDATE]   INT           IDENTITY (1, 1) NOT NULL,
    [SUITE]       VARCHAR (50)  NULL,
    [SPRINT]      VARCHAR (10)  NULL,
    [LAST_SCRIPT] VARCHAR (150) NULL,
    [UPDATE_BY]   VARCHAR (50)  NULL,
    [LAST_UPDATE] DATETIME      NULL,
    [COMMENT]     VARCHAR (MAX) NULL
);

