CREATE TABLE [SONDA].[SWIFT_PRIVILEGES] (
    [ID]             NUMERIC (18)  NOT NULL,
    [PRIVILEGE_ID]   VARCHAR (50)  NOT NULL,
    [PARENT_ID]      VARCHAR (50)  NULL,
    [SEQUENCE]       NUMERIC (18)  NOT NULL,
    [NAME]           VARCHAR (100) NOT NULL,
    [PRIVILEGE_TYPE] VARCHAR (50)  NOT NULL,
    [DISPLAY_NAME]   VARCHAR (50)  NOT NULL,
    [IMAGE_URL]      VARCHAR (50)  NULL,
    [DESCRIPTION]    VARCHAR (100) NULL,
    [ACTIVE]         BIT           DEFAULT ((1)) NOT NULL,
    [URL]            VARCHAR (200) NULL,
    [IS_PATER]       INT           NULL,
    [ACCESS]         VARCHAR (50)  DEFAULT ('PUBLIC') NOT NULL,
    [IS_SCREEN]      INT           DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_SWIFT_PRIVILEGES] PRIMARY KEY CLUSTERED ([PRIVILEGE_ID] ASC),
    CONSTRAINT [FK_SWIFT_PRIVILEGES_SWIFT_PRIVILEGES] FOREIGN KEY ([PARENT_ID]) REFERENCES [SONDA].[SWIFT_PRIVILEGES] ([PRIVILEGE_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PRIVILEGES_ID]
    ON [SONDA].[SWIFT_PRIVILEGES]([ID] ASC)
    INCLUDE([DISPLAY_NAME], [SEQUENCE], [PRIVILEGE_ID], [IS_SCREEN]);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PRIVILEGES_PRIVILEGE_ID]
    ON [SONDA].[SWIFT_PRIVILEGES]([PRIVILEGE_ID] ASC)
    INCLUDE([DISPLAY_NAME], [SEQUENCE], [ID]);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PRIVILEGES_PRIVILEGE_ID_ACTIVE]
    ON [SONDA].[SWIFT_PRIVILEGES]([PRIVILEGE_ID] ASC)
    INCLUDE([ACTIVE]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla para manejar los privilegios ', @level0type = N'SCHEMA', @level0name = N'SONDA', @level1type = N'TABLE', @level1name = N'SWIFT_PRIVILEGES';

