CREATE TABLE [SONDA].[SWIFT_BRANCHES] (
    [BRANCH_PK]       INT           IDENTITY (1, 1) NOT NULL,
    [CUSTOMER_CODE]   VARCHAR (50)  NOT NULL,
    [BRANCH_CODE]     VARCHAR (50)  NOT NULL,
    [BRANCH_PDE]      VARCHAR (50)  NULL,
    [BRANCH_NAME]     VARCHAR (150) NULL,
    [BRANCH_ADDRESS]  VARCHAR (350) NULL,
    [GEO_ROUTE]       VARCHAR (50)  NULL,
    [GPS_LAT_LON]     VARCHAR (150) NULL,
    [PHONE]           VARCHAR (25)  NULL,
    [DELIVERY_EMAIL]  VARCHAR (200) NULL,
    [RECOLLECT_EMAIL] VARCHAR (200) NULL,
    [STATUS]          VARCHAR (20)  NULL,
    [LAST_UPDATED]    DATETIME      NULL,
    [LAST_UPDATED_BY] VARCHAR (25)  NULL,
    [CONTACT_NAME]    VARCHAR (150) NULL,
    [IS_DEFAULT]      INT           NULL,
    CONSTRAINT [PK_SWIFT_BRANCHES] PRIMARY KEY CLUSTERED ([BRANCH_PK] ASC)
);

