CREATE TABLE [SONDA].[SWIFT_BONUS_LIST_BY_COMBO_SKU] (
    [BONUS_LIST_ID]  INT          NOT NULL,
    [COMBO_ID]       INT          NOT NULL,
    [CODE_SKU]       VARCHAR (50) NOT NULL,
    [CODE_PACK_UNIT] VARCHAR (50) NOT NULL,
    [QTY]            INT          NULL,
    [IS_MULTIPLE]    INT          NULL,
    PRIMARY KEY CLUSTERED ([BONUS_LIST_ID] ASC, [COMBO_ID] ASC, [CODE_SKU] ASC, [CODE_PACK_UNIT] ASC),
    CONSTRAINT [FK__SWIFT_BON__BONUS__155D7D75] FOREIGN KEY ([BONUS_LIST_ID]) REFERENCES [SONDA].[SWIFT_BONUS_LIST] ([BONUS_LIST_ID]),
    CONSTRAINT [FK__SWIFT_BON__COMBO__1651A1AE] FOREIGN KEY ([COMBO_ID]) REFERENCES [SONDA].[SWIFT_COMBO] ([COMBO_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_BONUS_LIST_BY_COMBO_SKU_COMBO_ID]
    ON [SONDA].[SWIFT_BONUS_LIST_BY_COMBO_SKU]([COMBO_ID] ASC);

