CREATE TABLE [SONDA].[SWIFT_SURVEY_ANSWER] (
    [ANSWER_ID]           NUMERIC (18)  NOT NULL,
    [SURVEY_ID]           NUMERIC (18)  NOT NULL,
    [QUESTION_ID]         NUMERIC (18)  NOT NULL,
    [ANSWER]              VARCHAR (250) NOT NULL,
    [VALIDATION_FUNCTION] VARCHAR (50)  NULL,
    [ORDER]               SMALLINT      NOT NULL,
    CONSTRAINT [PK_SWIFT_SURVEY_ANSWER_1] PRIMARY KEY CLUSTERED ([ANSWER_ID] ASC),
    CONSTRAINT [FK_SWIFT_SURVEY_ANSWER_SWIFT_SURVEY] FOREIGN KEY ([SURVEY_ID]) REFERENCES [SONDA].[SWIFT_SURVEY] ([SURVEY_ID]),
    CONSTRAINT [FK_SWIFT_SURVEY_ANSWER_SWIFT_SURVEY_QUESTION] FOREIGN KEY ([QUESTION_ID]) REFERENCES [SONDA].[SWIFT_SURVEY_QUESTION] ([QUESTION_ID])
);

