CREATE TABLE [SONDA].[SWIFT_SKU_SALES_BY_MULTIPLE_PRIORITY] (
    [SALES_BY_MULTIPLE_PRORITY_ID] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]                  VARCHAR (250) NULL,
    [ORDER]                        INT           NULL,
    [ACTIVE_SWIFT_EXPRESS]         INT           NULL,
    [SP_SWIFT_EXPRESS]             VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([SALES_BY_MULTIPLE_PRORITY_ID] ASC)
);

