CREATE TABLE [SONDA].[SWIFT_PICKING_HEADER] (
    [PICKING_HEADER]         INT           IDENTITY (1, 1) NOT NULL,
    [CLASSIFICATION_PICKING] VARCHAR (50)  NULL,
    [CODE_CLIENT]            VARCHAR (50)  NULL,
    [CODE_USER]              VARCHAR (50)  NULL,
    [REFERENCE]              VARCHAR (50)  NULL,
    [DOC_SAP_RECEPTION]      VARCHAR (150) NULL,
    [STATUS]                 VARCHAR (50)  NULL,
    [LAST_UPDATE]            DATETIME      NULL,
    [LAST_UPDATE_BY]         VARCHAR (50)  NULL,
    [COMMENTS]               VARCHAR (MAX) NULL,
    [SCHEDULE_FOR]           DATE          NULL,
    [SEQ]                    INT           NULL,
    [FF]                     VARCHAR (1)   NULL,
    [FF_STATUS]              VARCHAR (20)  NULL,
    [ATTEMPTED_WITH_ERROR]   INT           NULL,
    [IS_POSTED_ERP]          INT           NULL,
    [POSTED_ERP]             DATETIME      NULL,
    [POSTED_RESPONSE]        VARCHAR (150) NULL,
    [CODE_WAREHOUSE_SOURCE]  VARCHAR (50)  NULL,
    [SOURCE_DOC_TYPE]        VARCHAR (15)  NULL,
    [SOURCE_DOC]             INT           NULL,
    [TARGET_DOC]             INT           NULL,
    [CODE_SELLER]            VARCHAR (50)  NULL,
    [CODE_ROUTE]             VARCHAR (50)  NULL,
    [ERP_REFERENCE]          VARCHAR (256) NULL,
    PRIMARY KEY CLUSTERED ([PICKING_HEADER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PICKING_HEADER_PICKING_HEADER_CODE_CLIENT_CODE_USER_STATUS]
    ON [SONDA].[SWIFT_PICKING_HEADER]([PICKING_HEADER] ASC, [CODE_CLIENT] ASC, [CODE_USER] ASC, [STATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PICKING_HEADER_CODE_CLIENT]
    ON [SONDA].[SWIFT_PICKING_HEADER]([CODE_CLIENT] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PICKING_HEADER_CODE_USER]
    ON [SONDA].[SWIFT_PICKING_HEADER]([CODE_USER] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PICKING_HEADER_STATUS]
    ON [SONDA].[SWIFT_PICKING_HEADER]([STATUS] ASC);

