CREATE TABLE [SONDA].[SWIFT_SKU_BY_COMBO] (
    [COMBO_ID]    INT          NOT NULL,
    [CODE_SKU]    VARCHAR (50) NOT NULL,
    [PACK_UNIT]   INT          NOT NULL,
    [QTY]         INT          NOT NULL,
    [LAST_UPDATE] DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([COMBO_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC),
    CONSTRAINT [FK__SWIFT_SKU__COMBO__350B32F8] FOREIGN KEY ([COMBO_ID]) REFERENCES [SONDA].[SWIFT_COMBO] ([COMBO_ID]),
    CONSTRAINT [FK__SWIFT_SKU__PACK___35FF5731] FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT])
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_SKU_BY_COMBO_LAST_UPDATE]
    ON [SONDA].[SWIFT_SKU_BY_COMBO]([LAST_UPDATE] ASC);

