CREATE TABLE [SONDA].[SWIFT_SKU_BASE_PRICE_BY_PACK] (
    [CODE_PRICE_LIST] VARCHAR (25)    NOT NULL,
    [CODE_SKU]        VARCHAR (50)    NOT NULL,
    [CODE_PACK_UNIT]  VARCHAR (25)    NOT NULL,
    [PRICE]           NUMERIC (18, 6) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODE_PRICE_LIST] ASC, [CODE_SKU] ASC, [CODE_PACK_UNIT] ASC)
);

