CREATE TABLE [SONDA].[SWIFT_DISCOUNT_PRIORITY] (
    [DISCOUNT_PRIORITY_ID]                       INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]                                VARCHAR (250) NULL,
    [ORDER]                                      INT           NULL,
    [ACTIVE_SWIFT_EXPRESS]                       INT           NULL,
    [ACTIVE_SWIFT_INTERFACE_ONLINE]              INT           NULL,
    [SP_SWIFT_EXPRESS]                           VARCHAR (250) NULL,
    [SP_SWIFT_INTERFACE_ONLINE]                  VARCHAR (250) NULL,
    [LINKED_TO]                                  VARCHAR (250) NULL,
    [SP_SWIFT_EXPRESS_GENERAL_AMOUNT]            VARCHAR (250) NULL,
    [SP_SWIFT_EXPRESS_GENERAL_AMOUNT_AND_FAMILY] VARCHAR (250) NULL,
    [SP_SWIFT_EXPRESS_FAMILY_AND_PAYMENT_TYPE]   VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([DISCOUNT_PRIORITY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_DISCOUNT_PRIORITY_ORDER_ACTIVE_SWIFT_EXPRESS]
    ON [SONDA].[SWIFT_DISCOUNT_PRIORITY]([ORDER] ASC, [ACTIVE_SWIFT_EXPRESS] ASC)
    INCLUDE([DISCOUNT_PRIORITY_ID], [LINKED_TO]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_DISCOUNT_PRIORITY_ORDER_ACTIVE_SWIFT_INTERFACE_ONLINE]
    ON [SONDA].[SWIFT_DISCOUNT_PRIORITY]([ORDER] ASC, [ACTIVE_SWIFT_INTERFACE_ONLINE] ASC);

