CREATE TABLE [SONDA].[SWIFT_SKU_FAMILY] (
    [CODE_FAMILY_SKU]        VARCHAR (50)  NULL,
    [DESCRIPTION_FAMILY_SKU] VARCHAR (255) NULL,
    [ORDER]                  INT           NULL,
    [LAST_UPDATE]            DATETIME      NULL,
    [LAST_UPDATE_BY]         VARCHAR (50)  NULL
);

