CREATE TABLE [SONDA].[SWIFT_DISCOUNT_LIST_BY_PAYMENT_TYPE_AND_FAMILY] (
    [DISCOUNT_LIST_ID] INT             NOT NULL,
    [PAYMENT_TYPE]     VARCHAR (50)    NOT NULL,
    [CODE_FAMILY]      VARCHAR (50)    NOT NULL,
    [DISCOUNT_TYPE]    VARCHAR (50)    NOT NULL,
    [DISCOUNT]         NUMERIC (18, 6) NOT NULL,
    [PROMO_ID]         INT             NULL,
    [PROMO_NAME]       VARCHAR (250)   NULL,
    [PROMO_TYPE]       VARCHAR (50)    NULL,
    [FREQUENCY]        VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([DISCOUNT_LIST_ID] ASC, [PAYMENT_TYPE] ASC, [CODE_FAMILY] ASC, [DISCOUNT_TYPE] ASC),
    CONSTRAINT [FK_SWIFT_DISCOUNT_LIST_BY_PAYMENT_TYPE_AND_FAMILY_SWIFT_DISCOUNT_LIST] FOREIGN KEY ([DISCOUNT_LIST_ID]) REFERENCES [SONDA].[SWIFT_DISCOUNT_LIST] ([DISCOUNT_LIST_ID])
);

