CREATE TABLE [SONDA].[SWIFT_USER_BY_TEAM] (
    [TEAM_ID] INT NOT NULL,
    [USER_ID] INT NOT NULL,
    CONSTRAINT [FK_SWIFT_USER_BY_TEAM_TEAM_ID] FOREIGN KEY ([TEAM_ID]) REFERENCES [SONDA].[SWIFT_TEAM] ([TEAM_ID]),
    CONSTRAINT [FK_SWIFT_USER_BY_TEAM_USER_ID] FOREIGN KEY ([USER_ID]) REFERENCES [SONDA].[USERS] ([CORRELATIVE])
);

