CREATE TABLE [SONDA].[SWIFT_BONUS_LIST_BY_GENERAL_AMOUNT] (
    [BONUS_LIST_ID]        INT          NOT NULL,
    [LOW_LIMIT]            INT          NOT NULL,
    [HIGH_LIMIT]           INT          NOT NULL,
    [CODE_SKU_BONUS]       VARCHAR (50) NOT NULL,
    [CODE_PACK_UNIT_BONUS] INT          NOT NULL,
    [BONUS_QTY]            INT          NOT NULL,
    [PROMO_ID]             INT          NOT NULL,
    [PROMO_NAME]           VARCHAR (50) NOT NULL,
    [PROMO_TYPE]           VARCHAR (50) NOT NULL,
    [FREQUENCY]            VARCHAR (50) NULL,
    CONSTRAINT [PK_SWIFT_BONUS_LIST_BY_GENERAL_AMOUNT] PRIMARY KEY CLUSTERED ([BONUS_LIST_ID] ASC, [LOW_LIMIT] ASC, [CODE_SKU_BONUS] ASC, [CODE_PACK_UNIT_BONUS] ASC),
    CONSTRAINT [FK_SWIFT_BONUS_LIST_BY_GENERAL_AMOUNT_BONUS_LIST_ID] FOREIGN KEY ([BONUS_LIST_ID]) REFERENCES [SONDA].[SWIFT_BONUS_LIST] ([BONUS_LIST_ID])
);

