CREATE TABLE [SONDA].[SWIFT_TAG_X_CUSTOMER] (
    [TAG_COLOR] VARCHAR (8)  NOT NULL,
    [CUSTOMER]  VARCHAR (50) NOT NULL,
    CONSTRAINT [PK__SWIFT_TA__604C55CC5A1103C7] PRIMARY KEY CLUSTERED ([TAG_COLOR] ASC, [CUSTOMER] ASC)
);

