CREATE TABLE [SONDA].[SWIFT_SKU_INTERCOMPANY] (
    [SKU_INTERCOMPAY] INT          IDENTITY (1, 1) NOT NULL,
    [MASTER_ID]       VARCHAR (50) NOT NULL,
    [ITEM_CODE]       VARCHAR (50) NOT NULL,
    [SOURCE]          VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([SKU_INTERCOMPAY] ASC)
);

