CREATE TABLE [SONDA].[SWIFT_SPECIAL_PRICE_LIST_BY_CUSTOMER] (
    [SPECIAL_PRICE_LIST_ID] INT          NOT NULL,
    [CODE_CUSTOMER]         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SWIFT_SPECIAL_PRICE_LIST_BY_CUSTOMER] PRIMARY KEY CLUSTERED ([SPECIAL_PRICE_LIST_ID] ASC, [CODE_CUSTOMER] ASC),
    CONSTRAINT [FK_SWIFT_SPECIAL_PRICE_LIST_BY_CUSTOMER_TO_SPECIAL_PRICE_LIST] FOREIGN KEY ([SPECIAL_PRICE_LIST_ID]) REFERENCES [SONDA].[SWIFT_SPECIAL_PRICE_LIST] ([SPECIAL_PRICE_LIST_ID])
);

