CREATE TABLE [SONDA].[SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY] (
    [PROMO_DISCOUNT_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]          INT             NOT NULL,
    [CODE_FAMILY_SKU]   VARCHAR (50)    NOT NULL,
    [PAYMENT_TYPE]      VARCHAR (50)    NOT NULL,
    [DISCOUNT_TYPE]     VARCHAR (50)    DEFAULT ('PERCENTAGE') NOT NULL,
    [DISCOUNT]          NUMERIC (18, 6) NOT NULL,
    [LAST_UPDATE]       DATETIME        DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_DISCOUNT_ID] ASC),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY_T0]
    ON [SONDA].[SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY]([CODE_FAMILY_SKU] ASC, [PROMO_ID] ASC)
    INCLUDE([PROMO_DISCOUNT_ID], [DISCOUNT], [DISCOUNT_TYPE]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY_LAST_UPDATE]
    ON [SONDA].[SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY_PROMO_ID]
    ON [SONDA].[SWIFT_PROMO_DISCOUNT_BY_PAYMENT_TYPE_AND_FAMILY]([PROMO_ID] ASC)
    INCLUDE([CODE_FAMILY_SKU], [PAYMENT_TYPE], [DISCOUNT], [DISCOUNT_TYPE]);

