CREATE TABLE [SONDA].[SWIFT_SETUP_EXTERNAL_SOURCE] (
    [EXTERNAL_SOURCE_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [DATABASE_NAME]           VARCHAR (50)  NULL,
    [INTERFACE_DATABASE_NAME] VARCHAR (50)  NULL,
    [SCHEMA_NAME]             VARCHAR (50)  NULL,
    [COMMENT]                 VARCHAR (250) NULL,
    [LINKED_SERVER]           VARCHAR (50)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_DATABASE_SCHEMA_EXTERNAL_SOURCE]
    ON [SONDA].[SWIFT_SETUP_EXTERNAL_SOURCE]([EXTERNAL_SOURCE_ID] ASC)
    INCLUDE([DATABASE_NAME], [SCHEMA_NAME]);

