CREATE TABLE [SONDA].[SWIFT_WAREHOUSE_X_DISTRIBUTION_CENTER] (
    [DISTRIBUTION_CENTER_ID] INT          NOT NULL,
    [CODE_WAREHOUSE]         VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([DISTRIBUTION_CENTER_ID] ASC, [CODE_WAREHOUSE] ASC),
    CONSTRAINT [FK__SWIFT_WAR__CODE___3945D830] FOREIGN KEY ([CODE_WAREHOUSE]) REFERENCES [SONDA].[SWIFT_WAREHOUSES] ([CODE_WAREHOUSE]),
    CONSTRAINT [FK__SWIFT_WAR__DISTR__3851B3F7] FOREIGN KEY ([DISTRIBUTION_CENTER_ID]) REFERENCES [SONDA].[SWIFT_DISTRIBUTION_CENTER] ([DISTRIBUTION_CENTER_ID]),
    UNIQUE NONCLUSTERED ([CODE_WAREHOUSE] ASC)
);

