CREATE TABLE [SONDA].[SWIFT_CUSTOMER_GPS_ASSOCIATE_TO_POLYGON] (
    [ASSOCIATE_CUSTOMER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [CODE_CUSTOMER]         VARCHAR (50)  NULL,
    [GPS]                   VARCHAR (MAX) NULL,
    [LAST_UPDATE]           DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ASSOCIATE_CUSTOMER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SWIFT_CUSTOMER_POLYGON]
    ON [SONDA].[SWIFT_CUSTOMER_GPS_ASSOCIATE_TO_POLYGON]([CODE_CUSTOMER] ASC);

