CREATE TABLE [SONDA].[SWIFT_DISCOUNT_LIST_BY_SKU] (
    [DISCOUNT_LIST_ID] INT             NOT NULL,
    [CODE_SKU]         VARCHAR (50)    NOT NULL,
    [PACK_UNIT]        INT             NOT NULL,
    [LOW_LIMIT]        INT             NOT NULL,
    [HIGH_LIMIT]       INT             NOT NULL,
    [DISCOUNT]         NUMERIC (18, 6) NOT NULL,
    [PROMO_ID]         INT             NULL,
    [PROMO_NAME]       VARCHAR (250)   NULL,
    [PROMO_TYPE]       VARCHAR (50)    NULL,
    [DISCOUNT_TYPE]    VARCHAR (50)    NULL,
    [FREQUENCY]        VARCHAR (50)    NULL,
    [IS_UNIQUE]        INT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([DISCOUNT_LIST_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC, [LOW_LIMIT] ASC, [HIGH_LIMIT] ASC),
    CONSTRAINT [FK__SWIFT_DIS__PACK___3F53B741] FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK_SWIFT_DISCOUNT_LIST_BY_SKU_SWIFT_DISCOUNT_LIST] FOREIGN KEY ([DISCOUNT_LIST_ID]) REFERENCES [SONDA].[SWIFT_DISCOUNT_LIST] ([DISCOUNT_LIST_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_DISCOUNT_LIST_BY_SKU_DISCOUNT_LIST_ID]
    ON [SONDA].[SWIFT_DISCOUNT_LIST_BY_SKU]([DISCOUNT_LIST_ID] ASC)
    INCLUDE([HIGH_LIMIT], [LOW_LIMIT], [PACK_UNIT], [PROMO_ID], [PROMO_NAME], [PROMO_TYPE], [CODE_SKU], [DISCOUNT]);

