CREATE TABLE [SONDA].[SWIFT_POLYGON_X_CUSTOMER] (
    [POLYGON_ID]    INT          NOT NULL,
    [CODE_CUSTOMER] VARCHAR (50) NOT NULL,
    [IS_NEW]        INT          DEFAULT ((0)) NULL,
    [HAS_PROPOSAL]  INT          DEFAULT ((0)) NULL,
    [HAS_FREQUENCY] INT          DEFAULT ((0)) NULL,
    CONSTRAINT [PK_POLYGON_X_CUSTOMER] PRIMARY KEY CLUSTERED ([POLYGON_ID] ASC, [CODE_CUSTOMER] ASC),
    CONSTRAINT [FK_POLYGON_X_CUSTOMER_POLYGON] FOREIGN KEY ([POLYGON_ID]) REFERENCES [SONDA].[SWIFT_POLYGON] ([POLYGON_ID])
);

