CREATE TABLE [SONDA].[SWIFT_PRICE_LIST] (
    [CODE_PRICE_LIST] VARCHAR (25)  NOT NULL,
    [NAME_PRICE_LIST] VARCHAR (50)  NULL,
    [COMMENT]         VARCHAR (250) NULL,
    [LAST_UPDATE]     DATE          NULL,
    [LAST_UPDATE_BY]  VARCHAR (50)  NULL,
    [OWNER]           VARCHAR (50)  NOT NULL,
    [OWNER_ID]        VARCHAR (50)  NULL,
    CONSTRAINT [PK_SWIFT_PRICE_LIST] PRIMARY KEY CLUSTERED ([OWNER] ASC, [CODE_PRICE_LIST] ASC)
);

