CREATE TABLE [SONDA].[SWIFT_PROMO_BONUS_BY_MULTIPLE] (
    [PROMO_BONUS_BY_MULTIPLE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]                   INT          NOT NULL,
    [CODE_SKU]                   VARCHAR (50) NOT NULL,
    [PACK_UNIT]                  INT          NULL,
    [MULTIPLE]                   NUMERIC (18) NOT NULL,
    [CODE_SKU_BONUS]             VARCHAR (50) NOT NULL,
    [PACK_UNIT_BONUS]            INT          NULL,
    [BONUS_QTY]                  NUMERIC (18) NOT NULL,
    [LAST_UPDATE]                DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_BONUS_BY_MULTIPLE_ID] ASC),
    FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PACK_UNIT_BONUS]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID]),
    UNIQUE NONCLUSTERED ([PROMO_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC, [CODE_SKU_BONUS] ASC, [PACK_UNIT_BONUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_PROMO]
    ON [SONDA].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([PROMO_ID] ASC)
    INCLUDE([CODE_SKU], [PACK_UNIT], [MULTIPLE], [CODE_SKU_BONUS], [PACK_UNIT_BONUS], [BONUS_QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_PROMO_PROMO_ID_PACK_UNIT]
    ON [SONDA].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([PROMO_ID] ASC, [PACK_UNIT] ASC, [PACK_UNIT_BONUS] ASC)
    INCLUDE([CODE_SKU], [MULTIPLE], [CODE_SKU_BONUS], [BONUS_QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_LAST_UPDATE]
    ON [SONDA].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([LAST_UPDATE] ASC);

