CREATE TABLE [SONDA].[SWIFT_TXNS] (
    [TXN_ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [MANIFEST_SOURCE]           INT             NULL,
    [SAP_REFERENCE]             VARCHAR (50)    NULL,
    [TASK_SOURCE_ID]            INT             NULL,
    [TXN_TYPE]                  VARCHAR (25)    NULL,
    [TXN_DESCRIPTION]           VARCHAR (50)    NULL,
    [TXN_CATEGORY]              VARCHAR (25)    NULL,
    [TXN_CREATED_STAMP]         DATETIME        NULL,
    [TXN_OPERATOR_ID]           VARCHAR (25)    NULL,
    [TXN_OPERATOR_NAME]         VARCHAR (250)   NULL,
    [TXN_CODE_SKU]              VARCHAR (50)    NULL,
    [TXN_DESCRIPTION_SKU]       VARCHAR (250)   NULL,
    [TXN_QTY]                   NUMERIC (18, 2) NULL,
    [HEADER_REFERENCE]          INT             NULL,
    [TXN_ATTEMPTED_WITH_ERROR]  INT             NULL,
    [TXN_IS_POSTED_ERP]         INT             NULL,
    [TXN_POSTED_ERP]            DATETIME        NULL,
    [TXN_POSTED_RESPONSE]       VARCHAR (150)   NULL,
    [TXN_SIGNATURE]             VARCHAR (MAX)   NULL,
    [TXN_TASK_SOURCE]           INT             NULL,
    [TXN_IMAGE_1]               VARCHAR (MAX)   NULL,
    [TXN_BATCH]                 VARCHAR (50)    NULL,
    [TXN_SERIE]                 VARCHAR (75)    NULL,
    [TXN_SOURCE_CODE_WAREHOUSE] VARCHAR (50)    NULL,
    [TXN_TARGET_CODE_WAREHOUSE] VARCHAR (50)    NULL,
    [TXN_SOURCE_CODE_LOCATION]  VARCHAR (50)    NULL,
    [TXN_TARGET_CODE_LOCATION]  VARCHAR (50)    NULL,
    [TXN_SOURCE_PALLET_ID]      INT             NULL,
    [TXN_TARGET_PALLET_ID]      INT             NULL,
    [TXN_BARCODE_SKU]           VARCHAR (50)    NULL,
    [TXN_COSTUMER_CODE]         VARCHAR (25)    NULL,
    [TXN_COSTUMER_NAME]         VARCHAR (250)   NULL,
    CONSTRAINT [PK_SONDA_TXNS] PRIMARY KEY CLUSTERED ([TXN_ID] ASC)
);

