CREATE TABLE [SONDA].[SWIFT_KPI] (
    [KPI]       INT           IDENTITY (1, 1) NOT NULL,
    [NAME]      VARCHAR (255) NOT NULL,
    [POSITION]  VARCHAR (50)  NOT NULL,
    [PARAMETER] VARCHAR (50)  NOT NULL,
    [KPI_TYPE]  VARCHAR (50)  NULL
);

