CREATE TABLE [SONDA].[SWIFT_PRICE_LIST_BY_SKU_PACK_SCALE_FOR_ROUTE] (
    [CODE_ROUTE]      VARCHAR (50)    NOT NULL,
    [CODE_PRICE_LIST] VARCHAR (25)    NOT NULL,
    [CODE_SKU]        VARCHAR (50)    NOT NULL,
    [CODE_PACK_UNIT]  VARCHAR (25)    NOT NULL,
    [PRIORITY]        NUMERIC (18)    NOT NULL,
    [LOW_LIMIT]       NUMERIC (18)    NOT NULL,
    [HIGH_LIMIT]      NUMERIC (18)    NOT NULL,
    [PRICE]           NUMERIC (18, 6) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODE_ROUTE] ASC, [CODE_PRICE_LIST] ASC, [CODE_SKU] ASC, [CODE_PACK_UNIT] ASC, [PRIORITY] ASC, [LOW_LIMIT] ASC, [HIGH_LIMIT] ASC)
);

