CREATE TABLE [SONDA].[SWIFT_DRIVERS] (
    [DRIVER]                INT          IDENTITY (1, 1) NOT NULL,
    [CODE_DRIVER]           VARCHAR (50) NULL,
    [NAME_DRIVER]           VARCHAR (50) NULL,
    [LICENSE_DRIVER]        VARCHAR (30) NULL,
    [PHONE_DRIVER]          VARCHAR (20) NULL,
    [CLASSIFICATION_DRIVER] VARCHAR (50) NULL,
    [LAST_UPDATE]           DATETIME     NULL,
    [LAST_UPDATE_BY]        VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([DRIVER] ASC)
);

