CREATE TABLE [SONDA].[SWIFT_SURVEY_PAGE] (
    [PAGE_ID]     NUMERIC (18)  NOT NULL,
    [SURVEY_ID]   NUMERIC (18)  NOT NULL,
    [NAME]        VARCHAR (50)  NOT NULL,
    [DESCRIPTION] VARCHAR (250) NULL,
    [ORDER]       SMALLINT      NOT NULL,
    CONSTRAINT [PK_SWIFT_SURVEY_PAGE_1] PRIMARY KEY CLUSTERED ([PAGE_ID] ASC),
    CONSTRAINT [FK_SWIFT_SURVEY_PAGE_SWIFT_SURVEY] FOREIGN KEY ([SURVEY_ID]) REFERENCES [SONDA].[SWIFT_SURVEY] ([SURVEY_ID])
);

