CREATE TABLE [SONDA].[SWIFT_BONUS_LIST_BY_SKU] (
    [BONUS_LIST_ID]         INT           NOT NULL,
    [CODE_SKU]              VARCHAR (50)  NOT NULL,
    [CODE_PACK_UNIT]        VARCHAR (25)  NOT NULL,
    [LOW_LIMIT]             NUMERIC (18)  NOT NULL,
    [HIGH_LIMIT]            NUMERIC (18)  NOT NULL,
    [CODE_SKU_BONUS]        VARCHAR (50)  NOT NULL,
    [BONUS_QTY]             INT           NULL,
    [CODE_PACK_UNIT_BONUES] VARCHAR (25)  NOT NULL,
    [PROMO_ID]              INT           NULL,
    [PROMO_NAME]            VARCHAR (250) NULL,
    [PROMO_TYPE]            VARCHAR (50)  NULL,
    [FREQUENCY]             VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([BONUS_LIST_ID] ASC, [CODE_SKU] ASC, [CODE_PACK_UNIT] ASC, [LOW_LIMIT] ASC, [HIGH_LIMIT] ASC, [CODE_SKU_BONUS] ASC, [CODE_PACK_UNIT_BONUES] ASC),
    CONSTRAINT [FK_SWIFT_BONUS_LIST_BY_SKU_SWIFT_BONUS_LIST] FOREIGN KEY ([BONUS_LIST_ID]) REFERENCES [SONDA].[SWIFT_BONUS_LIST] ([BONUS_LIST_ID])
);

