CREATE TABLE [SONDA].[SWIFT_SPECIAL_PRICE_LIST] (
    [SPECIAL_PRICE_LIST_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [SPECIAL_PRICE_LIST_NAME] VARCHAR (250) NULL,
    [CODE_ROUTE]              VARCHAR (50)  NULL,
    CONSTRAINT [PK_SWIFT_SPECIAL_PRICE_LIST] PRIMARY KEY CLUSTERED ([SPECIAL_PRICE_LIST_ID] ASC)
);

