CREATE TABLE [SONDA].[SWIFT_SEQUENCES] (
    [SEQUENCE_NAME]  VARCHAR (50) NOT NULL,
    [CURRENT_NUMBER] NUMERIC (18) NULL,
    CONSTRAINT [PK_SWIFT_SEQUENCES] PRIMARY KEY CLUSTERED ([SEQUENCE_NAME] ASC)
);

