CREATE TABLE [SONDA].[SWIFT_SKU] (
    [SKU]                  INT             IDENTITY (1, 1) NOT NULL,
    [CODE_SKU]             VARCHAR (50)    NULL,
    [DESCRIPTION_SKU]      VARCHAR (MAX)   NULL,
    [CLASSIFICATION_SKU]   VARCHAR (50)    NULL,
    [BARCODE_SKU]          VARCHAR (50)    NULL,
    [CODE_PROVIDER]        VARCHAR (50)    NULL,
    [COST]                 FLOAT (53)      NULL,
    [MEASURE]              VARCHAR (50)    NULL,
    [LAST_UPDATE]          DATETIME        NULL,
    [LAST_UPDATE_BY]       VARCHAR (50)    NULL,
    [HANDLE_SERIAL_NUMBER] VARCHAR (2)     NULL,
    [HANDLE_BATCH]         VARCHAR (2)     NULL,
    [UNIT_MEASURE_SKU]     INT             NULL,
    [WEIGHT_SKU]           NUMERIC (18, 2) NULL,
    [VOLUME_SKU]           NUMERIC (18, 2) NULL,
    [LONG_SKU]             NUMERIC (18, 2) NULL,
    [WIDTH_SKU]            NUMERIC (18, 2) NULL,
    [HIGH_SKU]             NUMERIC (18, 2) NULL,
    [CODE_FAMILY_SKU]      VARCHAR (50)    NULL,
    [HANDLE_DIMENSION]     INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK__SWIFT_SK__CA1ECF0C0F975522] PRIMARY KEY CLUSTERED ([SKU] ASC),
    FOREIGN KEY ([CODE_FAMILY_SKU]) REFERENCES [SONDA].[SWIFT_FAMILY_SKU] ([CODE_FAMILY_SKU])
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_SKU_CODE_SKU]
    ON [SONDA].[SWIFT_SKU]([CODE_SKU] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_SKU_CODE_SKU_DESCRIPTION_SKU_CODE_FAMILY_SKU]
    ON [SONDA].[SWIFT_SKU]([CODE_SKU] ASC)
    INCLUDE([CODE_FAMILY_SKU]);

