CREATE TABLE [SONDA].[SWIFT_POLYGON_BY_DEPARTMENT_DETAIL] (
    [POSITION_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [POSITION]      INT          NOT NULL,
    [DEPARTMENT_ID] INT          NOT NULL,
    [LATITUDE]      VARCHAR (50) NOT NULL,
    [LONGITUDE]     VARCHAR (50) NOT NULL
);

