CREATE TABLE [SONDA].[SWIFT_WAREHOUSES_PRESALE_FOR_3PL] (
    [WAREHOUSE]             INT           IDENTITY (1, 1) NOT NULL,
    [CODE_WAREHOUSE]        VARCHAR (50)  NULL,
    [DESCRIPTION_WAREHOUSE] VARCHAR (MAX) NULL,
    [IS_WAREHOUSE_3PL]      INT           NULL
);

