CREATE TABLE [SONDA].[SWIFT_PRICE_LIST_BY_SKU] (
    [CODE_PRICE_LIST] VARCHAR (25)    NOT NULL,
    [CODE_SKU]        VARCHAR (50)    NOT NULL,
    [COST]            NUMERIC (18, 6) NULL,
    [CODE_PACK_UNIT]  VARCHAR (25)    NULL,
    [UM_ENTRY]        VARCHAR (250)   NULL,
    [OWNER]           VARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_SWIFT_PRICE_LIST_BY_SKU] PRIMARY KEY CLUSTERED ([OWNER] ASC, [CODE_PRICE_LIST] ASC, [CODE_SKU] ASC)
);

