CREATE TABLE [SONDA].[SWIFT_CUSTOMERS] (
    [CUSTOMER]                INT           IDENTITY (1, 1) NOT NULL,
    [CODE_CUSTOMER]           VARCHAR (50)  NULL,
    [NAME_CUSTOMER]           VARCHAR (50)  NULL,
    [PHONE_CUSTOMER]          VARCHAR (50)  NULL,
    [ADRESS_CUSTOMER]         VARCHAR (MAX) NULL,
    [CLASSIFICATION_CUSTOMER] VARCHAR (50)  NULL,
    [CONTACT_CUSTOMER]        VARCHAR (50)  NULL,
    [CODE_ROUTE]              VARCHAR (50)  NULL,
    [LAST_UPDATE]             DATETIME      NULL,
    [LAST_UPDATE_BY]          VARCHAR (50)  NULL,
    [SELLER_DEFAULT_CODE]     VARCHAR (50)  NULL,
    [CREDIT_LIMIT]            FLOAT (53)    NULL,
    [GPS]                     VARCHAR (MAX) CONSTRAINT [DF_SWIFT_CUSTOMERS_GPS] DEFAULT ('0,0') NULL,
    [FREQUENCY]               VARCHAR (50)  CONSTRAINT [DF_SWIFT_CUSTOMERS_FREQUENCY] DEFAULT ((1)) NULL,
    [MONDAY]                  VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_MONDAY] DEFAULT ((0)) NULL,
    [TUESDAY]                 VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_TUESDAY] DEFAULT ((0)) NULL,
    [WEDNESDAY]               VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_WEDNESDAY] DEFAULT ((0)) NULL,
    [THURSDAY]                VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_THURSDAY] DEFAULT ((0)) NULL,
    [FRIDAY]                  VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_FRIDAY] DEFAULT ((0)) NULL,
    [SATURDAY]                VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_SATURDAY] DEFAULT ((0)) NULL,
    [SUNDAY]                  VARCHAR (1)   CONSTRAINT [DF_SWIFT_CUSTOMERS_SUNDAY] DEFAULT ((0)) NULL,
    [LATITUDE]                VARCHAR (50)  CONSTRAINT [DF_SWIFT_CUSTOMERS_LATITUDE] DEFAULT ('0') NULL,
    [LONGITUDE]               VARCHAR (50)  CONSTRAINT [DF_SWIFT_CUSTOMERS_LONGITUDE] DEFAULT ('0') NULL,
    [SCOUTING_ROUTE]          VARCHAR (50)  NULL,
    CONSTRAINT [PK__SWIFT_CU__DFC107291367E606] PRIMARY KEY CLUSTERED ([CUSTOMER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_CUSTOMERS_CODE_CUSTOMER]
    ON [SONDA].[SWIFT_CUSTOMERS]([CODE_CUSTOMER] ASC)
    INCLUDE([CUSTOMER], [NAME_CUSTOMER], [ADRESS_CUSTOMER], [CODE_ROUTE], [SELLER_DEFAULT_CODE]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_ERP_CUSTOMERS_SELLER_DEFAULT_CODE]
    ON [SONDA].[SWIFT_CUSTOMERS]([SELLER_DEFAULT_CODE] ASC)
    INCLUDE([CODE_CUSTOMER]);


GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER_GPS]
    ON [SONDA].[SWIFT_CUSTOMERS]([CODE_CUSTOMER] ASC)
    INCLUDE([GPS], [PHONE_CUSTOMER]);

