CREATE TABLE [SONDA].[SWIFT_MEASURE_UNIT] (
    [CODE]         INT            NULL,
    [DESCRIPTION]  NVARCHAR (255) NULL,
    [ABBREVIATION] NVARCHAR (255) NULL,
    [TYPE]         NVARCHAR (255) NULL
);

