CREATE TABLE [SONDA].[SWIFT_VEHICLES] (
    [VEHICLE]                INT          IDENTITY (1, 1) NOT NULL,
    [CODE_VEHICLE]           VARCHAR (50) NULL,
    [PLATE_VEHICLE]          VARCHAR (50) NULL,
    [CLASSIFICATION_VEHICLE] VARCHAR (50) NULL,
    [MAXIMUM_WEIGHT]         FLOAT (53)   NULL,
    [BRAND]                  VARCHAR (20) NULL,
    [UNIT]                   VARCHAR (20) NULL,
    [LAST_UPDATE]            DATETIME     NULL,
    [LAST_UPDATE_BY]         VARCHAR (50) NULL,
    CONSTRAINT [PK__SWIFT_VE__E7568DB31BFD2C07] PRIMARY KEY CLUSTERED ([VEHICLE] ASC)
);

