CREATE TABLE [SONDA].[SWIFT_PROVIDERS] (
    [PROVIDER]                INT          IDENTITY (1, 1) NOT NULL,
    [CODE_PROVIDER]           VARCHAR (50) NULL,
    [NAME_PROVIDER]           VARCHAR (50) NULL,
    [CLASSIFICATION_PROVIDER] VARCHAR (50) NULL,
    [CONTACT_PROVIDER]        VARCHAR (50) NULL,
    [LAST_UPDATE]             DATETIME     NULL,
    [LAST_UPDATE_BY]          VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([PROVIDER] ASC)
);

