CREATE TABLE [SONDA].[SWIFT_PALLET] (
    [PALLET_ID]      INT          IDENTITY (1, 1) NOT NULL,
    [BATCH_ID]       INT          NOT NULL,
    [STATUS]         VARCHAR (20) NOT NULL,
    [QTY]            INT          NOT NULL,
    [LAST_UPDATE]    DATETIME     NOT NULL,
    [LAST_UPDATE_BY] VARCHAR (50) NOT NULL,
    [WAREHOUSE]      VARCHAR (50) NULL,
    [LOCATION]       VARCHAR (50) NULL,
    [TASK_ID]        INT          NOT NULL,
    CONSTRAINT [PK_SWIFT_PALLET] PRIMARY KEY CLUSTERED ([PALLET_ID] ASC),
    CONSTRAINT [FK_SWIFT_PALLET_BATCH_ID] FOREIGN KEY ([BATCH_ID]) REFERENCES [SONDA].[SWIFT_BATCH] ([BATCH_ID]),
    CONSTRAINT [FK_SWIFT_PALLET_TASK_ID] FOREIGN KEY ([TASK_ID]) REFERENCES [SONDA].[SWIFT_TASKS] ([TASK_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PALLET_TASK_ID]
    ON [SONDA].[SWIFT_PALLET]([TASK_ID] ASC);

