CREATE TABLE [SONDA].[SWIFT_TRADE_AGREEMENT_DISCOUNT_BY_GENERAL_AMOUNT] (
    [TRADE_AGREEMENT_ID] INT             NOT NULL,
    [LOW_AMOUNT]         NUMERIC (18, 6) NOT NULL,
    [HIGH_AMOUNT]        NUMERIC (18, 6) NOT NULL,
    [DISCOUNT]           NUMERIC (18, 6) NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_AGREEMENT_ID] ASC, [LOW_AMOUNT] ASC, [HIGH_AMOUNT] ASC),
    CONSTRAINT [FK__SWIFT_TRA__TRADE__2A589A5B] FOREIGN KEY ([TRADE_AGREEMENT_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT] ([TRADE_AGREEMENT_ID])
);

