CREATE TABLE [SONDA].[SWIFT_BONUS_LIST_BY_CUSTOMER] (
    [BONUS_LIST_ID] INT          NOT NULL,
    [CODE_CUSTOMER] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SWIFT_BONUS_LIST_BY_CUSTOMER] PRIMARY KEY CLUSTERED ([BONUS_LIST_ID] ASC, [CODE_CUSTOMER] ASC),
    CONSTRAINT [FK_SWIFT_BONUS_LIST_BY_CUSTOMER_MULTIPLE_SWIFT_BONUS_LIST] FOREIGN KEY ([BONUS_LIST_ID]) REFERENCES [SONDA].[SWIFT_BONUS_LIST] ([BONUS_LIST_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_BONUS_LIST_BY_CUSTOMER_T0]
    ON [SONDA].[SWIFT_BONUS_LIST_BY_CUSTOMER]([CODE_CUSTOMER] ASC)
    INCLUDE([BONUS_LIST_ID]);

