CREATE TABLE [SONDA].[SWIFT_CUSTOMER_INTERCOMPAY] (
    [CUSTOMER_INTERCOMPAY] INT          IDENTITY (1, 1) NOT NULL,
    [MASTER_ID]            VARCHAR (50) NOT NULL,
    [CARD_CODE]            VARCHAR (50) NOT NULL,
    [SOURCE]               VARCHAR (50) NOT NULL,
    [GROUPNUM]             VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([CUSTOMER_INTERCOMPAY] ASC),
    UNIQUE NONCLUSTERED ([MASTER_ID] ASC, [CARD_CODE] ASC, [SOURCE] ASC)
);

