CREATE TABLE [SONDA].[SWIFT_SALES_OFFICE] (
    [SALES_OFFICE_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [SALES_ORGANIZATION_ID]    INT          NULL,
    [NAME_SALES_OFFICE]        VARCHAR (50) NOT NULL,
    [DESCRIPTION_SALES_OFFICE] VARCHAR (50) NOT NULL,
    [SOURCE]                   VARCHAR (50) DEFAULT ('BO') NULL,
    PRIMARY KEY CLUSTERED ([SALES_OFFICE_ID] ASC),
    FOREIGN KEY ([SALES_ORGANIZATION_ID]) REFERENCES [SONDA].[SWIFT_SALES_ORGANIZATION] ([SALES_ORGANIZATION_ID]),
    UNIQUE NONCLUSTERED ([NAME_SALES_OFFICE] ASC)
);

