CREATE TABLE [SONDA].[SWIFT_PORTFOLIO] (
    [CODE_PORTFOLIO] VARCHAR (25)  NOT NULL,
    [NAME_PORTFOLIO] VARCHAR (50)  NULL,
    [COMMENT]        VARCHAR (250) NULL,
    [LAST_UPDATE]    DATE          NULL,
    [LAST_UPDATE_BY] VARCHAR (50)  NULL,
    CONSTRAINT [PK_SWIFT_PORTFOLIO] PRIMARY KEY CLUSTERED ([CODE_PORTFOLIO] ASC)
);

