CREATE TABLE [SONDA].[SWIFT_TRADE_AGREEMENT_BY_BONUS_RULE] (
    [TRADE_AGREEMENT_ID]                     INT NOT NULL,
    [TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_AGREEMENT_ID] ASC, [TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] ASC),
    CONSTRAINT [FK__SWIFT_TRA__TRADE__60E9B536] FOREIGN KEY ([TRADE_AGREEMENT_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT] ([TRADE_AGREEMENT_ID]),
    CONSTRAINT [FK__SWIFT_TRA__TRADE__61DDD96F] FOREIGN KEY ([TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE] ([TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID])
);

