CREATE TABLE [SONDA].[SWIFT_DISCOUNT_LIST_BY_GENERAL_AMOUNT] (
    [DISCOUNT_LIST_ID] INT             NOT NULL,
    [LOW_AMOUNT]       NUMERIC (18, 6) NOT NULL,
    [HIGH_AMOUNT]      NUMERIC (18, 6) NOT NULL,
    [DISCOUNT]         NUMERIC (18, 6) NOT NULL,
    [PROMO_ID]         INT             NULL,
    [PROMO_NAME]       VARCHAR (250)   NULL,
    [PROMO_TYPE]       VARCHAR (50)    NULL,
    [FREQUENCY]        VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([DISCOUNT_LIST_ID] ASC, [LOW_AMOUNT] ASC, [HIGH_AMOUNT] ASC),
    CONSTRAINT [FK_SWIFT_DISCOUNT_LIST_BY_GENERAL_AMOUNT_SWIFT_DISCOUNT_LIST] FOREIGN KEY ([DISCOUNT_LIST_ID]) REFERENCES [SONDA].[SWIFT_DISCOUNT_LIST] ([DISCOUNT_LIST_ID])
);

