CREATE TABLE [SONDA].[SWIFT_PORTFOLIO_BY_SKU] (
    [CODE_PORTFOLIO] VARCHAR (25) NOT NULL,
    [CODE_SKU]       VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SWIFT_PORTFOLIO_BY_SKU] PRIMARY KEY CLUSTERED ([CODE_PORTFOLIO] ASC, [CODE_SKU] ASC),
    CONSTRAINT [FK_SWIFT_PORTFOLIO_BY_SKU_SWIFT_PORTFOLIO] FOREIGN KEY ([CODE_PORTFOLIO]) REFERENCES [SONDA].[SWIFT_PORTFOLIO] ([CODE_PORTFOLIO])
);

