CREATE TABLE [SONDA].[SWIFT_TRADE_AGREEMENT_BONUS_BY_MULTIPLE] (
    [TRADE_AGREEMENT_BONUS_MULTIPLE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [TRADE_AGREEMENT_ID]                INT          NOT NULL,
    [CODE_SKU]                          VARCHAR (50) NOT NULL,
    [PACK_UNIT]                         INT          NULL,
    [MULTIPLE]                          NUMERIC (18) NOT NULL,
    [CODE_SKU_BONUS]                    VARCHAR (50) NOT NULL,
    [PACK_UNIT_BONUS]                   INT          NULL,
    [BONUS_QTY]                         NUMERIC (18) NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_AGREEMENT_BONUS_MULTIPLE_ID] ASC),
    CONSTRAINT [FK__SWIFT_TRA__PACK___2D150B75] FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK__SWIFT_TRA__PACK___2E092FAE] FOREIGN KEY ([PACK_UNIT_BONUS]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK__SWIFT_TRA__TRADE__2C20E73C] FOREIGN KEY ([TRADE_AGREEMENT_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT] ([TRADE_AGREEMENT_ID]),
    UNIQUE NONCLUSTERED ([TRADE_AGREEMENT_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC, [CODE_SKU_BONUS] ASC, [PACK_UNIT_BONUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_TRADE_AGREEMENT_BONUS_BY_MULTIPLE_TRADE_AGREEMENT]
    ON [SONDA].[SWIFT_TRADE_AGREEMENT_BONUS_BY_MULTIPLE]([TRADE_AGREEMENT_ID] ASC)
    INCLUDE([CODE_SKU], [PACK_UNIT], [MULTIPLE], [CODE_SKU_BONUS], [PACK_UNIT_BONUS], [BONUS_QTY]);

