CREATE TABLE [SONDA].[SWIFT_TXNS_SERIES] (
    [TXN_ID]              INT           NOT NULL,
    [TXN_CODE_SKU]        VARCHAR (50)  NOT NULL,
    [TXN_DESCRIPTION_SKU] VARCHAR (250) NULL,
    [TXN_SERIE]           VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_SWIFT_TXNS_SERIES] PRIMARY KEY CLUSTERED ([TXN_CODE_SKU] ASC, [TXN_SERIE] ASC)
);

