CREATE TABLE [SONDA].[SWIFT_TRADE_AGREEMENT_SKU_SALES_BY_MULTIPLE] (
    [TRADE_AGREEMENT_ID] INT          NOT NULL,
    [CODE_SKU]           VARCHAR (50) NOT NULL,
    [PACK_UNIT]          INT          NOT NULL,
    [MULTIPLE]           INT          DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_AGREEMENT_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC),
    CONSTRAINT [FK__SWIFT_TRA__PACK___018B8EF2] FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK_SWIFT_TRADE_AGREENENT] FOREIGN KEY ([TRADE_AGREEMENT_ID]) REFERENCES [SONDA].[SWIFT_TRADE_AGREEMENT] ([TRADE_AGREEMENT_ID])
);

