CREATE TABLE [SONDA].[SWIFT_GOAL_DETAIL] (
    [GOAL_DETAIL_ID]       INT             IDENTITY (1, 1) NOT NULL,
    [GOAL_HEADER_ID]       INT             NOT NULL,
    [SELLER_ID]            INT             NOT NULL,
    [GOAL_BY_SELLER]       DECIMAL (18, 6) NOT NULL,
    [DAILY_GOAL_BY_SELLER] DECIMAL (18, 6) NOT NULL,
    CONSTRAINT [PK_GOAL_HEADER] FOREIGN KEY ([GOAL_HEADER_ID]) REFERENCES [SONDA].[SWIFT_GOAL_HEADER] ([GOAL_HEADER_ID])
);

