CREATE TABLE [SONDA].[SWIFT_CYCLE_COUNT_DETAIL] (
    [COUNT]                 INT           IDENTITY (1, 1) NOT NULL,
    [COUNT_ID]              INT           NULL,
    [LOCATION]              VARCHAR (50)  NULL,
    [COUNT_OPERATOR]        VARCHAR (50)  NULL,
    [COUNT_POSTED]          DATETIME      NULL,
    [COUNT_SKU]             VARCHAR (50)  NULL,
    [COUNT_SKU_DESCRIPTION] VARCHAR (MAX) NULL,
    [COUNT_HIT_OR_MISS]     VARCHAR (1)   NULL,
    [COUNT_BATCH_ID]        VARCHAR (50)  NULL,
    [COUNT_SKU_COUNTED]     FLOAT (53)    NULL,
    [COUNT_SKU_ONHAND]      FLOAT (53)    NULL,
    [COUNT_STATUS]          VARCHAR (10)  NULL,
    CONSTRAINT [PK_SWIFT_CYCLE_COUNT_DETAIL] PRIMARY KEY CLUSTERED ([COUNT] ASC)
);

