CREATE TABLE [SONDA].[SWIFT_SURVEY] (
    [SURVEY_ID]       NUMERIC (18)  NOT NULL,
    [NAME]            VARCHAR (50)  NOT NULL,
    [DESCRIPTION]     VARCHAR (250) NULL,
    [LAST_UPDATED]    DATETIME      NOT NULL,
    [LAST_UPDATED_BY] VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_SWIFT_SURVEY_1] PRIMARY KEY CLUSTERED ([SURVEY_ID] ASC)
);

