CREATE TABLE [SONDA].[SWIFT_PROMO_BONUS_BY_SCALE] (
    [PROMO_BONUS_BY_SCALE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]                INT          NOT NULL,
    [CODE_SKU]                VARCHAR (50) NOT NULL,
    [PACK_UNIT]               INT          NULL,
    [LOW_LIMIT]               NUMERIC (18) NOT NULL,
    [HIGH_LIMIT]              NUMERIC (18) NOT NULL,
    [CODE_SKU_BONUS]          VARCHAR (50) NOT NULL,
    [PACK_UNIT_BONUS]         INT          NULL,
    [BONUS_QTY]               NUMERIC (18) NOT NULL,
    [LAST_UPDATE]             DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_BONUS_BY_SCALE_ID] ASC),
    FOREIGN KEY ([PACK_UNIT]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PACK_UNIT_BONUS]) REFERENCES [SONDA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [SONDA].[SWIFT_PROMO] ([PROMO_ID]),
    UNIQUE NONCLUSTERED ([PROMO_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC, [LOW_LIMIT] ASC, [CODE_SKU_BONUS] ASC, [PACK_UNIT_BONUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_SCALE_PROMO_ID]
    ON [SONDA].[SWIFT_PROMO_BONUS_BY_SCALE]([PROMO_ID] ASC)
    INCLUDE([PROMO_BONUS_BY_SCALE_ID], [CODE_SKU], [PACK_UNIT], [LOW_LIMIT], [HIGH_LIMIT], [CODE_SKU_BONUS], [PACK_UNIT_BONUS], [BONUS_QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_SCALE_LAST_UPDATE]
    ON [SONDA].[SWIFT_PROMO_BONUS_BY_SCALE]([LAST_UPDATE] ASC);

