CREATE TABLE [SONDA].[SWIFT_RULE] (
    [RULE_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [CODE]        VARCHAR (50)  NOT NULL,
    [NAME]        VARCHAR (150) NOT NULL,
    [DESCRIPTION] VARCHAR (150) NULL,
    CONSTRAINT [PK_RULE_EVENT] PRIMARY KEY CLUSTERED ([RULE_ID] ASC)
);

