CREATE TABLE [SONDA].[SWIFT_COMBO] (
    [COMBO_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [NAME_COMBO]        VARCHAR (250) NOT NULL,
    [DESCRIPTION_COMBO] VARCHAR (250) NOT NULL,
    [LAST_UPDATE]       DATETIME      DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([COMBO_ID] ASC),
    UNIQUE NONCLUSTERED ([NAME_COMBO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_COMBO_LAST_UPDATE]
    ON [SONDA].[SWIFT_COMBO]([LAST_UPDATE] ASC);

