CREATE TABLE [SONDA].[SWIFT_MANIFEST_HEADER] (
    [MANIFEST_HEADER]      INT           IDENTITY (1, 1) NOT NULL,
    [CODE_MANIFEST_HEADER] VARCHAR (50)  NULL,
    [CODE_DRIVER]          VARCHAR (50)  NULL,
    [CODE_VEHICLE]         VARCHAR (50)  NULL,
    [COMMENTS]             VARCHAR (MAX) NULL,
    [STATUS]               VARCHAR (50)  NULL,
    [LAST_UPDATE]          DATETIME      NULL,
    [LAST_UPDATE_BY]       VARCHAR (50)  NULL,
    [CODE_ROUTE]           NVARCHAR (50) NULL,
    [CREATED_DATE]         DATETIME      NULL,
    [ACCEPTED_STAMP]       DATETIME      NULL,
    [COMPLETED_STAMP]      DATETIME      NULL,
    [NAME_DRIVER]          VARCHAR (50)  NULL,
    [PLATE_VEHICLE]        VARCHAR (25)  NULL,
    [NAME_ROUTE]           VARCHAR (50)  NULL,
    [MANIFEST_SOURCE]      VARCHAR (25)  DEFAULT ('SWIFT_EXPRESS') NULL,
    PRIMARY KEY CLUSTERED ([MANIFEST_HEADER] ASC)
);

