CREATE TABLE [SONDA].[SWIFT_POLYGON_BY_ROUTE] (
    [ROUTE]           INT NOT NULL,
    [POLYGON_ID]      INT NOT NULL,
    [ID_FREQUENCY]    INT NULL,
    [IS_MULTIPOLYGON] INT DEFAULT ((0)) NOT NULL,
    [IS_MULTISELLER]  INT DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ROUTE] ASC, [POLYGON_ID] ASC),
    FOREIGN KEY ([ID_FREQUENCY]) REFERENCES [SONDA].[SWIFT_FREQUENCY] ([ID_FREQUENCY]),
    FOREIGN KEY ([POLYGON_ID]) REFERENCES [SONDA].[SWIFT_POLYGON] ([POLYGON_ID]),
    CONSTRAINT [FK_SWIFT_POLYGON_BY_ROUTE_ROUTE] FOREIGN KEY ([ROUTE]) REFERENCES [SONDA].[SWIFT_ROUTES] ([ROUTE]),
    CONSTRAINT [UC_SWIFT_POLYGON_BY_ROUTE_POLYGON_ID] UNIQUE NONCLUSTERED ([POLYGON_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_POLYGON_BY_ROUTE_ID_FREQUENCY]
    ON [SONDA].[SWIFT_POLYGON_BY_ROUTE]([ID_FREQUENCY] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_POLYGON_BY_ROUTE_ROUTE]
    ON [SONDA].[SWIFT_POLYGON_BY_ROUTE]([ROUTE] ASC);

