CREATE TABLE [SONDA].[SWIFT_CHANNEL_X_CUSTOMER] (
    [CHANNEL_ID]    INT          NOT NULL,
    [CODE_CUSTOMER] VARCHAR (50) NOT NULL,
    [LAST_UPDATE]   DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([CHANNEL_ID] ASC, [CODE_CUSTOMER] ASC),
    CONSTRAINT [FK__SWIFT_CHA__CHANN__2335D029] FOREIGN KEY ([CHANNEL_ID]) REFERENCES [SONDA].[SWIFT_CHANNEL] ([CHANNEL_ID]),
    CONSTRAINT [UC_SWIFT_CHANNEL_X_CUSTOMER_CODE_CUSTOMER] UNIQUE NONCLUSTERED ([CODE_CUSTOMER] ASC)
);

