

-- =============================================
-- Autor:				Alex Carrillo
-- Fecha de Creacion: 	02-04-2020
-- Description:			se crea vista para poder leer sin archivos xml desde SAE 

/*				
-- Ejemplo de Ejecucion:
				-- 

				SELECT * FROM [SONDA].[SONDA_VIEW_POS_INVOICE_HEADER]
*/
-- =============================================
CREATE VIEW [SONDA].[SONDA_VIEW_POS_INVOICE_HEADER]
AS
SELECT  [INVOICE_ID]
      ,[TERMS]
      ,[POSTED_DATETIME]
      ,[CLIENT_ID]
      ,[POS_TERMINAL]
      ,[GPS_URL]
      ,[TOTAL_AMOUNT]
      ,[STATUS]
      ,[POSTED_BY]
      ,[IMAGE_1]
      ,[IMAGE_2]
      ,[IMAGE_3]
      ,[IS_POSTED_OFFLINE]
      ,[INVOICED_DATETIME]
      ,[DEVICE_BATTERY_FACTOR]
      ,[CDF_INVOICENUM]
      ,[CDF_DOCENTRY]
      ,[CDF_SERIE]
      ,[CDF_NIT]
      ,[CDF_NOMBRECLIENTE]
      ,[CDF_RESOLUCION]
      ,[CDF_POSTED_ERP]
      ,[IS_CREDIT_NOTE]
      ,[VOID_DATETIME]
      ,[CDF_PRINTED_COUNT]
      ,[VOID_REASON]
      ,[VOID_NOTES]
      ,[VOIDED_INVOICE]
      ,[CLOSED_ROUTE_DATETIME]
      ,[CLEARING_DATETIME]
      ,[IS_ACTIVE_ROUTE]
      ,[SOURCE_CODE]
      ,[GPS_EXPECTED]
      ,[ATTEMPTED_WITH_ERROR]
      ,[IS_POSTED_ERP]
      ,[POSTED_ERP]
      ,[POSTED_RESPONSE]
      ,[IS_DRAFT]
      ,[ERP_REFERENCE]
      ,[CONSIGNMENT_ID]
      ,[LIQUIDATION_ID]
      ,[INITIAL_TASK_IMAGE]
      ,[IN_ROUTE_PLAN]
      ,[ID]
      ,[IS_READY_TO_SEND]
      ,[IS_SENDING]
      ,[LAST_UPDATE_IS_SENDING]
      ,[HANDLE_TAX]
      ,[TAX_PERCENT]
      ,[SIGNATURE]
      ,[TELEPHONE_NUMBER]
      ,[IS_FROM_DELIVERY_NOTE]
      ,[DISCOUNT]
      ,[COMMENT]
      ,[DUE_DATE]
      ,[CREDIT_AMOUNT]
      ,[CASH_AMOUNT]
      ,[PAID_TO_DATE]
      ,[GOAL_HEADER_ID]
      ,[TASK_ID]
      ,[IS_POSTED_ERP_PAYMENT]
      ,[POSTED_ERP_PAYMENT]
      ,[POSTED_RESPONSE_ERP_PAYMENT]
      ,[SENDING_ERP_PAYMENT]
      ,[SENDING_DATE_PAYMENT]
      ,[ATTEMPTED_WITH_ERROR_PAYMENT]
      ,[ERP_REFERENCE_PAYMENT]
      ,[USER_AMOUNT]
      ,[CHANGE]
  FROM [SWIFT_EXPRESS].[SONDA].[SONDA_POS_INVOICE_HEADER]
