-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	03-03-2016
-- Description:			obtiene los detalles de facturas y pedidos 

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [SONDA].[SWIFT_VIEW_DOCUMENTS_DETAIL]
*/
-- =============================================
CREATE VIEW [SONDA].SWIFT_VIEW_DOCUMENTS_DETAIL
AS
	SELECT 
		H.DOC_SERIE
		,CONVERT(VARCHAR(50),H.DOC_NUM) AS [DOC_ID]
		,D.SKU AS [SKU_ID]
		,ISNULL(S.DESCRIPTION_SKU,'Sin Descripcion') AS [SKU_DESCRIPTION]
		,D.QTY
		,D.PRICE AS [SKU_PRICE]
		,D.TOTAL_LINE
		,'NA' AS [INVOICE_RESOLUTION]
		,'SALES_ORDER' AS [DOC_TYPE]
	FROM [SONDA].SONDA_SALES_ORDER_DETAIL D
	INNER JOIN [SONDA].SONDA_SALES_ORDER_HEADER H ON (
		H.SALES_ORDER_ID = D.SALES_ORDER_ID
	)
	LEFT OUTER JOIN [SONDA].SWIFT_VIEW_ALL_SKU S ON (
		D.SKU = S.CODE_SKU
	)
    WHERE H.IS_READY_TO_SEND=1
	UNION ALL
	SELECT
		D.INVOICE_SERIAL AS [DOC_SERIE]
		,CONVERT(VARCHAR(50),D.[INVOICE_ID]) AS [DOC_ID]
		,D.[SKU] AS [SKU_ID]
		,ISNULL(S.DESCRIPTION_SKU,'Sin Descripcion') AS [SKU_DESCRIPTION]
		,D.[QTY] AS [QTY]
		,D.[PRICE] AS [SKU_PRICE]
		,D.[TOTAL_LINE] AS [TOTAL_LINE]
		,D.[INVOICE_RESOLUTION]	AS [INVOICE_RESOLUTION]
		,'INVOICE' AS [DOC_TYPE]
	FROM [SONDA].[SONDA_POS_INVOICE_DETAIL] AS D
	LEFT OUTER JOIN [SONDA].[SWIFT_VIEW_ALL_SKU] AS S ON (
		D.SKU = S.CODE_SKU
	)
