-- =============================================
-- Autor:					rodrigo.gomez
-- Fecha de Creacion: 		6/21/2017 @ A-Team Sprint Khalid 
-- Description:			    Vista para los scoutings provenientes de ambas tablas, SWIFT_CUSTOMERS_NEW y SONDA_CUSTOMER_NEW

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [SONDA].[SWIFT_VIEW_ALL_CUSTOMER_NEW]
*/
-- =============================================
CREATE VIEW [SONDA].[SWIFT_VIEW_ALL_CUSTOMER_NEW]
AS (
	SELECT
		[CUSTOMER]
		,CAST([CODE_CUSTOMER] AS VARCHAR(50)) CODE_CUSTOMER
		,[NAME_CUSTOMER]
		,[PHONE_CUSTOMER]
		,[ADRESS_CUSTOMER]
		,[CLASSIFICATION_CUSTOMER]
		,[CONTACT_CUSTOMER]
		,[CODE_ROUTE]
		,[LAST_UPDATE]
		,[LAST_UPDATE_BY]
		,[SELLER_DEFAULT_CODE]
		,[CREDIT_LIMIT]
		,[SIGN]
		,[PHOTO]
		,[STATUS]
		,[NEW]
		,[GPS]
		,[CODE_CUSTOMER_HH]
		,[REFERENCE]
		,[POST_DATETIME]
		,[POS_SALE_NAME]
		,[INVOICE_NAME]
		,[INVOICE_ADDRESS]
		,[NIT]
		,[CONTACT_ID]
		,[COMMENTS]
		,[ATTEMPTED_WITH_ERROR]
		,[IS_POSTED_ERP]
		,[POSTED_ERP]
		,[POSTED_RESPONSE]
		,[LATITUDE]
		,[LONGITUDE]
		,[DEPARTAMENT]
		,[MUNICIPALITY]
		,[COLONY]
		,[UPDATED_FROM_BO]
		,[SYNC_ID]
		,[CODE_CUSTOMER_BO]
		,[PHOTO_2]
		,[PHOTO_3]
		,[PHOTO_4]
		,[OWNER_ID]
		,'SONDA_CORE' [IS_FROM]
		,[JSON]
		,'' [DOC_SERIE]
		,0 [DOC_NUM]
		,'' [POSTED_BY]
		,1 [IS_READY_TO_SEND]
		,0 [IS_SENDING]
		,GETDATE() [LAST_UPDATE_IS_SENDING]
	FROM [SONDA].[SWIFT_CUSTOMERS_NEW]
	UNION ALL
	SELECT 
		[CUSTOMER_ID] CUSTOMER
		,[CODE_CUSTOMER]
		,[CUSTOMER_NAME] NAME_CUSTOMER
		,[CONTACT_PHONE] PHONE_CUSTOMER
		,[CUSTOMER_ADDRESS] ADDRESS_CUSTOMER
		,'' CLASSIFICATION_CUSTOMER
		,[CONTACT_NAME] CONTACT_CUSTOMER
		,[CODE_ROUTE]
		,[LAST_UPDATE]
		,[LAST_UPDATE_BY]
		,[CN].[POSTED_BY] [SELLER_DEFAULT_CODE]
		,0.00 CREDIT_LIMIT
		,'' [SIGN]
		,'' PHOTO
		,[STATUS]
		,1 NEW
		,[GPS]
		,CONVERT(VARCHAR(50),[SALES_ORDER_ID_HH]) CODE_CUSTOMER_HH
		,'...' REFERENCE
		,[POSTED_DATETIME] POST_DATETIME
		,CUSTOMER_NAME [POS_SALE_NAME]
		,[BILLING_NAME] INVOICE_NAME
		,[BILLING_ADDRESS] INVOICE_ADDRESS
		,[TAX_ID] NIT
		,'...' CONTACT_ID
		,CAST(NULL AS VARCHAR) COMMENT
		,[ATTEMPTED_WITH_ERROR]
		,ISNULL([IS_POSTED_ERP],-1) [IS_POSTED_ERP]
		,[POSTED_ERP]
		,[POSTED_RESPONSE]
		,[LATITUDE]
		,[LONGITUDE]
		,DEPARTAMENT
		,MUNICIPALITY
		,COLONY
		,UPDATED_FROM_BO
		,[SYNC_ID]
		,CAST(NULL AS VARCHAR) CODE_CUSTOMER_BO
		,[IMAGE_1] PHOTO_2
		,[IMAGE_2] PHOTO_3
		,[IMAGE_3] PHOTO_4
		,[OWNER] OWNER_ID
		,[IS_FROM]
		,[JSON]
		,[DOC_SERIE]
		,[DOC_NUM]
		,[POSTED_BY]
		,[IS_READY_TO_SEND]
		,[IS_SENDING]
		,[LAST_UPDATE_IS_SENDING]
	FROM [SONDA].[SONDA_CUSTOMER_NEW] CN
)
