-- =============================================
-- Autor:					rodrigo.gomez
-- Fecha de Creacion: 		3/28/2017 @ A-Team Sprint Fenyang
-- Description:			    Creacion de vista

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [SONDA].SWIFT_VIEW_COMBO_BY_TRADE_AGREEMENT
*/
-- =============================================

CREATE VIEW [SONDA].SWIFT_VIEW_COMBO_BY_TRADE_AGREEMENT
AS
    SELECT [SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID]
			,[COMBO_ID]
			,[BONUS_TYPE]
			,[BONUS_SUB_TYPE]
			,[IS_BONUS_BY_LOW_PURCHASE]
			,[IS_BONUS_BY_COMBO]
			,[LOW_QTY]
			,[TRADE_AGREEMENT_ID]
	FROM [SONDA].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE]
		INNER JOIN [SONDA].[SWIFT_TRADE_AGREEMENT_BY_BONUS_RULE] 
	ON [SWIFT_TRADE_AGREEMENT_BY_BONUS_RULE].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] = [SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID]
