-- =============================================
-- Autor:				rudi.garcia
-- Fecha de Creacion: 	21/07/2017 @ Reborn-TEAM Sprint Bearbeitung
-- Description:			Se agregon los siguientes campos [DEPARTAMENT], [MUNICIPALITY], [COLONY]

/*
-- Ejemplo de Ejecucion:
		SELECT * FROM [SONDA].SWIFT_VIEW_CUSTOMERS
*/

CREATE VIEW [SONDA].[SWIFT_VIEW_CUSTOMERS]
AS SELECT
  CAST(A.CUSTOMER AS VARCHAR) CUSTOMER
 ,A.CODE_CUSTOMER
 ,A.NAME_CUSTOMER
 ,B.NAME_CLASSIFICATION
 ,A.CONTACT_CUSTOMER
 ,C.NAME_ROUTE
 ,A.PHONE_CUSTOMER
 ,A.SELLER_DEFAULT_CODE
 ,A.CREDIT_LIMIT
 ,0 FROM_ERP
 ,1 AS PRIORIDAD
 ,NULL AS RGA_CODE
 ,NULL AS [DEPARTAMENT]
 ,NULL AS [MUNICIPALITY]
 ,NULL AS [COLONY]
 ,[A].[GPS] 
FROM [SONDA].SWIFT_CUSTOMERS AS A
LEFT OUTER JOIN [SONDA].SWIFT_CLASSIFICATION AS B
  ON A.CLASSIFICATION_CUSTOMER = B.CLASSIFICATION
LEFT OUTER JOIN [SONDA].SWIFT_ROUTES AS C
  ON A.CODE_ROUTE = C.CODE_ROUTE
WHERE (ISNULL(B.GROUP_CLASSIFICATION, 'CUSTOMER') = 'CUSTOMER')
UNION
SELECT
  CUSTOMER COLLATE SQL_Latin1_General_CP1_CI_AS CUSTOMER
 ,CODE_CUSTOMER COLLATE SQL_Latin1_General_CP1_CI_AS CODE_CUSTOMER
 ,NAME_CUSTOMER COLLATE SQL_Latin1_General_CP1_CI_AS NAME_CUSTOMER
 ,NAME_CLASSIFICATION COLLATE SQL_Latin1_General_CP1_CI_AS NAME_CLASSIFICATION
 ,CONTACT_CUSTOMER COLLATE SQL_Latin1_General_CP1_CI_AS CONTACT_CUSTOMER
 ,NAME_ROUTE COLLATE SQL_Latin1_General_CP1_CI_AS NAME_ROUTE
 ,PHONE_CUSTOMER COLLATE SQL_Latin1_General_CP1_CI_AS PHONE_CUSTOMER
 ,SELLER_DEFAULT_CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS SELLER_DEFAULT_CODE
 ,CREDIT_LIMIT AS CREDIT_LIMIT
 ,FROM_ERP FROM_ERP
 ,1 AS PRIORIDAD
 ,RGA_CODE
 ,[DEPARTAMENT]
 ,[MUNICIPALITY]
 ,[COLONY]
 ,[GPS]
FROM [SWIFT_INTERFACES].[SONDA].[ERP_VIEW_COSTUMER]
