CREATE VIEW [SONDA].[SWIFT_VIEW_ORDERS]
AS
SELECT     
	A.ORDER_SERIAL, 
	A.PRESALE_ROUTE, 
	A.POSTED_DATETIME, 
	A.CLIENT_CODE + '-' + A.CLIENT_NAME AS CLIENT, 
	ISNULL(B.ASSIGEND_TO, A.CREATED_BY ) AS ASSIGNED_TO, 
	A.TOTAL_AMOUNT,
    (SELECT     
		SUM(QTY)
		FROM  [SONDA].SWIFT_SKUS_BY_ORDER AS X
        WHERE ORDER_ID = A.ORDER_ID) AS UNIDADES_VENDIDAS, 
	A.ORDER_ID, 
	A.[SIGNATURE], 
	A.[IMAGE], 
	ISNULL(A.GPS_URL , B.POSTED_GPS) AS EXPECTED_GPS, 
	SUBSTRING(ISNULL(A.GPS_URL , B.POSTED_GPS), 1, CHARINDEX(',', ISNULL(A.GPS_URL , B.POSTED_GPS)) - 1) AS Latitude, 
	SUBSTRING(ISNULL(A.GPS_URL , B.POSTED_GPS), CHARINDEX(',', ISNULL(A.GPS_URL , B.POSTED_GPS)) + 1, LEN(ISNULL(A.GPS_URL , B.POSTED_GPS))) AS Longitude, 
	A.CREATED_DATESTAMP
FROM     [SONDA].SWIFT_ORDERS AS A 
	LEFT OUTER JOIN
         [SONDA].SWIFT_TASKS AS B ON A.TASK_SOURCE = B.TASK_ID
