CREATE VIEW [SONDA].[SWIFT_VIEW_ALL_CLASSIFICATION]
AS
SELECT     CLASSIFICATION, GROUP_CLASSIFICATION, NAME_CLASSIFICATION, PRIORITY_CLASSIFICATION, VALUE_TEXT_CLASSIFICATION, MPC01
FROM         SWIFT_CLASSIFICATION
WHERE [GROUP_CLASSIFICATION] <> 'PAYMENT_METHODS'
