

CREATE VIEW [SONDA].[SWIFT_VIEW_NO_VISIT_REASONS]
AS
SELECT 
	CLASSIFICATION				AS CLASSIFICATION,
	GROUP_CLASSIFICATION		AS PARAM_NAME,
	NAME_CLASSIFICATION			AS NAME_CLASSIFICATION,
	PRIORITY_CLASSIFICATION		AS PRIORITY_CLASSIFICATION,
	VALUE_TEXT_CLASSIFICATION	AS PARAM_CAPTION
FROM 
	[SONDA].SWIFT_CLASSIFICATION
WHERE 
	GROUP_CLASSIFICATION = 'NO_VISIT'
