
-- Modificacion 1/27/2017 @ A-Team Sprint Bankole
					-- rodrigo.gomez
					-- se agrego el disctinct al select ya que duplicaba datos.

CREATE VIEW [SONDA].[SWIFT_VIEW_SELLER_LOGIN]
AS
SELECT DISTINCT	
	A.SELLER_CODE,
	A.SELLER_NAME, 
	A.ASSIGNED_VEHICLE_CODE,
	A.ASSIGNED_DISTRIBUTION_CENTER,
	B.[LOGIN],
	CASE
		WHEN B.[USER_TYPE] = 'PRE'
		THEN (SELECT ISNULL([VALUE_TEXT_CLASSIFICATION],'Preventa') FROM [SONDA].[SWIFT_CLASSIFICATION] WHERE [NAME_CLASSIFICATION] = 'PRE')
		WHEN B.[USER_TYPE] = 'VEN'
		THEN (SELECT ISNULL([VALUE_TEXT_CLASSIFICATION],'Venta directa') FROM [SONDA].[SWIFT_CLASSIFICATION] WHERE [NAME_CLASSIFICATION] = 'VEN')
	END AS USER_ROLE
	, B.DEFAULT_WAREHOUSE
	, B.SELLER_ROUTE 
	, VR.NAME_ROUTE
	, VW.DESCRIPTION_WAREHOUSE
	FROM [SONDA].SWIFT_VIEW_ALL_SELLERS A
	LEFT OUTER JOIN [SONDA].USERS B
	ON B.RELATED_SELLER = A.SELLER_CODE
	LEFT JOIN [SONDA].[SWIFT_VIEW_ALL_ROUTE] VR ON (B.SELLER_ROUTE = VR.CODE_ROUTE)
	LEFT JOIN [SONDA].[SWIFT_VIEW_WAREHOUSES] VW ON (B.DEFAULT_WAREHOUSE = VW.CODE_WAREHOUSE)
WHERE
	B.[USER_TYPE] = 'PRE' OR B.[USER_TYPE] = 'VEN'
