CREATE VIEW [SONDA].[SWIFT_VIEW_WAREHOUSES_NOT_SELLER]
AS
SELECT *
FROM [SONDA].[SWIFT_VIEW_WAREHOUSES] VW
WHERE NOT EXISTS(SELECT 1
				FROM [SONDA].[SWIFT_VIEW_SELLER_LOGIN] SL
				WHERE VW.CODE_WAREHOUSE = SL.DEFAULT_WAREHOUSE)
