-- =============================================
-- Autor:					alberto.ruiz
-- Fecha de Creacion: 		27-Jan-17 @ A-Team Sprint Bankole
-- Description:			    Vista para las transferencias

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [SONDA].[SWIFT_VIEW_TRANSFER_HEADER]
*/
-- =============================================
CREATE VIEW [SONDA].[SWIFT_VIEW_TRANSFER_HEADER]
AS
	SELECT DISTINCT 
		[TH].[TRANSFER_ID]
		,[TH].[SELLER_CODE]
		,[VSL].[SELLER_NAME]
		,[TH].[SELLER_ROUTE]
		,[VR].[NAME_ROUTE]
		,[TH].[CODE_WAREHOUSE_SOURCE]
		,[WS].[DESCRIPTION_WAREHOUSE] [NAME_WAREHOUSE_SOURCE]--,(SELECT [W].[DESCRIPTION_WAREHOUSE] FROM [SONDA].[SWIFT_WAREHOUSES] [W] WHERE [W].[CODE_WAREHOUSE] = [TH].[CODE_WAREHOUSE_SOURCE] ) AS [NAME_WAREHOUSE_SOURCE]
		,[TH].[CODE_WAREHOUSE_TARGET]
		,[WT].[DESCRIPTION_WAREHOUSE] [NAME_WAREHOUSE_TARGET]--,(SELECT [W].[DESCRIPTION_WAREHOUSE] FROM [SONDA].[SWIFT_WAREHOUSES] [W] WHERE [W].[CODE_WAREHOUSE] = [TH].[CODE_WAREHOUSE_TARGET] ) AS [NAME_WAREHOUSE_TARGET]
		,[TH].[STATUS]
		,[TH].[LAST_UPDATE]
		,[TH].[LAST_UPDATE_BY]
		,[TH].[COMMENT]
		,[TH].[IS_ONLINE]
	FROM [SONDA].[SWIFT_TRANSFER_HEADER] [TH]
	INNER JOIN [SONDA].[SWIFT_VIEW_SELLER_LOGIN] VSL ON (
		TH.SELLER_CODE = VSL.SELLER_CODE
	)
	INNER JOIN [SONDA].[SWIFT_WAREHOUSES] [WS] ON (
		[WS].[CODE_WAREHOUSE] = [TH].[CODE_WAREHOUSE_SOURCE]
	)
	INNER JOIN [SONDA].[SWIFT_WAREHOUSES] [WT] ON (
		[WT].[CODE_WAREHOUSE] = [TH].[CODE_WAREHOUSE_TARGET]
	)
	LEFT JOIN [SONDA].[SWIFT_VIEW_ROUTES] [VR] ON (
		[VR].[CODE_ROUTE] = [TH].[SELLER_ROUTE]
	)
