
CREATE VIEW [SONDA].[SWIFT_VIEW_ALL_BRANCHES]
AS
SELECT 
	A.BRANCH_PK,
	B.NAME_CUSTOMER,
	A.BRANCH_CODE,
	A.BRANCH_PDE,
	A.BRANCH_NAME,
	A.BRANCH_ADDRESS,
	A.GEO_ROUTE,
	A.GPS_LAT_LON,
	A.PHONE,
	A.DELIVERY_EMAIL,
	A.RECOLLECT_EMAIL,
	CASE A.[STATUS]
	WHEN 'ACTIVE' THEN 'Activa'
	WHEN 'INACTIVE' THEN 'Inactiva'
	END AS 'STATUS',
	A.CONTACT_NAME,
	A.IS_DEFAULT
FROM
	[SONDA].SWIFT_BRANCHES AS A
LEFT OUTER JOIN
	[SONDA].SWIFT_VIEW_ALL_COSTUMER AS B
	ON A.CUSTOMER_CODE = B.CODE_CUSTOMER
