
CREATE VIEW [SONDA].[SWIFT_VIEW_VALORIZATION_INVENTORY]
AS
--SELECT distinct
--	A.INVENTORY, 
--	ISNULL(A.SERIAL_NUMBER,'N/A') AS SERIAL_NUMBER, 
--	A.WAREHOUSE AS CODE_WAREHOUSE, 
--	A.LOCATION AS CODE_LOCATION, 
--	A.SKU AS CODE_SKU, 
--	A.SKU_DESCRIPTION, 
--	A.ON_HAND,
--	C.COST, 
--	ISNULL(D.BATCH_ID,'N/A') AS BATCH_ID, 
--	CONVERT(FLOAT,(A.ON_HAND * C.COST)) AS VALORIZATION,
--	(SELECT COUNT(DISTINCT TAG_COLOR) FROM [SONDA].SWIFT_VIEW_TAGS_BY_SKU AS C WHERE C.BATCH_ID = A.BATCH_ID GROUP BY SKU) AS TAGS_BY_BATCH,
--						 (SELECT COUNT(DISTINCT TAG_COLOR) FROM [SONDA].SWIFT_VIEW_TAGS_BY_SKU AS C WHERE C.SERIAL_NUMBER = A.SERIAL_NUMBER GROUP BY SKU) AS TAGS_BY_SERIE
--FROM 
--	[SONDA].SWIFT_INVENTORY AS A
--	LEFT OUTER JOIN
--    [SONDA].SWIFT_VIEW_ALL_SKU AS C ON A.SKU = C.CODE_SKU
--    LEFT OUTER JOIN
--    [SONDA].SWIFT_BATCHES AS D ON A.BATCH_ID = D.BATCH
--WHERE A.ON_HAND > 0
SELECT DISTINCT
	ROW_NUMBER() OVER(ORDER BY A.SERIAL_NUMBER DESC) AS INVENTORY,
	ISNULL(A.SERIAL_NUMBER,'N/A') AS SERIAL_NUMBER, 
	A.WAREHOUSE AS CODE_WAREHOUSE, 
	A.LOCATION AS CODE_LOCATION, 
	A.SKU AS CODE_SKU, 
	A.SKU_DESCRIPTION, 
	SUM(A.ON_HAND) AS ON_HAND,
	C.COST, 
	ISNULL(D.BATCH_SUPPLIER ,'N/A') AS BATCH_ID, 
	CONVERT(FLOAT,(SUM(A.ON_HAND) * C.COST)) AS VALORIZATION,
	(SELECT COUNT(DISTINCT TAG_COLOR) FROM [SONDA].SWIFT_VIEW_TAGS_BY_SKU AS C WHERE C.BATCH_ID = A.BATCH_ID GROUP BY SKU) AS TAGS_BY_BATCH,
						 (SELECT COUNT(DISTINCT TAG_COLOR) FROM [SONDA].SWIFT_VIEW_TAGS_BY_SKU AS C WHERE C.SERIAL_NUMBER = A.SERIAL_NUMBER GROUP BY SKU) AS TAGS_BY_SERIE
FROM 
	[SONDA].SWIFT_INVENTORY AS A
	LEFT OUTER JOIN    [SONDA].SWIFT_VIEW_ALL_SKU AS C ON A.SKU = C.CODE_SKU
    LEFT OUTER JOIN    [SONDA].SWIFT_BATCH AS D ON A.BATCH_ID = D.BATCH_ID
WHERE A.ON_HAND > 0
GROUP BY 
  A.SERIAL_NUMBER
, A.WAREHOUSE
, A.LOCATION
, A.SKU
, A.SKU_DESCRIPTION
, C.COST
, D.BATCH_SUPPLIER
, A.BATCH_ID
, A.SERIAL_NUMBER
