

CREATE VIEW [SONDA].[SWIFT_VIEW_CONSOLIDATED_INVENTORY]
AS
SELECT     
	--ISNULL(A.SERIAL_NUMBER,'N/A') AS SERIAL_NUMBER,
	A.SKU,
	A.SKU_DESCRIPTION AS DESCRIPTION_SKU, 
	D.BARCODE_SKU AS BARCODE, 
	SUM(A.ON_HAND) AS ON_HAND
FROM         
	[SONDA].SWIFT_INVENTORY AS A 
	LEFT OUTER JOIN 
	[SONDA].SWIFT_VIEW_SKU AS D ON A.SKU = D.CODE_SKU
GROUP BY A.SKU, A.SKU_DESCRIPTION, D.BARCODE_SKU
