-- =============================================
-- Autor:					alberto.ruiz
-- Fecha de Creacion: 		01-06-2016
-- Description:			    Vista que obtiene las ordenes de venta del ERP

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [SONDA].[SWIFT_VW_ERP_SALES_ORDER_HEADER]
*/
-- =============================================
CREATE VIEW [SONDA].[SWIFT_VW_ERP_SALES_ORDER_HEADER]
AS
	SELECT DISTINCT 
		([P].SAP_REFERENCE)
		,[P].DOC_TYPE
		,[P].DESCRIPTION_TYPE
		,[P].CUSTOMER_ID
		,CASE [P].DOC_TYPE
			WHEN 'SO' THEN U.PRESALE_WAREHOUSE
			ELSE [P].COD_WAREHOUSE
		END AS COD_WAREHOUSE
		,[P].CUSTOMER_NAME
		,CASE [P].DOC_TYPE
			WHEN 'SO' THEN W.DESCRIPTION_WAREHOUSE
			ELSE [P].WAREHOUSE_NAME
		END AS WAREHOUSE_NAME
		,[P].CODE_OPER
		,R.CODE_ROUTE
		,R.NAME_ROUTE
		,S.SELLER_CODE
		,S.SELLER_NAME
		,[P].DOC_DATE
		,sv.CODE_VEHICLE
		,sv.PLATE_VEHICLE
	FROM [SWIFT_INTERFACES].[SONDA].[ERP_VIEW_DOC_FOR_PICKING] [P]
	LEFT JOIN [SONDA].[USERS] U ON ([P].CODE_OPER = U.LOGIN)
	LEFT JOIN [SONDA].[SWIFT_ROUTES] R ON (U.SELLER_ROUTE = R.CODE_ROUTE)
	LEFT JOIN [SONDA].[SWIFT_VIEW_ALL_SELLERS] S ON (U.RELATED_SELLER = S.SELLER_CODE)
	LEFT JOIN [SONDA].[SWIFT_WAREHOUSES] W ON (U.PRESALE_WAREHOUSE = W.CODE_WAREHOUSE)
	LEFT JOIN [SONDA].[SWIFT_VEHICLE_X_USER] svxu ON (svxu.LOGIN = [P].CODE_OPER)
	LEFT JOIN [SONDA].[SWIFT_VEHICLES] sv  ON (sv.VEHICLE = svxu.VEHICLE)
	WHERE [P].DOC_TYPE = 'SO' AND R.CODE_ROUTE IS NOT NULL
