
CREATE VIEW [SONDA].[SWIFT_VIEW_ALL_SELLERS]
AS
SELECT CONVERT(VARCHAR(50), SELLER_CODE) AS SELLER_CODE
	, SELLER_NAME
	, '' AS PHONE1
	, '' AS PHONE2
	, '' AS RATED_SELLER
	, '' AS [STATUS]
	, '' AS EMAIL
	, ASSIGNED_VEHICLE_CODE
	, ASSIGNED_DISTRIBUTION_CENTER
FROM [SONDA].SWIFT_VIEW_SAP_SELLERS
UNION 
SELECT SELLER_CODE
	, SELLER_NAME
	, PHONE1	
	, PHONE2
	, RATED_SELLER
	, [STATUS]
	, EMAIL
	, ASSIGNED_VEHICLE_CODE
	, ASSIGNED_DISTRIBUTION_CENTER
FROM [SONDA].SWIFT_SELLER
