CREATE TABLE [wms].[ERP_SALES_ORDER_SEQUENCE_CHANNEL_MODERN] (
    [Sequence]  INT      IDENTITY (1, 1) NOT NULL,
    [StartDate] DATETIME NULL,
    [EndDate]   DATETIME NULL,
    CONSTRAINT [PK_ERP_SALES_ORDER_SEQUENCE_CHANNEL_MODERN] PRIMARY KEY CLUSTERED ([Sequence] ASC)
);

