CREATE TABLE [wms].[SWIFT_ERP_CUSTOMERS] (
    [CUSTOMER]                NVARCHAR (15)   NULL,
    [CODE_CUSTOMER]           NVARCHAR (15)   NOT NULL,
    [NAME_CUSTOMER]           NVARCHAR (100)  NULL,
    [PHONE_CUSTOMER]          NVARCHAR (20)   NULL,
    [ADRESS_CUSTOMER]         NVARCHAR (250)  NULL,
    [CLASSIFICATION_CUSTOMER] VARCHAR (1)     NOT NULL,
    [CONTACT_CUSTOMER]        NVARCHAR (90)   NULL,
    [CODE_ROUTE]              VARCHAR (30)    NULL,
    [LAST_UPDATE]             DATETIME        NULL,
    [LAST_UPDATE_BY]          VARCHAR (30)    NULL,
    [SELLER_DEFAULT_CODE]     NVARCHAR (155)  NULL,
    [CREDIT_LIMIT]            NUMERIC (19, 6) NULL,
    [FROM_ERP]                INT             NOT NULL,
    [NAME_ROUTE]              VARCHAR (30)    NULL,
    [NAME_CLASSIFICATION]     VARCHAR (30)    NULL,
    [GPS]                     VARCHAR (100)   NULL,
    [LATITUDE]                VARCHAR (50)    NULL,
    [LONGITUDE]               VARCHAR (50)    NULL,
    [FREQUENCY]               NVARCHAR (100)  NULL,
    [SUNDAY]                  CHAR (1)        NULL,
    [MONDAY]                  CHAR (1)        NULL,
    [TUESDAY]                 CHAR (1)        NULL,
    [WEDNESDAY]               CHAR (1)        NULL,
    [THURSDAY]                CHAR (1)        NULL,
    [FRIDAY]                  CHAR (1)        NULL,
    [SATURDAY]                CHAR (1)        NULL,
    [SCOUTING_ROUTE]          NVARCHAR (100)  NULL,
    [EXTRA_DAYS]              INT             NULL,
    [EXTRA_MONT]              INT             NULL,
    [DISCOUNT]                NUMERIC (18, 6) NULL,
    [OFIVENTAS]               VARCHAR (7)     NULL,
    [RUTAVENTAS]              VARCHAR (7)     NULL,
    [RUTAENTREGA]             VARCHAR (7)     NULL,
    [SECUENCIA]               INT             NULL,
    [RGA_CODE]                VARCHAR (150)   NULL,
    [PAYMENT_CONDITIONS]      VARCHAR (250)   NULL,
    [ORGANIZACION_VENTAS]     VARCHAR (250)   NULL,
    [OWNER]                   VARCHAR (50)    NULL,
    [OWNER_ID]                VARCHAR (50)    NULL,
    [BALANCE]                 NUMERIC (18, 6) CONSTRAINT [DF__SWIFT_ERP__BALAN__25A691D2] DEFAULT ((0.00)) NULL,
    [DEPARTAMENT]             VARCHAR (250)   CONSTRAINT [DF__SWIFT_ERP__DEPAR__278EDA44] DEFAULT ('NO ESPECIFICADO') NULL,
    [MUNICIPALITY]            VARCHAR (250)   CONSTRAINT [DF__SWIFT_ERP__MUNIC__2882FE7D] DEFAULT ('NO ESPECIFICADO') NULL,
    [COLONY]                  VARCHAR (250)   CONSTRAINT [DF__SWIFT_ERP__COLON__297722B6] DEFAULT ('NO ESPECIFICADO') NULL,
    [TAX_ID]                  VARCHAR (50)    NULL,
    [INVOICE_NAME]            VARCHAR (250)   NULL,
    [CODE_CUSTOMER_ALTERNATE] VARCHAR (50)    NULL,
    CONSTRAINT [PK_SWIFT_INTERFACES_CLOUD_ONLINE_CUSTOMER] PRIMARY KEY CLUSTERED ([CODE_CUSTOMER] ASC)
);

