CREATE TABLE [wms].[SWIFT_ERP_WAREHOUSE] (
    [CODE_WAREHOUSE]        VARCHAR (50)  NULL,
    [DESCRIPTION_WAREHOUSE] VARCHAR (MAX) NULL,
    [WEATHER_WAREHOUSE]     VARCHAR (50)  NULL,
    [STATUS_WAREHOUSE]      VARCHAR (10)  NULL,
    [LAST_UPDATE]           DATETIME      NULL,
    [LAST_UPDATE_BY]        VARCHAR (50)  NULL,
    [IS_EXTERNAL]           INT           NULL,
    CONSTRAINT [UQ__SWIFT_WA__D8193FC2656C112D] UNIQUE NONCLUSTERED ([CODE_WAREHOUSE] ASC)
);

