
-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	01-03-2016
-- Description:			SP que importa la conversion de los paquetes

-- Modificado 2016-04-14
				-- joel.delcompare
				-- SE AGREGO EL CAMPO DE ORDEN 

-- Modificado 2016-04-27
				-- alberto.ruiz
				-- Se cambio de orden los merga ya que primero es el de SONDA_PACK_UNIT y despues SONDA_PACK_CONVERSION
/*
-- Ejemplo de Ejecucion:
				-- 
				EXEC [SONDA].[BULK_DATA_SP_IMPORT_PACK_CONVERSION]
*/
-- =============================================
CREATE PROCEDURE [SONDA].[BULK_DATA_SP_IMPORT_PACK_CONVERSION]
AS
BEGIN
  SET NOCOUNT ON;
  --
  MERGE SWIFT_EXPRESS.[SONDA].SONDA_PACK_UNIT AS TRG
  USING (SELECT
      epu.CODE_PACK_UNIT
     ,epu.DESCRIPTION_PACK_UNIT
     ,epu.LAST_UPDATE
     ,epu.LAST_UPDATE_BY
     ,epu.UM_ENTRY
    FROM SWIFT_INTERFACES_ONLINE.[SONDA].ERP_PACK_UNIT epu) AS SRC
  ON TRG.CODE_PACK_UNIT COLLATE database_default = SRC.CODE_PACK_UNIT
  WHEN MATCHED
    THEN UPDATE
      SET DESCRIPTION_PACK_UNIT = SRC.DESCRIPTION_PACK_UNIT
         ,LAST_UPDATE = SRC.LAST_UPDATE
         ,LAST_UPDATE_BY = SRC.LAST_UPDATE_BY
         ,UM_ENTRY = SRC.UM_ENTRY
  WHEN NOT MATCHED
    THEN INSERT (CODE_PACK_UNIT
      , DESCRIPTION_PACK_UNIT
      , LAST_UPDATE
      , LAST_UPDATE_BY
      , UM_ENTRY)
        VALUES (SRC.CODE_PACK_UNIT, SRC.DESCRIPTION_PACK_UNIT, SRC.LAST_UPDATE, SRC.LAST_UPDATE_BY, SRC.UM_ENTRY);
  --
  MERGE SWIFT_EXPRESS.[SONDA].SONDA_PACK_CONVERSION AS TRG
  USING (SELECT
      epc.CODE_SKU
     ,epc.CODE_PACK_UNIT_FROM
     ,epc.CODE_PACK_UNIT_TO
     ,ISNULL(epc.CONVERSION_FACTOR, 1) CONVERSION_FACTOR
     ,epc.LAST_UPDATE
     ,epc.LAST_UPDATE_BY
     ,epc.[ORDER]
    FROM SWIFT_INTERFACES_ONLINE.[SONDA].ERP_PACK_CONVERSION epc) AS SRC
  ON TRG.CODE_SKU COLLATE database_default = SRC.CODE_SKU
    AND TRG.CODE_PACK_UNIT_FROM COLLATE database_default = SRC.CODE_PACK_UNIT_FROM
    AND TRG.CODE_PACK_UNIT_TO COLLATE database_default = SRC.CODE_PACK_UNIT_TO
  WHEN MATCHED
    THEN UPDATE
      SET CONVERSION_FACTOR = SRC.CONVERSION_FACTOR
         ,LAST_UPDATE = SRC.LAST_UPDATE
         ,LAST_UPDATE_BY = SRC.LAST_UPDATE_BY
         ,[ORDER] = SRC.[ORDER]
  WHEN NOT MATCHED
    THEN INSERT (CODE_SKU
      , CODE_PACK_UNIT_FROM
      , CODE_PACK_UNIT_TO
      , CONVERSION_FACTOR
      , LAST_UPDATE
      , LAST_UPDATE_BY
      , [ORDER])
        VALUES (SRC.CODE_SKU, SRC.CODE_PACK_UNIT_FROM, SRC.CODE_PACK_UNIT_TO, SRC.CONVERSION_FACTOR, SRC.LAST_UPDATE, SRC.LAST_UPDATE_BY, SRC.[ORDER]);
END