


CREATE VIEW [SONDA].[ERP_ORDER_HEADER]
AS
    SELECT    NULL DocEntry ,
        NULL DocNum ,
        NULL DocType ,
        NULL CANCELED ,
        NULL Handwrtten ,
        NULL Printed ,
        NULL DocStatus ,
        NULL InvntSttus ,
        NULL Transfered ,
        NULL ObjType ,
        NULL DocDate ,
        NULL DocDueDate ,
        NULL CardCode ,
        NULL CardName ,
        NULL Address ,
        NULL NumAtCard ,
        NULL VatPercent ,
        NULL VatSum ,
        NULL VatSumFC ,
        NULL DiscPrcnt ,
        NULL DiscSum ,
        NULL DiscSumFC ,
        NULL DocCur ,
        NULL DocRate ,
        NULL DocTotal ,
        NULL DocTotalFC ,
        NULL PaidToDate ,
        NULL PaidFC ,
        NULL GrosProfit ,
        NULL GrosProfFC ,
        NULL Ref1 ,
        NULL Ref2 ,
        NULL Comments ,
        NULL JrnlMemo ,
        NULL TransId ,
        NULL ReceiptNum ,
        NULL GroupNum ,
        NULL DocTime ,
        NULL SlpCode ,
        NULL TrnspCode ,
        NULL PartSupply ,
        NULL Confirmed ,
        NULL GrossBase ,
        NULL ImportEnt ,
        NULL CreateTran ,
        NULL SummryType ,
        NULL UpdInvnt ,
        NULL UpdCardBal ,
        NULL Instance ,
        NULL Flags ,
        NULL InvntDirec ,
        NULL CntctCode ,
        NULL ShowSCN ,
        NULL FatherCard ,
        NULL SysRate ,
        NULL CurSource ,
        NULL VatSumSy ,
        NULL DiscSumSy ,
        NULL DocTotalSy ,
        NULL PaidSys ,
        NULL FatherType ,
        NULL GrosProfSy ,
        NULL UpdateDate ,
        NULL IsICT ,
        NULL CreateDate ,
        NULL Volume ,
        NULL VolUnit ,
        NULL Weight ,
        NULL WeightUnit ,
        NULL Series ,
        NULL TaxDate ,
        NULL Filler ,
        NULL DataSource ,
        NULL StampNum ,
        NULL isCrin ,
        NULL FinncPriod ,
        NULL UserSign ,
        NULL selfInv ,
        NULL VatPaid ,
        NULL VatPaidFC ,
        NULL VatPaidSys ,
        NULL UserSign2 ,
        NULL WddStatus ,
        NULL draftKey ,
        NULL TotalExpns ,
        NULL TotalExpFC ,
        NULL TotalExpSC ,
        NULL DunnLevel ,
        NULL Address2 ,
        NULL LogInstanc ,
        NULL Exported ,
        NULL StationID ,
        NULL Indicator ,
        NULL NetProc ,
        NULL AqcsTax ,
        NULL AqcsTaxFC ,
        NULL AqcsTaxSC ,
        NULL CashDiscPr ,
        NULL CashDiscnt ,
        NULL CashDiscFC ,
        NULL CashDiscSC ,
        NULL ShipToCode ,
        NULL LicTradNum ,
        NULL PaymentRef ,
        NULL WTSum ,
        NULL WTSumFC ,
        NULL WTSumSC ,
        NULL RoundDif ,
        NULL RoundDifFC ,
        NULL RoundDifSy ,
        NULL CheckDigit ,
        NULL Form1099 ,
        NULL Box1099 ,
        NULL submitted ,
        NULL PoPrss ,
        NULL Rounding ,
        NULL RevisionPo ,
        NULL Segment ,
        NULL ReqDate ,
        NULL CancelDate ,
        NULL PickStatus ,
        NULL Pick ,
        NULL BlockDunn ,
        NULL PeyMethod ,
        NULL PayBlock ,
        NULL PayBlckRef ,
        NULL MaxDscn ,
        NULL Reserve ,
        NULL Max1099 ,
        NULL CntrlBnk ,
        NULL PickRmrk ,
        NULL ISRCodLine ,
        NULL ExpAppl ,
        NULL ExpApplFC ,
        NULL ExpApplSC ,
        NULL Project ,
        NULL DeferrTax ,
        NULL LetterNum ,
        NULL FromDate ,
        NULL ToDate ,
        NULL WTApplied ,
        NULL WTAppliedF ,
        NULL BoeReserev ,
        NULL AgentCode ,
        NULL WTAppliedS ,
        NULL EquVatSum ,
        NULL EquVatSumF ,
        NULL EquVatSumS ,
        NULL Installmnt ,
        NULL VATFirst ,
        NULL NnSbAmnt ,
        NULL NnSbAmntSC ,
        NULL NbSbAmntFC ,
        NULL ExepAmnt ,
        NULL ExepAmntSC ,
        NULL ExepAmntFC ,
        NULL VatDate ,
        NULL CorrExt ,
        NULL CorrInv ,
        NULL NCorrInv ,
        NULL CEECFlag ,
        NULL BaseAmnt ,
        NULL BaseAmntSC ,
        NULL BaseAmntFC ,
        NULL CtlAccount ,
        NULL BPLId ,
        NULL BPLName ,
        NULL VATRegNum ,
        NULL TxInvRptNo ,
        NULL TxInvRptDt ,
        NULL KVVATCode ,
        NULL WTDetails ,
        NULL SumAbsId ,
        NULL SumRptDate ,
        NULL PIndicator ,
        NULL ManualNum ,
        NULL UseShpdGd ,
        NULL BaseVtAt ,
        NULL BaseVtAtSC ,
        NULL BaseVtAtFC ,
        NULL NnSbVAt ,
        NULL NnSbVAtSC ,
        NULL NbSbVAtFC ,
        NULL ExptVAt ,
        NULL ExptVAtSC ,
        NULL ExptVAtFC ,
        NULL LYPmtAt ,
        NULL LYPmtAtSC ,
        NULL LYPmtAtFC ,
        NULL ExpAnSum ,
        NULL ExpAnSys ,
        NULL ExpAnFrgn ,
        NULL DocSubType ,
        NULL DpmStatus ,
        NULL DpmAmnt ,
        NULL DpmAmntSC ,
        NULL DpmAmntFC ,
        NULL DpmDrawn ,
        NULL DpmPrcnt ,
        NULL PaidSum ,
        NULL PaidSumFc ,
        NULL PaidSumSc ,
        NULL FolioPref ,
        NULL FolioNum ,
        NULL DpmAppl ,
        NULL DpmApplFc ,
        NULL DpmApplSc ,
        NULL LPgFolioN ,
        NULL Header ,
        NULL Footer ,
        NULL Posted ,
        NULL OwnerCode ,
        NULL BPChCode ,
        NULL BPChCntc ,
        NULL PayToCode ,
        NULL IsPaytoBnk ,
        NULL BnkCntry ,
        NULL BankCode ,
        NULL BnkAccount ,
        NULL BnkBranch ,
        NULL isIns ,
        NULL TrackNo ,
        NULL VersionNum ,
        NULL LangCode ,
        NULL BPNameOW ,
        NULL BillToOW ,
        NULL ShipToOW ,
        NULL RetInvoice ,
        NULL ClsDate ,
        NULL MInvNum ,
        NULL MInvDate ,
        NULL SeqCode ,
        NULL Serial ,
        NULL SeriesStr ,
        NULL SubStr ,
        NULL Model ,
        NULL TaxOnExp ,
        NULL TaxOnExpFc ,
        NULL TaxOnExpSc ,
        NULL TaxOnExAp ,
        NULL TaxOnExApF ,
        NULL TaxOnExApS ,
        NULL LastPmnTyp ,
        NULL LndCstNum ,
        NULL UseCorrVat ,
        NULL BlkCredMmo ,
        NULL OpenForLaC ,
        NULL Excised ,
        NULL ExcRefDate ,
        NULL ExcRmvTime ,
        NULL SrvGpPrcnt ,
        NULL DepositNum ,
        NULL CertNum ,
        NULL DutyStatus ,
        NULL AutoCrtFlw ,
        NULL FlwRefDate ,
        NULL FlwRefNum ,
        NULL VatJENum ,
        NULL DpmVat ,
        NULL DpmVatFc ,
        NULL DpmVatSc ,
        NULL DpmAppVat ,
        NULL DpmAppVatF ,
        NULL DpmAppVatS ,
        NULL InsurOp347 ,
        NULL IgnRelDoc ,
        NULL BuildDesc ,
        NULL ResidenNum ,
        NULL Checker ,
        NULL Payee ,
        NULL CopyNumber ,
        NULL SSIExmpt ,
        NULL PQTGrpSer ,
        NULL PQTGrpNum ,
        NULL PQTGrpHW ,
        NULL ReopOriDoc ,
        NULL ReopManCls ,
        NULL DocManClsd ,
        NULL ClosingOpt ,
        NULL SpecDate ,
        NULL Ordered ,
        NULL NTSApprov ,
        NULL NTSWebSite ,
        NULL NTSeTaxNo ,
        NULL NTSApprNo ,
        NULL PayDuMonth ,
        NULL ExtraMonth ,
        NULL ExtraDays ,
        NULL CdcOffset ,
        NULL SignMsg ,
        NULL SignDigest ,
        NULL CertifNum ,
        NULL KeyVersion ,
        NULL EDocGenTyp ,
        NULL ESeries ,
        NULL EDocNum ,
        NULL EDocExpFrm ,
        NULL OnlineQuo ,
        NULL POSEqNum ,
        NULL POSManufSN ,
        NULL POSCashN ,
        NULL EDocStatus ,
        NULL EDocCntnt ,
        NULL EDocProces ,
        NULL EDocErrCod ,
        NULL EDocErrMsg ,
        NULL EDocCancel ,
        NULL EDocTest ,
        NULL EDocPrefix ,
        NULL CUP ,
        NULL CIG ,
        NULL DpmAsDscnt ,
        NULL Attachment ,
        NULL AtcEntry ,
        NULL SupplCode ,
        NULL GTSRlvnt ,
        NULL BaseDisc ,
        NULL BaseDiscSc ,
        NULL BaseDiscFc ,
        NULL BaseDiscPr ,
        NULL CreateTS ,
        NULL UpdateTS ,
        NULL SrvTaxRule ,
        NULL AnnInvDecR ,
        NULL Supplier ,
        NULL Releaser ,
        NULL Receiver ,
        NULL AgrNo ,
        NULL IsAlt ,
        NULL AltBaseTyp ,
        NULL AltBaseEnt ,
        NULL PaidDpm ,
        NULL PaidDpmF ,
        NULL PaidDpmS ,
        NULL U_Guatex ,
        NULL U_KM ,
        NULL  Ship_To_Address_Type ,
        NULL   Ship_To_Street ,
        NULL  Ship_To_State ,
        NULL   Ship_To_Country
  --  FROM    OPENQUERY(ERP_SERVER,
  --                    'SELECT
  --so.DocEntry, so.DocNum, so.DocType, so.CANCELED, so.Handwrtten, so.Printed, so.DocStatus, so.InvntSttus, so.Transfered, so.ObjType, so.DocDate, so.DocDueDate, so.CardCode, 
  --                                                 so.CardName, so.Address, so.NumAtCard, so.VatPercent, so.VatSum, so.VatSumFC, so.DiscPrcnt, so.DiscSum, so.DiscSumFC, so.DocCur, so.DocRate, so.DocTotal, so.DocTotalFC, 
  --                                                 so.PaidToDate, so.PaidFC, so.GrosProfit, so.GrosProfFC, so.Ref1, so.Ref2, so.Comments, so.JrnlMemo, so.TransId, so.ReceiptNum, so.GroupNum, so.DocTime, so.SlpCode, 
  --                                                 so.TrnspCode, so.PartSupply, so.Confirmed, so.GrossBase, so.ImportEnt, so.CreateTran, so.SummryType, so.UpdInvnt, so.UpdCardBal, so.Instance, so.Flags, so.InvntDirec, 
  --                                                 so.CntctCode, so.ShowSCN, so.FatherCard, so.SysRate, so.CurSource, so.VatSumSy, so.DiscSumSy, so.DocTotalSy, so.PaidSys, so.FatherType, so.GrosProfSy, so.UpdateDate, 
  --                                                 so.IsICT, so.CreateDate, so.Volume, so.VolUnit, so.Weight, so.WeightUnit, so.Series, so.TaxDate, so.Filler, so.DataSource, so.StampNum, so.isCrin, so.FinncPriod, so.UserSign, 
  --                                                 so.selfInv, so.VatPaid, so.VatPaidFC, so.VatPaidSys, so.UserSign2, so.WddStatus, so.draftKey, so.TotalExpns, so.TotalExpFC, so.TotalExpSC, so.DunnLevel, so.Address2, 
  --                                                 so.LogInstanc, so.Exported, so.StationID, so.Indicator, so.NetProc, so.AqcsTax, so.AqcsTaxFC, so.AqcsTaxSC, so.CashDiscPr, so.CashDiscnt, so.CashDiscFC, so.CashDiscSC, 
  --                                                 so.ShipToCode, so.LicTradNum, so.PaymentRef, so.WTSum, so.WTSumFC, so.WTSumSC, so.RoundDif, so.RoundDifFC, so.RoundDifSy, so.CheckDigit, so.Form1099, so.Box1099, 
  --                                                 so.submitted, so.PoPrss, so.Rounding, so.RevisionPo, so.Segment, so.ReqDate, so.CancelDate, so.PickStatus, so.Pick, so.BlockDunn, so.PeyMethod, so.PayBlock, so.PayBlckRef, 
  --                                                 so.MaxDscn, so.Reserve, so.Max1099, so.CntrlBnk, so.PickRmrk, so.ISRCodLine, so.ExpAppl, so.ExpApplFC, so.ExpApplSC, so.Project, so.DeferrTax, so.LetterNum, so.FromDate, 
  --                                                 so.ToDate, so.WTApplied, so.WTAppliedF, so.BoeReserev, so.AgentCode, so.WTAppliedS, so.EquVatSum, so.EquVatSumF, so.EquVatSumS, so.Installmnt, so.VATFirst, so.NnSbAmnt, 
  --                                                 so.NnSbAmntSC, so.NbSbAmntFC, so.ExepAmnt, so.ExepAmntSC, so.ExepAmntFC, so.VatDate, so.CorrExt, so.CorrInv, so.NCorrInv, so.CEECFlag, so.BaseAmnt, so.BaseAmntSC, 
  --                                                 so.BaseAmntFC, so.CtlAccount, so.BPLId, so.BPLName, so.VATRegNum, so.TxInvRptNo, so.TxInvRptDt, so.KVVATCode, so.WTDetails, so.SumAbsId, so.SumRptDate, so.PIndicator, 
  --                                                 so.ManualNum, so.UseShpdGd, so.BaseVtAt, so.BaseVtAtSC, so.BaseVtAtFC, so.NnSbVAt, so.NnSbVAtSC, so.NbSbVAtFC, so.ExptVAt, so.ExptVAtSC, so.ExptVAtFC, so.LYPmtAt, 
  --                                                 so.LYPmtAtSC, so.LYPmtAtFC, so.ExpAnSum, so.ExpAnSys, so.ExpAnFrgn, so.DocSubType, so.DpmStatus, so.DpmAmnt, so.DpmAmntSC, so.DpmAmntFC, so.DpmDrawn, so.DpmPrcnt, 
  --                                                 so.PaidSum, so.PaidSumFc, so.PaidSumSc, so.FolioPref, so.FolioNum, so.DpmAppl, so.DpmApplFc, so.DpmApplSc, so.LPgFolioN, so.Header, so.Footer, so.Posted, so.OwnerCode, 
  --                                                 so.BPChCode, so.BPChCntc, so.PayToCode, so.IsPaytoBnk, so.BnkCntry, so.BankCode, so.BnkAccount, so.BnkBranch, so.isIns, so.TrackNo, so.VersionNum, so.LangCode, 
  --                                                 so.BPNameOW, so.BillToOW, so.ShipToOW, so.RetInvoice, so.ClsDate, so.MInvNum, so.MInvDate, so.SeqCode, so.Serial, so.SeriesStr, so.SubStr, so.Model, so.TaxOnExp, 
  --                                                 so.TaxOnExpFc, so.TaxOnExpSc, so.TaxOnExAp, so.TaxOnExApF, so.TaxOnExApS, so.LastPmnTyp, so.LndCstNum, so.UseCorrVat, so.BlkCredMmo, so.OpenForLaC, so.Excised, 
  --                                                 so.ExcRefDate, so.ExcRmvTime, so.SrvGpPrcnt, so.DepositNum, so.CertNum, so.DutyStatus, so.AutoCrtFlw, so.FlwRefDate, so.FlwRefNum, so.VatJENum, so.DpmVat, so.DpmVatFc, 
  --                                                 so.DpmVatSc, so.DpmAppVat, so.DpmAppVatF, so.DpmAppVatS, so.InsurOp347, so.IgnRelDoc, so.BuildDesc, so.ResidenNum, so.Checker, so.Payee, so.CopyNumber, so.SSIExmpt, 
  --                                                 so.PQTGrpSer, so.PQTGrpNum, so.PQTGrpHW, so.ReopOriDoc, so.ReopManCls, so.DocManClsd, so.ClosingOpt, so.SpecDate, so.Ordered, so.NTSApprov, so.NTSWebSite, 
  --                                                 so.NTSeTaxNo, so.NTSApprNo, so.PayDuMonth, so.ExtraMonth, so.ExtraDays, so.CdcOffset, so.SignMsg, so.SignDigest, so.CertifNum, so.KeyVersion, so.EDocGenTyp, so.ESeries, 
  --                                                 so.EDocNum, so.EDocExpFrm, so.OnlineQuo, so.POSEqNum, so.POSManufSN, so.POSCashN, so.EDocStatus, so.EDocCntnt, so.EDocProces, so.EDocErrCod, so.EDocErrMsg, 
  --                                                 so.EDocCancel, so.EDocTest, so.EDocPrefix, so.CUP, so.CIG, so.DpmAsDscnt, so.Attachment, so.AtcEntry, so.SupplCode, so.GTSRlvnt, so.BaseDisc, so.BaseDiscSc, so.BaseDiscFc, 
  --                                                 so.BaseDiscPr, so.CreateTS, so.UpdateTS, so.SrvTaxRule, so.AnnInvDecR, so.Supplier, so.Releaser, so.Receiver, so.AgrNo, so.IsAlt, so.AltBaseTyp, so.AltBaseEnt, so.PaidDpm, 
  --                                                 so.PaidDpmF, so.PaidDpmS,  '' U_Guatex,  '' U_KM, ae.AddrTypeS AS Ship_To_Address_Type, ae.StreetS AS Ship_To_Street, ae.StateS AS Ship_To_State, 
  --                                                 ae.CountryS AS Ship_To_Country
		--											FROM  [Prueba].dbo.ORDR AS so  LEFT OUTER JOIN
  --                                                 [Prueba].dbo.RDR12 AS ae ON ae.DocEntry = so.DocEntry ');

