CREATE VIEW [SONDA].[ERP_PRICE_LIST_BY_SKU_PACK_SCALE] 
AS 

	SELECT
		CODE_PRICE_LIST 
		,CODE_SKU
		,CODE_PACK_UNIT 
		,LIMIT
		,[BASE_PRICE]
		,([BASE_PRICE] + [VAT]) AS [COST]
	FROM OPENQUERY(ERP_SERVER, '
		SELECT 
			CAST(p.[CVE_PRECIO] AS varchar) AS CODE_PRICE_LIST 
			,p.[CVE_ART] AS CODE_SKU 
			,MAX(p.[PRECIO]) AS [BASE_PRICE]
			,(CASE WHEN ISNULL(imp.[IMPUESTO4],0) > 0 THEN ROUND((MAX(p.[PRECIO])*(imp.[IMPUESTO4]/100)),6) ELSE 0 END) AS VAT
			,UPPER(i.[UNI_MED]) AS CODE_PACK_UNIT 
			,9999999 AS LIMIT
		FROM [SAE70EMPRESA01].[dbo].[PRECIO_X_PROD01] p
		INNER JOIN [SAE70EMPRESA01].[dbo].[INVE01] i ON p.[CVE_ART]=i.[CVE_ART]
		LEFT JOIN [SAE70EMPRESA01].[dbo].[IMPU01] imp ON i.[CVE_ESQIMPU] = imp.[CVE_ESQIMPU]
		WHERE i.[TIPO_ELE]=''P'' AND p.[PRECIO]>0 AND i.[STATUS]<>''B''
		GROUP BY p.[CVE_ART],p.[CVE_PRECIO],i.[UNI_MED],imp.[IMPUESTO4]
	')
	




