
CREATE VIEW [SONDA].[ERP_PRICE_LIST]
AS 

	SELECT 
	   CODE_PRICE_LIST 
	   ,NAME_PRICE_LIST 
	   , '--' COMMENT 
	   , GETDATE() LAST_UPDATE  
	   , 'BULK_DATA' LAST_UPDATE_BY  
	   ,CAST('SONDA' AS VARCHAR) AS [OWNER]
	   ,CAST(CODE_PRICE_LIST AS VARCHAR) COLLATE SQL_Latin1_General_CP1_CI_AS AS [OWNER_ID] 
	FROM OPENQUERY ([ERP_SERVER],'SELECT DISTINCT
		[CVE_PRECIO]  as CODE_PRICE_LIST 
	   ,[DESCRIPCION] as NAME_PRICE_LIST 
	FROM [SAE70EMPRESA01].[dbo].[PRECIOS01]
	')


