-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	06-01-2016
-- Description:			obtiene la informacion de la recepcion por la tarea

/*
-- Ejemplo de Ejecucion:				
				--SELECT * from [SONDA].[OP_WMS_FUNC_GET_RECEPTION_TASK] (12878)
*/
-- =============================================
CREATE FUNCTION [SONDA].[OP_WMS_FUNC_GET_RECEPTION_TASK]
(     
      @TASK_ID INT     
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		T.CREATED_STAMP
		,T.ASSIGNED_BY
		,T.RELATED_PROVIDER_CODE
		,T.RELATED_PROVIDER_NAME
		--(SELECT NAME_PROVIDER FROM [SONDA].SWIFT_VIEW_ALL_PROVIDERS WHERE CODE_PROVIDER = T.RELATED_PROVIDER_CODE) AS RELATED_PROVIDER_NAME,
		,T.TASK_STATUS
		,(SELECT VALUE_TEXT_CLASSIFICATION FROM [SONDA].SWIFT_CLASSIFICATION WHERE GROUP_CLASSIFICATION = 'RECEPTION' AND MPC01 =  H.TYPE_RECEPTION) AS TYPE_RECEPTION
		,H.TYPE_RECEPTION AS MPC01
		,H.DOC_SAP_RECEPTION AS DOC_SAP
		,T.TASK_COMMENTS AS COMMENTS
		,H.SEQ
		,D.CODE_SKU
		,D.DESCRIPTION_SKU
		,ISNULL(S.HANDLE_SERIAL_NUMBER,0) AS HANDLE_SERIAL_NUMBER
		,ISNULL((SELECT COUNT(1) FROM SWIFT_TXNS_SERIES WHERE TXN_ID = @TASK_ID AND TXN_CODE_SKU = D.CODE_SKU),0) AS SERIALIZED
		,D.EXPECTED
		,ISNULL(D.SCANNED,0) AS SCANNED
		,ISNULL(D.ALLOCATED,0) AS ALLOCATED
		,ISNULL(D.[DIFFERENCE],0) AS [DIFFERENCE]
		,ISNULL(T.ALLOW_STORAGE_ON_DIFF,0) AS ALLOW_STORAGE_ON_DIFF
		,D.RESULT
		,CASE S.HANDLE_BATCH WHEN '' THEN '0' ELSE S.HANDLE_BATCH END AS HANDLE_BATCH
		,(SELECT ISNULL(SUM(P.QTY),0) FROM [SONDA].[SWIFT_PALLET] P INNER JOIN [SONDA].[SWIFT_BATCH] B ON (P.BATCH_ID = B.BATCH_ID) WHERE P.TASK_ID = @TASK_ID AND B.SKU = D.CODE_SKU) AS QTY_IN_PALLETS
		,ISNULL((SELECT TOP 1 1 FROM [SONDA].[SWIFT_BATCH] B WHERE [TASK_ID] = @TASK_ID AND [STATUS] = 'OPEN' AND D.CODE_SKU = B.SKU),0) AS BATCH_OPEN
	FROM [SONDA].SWIFT_TASKS T
	INNER JOIN [SONDA].SWIFT_RECEPTION_HEADER H ON (H.RECEPTION_HEADER = T.RECEPTION_NUMBER)
	INNER JOIN [SONDA].SWIFT_RECEPTION_DETAIL D ON (D.RECEPTION_HEADER = H.RECEPTION_HEADER)
	INNER JOIN [SONDA].SWIFT_VIEW_SKU S ON (D.CODE_SKU = S.CODE_SKU)
	WHERE T.TASK_ID = @TASK_ID
)
