
-- =============================================
-- Autor:	pablo.aguilar
-- Fecha de Creacion: 	2017-04-12 @ Team ERGON - Sprint ERGON Ganandorf
-- Description:	 Función para obttiene los materiales padre de una material. 

--Modificación:			Elder Lucas
--Fecha:				24-08-2022
--Descripción:			Control de decimales en masterpack

/*
-- Ejemplo de Ejecucion:
			SELECT * FROM [wms].OP_WMS_FN_GET_PARENT_MATERIALS_OF_MATERIAL ('wms/U00000491')
  
  SELECT * FROM [wms].[OP_WMS_COMPONENTS_BY_MASTER_PACK] [OWCBMP] -- WHERE COMPONENT_MATERIAL = 'wms/CP0000705' 
*/
-- =============================================
CREATE FUNCTION [wms].[OP_WMS_FN_GET_PARENT_MATERIALS_OF_MATERIAL] (@MATERIAL_ID VARCHAR(50))
RETURNS @PARENTS_MATERIALS TABLE (
  PARENT_MATERIAL_ID VARCHAR(50)
  , CONVERTION_TO_BASE_CHILD NUMERIC (18,6)
  , LEVEL INT
)
AS
BEGIN

  INSERT INTO  @PARENTS_MATERIALS VALUES (@MATERIAL_ID , 1 , 0)
  INSERT INTO @PARENTS_MATERIALS
    SELECT
      [C].[MASTER_PACK_CODE] PARENT
      , [C].[QTY]
      , 1
    FROM [wms].[OP_WMS_COMPONENTS_BY_MASTER_PACK] [C]
    WHERE [C].[COMPONENT_MATERIAL] = @MATERIAL_ID
  DECLARE @COUNT_PADRES INT
  SELECT
    @COUNT_PADRES = COUNT(*)
  FROM @PARENTS_MATERIALS

  WHILE @COUNT_PADRES <> (SELECT
        @COUNT_PADRES + COUNT(*)
      FROM @PARENTS_MATERIALS [P]
      INNER JOIN [wms].[OP_WMS_COMPONENTS_BY_MASTER_PACK] [C]
        ON [C].[COMPONENT_MATERIAL] = P.PARENT_MATERIAL_ID
      WHERE NOT EXISTS (SELECT TOP 1
          1
        FROM @PARENTS_MATERIALS [P1]
        WHERE [P1].PARENT_MATERIAL_ID = [C].[MASTER_PACK_CODE]))
  BEGIN
    INSERT INTO @PARENTS_MATERIALS
      SELECT
        [MASTER_PACK_CODE]
        , [C].[QTY] * P.CONVERTION_TO_BASE_CHILD
        , P.LEVEL + 1 
      FROM @PARENTS_MATERIALS [P]
      INNER JOIN [wms].[OP_WMS_COMPONENTS_BY_MASTER_PACK] [C]
        ON [C].[COMPONENT_MATERIAL] = P.PARENT_MATERIAL_ID
      WHERE NOT EXISTS (SELECT TOP 1
          1
        FROM @PARENTS_MATERIALS [P1]
        WHERE [P1].PARENT_MATERIAL_ID = [C].[MASTER_PACK_CODE])

    SELECT
      @COUNT_PADRES = COUNT(*)
    FROM @PARENTS_MATERIALS
  END

  RETURN;
END