
CREATE FUNCTION [wms].[OP_WMS_FUNC_GET_MY_COUNTING_HEADER]
(	
	@pLOGIN_ID VARCHAR(25)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		COUNT_ID,
		COUNT_TYPE,
		COUNT_CLIENT_NAME
	FROM
		[wms].OP_WMS_TASK_LIST_COUNTING
	WHERE 
		ASSIGNED_TO		= @pLOGIN_ID AND 
		COUNTED_DATE	IS NULL AND 
		CANCELED_DATE	IS NULL 
	GROUP BY
		COUNT_ID, 
		COUNT_TYPE,
		COUNT_CLIENT_NAME
)