




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [wms].[OP_WMS_FUNC_GET_AUDIT_RECEPTION]
(	
	@pSINCE_DATE	DATETIME,
	@pTO_DATE		DATETIME
)
RETURNS TABLE 
AS
RETURN 
(

SELECT DISTINCT
	A.CODIGO_POLIZA,			
	A.AUDIT_ID,				
	A.COUNTING_METHOD,		
	A.NUMERO_ORDEN,
	A.STATUS, 
	B.MATERIAL_ID,
	B.BARCODE_ID, 
	B.MATERIAL_NAME,
	(CASE B.SCANNED_COUNT WHEN 0 THEN B.INPUTED_COUNT ELSE B.SCANNED_COUNT END) AS COUNTED,
	A.LAST_UPDATED_BY, 
	A.COMMENTS, 
	CONVERT(VARCHAR(25),A.LAST_UPDATED) AS LAST_UPDATED
	, ISNULL(
		(
		SELECT sum (IV.ENTERED_QTY)
		FROM [wms].OP_WMS_LICENSES L
			INNER JOIN [wms].OP_WMS_INV_X_LICENSE IV ON L.LICENSE_ID = IV.LICENSE_ID	
		WHERE L.CODIGO_POLIZA = B.CODIGO_POLIZA
		AND B.BARCODE_ID = IV.BARCODE_ID
		)
		,0) AS QTYINV	
	
	, (CASE B.SCANNED_COUNT WHEN 0 THEN B.INPUTED_COUNT ELSE B.SCANNED_COUNT END) -
		ISNULL(
		(
		SELECT sum (IV.ENTERED_QTY)
		FROM [wms].OP_WMS_LICENSES L
			INNER JOIN [wms].OP_WMS_INV_X_LICENSE IV ON L.LICENSE_ID = IV.LICENSE_ID	
		WHERE L.CODIGO_POLIZA = B.CODIGO_POLIZA
		AND B.BARCODE_ID = IV.BARCODE_ID
		)
		,0) AS Diferencia
	, M.CLIENT_OWNER
	, C.CLIENT_NAME	
	, P.WAREHOUSE_REGIMEN
	, (CASE (SELECT COUNT(0)
		FROM [wms].OP_WMS_IMAGENES_POLIZA IP
		WHERE IP.CODIGO_POLIZA = A.CODIGO_POLIZA)
		WHEN 0 THEN 'NO'
		ELSE 'SI'
		END) AS FOTOS		
	--, ISNULL(S.SERIAL_NUMBER, 'NA/A') AS SERIAL_NUMBER
 FROM 
	[wms].OP_WMS_AUDIT_RECEPTION_CONTROL A,  
	[wms].OP_WMS_AUDIT_RECEPTION_SKUS B
	INNER JOIN [wms].OP_WMS_MATERIALS M ON M.MATERIAL_ID = B.MATERIAL_ID
	INNER JOIN [wms].OP_WMS_VIEW_CLIENTS C ON M.CLIENT_OWNER = C.CLIENT_CODE
	INNER JOIN [wms].OP_WMS_POLIZA_HEADER P ON P.CODIGO_POLIZA = B.CODIGO_POLIZA
	--LEFT JOIN [wms].OP_WMS_AUDIT_RECEPTION_SERIES S ON M.MATERIAL_ID = S.MATERIAL_ID AND B.AUDIT_ID = S.AUDIT_ID
 WHERE 
	A.LAST_UPDATED >= @pSINCE_DATE AND A.LAST_UPDATED <= @pTO_DATE AND 
	B.AUDIT_ID = A.AUDIT_ID  

)