-- =============================================
-- Author:		rudi.garcia
-- Create date: 14-02-2016
-- Description:	Obtiene las ubicaciones concateneadas por sku y documento
-- =============================================
CREATE FUNCTION [wms].OP_WMS_FUNC_GET_CONCATENATE_LOCATION_BY_SKU_ALMACEN 
(
	@DOC_ID INT
	,@MATERIAL VARCHAR(200)
)
RETURNS VARCHAR(200)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @UBICACIONES VARCHAR(200)

	SELECT 
		--IL.MATERIAL_ID
		@UBICACIONES = COALESCE(@UBICACIONES + N', ', N'') + [L].[CURRENT_WAREHOUSE] --L.CURRENT_LOCATION
		--@UBICACIONES = L.CURRENT_LOCATION
	FROM [wms].[OP_WMS_INV_X_LICENSE] IL
	INNER JOIN [wms].[OP_WMS_LICENSES] L ON (IL.LICENSE_ID = L.LICENSE_ID)
	INNER JOIN [wms].[OP_WMS_POLIZA_HEADER] PH ON (L.CODIGO_POLIZA = PH.CODIGO_POLIZA)
	WHERE 
		@MATERIAL LIKE '%' + IL.MATERIAL_ID +'%'
	--WHERE IL.MATERIAL_ID LIKE '%C01096/88056-SUN TE NEGRO LIMON 2.5L PETX%'
		AND PH.DOC_ID = @DOC_ID
	GROUP BY [CURRENT_WAREHOUSE]--CURRENT_LOCATION
	ORDER BY [CURRENT_WAREHOUSE]--L.CURRENT_LOCATION
		
	RETURN @UBICACIONES
END