

CREATE FUNCTION [wms].OP_WMS_FUNC_GET_SKU_VALOR_UNITARIO_ALMGEN
(	
	@pDOC_ID		INT,
	@pSKU			varchar(50)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		(SUM(b.CUSTOMS_AMOUNT)+
		SUM(b.DAI)+
		SUM(b.IVA))/  SUM(ISNULL(B.QTY, b.BULTOS ))  AS VALOR_UNITARIO
	FROM 
		[wms].OP_WMS_POLIZA_HEADER a 
	INNER JOIN
		[wms].OP_WMS_POLIZA_DETAIL b on a.DOC_ID=b.DOC_ID
	WHERE
		B.SKU_DESCRIPTION	LIKE '%'+ @pSKU + '%' and 
		a.DOC_ID			=	@pDOC_ID  AND
		A.WAREHOUSE_REGIMEN	=	'GENERAL'	
)