CREATE FUNCTION [wms].[OP_WMS_FUNC_GETTRANS_DESC]
(	
	@pTransID varchar(25)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT PARAM_CAPTION
	FROM [wms].OP_WMS_CONFIGURATIONS
	WHERE PARAM_TYPE = 'SISTEMA' AND 
	PARAM_GROUP = 'TRANS_TYPES' AND
	PARAM_NAME = @pTransID
)