-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [wms].OP_WMS_FUNC_GET_AUDIT_DISPATCH
(	
	@pSINCE_DATE	DATETIME,
	@pTO_DATE		DATETIME
)
RETURNS TABLE 
AS
RETURN 
(

SELECT DISTINCT
	A.CODIGO_POLIZA,			
	A.AUDIT_ID,				
	A.COUNTING_METHOD,		
	A.NUMERO_ORDEN,
	A.STATUS, 
	B.MATERIAL_ID,
	B.BARCODE_ID, 
	B.MATERIAL_NAME,
	(CASE B.SCANNED_COUNT WHEN 0 THEN B.INPUTED_COUNT ELSE B.SCANNED_COUNT END) AS COUNTED,
	--C.PICKED,
	MP.[QTY] AS PICKED,--(CASE B.SCANNED_COUNT WHEN 0 THEN B.INPUTED_COUNT ELSE B.SCANNED_COUNT END) AS PICKED,
	(
		(CASE B.SCANNED_COUNT WHEN 0 THEN B.INPUTED_COUNT ELSE B.SCANNED_COUNT END)
		-
		MP.[QTY]
	)AS AUDIT_DIFF,
	A.LAST_UPDATED_BY, 
	A.COMMENTS, 
	CONVERT(VARCHAR(25),A.LAST_UPDATED) AS LAST_UPDATED
	, M.CLIENT_OWNER
	, C.CLIENT_NAME
	, (CASE (SELECT COUNT(0)
		FROM [wms].OP_WMS_IMAGENES_POLIZA IP
		WHERE IP.CODIGO_POLIZA = A.CODIGO_POLIZA)
		WHEN 0 THEN 'NO'
		ELSE 'SI'
		END) AS FOTOS	
	--, ISNULL(S.SERIAL_NUMBER, 'NA/A') AS SERIAL_NUMBER
 FROM 
	[wms].OP_WMS_AUDIT_DISPATCH_CONTROL A,  
	[wms].OP_WMS_AUDIT_DISPATCH_SKUS B
	INNER JOIN [wms].OP_WMS_MATERIALS M ON M.MATERIAL_ID = B.MATERIAL_ID
	INNER JOIN [wms].OP_WMS_VIEW_CLIENTS C ON M.CLIENT_OWNER = C.CLIENT_CODE
  LEFT JOIN [wms].OP_WMS_FUN_GET_MATERIAL_PICKING() MP ON(
    MP.[MATERIAL_ID] = M.[MATERIAL_ID]    
  )
	--LEFT JOIN [wms].OP_WMS_AUDIT_DISPATCH_SERIES S ON M.MATERIAL_ID = S.MATERIAL_ID AND B.AUDIT_ID = S.AUDIT_ID
	--wms.OP_WMS_VIEW_PICKING_VS_AUDIT C
 WHERE 
	A.LAST_UPDATED			BETWEEN 
	@pSINCE_DATE			AND 
	@pTO_DATE				AND 
	B.AUDIT_ID				=	A.AUDIT_ID
  and  A.[CODIGO_POLIZA] = [MP].[CODIGO_POLIZA_TARGET]
	--C.MATERIAL_ID			=	B.MATERIAL_ID	
	
)