-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [wms].[OP_WMS_FUNC_GET_INSURANCE_DOC]
(	
	-- Add the parameters for the function here
	
)
RETURNS  @TB_INSURACE_DOC TABLE 
(
    -- columns returned by the function
	DOC_ID VARCHAR(50)
	, POLIZA_INSURANCE VARCHAR(200)
	, COMPANY_NAME VARCHAR(150)
	, AMOUNT MONEY
	, VALIN_TO DATE
	, CLIENT_NAME NVARCHAR(100)
 	, COVERAGE VARCHAR(250)
	, INSURANCE_OWHEN VARCHAR(50)
	, AMOUNTINV NUMERIC(38,6)
	, AMOUNTDIF NUMERIC(38,6))

AS
BEGIN
	DECLARE @TB_VALORIZACION TABLE(CLIENT_NAME NVARCHAR(100)									
									, CLIENT_OWNER VARCHAR(25)
									, NUMERO_ORDEN VARCHAR(25)
									, LICENSE_ID NUMERIC(18,0)
									, BARCODE_ID VARCHAR(25)
									, MATERIAL_NAME VARCHAR(150)
									, QTY NUMERIC(18,0)
									, CURRENT_LOCATION VARCHAR(25)
									, BODEGA VARCHAR(3)
									, VALOR_UNITARIO NUMERIC(38,6)
									, TOTAL_VALOR NUMERIC(38,6)
									, VOLUMEN NUMERIC(18,4)
									, TOTAL_VOLUMEN NUMERIC(37,4)
									, TERMS_OF_TRADE VARCHAR(50)
									, CODIGO_POLIZA VARCHAR(50)	
									);
	INSERT INTO @TB_VALORIZACION
	SELECT [CLIENT_NAME]
			,[CLIENT_OWNER]
			,[NUMERO_ORDEN]
			,[LICENSE_ID]
			,[BARCODE_ID]
			,[MATERIAL_NAME]
			,[QTY]
			,[CURRENT_LOCATION]
			,[BODEGA]
			,[VALOR_UNITARIO]
			,[TOTAL_VALOR]
			,[VOLUMEN]
			,[TOTAL_VOLUMEN]
			,[TERMS_OF_TRADE]
			,[CODIGO_POLIZA] FROM [wms].OP_WMS_VIEW_VALORIZACION;
	
	INSERT INTO @TB_INSURACE_DOC
	SELECT DOC_ID
			, POLIZA_INSURANCE
			, COMPANY_NAME, AMOUNT
			, VALIN_TO
			, CLIENT_NAME
			, COVERAGE
			, INSURANCE_OWHEN
			, ( SELECT ISNULL(SUM(TOTAL_VALOR),0) FROM @TB_VALORIZACION V 
					INNER JOIN [wms].OP_WMS_POLIZA_HEADER P ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
				where POLIZA_ASEGURADA  = isd.DOC_ID ) AS AMOUNTINV
			, AMOUNT - ( SELECT ISNULL(SUM(TOTAL_VALOR),0) FROM @TB_VALORIZACION V 
							INNER JOIN [wms].OP_WMS_POLIZA_HEADER P ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
						where POLIZA_ASEGURADA  = isd.DOC_ID ) AS AMOUNTDIF
		FROM [wms].OP_WMS_INSURANCE_DOCS isd
			INNER JOIN [wms].OP_WMS_INSURANCE_COMPANIES isc ON isd.COMPANY_ID = isc.COMPANY_ID
			INNER JOIN [wms].OP_WMS_VIEW_CLIENTS vc ON  isd.CLIENT_CODE = vc.CLIENT_CODE COLLATE DATABASE_DEFAULT
		UNION
		SELECT 0 AS DOC_ID 
			, C.TEXT_VALUE AS POLIZA_INSURANCE
			, SPARE1 AS COMPANY_NAME
			, CONVERT(MONEY,MONEY_VALUE) AS AMOUNT
			, CONVERT(DATE,RANGE_DATE_END) AS VALIN_TO
			, C.PARAM_CAPTION AS CLIENT_NAME
			, SPARE2 AS COVERAGE
			, 'PROPIA' AS INSURANCE_OWHEN
			,( SELECT ISNULL(SUM(TOTAL_VALOR),0) FROM @TB_VALORIZACION V 
					INNER JOIN [wms].OP_WMS_POLIZA_HEADER P ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
				where POLIZA_ASEGURADA  =  C.TEXT_VALUE ) AS AMOUNTINV 
			, CONVERT(MONEY,MONEY_VALUE) - ( SELECT ISNULL(SUM(TOTAL_VALOR),0) FROM @TB_VALORIZACION V  
													INNER JOIN [wms].OP_WMS_POLIZA_HEADER P ON V.CODIGO_POLIZA = P.CODIGO_POLIZA
											where POLIZA_ASEGURADA  =  C.TEXT_VALUE ) AS AMOUNTDIF 
		FROM [wms].OP_WMS_CONFIGURATIONS C
		WHERE PARAM_TYPE = 'POLIZAS' 
		AND PARAM_GROUP = 'POLIZAS_SEGUROS'
	RETURN
END