CREATE FUNCTION [wms].OP_WMS_FUN_GET_MATERIAL_PICKING (
 
)
RETURNS TABLE 
AS
RETURN (
  SELECT
    [CODIGO_POLIZA_TARGET]
    ,[TL].[MATERIAL_ID]
    ,MAX([TL].[QUANTITY_PENDING] - [TL].[QUANTITY_ASSIGNED]) *-1 AS QTY
  FROM [wms].[OP_WMS_TASK_LIST] [TL]
  
  GROUP BY [CODIGO_POLIZA_TARGET]
           ,[TL].[MATERIAL_ID]
	
)