

CREATE FUNCTION [wms].[OP_WMS_FUNC_GET_MY_PICKING_DI_LIST_HEADER]
(	
	@pLOGIN_ID varchar(25)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		A.WAVE_PICKING_ID, A.IS_COMPLETED,
		MAX(ISNULL(A.TASK_COMMENTS,'SC')+ ' (TRASLADO A GENERAL)') AS TASK_COMMENTS,
		MAX(CONVERT(VARCHAR(12), A.ASSIGNED_DATE)) AS ASSIGNED_DATE
FROM 
	[wms].[OP_WMS_VIEW_PICKING_TASK_DI] A
WHERE 
	A.TASK_ASSIGNEDTO = @pLOGIN_ID
	AND A.IS_COMPLETED = 'INCOMPLETA' AND A.IS_PAUSED = 0 AND A.IS_CANCELED = 0
	AND A.TASK_SUBTYPE = 'TRASLADO_GENERAL'
GROUP BY 
	A.IS_COMPLETED, A.WAVE_PICKING_ID
)