CREATE TABLE [SONDA].[ERP_TB_BONUS] (
    [CODE_ROUTE]      VARCHAR (50)    NULL,
    [CODE_CUSTOMER]   VARCHAR (50)    NULL,
    [SKU]             VARCHAR (50)    NULL,
    [SKU_PACK_UNIT]   VARCHAR (50)    NULL,
    [LOW_LIMIT]       NUMERIC (18, 6) NULL,
    [HIGT_LIMIT]      NUMERIC (18, 6) NULL,
    [BONUS_QTY]       NUMERIC (18, 6) NULL,
    [BONUS_SKU]       VARCHAR (18)    NULL,
    [BONUS_PACK_UNIT] VARCHAR (50)    NULL
);

